from typing import List

base_characters = ["Antonio Belpaese", "Imelda Belpaese", "Pasqualina Belpaese", "Gennaro Belpaese", "Arca Ladonna",
                   "Porta Ladonna", "Lama Ladonna", "Poe Ratcho", "Suor Clerici", "Dommario", "Krochi Freetto",
                   "Christine Davain", "Pugnala Provola", "Giovanna Grana", "Poppea Pecorina", "Concetta Caciotta",
                   "Mortaccio", "Yatta Cavallo", "Bianca Ramba", "O'Sole Meeo", "Sir Ambrojoe", "Iguana Gallo Valleto",
                   "Divano Thelma", "Zi'Assunta Belpaese", "Exdash Exiviiq", "Toastie", "Smith IV", "Random",
                   "Boon Marrabbio", "Avatar Infernas", "Minnah Mannarah", "Leda", "Cosmo Pavone", "Peppino",
                   "Big Trouser", "MissingN▯", "Gains Boros", "Gyorunton", "Mask of the Red Death", "Queen Sigma",
                   "Bat Robbert", "She-Moon Eeta", "Santa Ladonna", "Gazebo", "Space Dude", "Bats Bats Bats",
                   "Rose De Infernas", "Scorej-Oni", "Gyoruntin", "Space Dette"]

moonspell_characters = ["Miang Moonspell", "Menya Moonspell", "Syuuto Moonspell", "Babi-Onna", "McCoy-Oni",
                        "Megalo Menya Moonspell", "Megalo Syuuto Moonspell", "Gav'Et-Oni"]

foscari_characters = ["Eleanor Uziron", "Maruto Cuts", "Keitha Muort", "Luminaire Foscari", "Genevieve Gruyére",
                      "Je-Ne-Viv", "Sammy", "Rottin'Ghoul"]

amogus_characters = ["Crewmate Dino", "Engineer Gino", "Ghost Lino", "Shapeshifter Nino", "Guardian Pina",
                     "Impostor Rina", "Scientist Mina", "Horse", "Megalo Impostor Rina"]

guns_characters = ["Bill Rizer", "Lance Bean", "Ariana", "Lucia Zero", "Brad Fang", "Browny", "Sheena Etranzi",
                   "Probotector", "Stanley", "Newt Plissken", "Colonel Bahamut", "Simondo Belmont"]

castlevania_characters = ["Leon Belmont", "Sonia Belmont", "Trevor Belmont", "Christopher Belmont", "Simon Belmont",
                          "Juste Belmont", "Richter Belmont", "Julius Belmont", "Grant Danasty", "Quincy Morris",
                          "John Morris", "Jonathan Morris", "Maxim Kischine", "Henry", "Soma Cruz",
                          "Vlad Tepes Dracula", "Charlotte Aulin", "Sypha Belnades", "Julia Laforeze",
                          "Carrie Fernandez", "Yoko Belnades", "Rinaldo Gandolfi", "Mina Hakuba", "Elizabeth Bartley",
                          "Alucard", "Reinhardt Schneider", "Eric Lecarde", "Isaac", "Hector", "Sara Trantoul",
                          "Vincent Dorin", "Maria Renard", "Shanoa", "Albus", "Lisa Tepes", "Shaft", "Saint Germain",
                          "Nathan Graves", "Cornell", "Barlowe", "Young Maria Renard", "Familiar", "Innocent Devil",
                          "Blue Crescent Moon Cornell", "Ferryman", "Master Librarian", "Hammer", "Wind",
                          "Jonathan & Charlotte", "Charlotte & Jonathan", "Stella & Loretta Lecarde",
                          "Loretta & Stella Lecarde", "Stella Lecarde", "Loretta Lecarde", "Brauner", "Soleil Belmont",
                          "Dario Bossi", "Dmitrii Blinov", "Celia Fortner", "Graham Jones", "Joachim Armster",
                          "Walter Bernhard", "Carmilla", "Count Olrox", "Cave Troll", "Fleaman", "Axe Armor",
                          "Frozenshade", "Succubus", "Keremet", "Alamaric Sniper", "Blackmore", "Malphas", "Death",
                          "Galamoth", "Megalo Elizabeth Bartley", "Megalo Olrox", "Megalo Death", "Megalo Dracula",
                          "Chaos"]

emerald_characters = ["Tsunanori Mido", "Bonnie Blair", "Formina Franklyn", "Diva No. 5", "Ameya Aisling", "Siugnas",
                      "Final Emperor", "Dolores", "Macha Alter Ego", "Lita Caryx", "Kugutsu", "Mr. S",
                      "Lolo, Hiss, Meow, and Purr", "Kina", "Imakoo", "Malevolent Door Spirit"]

all_characters = base_characters + moonspell_characters + foscari_characters + amogus_characters + guns_characters + castlevania_characters + emerald_characters

normal_stages = ["Mad Forest", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna"]
bonus_stages = ["Il Molise", "Moongolow", "Whiteout", "The Coop", "Space 54", "Carlo Cart"]

EUDAI = "Eudaimonia M."
challenge_stages = ["Green Acres", "The Bone Zone", "Boss Rash", "Laborratory", "Bat Country", "Astral Stair",
                    "Tiny Bridge", "Room 1665", EUDAI]

moonspell_stages = ["Mt.Moonspell"]
foscari_stages = ["Lake Foscari", "Abyss Foscari"]
amogus_stages = ["Polus Replica"]
guns_stages = ["Neo Galuga", "Hectic Highway"]
castlevania_stages = ["Ode to Castlevania"]
emerald_stages = ["Emerald Diorama"]

all_stages: List[
    str] = normal_stages + bonus_stages + challenge_stages + moonspell_stages + foscari_stages + amogus_stages + guns_stages + castlevania_stages + emerald_stages

# EXCLUDERS
secret_characters = ["Exdash Exiviiq", "Toastie", "Smith IV", "Random", "Boon Marrabbio", "Avatar Infernas",
                     "Minnah Mannarah", "Leda", "Cosmo Pavone", "Peppino", "Big Trouser", "MissingN▯", "Gains Boros",
                     "Gyorunton", "Mask of the Red Death", "Bats Bats Bats", "Rose De Infernas", "Scorej-Oni",
                     "Gyoruntin", "Space Dette", "Young Maria Renard", "Familiar", "Innocent Devil",
                     "Blue Crescent Moon Cornell", "Ferryman", "Master Librarian", "Hammer", "Wind",
                     "Jonathan & Charlotte", "Charlotte & Jonathan", "Stella & Loretta Lecarde",
                     "Loretta & Stella Lecarde", "Stella Lecarde", "Loretta Lecarde", "Brauner", "Soleil Belmont",
                     "Dario Bossi", "Dmitrii Blinov", "Celia Fortner", "Graham Jones", "Joachim Armster",
                     "Walter Bernhard", "Carmilla", "Count Olrox", "Cave Troll", "Fleaman", "Axe Armor", "Frozenshade",
                     "Succubus", "Keremet", "Alamaric Sniper", "Blackmore", "Malphas", "Death", "Galamoth",
                     "Megalo Elizabeth Bartley", "Megalo Olrox", "Megalo Death", "Megalo Dracula", "Chaos",
                     "Lolo, Hiss, Meow, and Purr", "Kina", "Imakoo", "Malevolent Door Spirit"]

megalo_characters = ["Megalo Menya Moonspell", "Megalo Syuuto Moonspell", "Je-Ne-Viv", "Megalo Impostor Rina",
                     "Megalo Elizabeth Bartley", "Megalo Olrox", "Megalo Death", "Megalo Dracula"]

unfair_characters = ["Peppino", "MissingN▯", "Space Dette", "Megalo Menya Moonspell", "Ghost Lino", "Fleaman",
                     "Megalo Death", "Sammy", "Chaos"]

enemy_map = {
    "Pipeestrello": ["Mad Forest", "Gallo Tower", "Carlo Cart"],
    "Bloodbath": ["Gallo Tower"],
    "Skullino": ["Gallo Tower", "The Bone Zone"],
    "Skulorosso": ["Gallo Tower"],
    "Scarleton": ["Gallo Tower"],
    "Skeleton": ["Mad Forest", "Dairy Plant", "Gallo Tower", "The Bone Zone"],
    "Zombie": ["Mad Forest"],
    "Mudman": ["Mad Forest"],
    "Flower Wall": ["Mad Forest"],
    "Ghost": ["Mad Forest", "Inlaid Library", "Gallo Tower"],
    "Werewolf": ["Mad Forest"],
    "Dust Elemental": ["Inlaid Library"],
    "Lionhead": ["Inlaid Library", "Carlo Cart"],
    "Milk Elemental": ["Dairy Plant"],
    "Dragon Shrimp": ["Gallo Tower"],
    "Sig.ra Rossi": ["Inlaid Library"],
    "Poltergeist": ["Gallo Tower", "Cappella Magna"],
    "Hag": ["Inlaid Library"],
    "Nesufritto": ["Inlaid Library"],
    "Mummy": ["Inlaid Library"],
    "Sneaky Head": ["Inlaid Library"],
    "Harzia": ["Gallo Tower"],
    "Musc Musc": ["Inlaid Library", "Dairy Plant"],
    "Impefinger": ["Gallo Tower", "Carlo Cart"],
    "Testa di Mano": ["Inlaid Library", "Gallo Tower"],
    "Ghiavolo": ["Gallo Tower"],
    "Undead Mage": ["Gallo Tower"],
    "Undead Witch": ["Inlaid Library", "Gallo Tower"],
    "Undead Sassy Witch": ["Inlaid Library", "Gallo Tower"],
    "Archon Spada": ["Gallo Tower"],
    "Archon Disco": ["Gallo Tower"],
    "Merdusa": ["Inlaid Library"],
    "Giant Bat": ["Mad Forest", "Carlo Cart"],
    "Mantichana": ["Mad Forest"],
    "Big Mummy": ["Inlaid Library"],
    "Venus": ["Mad Forest"],
    "Merman": ["Dairy Plant", "Moongolow", "Carlo Cart"],
    "Lizard Pawn": ["Dairy Plant", "Carlo Cart"],
    "Twin Snakes": ["Dairy Plant", "Carlo Cart"],
    "Lizard Rook": ["Dairy Plant", "Carlo Cart"],
    "Twin Demons": ["Dairy Plant", "Carlo Cart"],
    "Jellyfish": ["Dairy Plant", "Moongolow"],
    "Skeleton Ninja": ["Dairy Plant", "The Bone Zone"],
    "Lost Twin": ["Dairy Plant", "The Bone Zone"],
    "Melone": ["Dairy Plant"],
    "Minotaur": ["Dairy Plant", "Carlo Cart"],
    "Mignotaur": ["Dairy Plant"],
    "Archon Lancia": ["Dairy Plant"],
    "Archon Ascia": ["Dairy Plant"],
    "Skelewing": ["Dairy Plant", "Gallo Tower", "The Bone Zone"],
    "Tritont": ["Dairy Plant"],
    "Manticore": ["Gallo Tower"],
    "Gallotrice": ["Dairy Plant", "Gallo Tower"],
    "Big Golem": ["Dairy Plant"],
    "Meat Golem": ["Gallo Tower"],
    "Sword Guardian": ["Dairy Plant"],
    "Giant Enemy Crab": ["Gallo Tower"],
    "Sad Molisano": ["Il Molise"],
    "Happy Molisano": ["Il Molise"],
    "Cute Molisano": ["Il Molise"],
    "Old Molisano": ["Il Molise"],
    "Dead Molisano": ["Il Molise"],
    "Bambaman": ["Whiteout"],
    "Miragellos": ["Whiteout"],
    "Menta Elemental": ["Whiteout"],
    "Madd-Onna": ["Whiteout"],
    "Kizzune": ["Whiteout"],
    "Holy Circuit Creations": ["Laborratory", "Carlo Cart"],
    "Bounty Hunter": ["Laborratory"],
    "Space Hunter": ["Laborratory"],
    "Tri-Blunder": ["Laborratory"],
    "Chickenfantry": ["The Coop"],
    "Cockreliutennant": ["The Coop"],
    "Chik": ["The Coop"],
    "Egge": ["The Coop"],
    "Pol.lo Rosso": ["The Coop"],
    "Abraxas": ["The Coop"],
    "Abraxas Phronesis": ["The Coop"],
    "Abraxas Dynamis": ["The Coop"],
    "Gala Invader": ["Space 54"],
    "Moon Rabbit": ["Space 54"],
    "Moon Duck": ["Space 54"],
    "Space Ant Onion": ["Space 54"],
    "Space Pickle": ["Space 54"],
    "ECMASlime": ["Space 54"],
    "Sinistronz": ["Space 54"],
    "Twin Skulls": ["The Bone Zone"],
    "Skullone": ["Inlaid Library", "The Bone Zone"],
    "Skeleton Panther": ["The Bone Zone"],
    "Giant Skeleton": ["The Bone Zone"],
    "Skeletone": ["The Bone Zone"],
    "Sketamari": ["The Bone Zone"],
    "Sun Atlantean": ["Moongolow", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna"],
    "Moon Atlantean": ["Moongolow", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna"],
    "City Atlantean": ["Moongolow", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna"],
    "Volcano Atlantean": ["Moongolow", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna"],
    "Moongolow Atlanteans": ["Moongolow"],
    "Serpentvine": ["Moongolow"],
    "Garlic": ["Moongolow"],
    "Nightshade": ["Moongolow"],
    "Sig.ra Blu": ["Moongolow"],
    "Non-Giant Enemy Crab": ["Moongolow"],
    "Unknown": ["Cappella Magna"],
    "Reaper Trainee": ["Cappella Magna"],
    "Tetrabrachia": ["Cappella Magna"],
    "Archon Fiamma": ["Cappella Magna"],
    "Succubus": ["Cappella Magna"],
    "Archon Rame": ["Cappella Magna"],
    "Demon Priest": ["Cappella Magna"],
    "Fallen Cherub": ["Cappella Magna"],
    "Fallen Cherubbello": ["Cappella Magna"],
    "Fallen Throne": ["Cappella Magna"],
    "Archon Oro": ["Cappella Magna"],
    "Demon Beast": ["Cappella Magna"],
    "Archdemon": ["Cappella Magna"],
    "Trinacria": ["Cappella Magna"],
    "Stage Killer": ["Cappella Magna"],
    "The Reaper": ["Mad Forest", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna", "Il Molise",
                   "Moongolow", "Green Acres", "The Bone Zone", "Carlo Cart"],
    "The Trickster": ["Inlaid Library", "Cappella Magna", "Carlo Cart"],
    "The Stalker": ["Dairy Plant", "Cappella Magna", "The Bone Zone", "Carlo Cart"],
    "The Drowner": ["Gallo Tower", "Cappella Magna", "The Bone Zone", "Carlo Cart"],
    "The Maddener": ["Cappella Magna", "Carlo Cart"],
    "The Ender": ["Cappella Magna", "Carlo Cart"],
    "Mimic Season One": ["Boss Rash"],
    "Mimic Season Two": ["Boss Rash"],
    "Mimic Season Three": ["Boss Rash"],
    "Tri-Anchors": ["Boss Rash"],
    "LV128 Golden Bat": ["Green Acres"],
    "The Directer": ["Eudaimonia M."],
    "Astral Elemental": ["Astral Stair"],
    "Astral Chair": ["Astral Stair"],
    "Astral Curtain": ["Astral Stair"],
    "Undead Stars": ["Astral Stair"],
    "Poetrait": ["Astral Stair"],
    "Lord Ghost": ["Astral Stair"],
    "Cosmic Egg": ["Astral Stair"],
    "Ska'sa Ka'sos": ["Room 1665"],
    "Juda R'kasso": ["Room 1665"],
    "Foo'Ori Darkasso": ["Room 1665"],
    "Shendi Darkasso": ["Room 1665"],
    "Sphon'Dato Darkasso": ["Room 1665"],
    "Eh'Lleve-Teh Darkasso": ["Room 1665"],
    "Levatee Darkasso": ["Room 1665"],
    "Levarsee Darkasso": ["Room 1665"],
    "Spiritello": ["Mt.Moonspell"],
    "Hitotsume-kozo": ["Mt.Moonspell"],
    "Kappa": ["Mt.Moonspell"],
    "Tsuchinoko": ["Mt.Moonspell"],
    "Mikoshi-nyudo": ["Mt.Moonspell"],
    "Kamaitachi": ["Mt.Moonspell"],
    "Raiju": ["Mt.Moonspell"],
    "Yamamba": ["Mt.Moonspell"],
    "Tanuki": ["Mt.Moonspell"],
    "Tengu": ["Mt.Moonspell"],
    "Tsuchigumo": ["Mt.Moonspell"],
    "Windy Oni": ["Mt.Moonspell"],
    "Thunderous Oni": ["Mt.Moonspell"],
    "Big Oni": ["Mt.Moonspell"],
    "Goshadokuro": ["Mt.Moonspell"],
    "Orochimario": ["Mt.Moonspell"],
    "Chompo": ["Lake Foscari"],
    "Ceffoose": ["Lake Foscari"],
    "Wiseparke": ["Lake Foscari"],
    "Nutmeg": ["Lake Foscari"],
    "Vulvio": ["Lake Foscari"],
    "Lammuga": ["Lake Foscari"],
    "Hill Trow": ["Lake Foscari"],
    "Sea Trow": ["Lake Foscari"],
    "Sam the Sandown Clown": ["Lake Foscari"],
    "Sammy the Caterpillar": ["Lake Foscari"],
    "Brownie": ["Lake Foscari"],
    "Green Knight": ["Lake Foscari"],
    "Crocifriggitore": ["Lake Foscari"],
    "Notadam": ["Lake Foscari"],
    "Hand of Glory": ["Lake Foscari"],
    "Maronna": ["Lake Foscari"],
    "Njuggles": ["Lake Foscari"],
    "Average Hag": ["Lake Foscari"],
    "Fungoman": ["Lake Foscari"],
    "Ghostly Apparition": ["Lake Foscari"],
    "Avatar of Gaea": ["Lake Foscari"],
    "Cauld": ["Abyss Foscari"],
    "Redusa Head": ["Abyss Foscari"],
    "Rellyfish": ["Abyss Foscari"],
    "Blood Moss": ["Abyss Foscari"],
    "The Blinder": ["Abyss Foscari"],
    "Rotting Ghoul": ["Abyss Foscari"],
    "Burning Skull": ["Abyss Foscari"],
    "Missing Church": ["Abyss Foscari"],
    "Snek": ["Abyss Foscari"],
    "Lost Head": ["Abyss Foscari"],
    "Meatball": ["Abyss Foscari"],
    "Followa": ["Abyss Foscari"],
    "Edna": ["Abyss Foscari"],
    "Cold Cauld": ["Abyss Foscari"],
    "Well Dweller": ["Abyss Foscari"],
    "Wet Njuggles": ["Abyss Foscari"],
    "Crocifiggitone": ["Abyss Foscari"],
    "Still Notadam": ["Abyss Foscari"],
    "Glove of Glory": ["Abyss Foscari"],
    "Maronna Meea": ["Abyss Foscari"],
    "Fomorians": ["Abyss Foscari"],
    "Je-Ne-Viv": ["Abyss Foscari"],
    "Frijjitello": ["Polus Replica"],
    "Brainoid": ["Polus Replica"],
    "Spotter": ["Polus Replica"],
    "Shapeunshifter": ["Polus Replica"],
    "Pinthot & Coldellini": ["Polus Replica"],
    "Space Apparition": ["Polus Replica"],
    "Mocholo": ["Polus Replica"],
    "Meat Bean": ["Polus Replica"],
    "Martian Face": ["Polus Replica"],
    "Suspicio": ["Polus Replica"],
    "Victor Frankenstein": ["Polus Replica"],
    "Sponkey": ["Polus Replica"],
    "Steroid": ["Polus Replica"],
    "Trip Trop": ["Polus Replica"],
    "G062T": ["Polus Replica"],
    "Suspicious Eyes": ["Polus Replica"],
    "Ledder": ["Neo Galuga"],
    "Greeder": ["Neo Galuga"],
    "Warlord": ["Neo Galuga"],
    "Evil Snowman": ["Neo Galuga"],
    "Alien Centipede": ["Neo Galuga"],
    "Gulcan Tank": ["Neo Galuga"],
    "Metal Alien": ["Neo Galuga"],
    "Human Faced Dog": ["Neo Galuga"],
    "Garth": ["Neo Galuga"],
    "Ball Walker": ["Neo Galuga"],
    "Hellrider": ["Neo Galuga"],
    "Junkyard Car": ["Neo Galuga"],
    "Flight Zako": ["Neo Galuga"],
    "M78": ["Neo Galuga"],
    "Bugger": ["Neo Galuga"],
    "Poisonous Insect Gel": ["Neo Galuga"],
    "Bundle": ["Neo Galuga"],
    "Zako Alien": ["Neo Galuga"],
    "Gigafly": ["Neo Galuga"],
    "Mutant Crawler": ["Neo Galuga"],
    "Kimkoh": ["Neo Galuga"],
    "Big Bot Gordea": ["Neo Galuga"],
    "Taka": ["Neo Galuga"],
    "Big Fuzz": ["Neo Galuga"],
    "Simondo Belmont": ["Neo Galuga"],
    "Fleaman": ["Ode to Castlevania"],
    "Flea Rider": ["Ode to Castlevania"],
    "Flea Armor": ["Ode to Castlevania"],
    "Spellbook": ["Ode to Castlevania"],
    "Frozen Shade": ["Ode to Castlevania"],
    "Harpy": ["Ode to Castlevania"],
    "Hippogryph": ["Ode to Castlevania"],
    "Imp": ["Ode to Castlevania"],
    "Moldy Corpse": ["Ode to Castlevania"],
    "Spittle Bone": ["Ode to Castlevania"],
    "Ukoback": ["Ode to Castlevania"],
    "Spectre": ["Ode to Castlevania"],
    "Valhalla Knight": ["Ode to Castlevania"],
    "Warg": ["Ode to Castlevania"],
    "Bitterfly": ["Ode to Castlevania"],
    "Bloody Painting": ["Ode to Castlevania"],
    "OG Merman": ["Ode to Castlevania"],
    "Persephone": ["Ode to Castlevania"],
    "OG Ghost": ["Ode to Castlevania"],
    "Flying Zombie": ["Ode to Castlevania"],
    "Dullahan": ["Ode to Castlevania"],
    "Yorick": ["Ode to Castlevania"],
    "Amalaric Sniper": ["Ode to Castlevania"],
    "Gurkha Knife Master": ["Ode to Castlevania"],
    "Gorgon": ["Ode to Castlevania"],
    "Bone Golem": ["Ode to Castlevania"],
    "Disc Armor": ["Ode to Castlevania"],
    "Alastor": ["Ode to Castlevania"],
    "Malachi": ["Ode to Castlevania"],
    "OG Werewolf": ["Ode to Castlevania"],
    "Axe Armor": ["Ode to Castlevania"],
    "Killer Doll": ["Ode to Castlevania"],
    "Corpseweed": ["Ode to Castlevania"],
    "Bone Ark": ["Ode to Castlevania"],
    "Bone Pillar": ["Ode to Castlevania"],
    "Jiang shi": ["Ode to Castlevania"],
    "Keremet": ["Ode to Castlevania"],
    "Zephyr": ["Ode to Castlevania"],
    "Gaibon": ["Ode to Castlevania"],
    "Slogra": ["Ode to Castlevania"],
    "Behemoth": ["Ode to Castlevania"],
    "Treant": ["Ode to Castlevania"],
    "Abbadon": ["Ode to Castlevania"],
    "Menace": ["Ode to Castlevania"],
    "Eligor": ["Ode to Castlevania"],
    "Gergoth": ["Ode to Castlevania"],
    "Giant Medusa Head": ["Ode to Castlevania"],
    "Puppet Master": ["Ode to Castlevania"],
    "Blackmore": ["Ode to Castlevania"],
    "Paranoia": ["Ode to Castlevania"],
    "Death": ["Ode to Castlevania"],
    "Doppelganger": ["Ode to Castlevania"],
    "The Creature": ["Ode to Castlevania"],
    "Bugbear": ["Ode to Castlevania"],
    "Devil": ["Ode to Castlevania"],
    "OG Minotaur": ["Ode to Castlevania"],
    "Calamity": ["Emerald Diorama"],
    "Divine Wood Spirit": ["Emerald Diorama"],
    "Boar Infantry": ["Emerald Diorama"],
    "Earth Dragon": ["Emerald Diorama"],
    "Forest Hermit": ["Emerald Diorama"],
    "Maggot Ball": ["Emerald Diorama"],
    "Skydiver": ["Emerald Diorama"],
    "Psychic Ogre": ["Emerald Diorama"],
    "Decobat": ["Emerald Diorama"],
    "Failinis": ["Emerald Diorama"],
    "Rana Combatant": ["Emerald Diorama"],
    "Kelpie": ["Emerald Diorama"],
    "Rascal": ["Emerald Diorama"],
    "Golden Baum": ["Emerald Diorama"],
    "Alraune": ["Emerald Diorama"],
    "Anti-Ant": ["Emerald Diorama"],
    "Moch": ["Emerald Diorama"],
    "Skeleton from Beyond": ["Emerald Diorama"],
    "Werewolf from Beyond": ["Emerald Diorama"],
    "Specter of Iwanaga-hime": ["Emerald Diorama"],
    "Iron Maiden": ["Emerald Diorama"],
    "Malevolent Door Spirit": ["Emerald Diorama"],
    "Living Anguish": ["Emerald Diorama"], }

location_dictionary: List[str] = [
    *[f"{stage} Beaten" for stage in all_stages],
    *[f"Beat with {character}" for character in all_characters],
    *[f"Open Chest #{i + 1} on {stage}" for i in range(10) for stage in all_stages],
    *[f"Kill {key}" for key, value in enemy_map.items()]
]

# Extra
non_special_characters = [character for character in all_characters if
                          character not in secret_characters and character not in megalo_characters and character not in unfair_characters]
