# File is Auto-generated, see: [https://github.com/SWCreeperKing/ApWorldFactories/tree/master/ApWorldFactories/Games]

stages_beaten = [
	["Mad Forest Beaten", "Mad Forest"],
	["Eudaimonia M. Beaten", "Eudaimonia M."],
	["Inlaid Library Beaten", "Inlaid Library"],
	["Dairy Plant Beaten", "Dairy Plant"],
	["Gallo Tower Beaten", "Gallo Tower"],
	["Cappella Magna Beaten", "Cappella Magna"],
	["Il Molise Beaten", "Il Molise"],
	["Moongolow Beaten", "Moongolow"],
	["Green Acres Beaten", "Green Acres"],
	["The Bone Zone Beaten", "The Bone Zone"],
	["Boss Rash Beaten", "Boss Rash"],
	["Whiteout Beaten", "Whiteout"],
	["The Coop Beaten", "The Coop"],
	["Space 54 Beaten", "Space 54"],
	["Carlo Cart Beaten", "Carlo Cart"],
	["Laborratory Beaten", "Laborratory"],
	["Westwoods Beaten", "Westwoods"],
	["Bat Country Beaten", "Bat Country"],
	["Astral Stair Beaten", "Astral Stair"],
	["Mazerella Beaten", "Mazerella"],
	["Tiny Bridge Beaten", "Tiny Bridge"],
	["Mt.Moonspell Beaten", "Mt.Moonspell"],
	["Lake Foscari Beaten", "Lake Foscari"],
	["Abyss Foscari Beaten", "Abyss Foscari"],
	["Ante Chamber Beaten", "Ante Chamber"],
	["Room 1665 Beaten", "Room 1665"],
	["Neo Galuga Beaten", "Neo Galuga"],
	["Hectic Highway Beaten", "Hectic Highway"],
	["Ode to Castlevania Beaten", "Ode to Castlevania"],
	["Polus Replica Beaten", "Polus Replica"],
	["Emerald Diorama Beaten", "Emerald Diorama"]
]

beat_with_character = [
	["Beat with Antonio Belpaese", "Characters"],
	["Beat with Imelda Belpaese", "Characters"],
	["Beat with Pasqualina Belpaese", "Characters"],
	["Beat with Gennaro Belpaese", "Characters"],
	["Beat with Arca Ladonna", "Characters"],
	["Beat with Porta Ladonna", "Characters"],
	["Beat with Lama Ladonna", "Characters"],
	["Beat with Poe Ratcho", "Characters"],
	["Beat with Suor Clerici", "Characters"],
	["Beat with Dommario", "Characters"],
	["Beat with Krochi Freetto", "Characters"],
	["Beat with Christine Davain", "Characters"],
	["Beat with Pugnala Provola", "Characters"],
	["Beat with Giovanna Grana", "Characters"],
	["Beat with Poppea Pecorina", "Characters"],
	["Beat with Concetta Caciotta", "Characters"],
	["Beat with Mortaccio", "Characters"],
	["Beat with Yatta Cavallo", "Characters"],
	["Beat with Bianca Ramba", "Characters"],
	["Beat with O'Sole Meeo", "Characters"],
	["Beat with Sir Ambrojoe", "Characters"],
	["Beat with Iguana Gallo Valletto", "Characters"],
	["Beat with Divano Thelma", "Characters"],
	["Beat with Zi'Assunta Belpaese", "Characters"],
	["Beat with Exdash Exiviiq", "Characters"],
	["Beat with Toastie", "Characters"],
	["Beat with Smith IV", "Characters"],
	["Beat with Random", "Characters"],
	["Beat with Boon Marrabbio", "Characters"],
	["Beat with Avatar Infernas", "Characters"],
	["Beat with Minnah Mannarah", "Characters"],
	["Beat with Leda", "Characters"],
	["Beat with Cosmo Pavone", "Characters"],
	["Beat with Peppino", "Characters"],
	["Beat with Big Trouser", "Characters"],
	["Beat with missingN", "Characters"],
	["Beat with Gains Boros", "Characters"],
	["Beat with Gyorunton", "Characters"],
	["Beat with Mask of the Red Death", "Characters"],
	["Beat with Queen Sigma", "Characters"],
	["Beat with Bat Robbert", "Characters"],
	["Beat with Zi'Appunta Belpaese", "Characters"],
	["Beat with She-Moon Eeta", "Characters"],
	["Beat with Santa Ladonna", "Characters"],
	["Beat with Gazebo", "Characters"],
	["Beat with Chula-Reh", "Characters"],
	["Beat with Space Dude", "Characters"],
	["Beat with Bats Bats Bats", "Characters"],
	["Beat with Rose De Infernas", "Characters"],
	["Beat with Torino", "Characters"],
	["Beat with Scorej-Oni", "Characters"],
	["Beat with Gyoruntin", "Characters"],
	["Beat with Secretino", "Characters"],
	["Beat with Space Dette", "Characters"],
	["Beat with Miang Moonspell", "Characters"],
	["Beat with Menya Moonspell", "Characters"],
	["Beat with Syuuto Moonspell", "Characters"],
	["Beat with Babi-Onna", "Characters"],
	["Beat with McCoy-Oni", "Characters"],
	["Beat with Megalo Menya Moonspell", "Characters"],
	["Beat with Megalo Syuuto Moonspell", "Characters"],
	["Beat with Gab'Et-Oni", "Characters"],
	["Beat with Eleanor Uziron", "Characters"],
	["Beat with Maruto Cuts", "Characters"],
	["Beat with Keitha Muort", "Characters"],
	["Beat with Luminaire Foscari", "Characters"],
	["Beat with Genevieve Gruyère", "Characters"],
	["Beat with Je-Ne-Viv", "Characters"],
	["Beat with Sammy", "Characters"],
	["Beat with Rottin'Ghoul", "Characters"],
	["Beat with Crewmate Dino", "Characters"],
	["Beat with Engineer Gino", "Characters"],
	["Beat with Ghost Lino", "Characters"],
	["Beat with Shapeshifter Nino", "Characters"],
	["Beat with Guardian Pina", "Characters"],
	["Beat with Impostor Rina", "Characters"],
	["Beat with Scientist Mina", "Characters"],
	["Beat with Horse", "Characters"],
	["Beat with Megalo Impostor Rina", "Characters"],
	["Beat with Bill Rizer", "Characters"],
	["Beat with Lance Bean", "Characters"],
	["Beat with Ariana", "Characters"],
	["Beat with Lucia Zero", "Characters"],
	["Beat with Brad Fang", "Characters"],
	["Beat with Browny", "Characters"],
	["Beat with Sheena Etranzi", "Characters"],
	["Beat with Probotector", "Characters"],
	["Beat with Stanley", "Characters"],
	["Beat with Newt Plissken", "Characters"],
	["Beat with Colonel Bahamut", "Characters"],
	["Beat with Simondo", "Characters"],
	["Beat with Leon Belmont", "Characters"],
	["Beat with Sonia Belmont", "Characters"],
	["Beat with Trevor Belmont", "Characters"],
	["Beat with Christopher Belmont", "Characters"],
	["Beat with Simon Belmont", "Characters"],
	["Beat with Juste Belmont", "Characters"],
	["Beat with Richter Belmont", "Characters"],
	["Beat with Julius Belmont", "Characters"],
	["Beat with Grant Danasty", "Characters"],
	["Beat with Quincy Morris", "Characters"],
	["Beat with John Morris", "Characters"],
	["Beat with Jonathan Morris", "Characters"],
	["Beat with Maxim Kischine", "Characters"],
	["Beat with Henry", "Characters"],
	["Beat with Soma Cruz", "Characters"],
	["Beat with Vlad Tepes Dracula", "Characters"],
	["Beat with Charlotte Aulin", "Characters"],
	["Beat with Sypha Belnades", "Characters"],
	["Beat with Julia Laforeze", "Characters"],
	["Beat with Carrie Fernandez", "Characters"],
	["Beat with Yoko Belnades", "Characters"],
	["Beat with Rinaldo Gandolfi", "Characters"],
	["Beat with Mina Hakuba", "Characters"],
	["Beat with Elizabeth Bartley", "Characters"],
	["Beat with Alucard", "Characters"],
	["Beat with Reinhardt Schneider", "Characters"],
	["Beat with Eric Lecarde", "Characters"],
	["Beat with Isaac", "Characters"],
	["Beat with Hector", "Characters"],
	["Beat with Sara Trantoul", "Characters"],
	["Beat with Vincent Dorin", "Characters"],
	["Beat with Maria Renard", "Characters"],
	["Beat with Shanoa", "Characters"],
	["Beat with Albus", "Characters"],
	["Beat with Lisa", "Characters"],
	["Beat with Shaft", "Characters"],
	["Beat with Saint Germain", "Characters"],
	["Beat with Nathan Graves", "Characters"],
	["Beat with Cornell", "Characters"],
	["Beat with Barlowe", "Characters"],
	["Beat with Young Maria Renard", "Characters"],
	["Beat with Familiar", "Characters"],
	["Beat with Innocent Devil", "Characters"],
	["Beat with Blue Crescent Moon Cornell", "Characters"],
	["Beat with Ferryman", "Characters"],
	["Beat with Librarian", "Characters"],
	["Beat with Hammer", "Characters"],
	["Beat with Wind", "Characters"],
	["Beat with Hugh Baldwin", "Characters"],
	["Beat with Morris Baldwin", "Characters"],
	["Beat with Annette", "Characters"],
	["Beat with Tera", "Characters"],
	["Beat with Jonathan & Charlotte", "Characters"],
	["Beat with Charlotte & Jonathan", "Characters"],
	["Beat with Stella & Loretta Lecarde", "Characters"],
	["Beat with Loretta & Stella Lecarde", "Characters"],
	["Beat with Stella Lecarde", "Characters"],
	["Beat with Loretta Lecarde", "Characters"],
	["Beat with Brauner", "Characters"],
	["Beat with Soleil Belmont", "Characters"],
	["Beat with Dario Bossi", "Characters"],
	["Beat with Dmitri Blinov", "Characters"],
	["Beat with Celia Fortner", "Characters"],
	["Beat with Graham Jones", "Characters"],
	["Beat with Joachim", "Characters"],
	["Beat with Walter", "Characters"],
	["Beat with Carmilla", "Characters"],
	["Beat with Cave Troll", "Characters"],
	["Beat with Fleaman", "Characters"],
	["Beat with Axe Armor", "Characters"],
	["Beat with Frozenshade", "Characters"],
	["Beat with Amalaric Sniper", "Characters"],
	["Beat with Stone Skull", "Characters"],
	["Beat with Sword Ruler", "Characters"],
	["Beat with Persephone", "Characters"],
	["Beat with Keremet", "Characters"],
	["Beat with Astarte", "Characters"],
	["Beat with Drolta", "Characters"],
	["Beat with Actrise", "Characters"],
	["Beat with Atlantis Shrine Wizard", "Characters"],
	["Beat with Succubus", "Characters"],
	["Beat with Fake Trio", "Characters"],
	["Beat with Slogra and Gaibon", "Characters"],
	["Beat with Zephyr", "Characters"],
	["Beat with Jiangshi", "Characters"],
	["Beat with Blackmore", "Characters"],
	["Beat with Count Olrox", "Characters"],
	["Beat with Malphas", "Characters"],
	["Beat with Death", "Characters"],
	["Beat with Galamoth", "Characters"],
	["Beat with Megalo Elizabeth Bartley", "Characters"],
	["Beat with Megalo Olrox", "Characters"],
	["Beat with Megalo Death", "Characters"],
	["Beat with Megalo Dracula", "Characters"],
	["Beat with Chaos", "Characters"],
	["Beat with Gaibon and Slogra", "Characters"],
	["Beat with Slogra", "Characters"],
	["Beat with Kid Dracula", "Characters"],
	["Beat with Aeon", "Characters"],
	["Beat with Desmond Belmont", "Characters"],
	["Beat with Dolores Belmont", "Characters"],
	["Beat with Zoe Belmont", "Characters"],
	["Beat with Fishman", "Characters"],
	["Beat with Fake Trevor", "Characters"],
	["Beat with Fake Sypha", "Characters"],
	["Beat with Fake Grant", "Characters"],
	["Beat with Tsunanori Mido", "Characters"],
	["Beat with Bonnie Blair", "Characters"],
	["Beat with Formina Franklyn", "Characters"],
	["Beat with Diva No. 5", "Characters"],
	["Beat with Ameya Aisling", "Characters"],
	["Beat with Siugnas", "Characters"],
	["Beat with Final Emperor", "Characters"],
	["Beat with Dolores", "Characters"],
	["Beat with Macha", "Characters"],
	["Beat with Lita", "Characters"],
	["Beat with Kugutsu", "Characters"],
	["Beat with Mr. S", "Characters"],
	["Beat with Lolo, Hiss, Meow and Purr", "Characters"],
	["Beat with Kina", "Characters"],
	["Beat with Imakoo", "Characters"],
	["Beat with Malevolent Door Spirit", "Characters"],
	["Beat with Jimbo", "Characters"],
	["Beat with Canio", "Characters"],
	["Beat with Chicot", "Characters"],
	["Beat with Perkeo", "Characters"],
	["Beat with Genya Arikado", "Characters"]
]

open_chests = [
	["Open Chest #1 on Mad Forest", "Mad Forest"],
	["Open Chest #2 on Mad Forest", "Mad Forest"],
	["Open Chest #3 on Mad Forest", "Mad Forest"],
	["Open Chest #4 on Mad Forest", "Mad Forest"],
	["Open Chest #5 on Mad Forest", "Mad Forest"],
	["Open Chest #6 on Mad Forest", "Mad Forest"],
	["Open Chest #7 on Mad Forest", "Mad Forest"],
	["Open Chest #8 on Mad Forest", "Mad Forest"],
	["Open Chest #9 on Mad Forest", "Mad Forest"],
	["Open Chest #10 on Mad Forest", "Mad Forest"],
	["Open Chest #1 on Eudaimonia M.", "Eudaimonia M."],
	["Open Chest #2 on Eudaimonia M.", "Eudaimonia M."],
	["Open Chest #3 on Eudaimonia M.", "Eudaimonia M."],
	["Open Chest #4 on Eudaimonia M.", "Eudaimonia M."],
	["Open Chest #5 on Eudaimonia M.", "Eudaimonia M."],
	["Open Chest #6 on Eudaimonia M.", "Eudaimonia M."],
	["Open Chest #7 on Eudaimonia M.", "Eudaimonia M."],
	["Open Chest #8 on Eudaimonia M.", "Eudaimonia M."],
	["Open Chest #9 on Eudaimonia M.", "Eudaimonia M."],
	["Open Chest #10 on Eudaimonia M.", "Eudaimonia M."],
	["Open Chest #1 on Inlaid Library", "Inlaid Library"],
	["Open Chest #2 on Inlaid Library", "Inlaid Library"],
	["Open Chest #3 on Inlaid Library", "Inlaid Library"],
	["Open Chest #4 on Inlaid Library", "Inlaid Library"],
	["Open Chest #5 on Inlaid Library", "Inlaid Library"],
	["Open Chest #6 on Inlaid Library", "Inlaid Library"],
	["Open Chest #7 on Inlaid Library", "Inlaid Library"],
	["Open Chest #8 on Inlaid Library", "Inlaid Library"],
	["Open Chest #9 on Inlaid Library", "Inlaid Library"],
	["Open Chest #10 on Inlaid Library", "Inlaid Library"],
	["Open Chest #1 on Dairy Plant", "Dairy Plant"],
	["Open Chest #2 on Dairy Plant", "Dairy Plant"],
	["Open Chest #3 on Dairy Plant", "Dairy Plant"],
	["Open Chest #4 on Dairy Plant", "Dairy Plant"],
	["Open Chest #5 on Dairy Plant", "Dairy Plant"],
	["Open Chest #6 on Dairy Plant", "Dairy Plant"],
	["Open Chest #7 on Dairy Plant", "Dairy Plant"],
	["Open Chest #8 on Dairy Plant", "Dairy Plant"],
	["Open Chest #9 on Dairy Plant", "Dairy Plant"],
	["Open Chest #10 on Dairy Plant", "Dairy Plant"],
	["Open Chest #1 on Gallo Tower", "Gallo Tower"],
	["Open Chest #2 on Gallo Tower", "Gallo Tower"],
	["Open Chest #3 on Gallo Tower", "Gallo Tower"],
	["Open Chest #4 on Gallo Tower", "Gallo Tower"],
	["Open Chest #5 on Gallo Tower", "Gallo Tower"],
	["Open Chest #6 on Gallo Tower", "Gallo Tower"],
	["Open Chest #7 on Gallo Tower", "Gallo Tower"],
	["Open Chest #8 on Gallo Tower", "Gallo Tower"],
	["Open Chest #9 on Gallo Tower", "Gallo Tower"],
	["Open Chest #10 on Gallo Tower", "Gallo Tower"],
	["Open Chest #1 on Cappella Magna", "Cappella Magna"],
	["Open Chest #2 on Cappella Magna", "Cappella Magna"],
	["Open Chest #3 on Cappella Magna", "Cappella Magna"],
	["Open Chest #4 on Cappella Magna", "Cappella Magna"],
	["Open Chest #5 on Cappella Magna", "Cappella Magna"],
	["Open Chest #6 on Cappella Magna", "Cappella Magna"],
	["Open Chest #7 on Cappella Magna", "Cappella Magna"],
	["Open Chest #8 on Cappella Magna", "Cappella Magna"],
	["Open Chest #9 on Cappella Magna", "Cappella Magna"],
	["Open Chest #10 on Cappella Magna", "Cappella Magna"],
	["Open Chest #1 on Il Molise", "Il Molise"],
	["Open Chest #2 on Il Molise", "Il Molise"],
	["Open Chest #3 on Il Molise", "Il Molise"],
	["Open Chest #4 on Il Molise", "Il Molise"],
	["Open Chest #5 on Il Molise", "Il Molise"],
	["Open Chest #6 on Il Molise", "Il Molise"],
	["Open Chest #7 on Il Molise", "Il Molise"],
	["Open Chest #8 on Il Molise", "Il Molise"],
	["Open Chest #9 on Il Molise", "Il Molise"],
	["Open Chest #10 on Il Molise", "Il Molise"],
	["Open Chest #1 on Moongolow", "Moongolow"],
	["Open Chest #2 on Moongolow", "Moongolow"],
	["Open Chest #3 on Moongolow", "Moongolow"],
	["Open Chest #4 on Moongolow", "Moongolow"],
	["Open Chest #5 on Moongolow", "Moongolow"],
	["Open Chest #6 on Moongolow", "Moongolow"],
	["Open Chest #7 on Moongolow", "Moongolow"],
	["Open Chest #8 on Moongolow", "Moongolow"],
	["Open Chest #9 on Moongolow", "Moongolow"],
	["Open Chest #10 on Moongolow", "Moongolow"],
	["Open Chest #1 on Green Acres", "Green Acres"],
	["Open Chest #2 on Green Acres", "Green Acres"],
	["Open Chest #3 on Green Acres", "Green Acres"],
	["Open Chest #4 on Green Acres", "Green Acres"],
	["Open Chest #5 on Green Acres", "Green Acres"],
	["Open Chest #6 on Green Acres", "Green Acres"],
	["Open Chest #7 on Green Acres", "Green Acres"],
	["Open Chest #8 on Green Acres", "Green Acres"],
	["Open Chest #9 on Green Acres", "Green Acres"],
	["Open Chest #10 on Green Acres", "Green Acres"],
	["Open Chest #1 on The Bone Zone", "The Bone Zone"],
	["Open Chest #2 on The Bone Zone", "The Bone Zone"],
	["Open Chest #3 on The Bone Zone", "The Bone Zone"],
	["Open Chest #4 on The Bone Zone", "The Bone Zone"],
	["Open Chest #5 on The Bone Zone", "The Bone Zone"],
	["Open Chest #6 on The Bone Zone", "The Bone Zone"],
	["Open Chest #7 on The Bone Zone", "The Bone Zone"],
	["Open Chest #8 on The Bone Zone", "The Bone Zone"],
	["Open Chest #9 on The Bone Zone", "The Bone Zone"],
	["Open Chest #10 on The Bone Zone", "The Bone Zone"],
	["Open Chest #1 on Boss Rash", "Boss Rash"],
	["Open Chest #2 on Boss Rash", "Boss Rash"],
	["Open Chest #3 on Boss Rash", "Boss Rash"],
	["Open Chest #4 on Boss Rash", "Boss Rash"],
	["Open Chest #5 on Boss Rash", "Boss Rash"],
	["Open Chest #6 on Boss Rash", "Boss Rash"],
	["Open Chest #7 on Boss Rash", "Boss Rash"],
	["Open Chest #8 on Boss Rash", "Boss Rash"],
	["Open Chest #9 on Boss Rash", "Boss Rash"],
	["Open Chest #10 on Boss Rash", "Boss Rash"],
	["Open Chest #1 on Whiteout", "Whiteout"],
	["Open Chest #2 on Whiteout", "Whiteout"],
	["Open Chest #3 on Whiteout", "Whiteout"],
	["Open Chest #4 on Whiteout", "Whiteout"],
	["Open Chest #5 on Whiteout", "Whiteout"],
	["Open Chest #6 on Whiteout", "Whiteout"],
	["Open Chest #7 on Whiteout", "Whiteout"],
	["Open Chest #8 on Whiteout", "Whiteout"],
	["Open Chest #9 on Whiteout", "Whiteout"],
	["Open Chest #10 on Whiteout", "Whiteout"],
	["Open Chest #1 on The Coop", "The Coop"],
	["Open Chest #2 on The Coop", "The Coop"],
	["Open Chest #3 on The Coop", "The Coop"],
	["Open Chest #4 on The Coop", "The Coop"],
	["Open Chest #5 on The Coop", "The Coop"],
	["Open Chest #6 on The Coop", "The Coop"],
	["Open Chest #7 on The Coop", "The Coop"],
	["Open Chest #8 on The Coop", "The Coop"],
	["Open Chest #9 on The Coop", "The Coop"],
	["Open Chest #10 on The Coop", "The Coop"],
	["Open Chest #1 on Space 54", "Space 54"],
	["Open Chest #2 on Space 54", "Space 54"],
	["Open Chest #3 on Space 54", "Space 54"],
	["Open Chest #4 on Space 54", "Space 54"],
	["Open Chest #5 on Space 54", "Space 54"],
	["Open Chest #6 on Space 54", "Space 54"],
	["Open Chest #7 on Space 54", "Space 54"],
	["Open Chest #8 on Space 54", "Space 54"],
	["Open Chest #9 on Space 54", "Space 54"],
	["Open Chest #10 on Space 54", "Space 54"],
	["Open Chest #1 on Carlo Cart", "Carlo Cart"],
	["Open Chest #2 on Carlo Cart", "Carlo Cart"],
	["Open Chest #3 on Carlo Cart", "Carlo Cart"],
	["Open Chest #4 on Carlo Cart", "Carlo Cart"],
	["Open Chest #5 on Carlo Cart", "Carlo Cart"],
	["Open Chest #6 on Carlo Cart", "Carlo Cart"],
	["Open Chest #7 on Carlo Cart", "Carlo Cart"],
	["Open Chest #8 on Carlo Cart", "Carlo Cart"],
	["Open Chest #9 on Carlo Cart", "Carlo Cart"],
	["Open Chest #10 on Carlo Cart", "Carlo Cart"],
	["Open Chest #1 on Laborratory", "Laborratory"],
	["Open Chest #2 on Laborratory", "Laborratory"],
	["Open Chest #3 on Laborratory", "Laborratory"],
	["Open Chest #4 on Laborratory", "Laborratory"],
	["Open Chest #5 on Laborratory", "Laborratory"],
	["Open Chest #6 on Laborratory", "Laborratory"],
	["Open Chest #7 on Laborratory", "Laborratory"],
	["Open Chest #8 on Laborratory", "Laborratory"],
	["Open Chest #9 on Laborratory", "Laborratory"],
	["Open Chest #10 on Laborratory", "Laborratory"],
	["Open Chest #1 on Westwoods", "Westwoods"],
	["Open Chest #2 on Westwoods", "Westwoods"],
	["Open Chest #3 on Westwoods", "Westwoods"],
	["Open Chest #4 on Westwoods", "Westwoods"],
	["Open Chest #5 on Westwoods", "Westwoods"],
	["Open Chest #6 on Westwoods", "Westwoods"],
	["Open Chest #7 on Westwoods", "Westwoods"],
	["Open Chest #8 on Westwoods", "Westwoods"],
	["Open Chest #9 on Westwoods", "Westwoods"],
	["Open Chest #10 on Westwoods", "Westwoods"],
	["Open Chest #1 on Bat Country", "Bat Country"],
	["Open Chest #2 on Bat Country", "Bat Country"],
	["Open Chest #3 on Bat Country", "Bat Country"],
	["Open Chest #4 on Bat Country", "Bat Country"],
	["Open Chest #5 on Bat Country", "Bat Country"],
	["Open Chest #6 on Bat Country", "Bat Country"],
	["Open Chest #7 on Bat Country", "Bat Country"],
	["Open Chest #8 on Bat Country", "Bat Country"],
	["Open Chest #9 on Bat Country", "Bat Country"],
	["Open Chest #10 on Bat Country", "Bat Country"],
	["Open Chest #1 on Astral Stair", "Astral Stair"],
	["Open Chest #2 on Astral Stair", "Astral Stair"],
	["Open Chest #3 on Astral Stair", "Astral Stair"],
	["Open Chest #4 on Astral Stair", "Astral Stair"],
	["Open Chest #5 on Astral Stair", "Astral Stair"],
	["Open Chest #6 on Astral Stair", "Astral Stair"],
	["Open Chest #7 on Astral Stair", "Astral Stair"],
	["Open Chest #8 on Astral Stair", "Astral Stair"],
	["Open Chest #9 on Astral Stair", "Astral Stair"],
	["Open Chest #10 on Astral Stair", "Astral Stair"],
	["Open Chest #1 on Mazerella", "Mazerella"],
	["Open Chest #2 on Mazerella", "Mazerella"],
	["Open Chest #3 on Mazerella", "Mazerella"],
	["Open Chest #4 on Mazerella", "Mazerella"],
	["Open Chest #5 on Mazerella", "Mazerella"],
	["Open Chest #6 on Mazerella", "Mazerella"],
	["Open Chest #7 on Mazerella", "Mazerella"],
	["Open Chest #8 on Mazerella", "Mazerella"],
	["Open Chest #9 on Mazerella", "Mazerella"],
	["Open Chest #10 on Mazerella", "Mazerella"],
	["Open Chest #1 on Tiny Bridge", "Tiny Bridge"],
	["Open Chest #2 on Tiny Bridge", "Tiny Bridge"],
	["Open Chest #3 on Tiny Bridge", "Tiny Bridge"],
	["Open Chest #4 on Tiny Bridge", "Tiny Bridge"],
	["Open Chest #5 on Tiny Bridge", "Tiny Bridge"],
	["Open Chest #6 on Tiny Bridge", "Tiny Bridge"],
	["Open Chest #7 on Tiny Bridge", "Tiny Bridge"],
	["Open Chest #8 on Tiny Bridge", "Tiny Bridge"],
	["Open Chest #9 on Tiny Bridge", "Tiny Bridge"],
	["Open Chest #10 on Tiny Bridge", "Tiny Bridge"],
	["Open Chest #1 on Mt.Moonspell", "Mt.Moonspell"],
	["Open Chest #2 on Mt.Moonspell", "Mt.Moonspell"],
	["Open Chest #3 on Mt.Moonspell", "Mt.Moonspell"],
	["Open Chest #4 on Mt.Moonspell", "Mt.Moonspell"],
	["Open Chest #5 on Mt.Moonspell", "Mt.Moonspell"],
	["Open Chest #6 on Mt.Moonspell", "Mt.Moonspell"],
	["Open Chest #7 on Mt.Moonspell", "Mt.Moonspell"],
	["Open Chest #8 on Mt.Moonspell", "Mt.Moonspell"],
	["Open Chest #9 on Mt.Moonspell", "Mt.Moonspell"],
	["Open Chest #10 on Mt.Moonspell", "Mt.Moonspell"],
	["Open Chest #1 on Lake Foscari", "Lake Foscari"],
	["Open Chest #2 on Lake Foscari", "Lake Foscari"],
	["Open Chest #3 on Lake Foscari", "Lake Foscari"],
	["Open Chest #4 on Lake Foscari", "Lake Foscari"],
	["Open Chest #5 on Lake Foscari", "Lake Foscari"],
	["Open Chest #6 on Lake Foscari", "Lake Foscari"],
	["Open Chest #7 on Lake Foscari", "Lake Foscari"],
	["Open Chest #8 on Lake Foscari", "Lake Foscari"],
	["Open Chest #9 on Lake Foscari", "Lake Foscari"],
	["Open Chest #10 on Lake Foscari", "Lake Foscari"],
	["Open Chest #1 on Abyss Foscari", "Abyss Foscari"],
	["Open Chest #2 on Abyss Foscari", "Abyss Foscari"],
	["Open Chest #3 on Abyss Foscari", "Abyss Foscari"],
	["Open Chest #4 on Abyss Foscari", "Abyss Foscari"],
	["Open Chest #5 on Abyss Foscari", "Abyss Foscari"],
	["Open Chest #6 on Abyss Foscari", "Abyss Foscari"],
	["Open Chest #7 on Abyss Foscari", "Abyss Foscari"],
	["Open Chest #8 on Abyss Foscari", "Abyss Foscari"],
	["Open Chest #9 on Abyss Foscari", "Abyss Foscari"],
	["Open Chest #10 on Abyss Foscari", "Abyss Foscari"],
	["Open Chest #1 on Ante Chamber", "Ante Chamber"],
	["Open Chest #2 on Ante Chamber", "Ante Chamber"],
	["Open Chest #3 on Ante Chamber", "Ante Chamber"],
	["Open Chest #4 on Ante Chamber", "Ante Chamber"],
	["Open Chest #5 on Ante Chamber", "Ante Chamber"],
	["Open Chest #6 on Ante Chamber", "Ante Chamber"],
	["Open Chest #7 on Ante Chamber", "Ante Chamber"],
	["Open Chest #8 on Ante Chamber", "Ante Chamber"],
	["Open Chest #9 on Ante Chamber", "Ante Chamber"],
	["Open Chest #10 on Ante Chamber", "Ante Chamber"],
	["Open Chest #1 on Room 1665", "Room 1665"],
	["Open Chest #2 on Room 1665", "Room 1665"],
	["Open Chest #3 on Room 1665", "Room 1665"],
	["Open Chest #4 on Room 1665", "Room 1665"],
	["Open Chest #5 on Room 1665", "Room 1665"],
	["Open Chest #6 on Room 1665", "Room 1665"],
	["Open Chest #7 on Room 1665", "Room 1665"],
	["Open Chest #8 on Room 1665", "Room 1665"],
	["Open Chest #9 on Room 1665", "Room 1665"],
	["Open Chest #10 on Room 1665", "Room 1665"],
	["Open Chest #1 on Neo Galuga", "Neo Galuga"],
	["Open Chest #2 on Neo Galuga", "Neo Galuga"],
	["Open Chest #3 on Neo Galuga", "Neo Galuga"],
	["Open Chest #4 on Neo Galuga", "Neo Galuga"],
	["Open Chest #5 on Neo Galuga", "Neo Galuga"],
	["Open Chest #6 on Neo Galuga", "Neo Galuga"],
	["Open Chest #7 on Neo Galuga", "Neo Galuga"],
	["Open Chest #8 on Neo Galuga", "Neo Galuga"],
	["Open Chest #9 on Neo Galuga", "Neo Galuga"],
	["Open Chest #10 on Neo Galuga", "Neo Galuga"],
	["Open Chest #1 on Hectic Highway", "Hectic Highway"],
	["Open Chest #2 on Hectic Highway", "Hectic Highway"],
	["Open Chest #3 on Hectic Highway", "Hectic Highway"],
	["Open Chest #4 on Hectic Highway", "Hectic Highway"],
	["Open Chest #5 on Hectic Highway", "Hectic Highway"],
	["Open Chest #6 on Hectic Highway", "Hectic Highway"],
	["Open Chest #7 on Hectic Highway", "Hectic Highway"],
	["Open Chest #8 on Hectic Highway", "Hectic Highway"],
	["Open Chest #9 on Hectic Highway", "Hectic Highway"],
	["Open Chest #10 on Hectic Highway", "Hectic Highway"],
	["Open Chest #1 on Ode to Castlevania", "Ode to Castlevania"],
	["Open Chest #2 on Ode to Castlevania", "Ode to Castlevania"],
	["Open Chest #3 on Ode to Castlevania", "Ode to Castlevania"],
	["Open Chest #4 on Ode to Castlevania", "Ode to Castlevania"],
	["Open Chest #5 on Ode to Castlevania", "Ode to Castlevania"],
	["Open Chest #6 on Ode to Castlevania", "Ode to Castlevania"],
	["Open Chest #7 on Ode to Castlevania", "Ode to Castlevania"],
	["Open Chest #8 on Ode to Castlevania", "Ode to Castlevania"],
	["Open Chest #9 on Ode to Castlevania", "Ode to Castlevania"],
	["Open Chest #10 on Ode to Castlevania", "Ode to Castlevania"],
	["Open Chest #1 on Polus Replica", "Polus Replica"],
	["Open Chest #2 on Polus Replica", "Polus Replica"],
	["Open Chest #3 on Polus Replica", "Polus Replica"],
	["Open Chest #4 on Polus Replica", "Polus Replica"],
	["Open Chest #5 on Polus Replica", "Polus Replica"],
	["Open Chest #6 on Polus Replica", "Polus Replica"],
	["Open Chest #7 on Polus Replica", "Polus Replica"],
	["Open Chest #8 on Polus Replica", "Polus Replica"],
	["Open Chest #9 on Polus Replica", "Polus Replica"],
	["Open Chest #10 on Polus Replica", "Polus Replica"],
	["Open Chest #1 on Emerald Diorama", "Emerald Diorama"],
	["Open Chest #2 on Emerald Diorama", "Emerald Diorama"],
	["Open Chest #3 on Emerald Diorama", "Emerald Diorama"],
	["Open Chest #4 on Emerald Diorama", "Emerald Diorama"],
	["Open Chest #5 on Emerald Diorama", "Emerald Diorama"],
	["Open Chest #6 on Emerald Diorama", "Emerald Diorama"],
	["Open Chest #7 on Emerald Diorama", "Emerald Diorama"],
	["Open Chest #8 on Emerald Diorama", "Emerald Diorama"],
	["Open Chest #9 on Emerald Diorama", "Emerald Diorama"],
	["Open Chest #10 on Emerald Diorama", "Emerald Diorama"]
]

kill_enemies = [
	["Kill Pipeestrello", "Enemies"],
	["Kill Zombie", "Enemies"],
	["Kill Skeleton", "Enemies"],
	["Kill Ghost", "Enemies"],
	["Kill Mudman", "Enemies"],
	["Kill Giant Bat", "Enemies"],
	["Kill Werewolf", "Enemies"],
	["Kill Mantichana", "Enemies"],
	["Kill Big Mummy", "Enemies"],
	["Kill Flower Wall", "Enemies"],
	["Kill Venus", "Enemies"],
	["Kill Dust Elemental", "Enemies"],
	["Kill Musc Musc", "Enemies"],
	["Kill Mummy", "Enemies"],
	["Kill Testa di Mano", "Enemies"],
	["Kill Sneaky Head", "Enemies"],
	["Kill Lionhead", "Enemies"],
	["Kill Undead Witch", "Enemies"],
	["Kill Undead Sassy Witch", "Enemies"],
	["Kill Skullone", "Enemies"],
	["Kill Merdusa", "Enemies"],
	["Kill Merman", "Enemies"],
	["Kill Lizard Pawn", "Enemies"],
	["Kill Milk Elemental", "Enemies"],
	["Kill Lizard Rook", "Enemies"],
	["Kill Skeleton Ninja", "Enemies"],
	["Kill Minotaur", "Enemies"],
	["Kill Twin Demons", "Enemies"],
	["Kill Twin Snakes", "Enemies"],
	["Kill Melone", "Enemies"],
	["Kill Archon Ascia", "Enemies"],
	["Kill Lost Twin", "Enemies"],
	["Kill Archon Lancia", "Enemies"],
	["Kill Tritont", "Enemies"],
	["Kill Big Golem", "Enemies"],
	["Kill Skelewing", "Enemies"],
	["Kill Sword Guardian", "Enemies"],
	["Kill Gallotrice", "Enemies"],
	["Kill Skullino", "Enemies"],
	["Kill Skulorosso", "Enemies"],
	["Kill Scarleton", "Enemies"],
	["Kill Ghiavolo", "Enemies"],
	["Kill Bloodbath", "Enemies"],
	["Kill Impefinger", "Enemies"],
	["Kill Dragon Shrimp", "Enemies"],
	["Kill Harzia", "Enemies"],
	["Kill Undead Mage", "Enemies"],
	["Kill Archon Spada", "Enemies"],
	["Kill Archon Disco", "Enemies"],
	["Kill Manticore", "Enemies"],
	["Kill Meat Golem", "Enemies"],
	["Kill Tetrabrachia", "Enemies"],
	["Kill Succubus", "Enemies"],
	["Kill Archon Fiamma", "Enemies"],
	["Kill Archon Rame", "Enemies"],
	["Kill Archon Oro", "Enemies"],
	["Kill Demon Beast", "Enemies"],
	["Kill Demon Priest", "Enemies"],
	["Kill Archdemon", "Enemies"],
	["Kill Stage Killer", "Enemies"],
	["Kill Fallen Cherub", "Enemies"],
	["Kill Fallen Cherubbello", "Enemies"],
	["Kill Fallen Throne", "Enemies"],
	["Kill Trinacria", "Enemies"],
	["Kill Reaper Trainee", "Enemies"],
	["Kill Sad Molisano", "Enemies"],
	["Kill Cute Molisano", "Enemies"],
	["Kill Happy Molisano", "Enemies"],
	["Kill Old Molisano", "Enemies"],
	["Kill Dead Molisano", "Enemies"],
	["Kill Serpentvine", "Enemies"],
	["Kill Sig.ra Blu", "Enemies"],
	["Kill Non-Giant Enemy Crab", "Enemies"],
	["Kill Nightshade", "Enemies"],
	["Kill Garlic", "Enemies"],
	["Kill Unknown", "Enemies"],
	["Kill Twin Skulls", "Enemies"],
	["Kill Skeleton Panther", "Enemies"],
	["Kill Giant Skeleton", "Enemies"],
	["Kill Skeletone", "Enemies"],
	["Kill Tri-Anchors", "Enemies"],
	["Kill Miragellos", "Enemies"],
	["Kill Madd-Onna", "Enemies"],
	["Kill Menta Elemental", "Enemies"],
	["Kill Bambaman", "Enemies"],
	["Kill Chickenfantry", "Enemies"],
	["Kill Cockreliutennant", "Enemies"],
	["Kill Chik", "Enemies"],
	["Kill Egge", "Enemies"],
	["Kill Pol.lo Rosso", "Enemies"],
	["Kill Abraxas", "Enemies"],
	["Kill Abraxas Phronesis", "Enemies"],
	["Kill Abraxas Dynamis", "Enemies"],
	["Kill Moon Duck", "Enemies"],
	["Kill Space Pickle", "Enemies"],
	["Kill Moon Rabbit", "Enemies"],
	["Kill Space Ant Onion", "Enemies"],
	["Kill ECMASlime", "Enemies"],
	["Kill Gala Invader", "Enemies"],
	["Kill Sinistronz", "Enemies"],
	["Kill Bounty Hunter", "Enemies"],
	["Kill Holy Circuit Creations", "Enemies"],
	["Kill Space Hunter", "Enemies"],
	["Kill Tri-Blunder", "Enemies"],
	["Kill Barm", "Enemies"],
	["Kill Squillers", "Enemies"],
	["Kill Goldie", "Enemies"],
	["Kill Gamblin", "Enemies"],
	["Kill Ghoulette", "Enemies"],
	["Kill Gambergar", "Enemies"],
	["Kill Toll", "Enemies"],
	["Kill Card Sharp", "Enemies"],
	["Kill Dandybrine", "Enemies"],
	["Kill Daimon", "Enemies"],
	["Kill Valentine", "Enemies"],
	["Kill Astral Elemental", "Enemies"],
	["Kill Undead Stars", "Enemies"],
	["Kill Astral Curtain", "Enemies"],
	["Kill Cosmic Egg", "Enemies"],
	["Kill Torino", "Enemies"],
	["Kill Joyatauro", "Enemies"],
	["Kill AccumulaTori", "Enemies"],
	["Kill Ska'sa Ka'sos", "Enemies"],
	["Kill Spiritello", "Enemies"],
	["Kill Tsuchinoko", "Enemies"],
	["Kill Kamaitachi", "Enemies"],
	["Kill Raiju", "Enemies"],
	["Kill Yamamba", "Enemies"],
	["Kill Mikoshinyudo", "Enemies"],
	["Kill Tengu", "Enemies"],
	["Kill Thunderous Oni", "Enemies"],
	["Kill Windy Oni", "Enemies"],
	["Kill Tsuchigumo", "Enemies"],
	["Kill Chompo", "Enemies"],
	["Kill Brownie", "Enemies"],
	["Kill Ceffoose", "Enemies"],
	["Kill Hill Trow", "Enemies"],
	["Kill Sea Trow", "Enemies"],
	["Kill Wiseparke", "Enemies"],
	["Kill Nutmeg", "Enemies"],
	["Kill Vulvio", "Enemies"],
	["Kill Lammuga", "Enemies"],
	["Kill Njuggles", "Enemies"],
	["Kill Sam the Sundown Clown", "Enemies"],
	["Kill Notadam", "Enemies"],
	["Kill Crocifriggitore", "Enemies"],
	["Kill Missing Church", "Enemies"],
	["Kill Green Knight", "Enemies"],
	["Kill Ghostly Apparition", "Enemies"],
	["Kill Average Hag", "Enemies"],
	["Kill Maronna", "Enemies"],
	["Kill Hand of Glory", "Enemies"],
	["Kill Cauld", "Enemies"],
	["Kill Redusa Head", "Enemies"],
	["Kill Blood Moss", "Enemies"],
	["Kill Rotting Ghoul", "Enemies"],
	["Kill Burning Skull", "Enemies"],
	["Kill Snek", "Enemies"],
	["Kill Meatball", "Enemies"],
	["Kill Lost Head", "Enemies"],
	["Kill Frozen Meatball", "Enemies"],
	["Kill Cold Cauld", "Enemies"],
	["Kill Edna", "Enemies"],
	["Kill Well Dweller", "Enemies"],
	["Kill Wet Njuggles", "Enemies"],
	["Kill Crocifriggitone", "Enemies"],
	["Kill Still Notadam", "Enemies"],
	["Kill Fomorians", "Enemies"],
	["Kill Glove of Glory", "Enemies"],
	["Kill Maronna Meea", "Enemies"],
	["Kill Brainoid", "Enemies"],
	["Kill Frijjitello", "Enemies"],
	["Kill Shapeunshifter", "Enemies"],
	["Kill Space Apparition", "Enemies"],
	["Kill Mocholo", "Enemies"],
	["Kill Spotter", "Enemies"],
	["Kill Sponkey", "Enemies"],
	["Kill Victor Frankenstein", "Enemies"],
	["Kill Martian Face", "Enemies"],
	["Kill Steroid", "Enemies"],
	["Kill Trip Trop", "Enemies"],
	["Kill G062T", "Enemies"],
	["Kill Ledder", "Enemies"],
	["Kill Greeder", "Enemies"],
	["Kill Evil Snowman", "Enemies"],
	["Kill Warlord", "Enemies"],
	["Kill Alien Centipede", "Enemies"],
	["Kill Human Faced Dog", "Enemies"],
	["Kill Garth", "Enemies"],
	["Kill Ball Walker", "Enemies"],
	["Kill Flight Zako", "Enemies"],
	["Kill Junkyard Car", "Enemies"],
	["Kill Bugger", "Enemies"],
	["Kill Bundle", "Enemies"],
	["Kill Poisonous Insect Gel", "Enemies"],
	["Kill Zako Alien", "Enemies"],
	["Kill Gigafly", "Enemies"],
	["Kill Mutant Crawler", "Enemies"],
	["Kill Gulcan Tank", "Enemies"],
	["Kill Metal Alien", "Enemies"],
	["Kill M78", "Enemies"],
	["Kill Kimkoh", "Enemies"],
	["Kill Hellrider", "Enemies"],
	["Kill Flying Zombie", "Enemies"],
	["Kill Bitterfly", "Enemies"],
	["Kill Yorick", "Enemies"],
	["Kill Fishman", "Enemies"],
	["Kill Dullahan", "Enemies"],
	["Kill Moldy Corpse", "Enemies"],
	["Kill Warg", "Enemies"],
	["Kill Gurkha Knife Master", "Enemies"],
	["Kill Disc Armor", "Enemies"],
	["Kill Valhalla Knight", "Enemies"],
	["Kill Flea Armor", "Enemies"],
	["Kill Flea Rider", "Enemies"],
	["Kill Spittle Bone", "Enemies"],
	["Kill Persephone", "Enemies"],
	["Kill Axe Armor", "Enemies"],
	["Kill Bone Ark", "Enemies"],
	["Kill Bloody Painting", "Enemies"],
	["Kill Bone Golem", "Enemies"],
	["Kill Frozen Shade", "Enemies"],
	["Kill Killer Doll", "Enemies"],
	["Kill Ukoback", "Enemies"],
	["Kill Gorgon", "Enemies"],
	["Kill Amalaric Sniper", "Enemies"],
	["Kill Magic Book", "Enemies"],
	["Kill Hippogyph", "Enemies"],
	["Kill Spectre", "Enemies"],
	["Kill Castle Werewolf", "Enemies"],
	["Kill Malachi", "Enemies"],
	["Kill Ghost (Castlevania DLC)", "Enemies"],
	["Kill Imp", "Enemies"],
	["Kill Harpy", "Enemies"],
	["Kill Alastor", "Enemies"],
	["Kill Rana Combatant", "Enemies"],
	["Kill Alraune", "Enemies"],
	["Kill Skydiver", "Enemies"],
	["Kill Forest Hermit", "Enemies"],
	["Kill Boar Infantry", "Enemies"],
	["Kill Decobat", "Enemies"],
	["Kill Rascal", "Enemies"],
	["Kill Skeleton from Beyond", "Enemies"],
	["Kill Failinis", "Enemies"],
	["Kill Maggot Ball", "Enemies"],
	["Kill Kelpie", "Enemies"],
	["Kill Werewolf from Beyond", "Enemies"],
	["Kill Anti-Ant", "Enemies"],
	["Kill Moch", "Enemies"],
	["Kill Psychic Ogre", "Enemies"],
	["Kill Golden Baum", "Enemies"],
	["Kill Zombalatro", "Enemies"],
	["Kill Jimbats", "Enemies"],
	["Kill Mr Bones", "Enemies"],
	["Kill Spectral Joker", "Enemies"],
	["Kill Moonlover", "Enemies"],
	["Kill Knight of Spades", "Enemies"],
	["Kill Playing Mantis", "Enemies"],
	["Kill Blue Venus", "Enemies"],
	["Kill Levatee Darkasso", "Enemies"],
	["Kill Juda R'kasso", "Enemies"],
	["Kill Levarsee Darkasso", "Enemies"],
	["Kill Shendi Darkasso", "Enemies"],
	["Kill Sphon'Dato Darkasso", "Enemies"],
	["Kill Eh'Lleve-Teh Darkasso", "Enemies"],
	["Kill Sig.ra Rossi", "Enemies"],
	["Kill Jellyfish", "Enemies"],
	["Kill Mignotaur", "Enemies"],
	["Kill The Drowner", "Enemies"],
	["Kill LV128 Golden Bat", "Enemies"],
	["Kill Suspicious Eyes", "Enemies"],
	["Kill Big Bot Gordea", "Enemies"],
	["Kill Taka", "Enemies"],
	["Kill Simondo Belmont", "Enemies"],
	["Kill Big Fuzz", "Enemies"],
	["Kill Devil", "Enemies"],
	["Kill Flea Man", "Enemies"],
	["Kill The Stalker", "Enemies"],
	["Kill Moongolow Atlanteans", "Enemies"],
	["Kill Giant Enemy Crab", "Enemies"],
	["Kill The Trickster", "Enemies"],
	["Kill The Maddener", "Enemies"],
	["Kill The Directer", "Enemies"],
	["Kill Rellyfish", "Enemies"],
	["Kill Je-Ne-Viv", "Enemies"],
	["Kill Bugbear", "Enemies"],
	["Kill Giant Medusa Head", "Enemies"],
	["Kill Behemoth", "Enemies"],
	["Kill Slogra", "Enemies"],
	["Kill Gaibon", "Enemies"],
	["Kill Doppelganger", "Enemies"],
	["Kill Puppet Master", "Enemies"],
	["Kill Blackmore", "Enemies"],
	["Kill Paranoia", "Enemies"],
	["Kill Zephyr", "Enemies"],
	["Kill Abbadon", "Enemies"],
	["Kill Death", "Enemies"],
	["Kill The Creature", "Enemies"],
	["Kill Keremet", "Enemies"],
	["Kill Menace", "Enemies"],
	["Kill Eligor", "Enemies"],
	["Kill Treant", "Enemies"],
	["Kill Spirit Beast", "Enemies"],
	["Kill Specter of Iwanaga-hime", "Enemies"],
	["Kill Earth Dragon", "Enemies"],
	["Kill Iron Maiden", "Enemies"],
	["Kill Living Anguish", "Enemies"],
	["Kill Sketamari", "Enemies"],
	["Kill Sun Atlantean", "Enemies"],
	["Kill Moon Atlantean", "Enemies"],
	["Kill City Atlantean", "Enemies"],
	["Kill Volcano Atlantean", "Enemies"],
	["Kill The Blinder", "Enemies"],
	["Kill Astral Chair", "Enemies"],
	["Kill Poetrait", "Enemies"],
	["Kill Much Much", "Enemies"],
	["Kill Hitotsumekozo", "Enemies"],
	["Kill Kappa", "Enemies"],
	["Kill Poltergeist", "Enemies"],
	["Kill Gold Pile", "Enemies"],
	["Kill Big Oni", "Enemies"],
	["Kill Goshadokuro", "Enemies"],
	["Kill Sammy the Caterpillar", "Enemies"],
	["Kill Fungoman", "Enemies"],
	["Kill Corpseweed", "Enemies"],
	["Kill Bone Pillar", "Enemies"],
	["Kill Gold Jellys", "Enemies"],
	["Kill Mantichana Idol", "Enemies"],
	["Kill Jastor", "Enemies"],
	["Kill Mushroulette", "Enemies"],
	["Kill 17th Collossus", "Enemies"],
	["Kill Pinthot & Coldellini", "Enemies"],
	["Kill Meat Bean", "Enemies"],
	["Kill Suspicio", "Enemies"],
	["Kill Jiang shi", "Enemies"],
	["Kill Gergoth", "Enemies"],
	["Kill Malevolent Door Spirit", "Enemies"],
	["Kill Flower Pot", "Enemies"],
	["Kill Spirit (Emerald DLC)", "Enemies"],
	["Kill Foo'Ori Darkasso", "Enemies"],
	["Kill The Reaper", "Enemies"],
	["Kill Nesufritto", "Enemies"],
	["Kill Hag", "Enemies"],
	["Kill The Ender", "Enemies"],
	["Kill Mimic Season One", "Enemies"],
	["Kill Mimic Season Two", "Enemies"],
	["Kill Mimic Season Three", "Enemies"],
	["Kill Lord Ghost", "Enemies"],
	["Kill Tanuki", "Enemies"],
	["Kill Orochimario", "Enemies"],
	["Kill Avatar of Gaea", "Enemies"],
	["Kill Minotaur (Castlevania DLC)", "Enemies"],
	["Kill Small Blind", "Enemies"],
	["Kill Big Blind", "Enemies"],
	["Kill The Ox", "Enemies"],
	["Kill The Manacle", "Enemies"],
	["Kill The Wall", "Enemies"],
	["Kill Crimson Heart", "Enemies"],
	["Kill Kizzune", "Enemies"],
	["Kill Skelegem", "Enemies"]
]

secret_characters = [
	"Exdash",
	"Toastie",
	"Smith IV",
	"Random",
	"Marrabbio",
	"Avatar",
	"Minnah",
	"Leda",
	"Cosmo",
	"Trouser",
	"Gains",
	"Gyorunton",
	"Red Death",
	"Bats",
	"Rose",
	"Scorej-Oni",
	"Gyoruntin",
	"Young Maria",
	"Familiar",
	"Innocent",
	"Cornell",
	"Ferryman",
	"Master Librarian",
	"Hammer",
	"Wind",
	"Jonathan & Charlotte",
	"Charlotte & Jonathan",
	"Stella & Loretta",
	"Loretta & Stella",
	"Stella",
	"Loretta",
	"Brauner",
	"Soleil",
	"Dario",
	"Dmitrii",
	"Celia",
	"Graham",
	"Joachim",
	"Walter",
	"Carmilla",
	"Olrox",
	"Cave Troll",
	"Axe Armor",
	"Frozenshade",
	"Succubus",
	"Keremet",
	"Sniper",
	"Blackmore",
	"Malphas",
	"Death",
	"Galamoth",
	"Lolo, Hiss, Meow, and Purr",
	"Kina",
	"Imakoo",
	"Door"
]

megalo_characters = [
	"Megalo Syuuto",
	"Je-Ne-Viv",
	"Megalo Impostor",
	"Megalo Elizabeth",
	"Megalo Olrox",
	"Megalo Dracula"
]

unfair_characters = [
	"Peppino",
	"MissingN▯",
	"Space Dette",
	"Megalo Menya",
	"Ghost",
	"Fleaman",
	"Megalo Death",
	"Chaos"
]

base_characters = [
	"Antonio Belpaese",
	"Imelda Belpaese",
	"Pasqualina Belpaese",
	"Gennaro Belpaese",
	"Arca Ladonna",
	"Porta Ladonna",
	"Lama Ladonna",
	"Poe Ratcho",
	"Suor Clerici",
	"Dommario",
	"Krochi Freetto",
	"Christine Davain",
	"Pugnala Provola",
	"Giovanna Grana",
	"Poppea Pecorina",
	"Concetta Caciotta",
	"Mortaccio",
	"Yatta Cavallo",
	"Bianca Ramba",
	"O'Sole Meeo",
	"Sir Ambrojoe",
	"Iguana Gallo Valletto",
	"Divano Thelma",
	"Zi'Assunta Belpaese",
	"Exdash Exiviiq",
	"Toastie",
	"Smith IV",
	"Random",
	"Boon Marrabbio",
	"Avatar Infernas",
	"Minnah Mannarah",
	"Leda",
	"Cosmo Pavone",
	"Peppino",
	"Big Trouser",
	"missingN",
	"Gains Boros",
	"Gyorunton",
	"Mask of the Red Death",
	"Queen Sigma",
	"Bat Robbert",
	"Zi'Appunta Belpaese",
	"She-Moon Eeta",
	"Santa Ladonna",
	"Gazebo",
	"Chula-Reh",
	"Space Dude",
	"Bats Bats Bats",
	"Rose De Infernas",
	"Torino",
	"Scorej-Oni",
	"Gyoruntin",
	"Secretino",
	"Space Dette",
	"Genya Arikado"
]

moonspell_characters = [
	"Miang Moonspell",
	"Menya Moonspell",
	"Syuuto Moonspell",
	"Babi-Onna",
	"McCoy-Oni",
	"Megalo Menya Moonspell",
	"Megalo Syuuto Moonspell",
	"Gab'Et-Oni"
]

foscari_characters = [
	"Eleanor Uziron",
	"Maruto Cuts",
	"Keitha Muort",
	"Luminaire Foscari",
	"Genevieve Gruyère",
	"Je-Ne-Viv",
	"Sammy",
	"Rottin'Ghoul"
]

amongus_characters = [
	"Crewmate Dino",
	"Engineer Gino",
	"Ghost Lino",
	"Shapeshifter Nino",
	"Guardian Pina",
	"Impostor Rina",
	"Scientist Mina",
	"Horse",
	"Megalo Impostor Rina"
]

operation_guns_characters = [
	"Bill Rizer",
	"Lance Bean",
	"Ariana",
	"Lucia Zero",
	"Brad Fang",
	"Browny",
	"Sheena Etranzi",
	"Probotector",
	"Stanley",
	"Newt Plissken",
	"Colonel Bahamut",
	"Simondo"
]

castlevania_characters = [
	"Leon Belmont",
	"Sonia Belmont",
	"Trevor Belmont",
	"Christopher Belmont",
	"Simon Belmont",
	"Juste Belmont",
	"Richter Belmont",
	"Julius Belmont",
	"Grant Danasty",
	"Quincy Morris",
	"John Morris",
	"Jonathan Morris",
	"Maxim Kischine",
	"Henry",
	"Soma Cruz",
	"Vlad Tepes Dracula",
	"Charlotte Aulin",
	"Sypha Belnades",
	"Julia Laforeze",
	"Carrie Fernandez",
	"Yoko Belnades",
	"Rinaldo Gandolfi",
	"Mina Hakuba",
	"Elizabeth Bartley",
	"Alucard",
	"Reinhardt Schneider",
	"Eric Lecarde",
	"Isaac",
	"Hector",
	"Sara Trantoul",
	"Vincent Dorin",
	"Maria Renard",
	"Shanoa",
	"Albus",
	"Lisa",
	"Shaft",
	"Saint Germain",
	"Nathan Graves",
	"Cornell",
	"Barlowe",
	"Young Maria Renard",
	"Familiar",
	"Innocent Devil",
	"Blue Crescent Moon Cornell",
	"Ferryman",
	"Librarian",
	"Hammer",
	"Wind",
	"Hugh Baldwin",
	"Morris Baldwin",
	"Annette",
	"Tera",
	"Jonathan & Charlotte",
	"Charlotte & Jonathan",
	"Stella & Loretta Lecarde",
	"Loretta & Stella Lecarde",
	"Stella Lecarde",
	"Loretta Lecarde",
	"Brauner",
	"Soleil Belmont",
	"Dario Bossi",
	"Dmitri Blinov",
	"Celia Fortner",
	"Graham Jones",
	"Joachim",
	"Walter",
	"Carmilla",
	"Cave Troll",
	"Fleaman",
	"Axe Armor",
	"Frozenshade",
	"Amalaric Sniper",
	"Stone Skull",
	"Sword Ruler",
	"Persephone",
	"Keremet",
	"Astarte",
	"Drolta",
	"Actrise",
	"Atlantis Shrine Wizard",
	"Succubus",
	"Fake Trio",
	"Slogra and Gaibon",
	"Zephyr",
	"Jiangshi",
	"Blackmore",
	"Count Olrox",
	"Malphas",
	"Death",
	"Galamoth",
	"Megalo Elizabeth Bartley",
	"Megalo Olrox",
	"Megalo Death",
	"Megalo Dracula",
	"Chaos",
	"Gaibon and Slogra",
	"Slogra",
	"Kid Dracula",
	"Aeon",
	"Desmond Belmont",
	"Dolores Belmont",
	"Zoe Belmont",
	"Fishman",
	"Fake Trevor",
	"Fake Sypha",
	"Fake Grant"
]

emerald_characters = [
	"Tsunanori Mido",
	"Bonnie Blair",
	"Formina Franklyn",
	"Diva No. 5",
	"Ameya Aisling",
	"Siugnas",
	"Final Emperor",
	"Dolores",
	"Macha",
	"Lita",
	"Kugutsu",
	"Mr. S",
	"Lolo, Hiss, Meow and Purr",
	"Kina",
	"Imakoo",
	"Malevolent Door Spirit"
]

balatro_characters = [
	"Jimbo",
	"Canio",
	"Chicot",
	"Perkeo"
]

normal_stages = [
	"Mad Forest",
	"Inlaid Library",
	"Dairy Plant",
	"Gallo Tower",
	"Cappella Magna",
	"Westwoods",
	"Mazerella"
]

bonus_stages = [
	"Il Molise",
	"Moongolow",
	"Whiteout",
	"The Coop",
	"Space 54",
	"Carlo Cart"
]

challenge_stages = [
	"Eudaimonia M.",
	"Green Acres",
	"The Bone Zone",
	"Boss Rash",
	"Laborratory",
	"Bat Country",
	"Astral Stair",
	"Tiny Bridge",
	"Room 1665"
]

moonspell_stages = [
	"Mt.Moonspell"
]

foscari_stages = [
	"Lake Foscari",
	"Abyss Foscari"
]

amongus_stages = [
	"Polus Replica"
]

operation_guns_stages = [
	"Neo Galuga",
	"Hectic Highway"
]

castlevania_stages = [
	"Ode to Castlevania"
]

emerald_stages = [
	"Emerald Diorama"
]

balatro_stages = [
	"Ante Chamber"
]

EUDAI = "Eudaimonia M."

all_stages = normal_stages + bonus_stages + challenge_stages + moonspell_stages + foscari_stages + amongus_stages + operation_guns_stages + castlevania_stages + emerald_stages + balatro_stages

all_characters = base_characters + moonspell_characters + foscari_characters + amongus_characters + operation_guns_characters + castlevania_characters + emerald_characters + balatro_characters

enemy_map = {
	"Pipeestrello": ["Mad Forest", "Gallo Tower", "Cappella Magna", "Green Acres", "Boss Rash", "Bat Country", "Tiny Bridge", "Mt.Moonspell", "Polus Replica", "Ante Chamber", "Whiteout", "Inlaid Library", "Carlo Cart", "Eudaimonia M."],
	"Zombie": ["Mad Forest", "Mt.Moonspell", "Eudaimonia M.", "Green Acres"],
	"Skeleton": ["Mad Forest", "Dairy Plant", "Gallo Tower", "The Bone Zone", "Boss Rash", "Eudaimonia M.", "Green Acres"],
	"Ghost": ["Mad Forest", "Inlaid Library", "Gallo Tower", "Whiteout", "Tiny Bridge", "Moongolow", "Boss Rash", "Astral Stair", "Eudaimonia M.", "Ode to Castlevania", "Green Acres"],
	"Mudman": ["Mad Forest", "Astral Stair", "Green Acres"],
	"Giant Bat": ["Mad Forest", "Inlaid Library", "Tiny Bridge", "Bat Country", "Boss Rash", "Carlo Cart", "Ode to Castlevania", "Green Acres"],
	"Werewolf": ["Mad Forest", "Boss Rash", "Green Acres"],
	"Mantichana": ["Mad Forest", "Boss Rash", "Green Acres"],
	"Big Mummy": ["Mad Forest", "Astral Stair", "Boss Rash", "Green Acres", "Inlaid Library"],
	"Flower Wall": ["Mad Forest", "Mt.Moonspell", "Polus Replica", "Green Acres"],
	"Venus": ["Mad Forest", "Boss Rash", "Green Acres"],
	"Dust Elemental": ["Inlaid Library", "Boss Rash", "Laborratory", "Eudaimonia M.", "Green Acres"],
	"Musc Musc": ["Inlaid Library", "Space 54", "Boss Rash", "Laborratory", "Green Acres"],
	"Mummy": ["Inlaid Library", "Astral Stair", "Eudaimonia M.", "Ode to Castlevania", "Green Acres"],
	"Testa di Mano": ["Inlaid Library", "Gallo Tower", "Room 1665", "Eudaimonia M.", "Green Acres"],
	"Sneaky Head": ["Inlaid Library", "Boss Rash", "Mazerella", "Moongolow", "Tiny Bridge", "Green Acres"],
	"Lionhead": ["Inlaid Library", "Boss Rash", "Carlo Cart", "Green Acres"],
	"Undead Witch": ["Inlaid Library", "Green Acres"],
	"Undead Sassy Witch": ["Inlaid Library", "Boss Rash", "Green Acres"],
	"Skullone": ["Inlaid Library", "The Bone Zone", "Gallo Tower", "Boss Rash", "Tiny Bridge", "Green Acres"],
	"Merdusa": ["Inlaid Library", "Boss Rash", "Green Acres"],
	"Merman": ["Dairy Plant", "Laborratory", "Moongolow", "Boss Rash", "Carlo Cart", "Eudaimonia M.", "Green Acres"],
	"Lizard Pawn": ["Dairy Plant", "Laborratory", "Carlo Cart", "Eudaimonia M.", "Green Acres"],
	"Milk Elemental": ["Dairy Plant", "Boss Rash", "Mazerella", "Eudaimonia M.", "Green Acres"],
	"Lizard Rook": ["Dairy Plant", "Laborratory", "Carlo Cart", "Green Acres"],
	"Skeleton Ninja": ["Dairy Plant", "The Bone Zone", "Green Acres"],
	"Minotaur": ["Dairy Plant", "Mazerella", "Ode to Castlevania", "Boss Rash", "Carlo Cart", "Laborratory", "Green Acres"],
	"Twin Demons": ["Dairy Plant", "The Bone Zone", "Carlo Cart", "Green Acres"],
	"Twin Snakes": ["Dairy Plant", "Green Acres"],
	"Melone": ["Dairy Plant", "Green Acres"],
	"Archon Ascia": ["Dairy Plant", "Cappella Magna", "Boss Rash", "Green Acres"],
	"Lost Twin": ["Dairy Plant", "The Bone Zone", "Carlo Cart", "Laborratory", "Green Acres"],
	"Archon Lancia": ["Dairy Plant", "Green Acres"],
	"Tritont": ["Dairy Plant", "Boss Rash", "Green Acres"],
	"Big Golem": ["Dairy Plant", "Astral Stair", "Boss Rash", "Green Acres"],
	"Skelewing": ["Dairy Plant", "Gallo Tower", "The Bone Zone", "Tiny Bridge", "Green Acres"],
	"Sword Guardian": ["Dairy Plant", "Boss Rash", "Green Acres"],
	"Gallotrice": ["Dairy Plant", "Gallo Tower", "Tiny Bridge", "Boss Rash", "Lake Foscari", "Green Acres"],
	"Skullino": ["Gallo Tower", "The Bone Zone", "Tiny Bridge", "Astral Stair", "Eudaimonia M.", "Green Acres"],
	"Skulorosso": ["Gallo Tower", "The Bone Zone", "Eudaimonia M.", "Green Acres"],
	"Scarleton": ["Gallo Tower", "The Bone Zone", "Green Acres"],
	"Ghiavolo": ["Gallo Tower", "Westwoods", "Green Acres"],
	"Bloodbath": ["Gallo Tower", "Green Acres"],
	"Impefinger": ["Gallo Tower", "Tiny Bridge", "Carlo Cart", "Green Acres"],
	"Dragon Shrimp": ["Gallo Tower", "The Bone Zone", "Boss Rash", "Green Acres"],
	"Harzia": ["Gallo Tower", "Boss Rash", "Westwoods", "Mazerella", "Tiny Bridge", "Green Acres"],
	"Undead Mage": ["Gallo Tower", "Green Acres"],
	"Archon Spada": ["Gallo Tower", "Cappella Magna", "Green Acres"],
	"Archon Disco": ["Gallo Tower", "Mazerella", "Boss Rash", "Green Acres"],
	"Manticore": ["Gallo Tower", "Mazerella", "Boss Rash", "Green Acres"],
	"Meat Golem": ["Gallo Tower", "Green Acres"],
	"Tetrabrachia": ["Cappella Magna", "Tiny Bridge", "Green Acres"],
	"Succubus": ["Cappella Magna", "Boss Rash", "Ode to Castlevania", "Green Acres"],
	"Archon Fiamma": ["Cappella Magna", "Green Acres"],
	"Archon Rame": ["Cappella Magna", "Tiny Bridge", "Boss Rash", "Green Acres"],
	"Archon Oro": ["Cappella Magna", "Green Acres"],
	"Demon Beast": ["Cappella Magna", "Green Acres"],
	"Demon Priest": ["Cappella Magna", "Room 1665", "Green Acres"],
	"Archdemon": ["Cappella Magna", "Boss Rash", "Green Acres"],
	"Stage Killer": ["Cappella Magna", "Green Acres"],
	"Fallen Cherub": ["Cappella Magna", "Green Acres"],
	"Fallen Cherubbello": ["Cappella Magna", "Green Acres"],
	"Fallen Throne": ["Cappella Magna", "Green Acres"],
	"Trinacria": ["Cappella Magna", "Boss Rash", "Green Acres"],
	"Reaper Trainee": ["Cappella Magna", "Tiny Bridge", "Eudaimonia M.", "Green Acres"],
	"Sad Molisano": ["Il Molise"],
	"Cute Molisano": ["Il Molise"],
	"Happy Molisano": ["Il Molise"],
	"Old Molisano": ["Il Molise"],
	"Dead Molisano": ["Il Molise"],
	"Serpentvine": ["Moongolow"],
	"Sig.ra Blu": ["Moongolow"],
	"Non-Giant Enemy Crab": ["Moongolow", "Boss Rash"],
	"Nightshade": ["Moongolow", "Boss Rash"],
	"Garlic": ["Moongolow", "Boss Rash"],
	"Unknown": ["Moongolow", "Boss Rash", "Cappella Magna", "Green Acres", "Eudaimonia M."],
	"Twin Skulls": ["The Bone Zone"],
	"Skeleton Panther": ["The Bone Zone"],
	"Giant Skeleton": ["The Bone Zone", "Boss Rash"],
	"Skeletone": ["The Bone Zone"],
	"Tri-Anchors": ["Boss Rash"],
	"Miragellos": ["Whiteout"],
	"Madd-Onna": ["Whiteout"],
	"Menta Elemental": ["Whiteout"],
	"Bambaman": ["Whiteout"],
	"Chickenfantry": ["The Coop"],
	"Cockreliutennant": ["The Coop"],
	"Chik": ["The Coop"],
	"Egge": ["The Coop"],
	"Pol.lo Rosso": ["The Coop"],
	"Abraxas": ["The Coop"],
	"Abraxas Phronesis": ["The Coop"],
	"Abraxas Dynamis": ["The Coop"],
	"Moon Duck": ["Space 54"],
	"Space Pickle": ["Space 54", "Polus Replica"],
	"Moon Rabbit": ["Space 54"],
	"Space Ant Onion": ["Space 54", "Polus Replica"],
	"ECMASlime": ["Space 54"],
	"Gala Invader": ["Space 54"],
	"Sinistronz": ["Space 54"],
	"Bounty Hunter": ["Laborratory"],
	"Holy Circuit Creations": ["Laborratory", "Carlo Cart"],
	"Space Hunter": ["Laborratory"],
	"Tri-Blunder": ["Laborratory"],
	"Barm": ["Westwoods"],
	"Squillers": ["Westwoods"],
	"Goldie": ["Westwoods"],
	"Gamblin": ["Westwoods", "Ante Chamber"],
	"Ghoulette": ["Westwoods", "Ante Chamber"],
	"Gambergar": ["Westwoods"],
	"Toll": ["Westwoods"],
	"Card Sharp": ["Westwoods", "Ante Chamber"],
	"Dandybrine": ["Westwoods"],
	"Daimon": ["Westwoods"],
	"Valentine": ["Westwoods"],
	"Astral Elemental": ["Astral Stair"],
	"Undead Stars": ["Astral Stair"],
	"Astral Curtain": ["Astral Stair"],
	"Cosmic Egg": ["Astral Stair"],
	"Torino": ["Mazerella"],
	"Joyatauro": ["Mazerella"],
	"AccumulaTori": ["Mazerella"],
	"Ska'sa Ka'sos": ["Room 1665"],
	"Spiritello": ["Mt.Moonspell"],
	"Tsuchinoko": ["Mt.Moonspell"],
	"Kamaitachi": ["Mt.Moonspell", "Tiny Bridge"],
	"Raiju": ["Mt.Moonspell"],
	"Yamamba": ["Mt.Moonspell"],
	"Mikoshinyudo": ["Mt.Moonspell"],
	"Tengu": ["Mt.Moonspell"],
	"Thunderous Oni": ["Mt.Moonspell"],
	"Windy Oni": ["Mt.Moonspell"],
	"Tsuchigumo": ["Mt.Moonspell"],
	"Chompo": ["Lake Foscari"],
	"Brownie": ["Lake Foscari"],
	"Ceffoose": ["Lake Foscari"],
	"Hill Trow": ["Lake Foscari"],
	"Sea Trow": ["Lake Foscari"],
	"Wiseparke": ["Lake Foscari"],
	"Nutmeg": ["Lake Foscari"],
	"Vulvio": ["Lake Foscari"],
	"Lammuga": ["Lake Foscari"],
	"Njuggles": ["Lake Foscari"],
	"Sam the Sundown Clown": ["Lake Foscari"],
	"Notadam": ["Lake Foscari"],
	"Crocifriggitore": ["Lake Foscari"],
	"Missing Church": ["Lake Foscari", "Abyss Foscari"],
	"Green Knight": ["Lake Foscari"],
	"Ghostly Apparition": ["Lake Foscari"],
	"Average Hag": ["Lake Foscari"],
	"Maronna": ["Lake Foscari"],
	"Hand of Glory": ["Lake Foscari"],
	"Cauld": ["Abyss Foscari"],
	"Redusa Head": ["Abyss Foscari", "Astral Stair"],
	"Blood Moss": ["Abyss Foscari", "Astral Stair"],
	"Rotting Ghoul": ["Abyss Foscari"],
	"Burning Skull": ["Abyss Foscari"],
	"Snek": ["Abyss Foscari", "Lake Foscari"],
	"Meatball": ["Abyss Foscari"],
	"Lost Head": ["Abyss Foscari"],
	"Frozen Meatball": ["Abyss Foscari"],
	"Cold Cauld": ["Abyss Foscari"],
	"Edna": ["Abyss Foscari"],
	"Well Dweller": ["Abyss Foscari"],
	"Wet Njuggles": ["Abyss Foscari"],
	"Crocifriggitone": ["Abyss Foscari"],
	"Still Notadam": ["Abyss Foscari"],
	"Fomorians": ["Abyss Foscari"],
	"Glove of Glory": ["Abyss Foscari"],
	"Maronna Meea": ["Abyss Foscari"],
	"Brainoid": ["Polus Replica"],
	"Frijjitello": ["Polus Replica"],
	"Shapeunshifter": ["Polus Replica"],
	"Space Apparition": ["Polus Replica"],
	"Mocholo": ["Polus Replica"],
	"Spotter": ["Polus Replica"],
	"Sponkey": ["Polus Replica"],
	"Victor Frankenstein": ["Polus Replica"],
	"Martian Face": ["Polus Replica"],
	"Steroid": ["Polus Replica"],
	"Trip Trop": ["Polus Replica"],
	"G062T": ["Polus Replica"],
	"Ledder": ["Neo Galuga"],
	"Greeder": ["Neo Galuga"],
	"Evil Snowman": ["Neo Galuga", "Hectic Highway"],
	"Warlord": ["Neo Galuga"],
	"Alien Centipede": ["Neo Galuga"],
	"Human Faced Dog": ["Neo Galuga"],
	"Garth": ["Neo Galuga"],
	"Ball Walker": ["Neo Galuga", "Hectic Highway"],
	"Flight Zako": ["Neo Galuga", "Hectic Highway"],
	"Junkyard Car": ["Neo Galuga", "Hectic Highway"],
	"Bugger": ["Neo Galuga"],
	"Bundle": ["Neo Galuga", "Hectic Highway"],
	"Poisonous Insect Gel": ["Neo Galuga"],
	"Zako Alien": ["Neo Galuga"],
	"Gigafly": ["Neo Galuga", "Hectic Highway"],
	"Mutant Crawler": ["Neo Galuga", "Hectic Highway"],
	"Gulcan Tank": ["Neo Galuga", "Hectic Highway"],
	"Metal Alien": ["Neo Galuga", "Hectic Highway"],
	"M78": ["Neo Galuga", "Hectic Highway"],
	"Kimkoh": ["Neo Galuga"],
	"Hellrider": ["Hectic Highway", "Neo Galuga"],
	"Flying Zombie": ["Ode to Castlevania"],
	"Bitterfly": ["Ode to Castlevania"],
	"Yorick": ["Ode to Castlevania"],
	"Fishman": ["Ode to Castlevania"],
	"Dullahan": ["Ode to Castlevania", "Inlaid Library", "Green Acres"],
	"Moldy Corpse": ["Ode to Castlevania"],
	"Warg": ["Ode to Castlevania"],
	"Gurkha Knife Master": ["Ode to Castlevania"],
	"Disc Armor": ["Ode to Castlevania"],
	"Valhalla Knight": ["Ode to Castlevania"],
	"Flea Armor": ["Ode to Castlevania"],
	"Flea Rider": ["Ode to Castlevania"],
	"Spittle Bone": ["Ode to Castlevania"],
	"Persephone": ["Ode to Castlevania"],
	"Axe Armor": ["Ode to Castlevania"],
	"Bone Ark": ["Ode to Castlevania"],
	"Bloody Painting": ["Ode to Castlevania"],
	"Bone Golem": ["Ode to Castlevania"],
	"Frozen Shade": ["Ode to Castlevania"],
	"Killer Doll": ["Ode to Castlevania"],
	"Ukoback": ["Ode to Castlevania"],
	"Gorgon": ["Ode to Castlevania"],
	"Amalaric Sniper": ["Ode to Castlevania"],
	"Magic Book": ["Ode to Castlevania"],
	"Hippogyph": ["Ode to Castlevania"],
	"Spectre": ["Ode to Castlevania"],
	"Castle Werewolf": ["Ode to Castlevania"],
	"Malachi": ["Ode to Castlevania"],
	"Ghost (Castlevania DLC)": ["Ode to Castlevania"],
	"Imp": ["Ode to Castlevania"],
	"Harpy": ["Ode to Castlevania"],
	"Alastor": ["Ode to Castlevania"],
	"Rana Combatant": ["Emerald Diorama"],
	"Alraune": ["Emerald Diorama"],
	"Skydiver": ["Emerald Diorama"],
	"Forest Hermit": ["Emerald Diorama"],
	"Boar Infantry": ["Emerald Diorama"],
	"Decobat": ["Emerald Diorama"],
	"Rascal": ["Emerald Diorama"],
	"Skeleton from Beyond": ["Emerald Diorama"],
	"Failinis": ["Emerald Diorama"],
	"Maggot Ball": ["Emerald Diorama"],
	"Kelpie": ["Emerald Diorama"],
	"Werewolf from Beyond": ["Emerald Diorama"],
	"Anti-Ant": ["Emerald Diorama"],
	"Moch": ["Emerald Diorama"],
	"Psychic Ogre": ["Emerald Diorama"],
	"Golden Baum": ["Emerald Diorama"],
	"Zombalatro": ["Ante Chamber"],
	"Jimbats": ["Ante Chamber"],
	"Mr Bones": ["Ante Chamber"],
	"Spectral Joker": ["Ante Chamber"],
	"Moonlover": ["Ante Chamber"],
	"Knight of Spades": ["Ante Chamber", "Westwoods"],
	"Playing Mantis": ["Ante Chamber"],
	"Blue Venus": ["Ante Chamber"],
	"Levatee Darkasso": ["Mad Forest", "Eudaimonia M.", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna", "Il Molise", "Moongolow", "Green Acres", "The Bone Zone", "Boss Rash", "Whiteout", "The Coop", "Space 54", "Carlo Cart", "Laborratory", "Westwoods", "Bat Country", "Astral Stair", "Mazerella", "Tiny Bridge", "Mt.Moonspell", "Lake Foscari", "Abyss Foscari", "Ante Chamber", "Room 1665", "Neo Galuga", "Hectic Highway", "Ode to Castlevania", "Polus Replica", "Emerald Diorama"],
	"Juda R'kasso": ["Room 1665"],
	"Levarsee Darkasso": ["Mad Forest", "Eudaimonia M.", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna", "Il Molise", "Moongolow", "Green Acres", "The Bone Zone", "Boss Rash", "Whiteout", "The Coop", "Space 54", "Carlo Cart", "Laborratory", "Westwoods", "Bat Country", "Astral Stair", "Mazerella", "Tiny Bridge", "Mt.Moonspell", "Lake Foscari", "Abyss Foscari", "Ante Chamber", "Room 1665", "Neo Galuga", "Hectic Highway", "Ode to Castlevania", "Polus Replica", "Emerald Diorama"],
	"Shendi Darkasso": ["Room 1665"],
	"Sphon'Dato Darkasso": ["Room 1665"],
	"Eh'Lleve-Teh Darkasso": ["Room 1665"],
	"Sig.ra Rossi": ["Inlaid Library", "Astral Stair", "Green Acres"],
	"Jellyfish": ["Dairy Plant", "Moongolow", "Boss Rash", "Laborratory", "Green Acres"],
	"Mignotaur": ["Laborratory", "Green Acres", "Dairy Plant"],
	"The Drowner": ["The Bone Zone", "Carlo Cart", "Boss Rash"],
	"LV128 Golden Bat": ["Bat Country"],
	"Suspicious Eyes": ["Polus Replica"],
	"Big Bot Gordea": ["Neo Galuga", "Hectic Highway"],
	"Taka": ["Neo Galuga", "Hectic Highway"],
	"Simondo Belmont": ["Neo Galuga"],
	"Big Fuzz": ["Neo Galuga"],
	"Devil": ["Ode to Castlevania"],
	"Flea Man": ["Ode to Castlevania"],
	"The Stalker": ["Dairy Plant", "Green Acres", "The Bone Zone", "Carlo Cart", "Boss Rash"],
	"Moongolow Atlanteans": ["Moongolow", "Abyss Foscari"],
	"Giant Enemy Crab": ["Boss Rash", "Gallo Tower", "Green Acres"],
	"The Trickster": ["Carlo Cart", "Boss Rash"],
	"The Maddener": ["Carlo Cart", "Boss Rash"],
	"The Directer": ["Eudaimonia M."],
	"Rellyfish": ["Abyss Foscari"],
	"Je-Ne-Viv": ["Abyss Foscari"],
	"Bugbear": ["Ode to Castlevania"],
	"Giant Medusa Head": ["Ode to Castlevania"],
	"Behemoth": ["Ode to Castlevania"],
	"Slogra": ["Ode to Castlevania"],
	"Gaibon": ["Ode to Castlevania"],
	"Doppelganger": ["Ode to Castlevania"],
	"Puppet Master": ["Ode to Castlevania"],
	"Blackmore": ["Ode to Castlevania"],
	"Paranoia": ["Ode to Castlevania"],
	"Zephyr": ["Ode to Castlevania"],
	"Abbadon": ["Ode to Castlevania"],
	"Death": ["Ode to Castlevania"],
	"The Creature": ["Ode to Castlevania"],
	"Keremet": ["Ode to Castlevania"],
	"Menace": ["Ode to Castlevania"],
	"Eligor": ["Ode to Castlevania"],
	"Treant": ["Ode to Castlevania"],
	"Spirit Beast": ["Emerald Diorama"],
	"Specter of Iwanaga-hime": ["Emerald Diorama"],
	"Earth Dragon": ["Emerald Diorama"],
	"Iron Maiden": ["Emerald Diorama"],
	"Living Anguish": ["Emerald Diorama"],
	"Sketamari": ["The Bone Zone"],
	"Sun Atlantean": ["Mad Forest", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna", "Il Molise", "Moongolow", "Green Acres", "The Bone Zone", "Whiteout", "Laborratory", "Bat Country", "Mt.Moonspell", "Lake Foscari", "Abyss Foscari", "Polus Replica", "Neo Galuga", "Ode to Castlevania", "Emerald Diorama", "Ante Chamber"],
	"Moon Atlantean": ["Mad Forest", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna", "Il Molise", "Moongolow", "Green Acres", "The Bone Zone", "Whiteout", "Laborratory", "Mt.Moonspell", "Lake Foscari", "Abyss Foscari", "Polus Replica", "Neo Galuga", "Ode to Castlevania", "Emerald Diorama", "Ante Chamber"],
	"City Atlantean": ["Mad Forest", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna", "Il Molise", "Moongolow", "Green Acres", "The Bone Zone", "Whiteout", "Laborratory", "Mt.Moonspell", "Lake Foscari", "Abyss Foscari", "Polus Replica", "Neo Galuga", "Ode to Castlevania", "Emerald Diorama", "Ante Chamber"],
	"Volcano Atlantean": ["Mad Forest", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna", "Il Molise", "Moongolow", "Green Acres", "The Bone Zone", "Whiteout", "Laborratory", "Mt.Moonspell", "Lake Foscari", "Abyss Foscari", "Polus Replica", "Neo Galuga", "Ode to Castlevania", "Emerald Diorama", "Ante Chamber"],
	"The Blinder": ["Abyss Foscari", "Astral Stair", "Polus Replica"],
	"Astral Chair": ["Astral Stair"],
	"Poetrait": ["Astral Stair"],
	"Much Much": ["Westwoods"],
	"Hitotsumekozo": ["Mt.Moonspell"],
	"Kappa": ["Mt.Moonspell"],
	"Poltergeist": ["Gallo Tower", "Cappella Magna", "Astral Stair", "Green Acres"],
	"Gold Pile": ["Westwoods"],
	"Big Oni": ["Mt.Moonspell"],
	"Goshadokuro": ["Mt.Moonspell"],
	"Sammy the Caterpillar": ["Lake Foscari"],
	"Fungoman": ["Lake Foscari"],
	"Corpseweed": ["Ode to Castlevania"],
	"Bone Pillar": ["Ode to Castlevania"],
	"Gold Jellys": ["Westwoods"],
	"Mantichana Idol": ["Westwoods"],
	"Jastor": ["Westwoods"],
	"Mushroulette": ["Westwoods"],
	"17th Collossus": ["Mazerella"],
	"Pinthot & Coldellini": ["Polus Replica"],
	"Meat Bean": ["Polus Replica"],
	"Suspicio": ["Polus Replica"],
	"Jiang shi": ["Ode to Castlevania"],
	"Gergoth": ["Ode to Castlevania"],
	"Malevolent Door Spirit": ["Emerald Diorama"],
	"Flower Pot": ["Ante Chamber"],
	"Spirit (Emerald DLC)": ["Emerald Diorama"],
	"Foo'Ori Darkasso": ["Room 1665"],
	"The Reaper": ["Mad Forest", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna", "Il Molise", "Moongolow", "Green Acres", "The Bone Zone", "Boss Rash", "Whiteout", "The Coop", "Space 54", "Carlo Cart", "Laborratory", "Westwoods", "Bat Country", "Astral Stair", "Mazerella", "Tiny Bridge", "Room 1665", "Mt.Moonspell", "Lake Foscari", "Abyss Foscari", "Polus Replica", "Neo Galuga", "Hectic Highway", "Ode to Castlevania", "Emerald Diorama", "Ante Chamber"],
	"Nesufritto": ["Inlaid Library", "Boss Rash", "Green Acres"],
	"Hag": ["Inlaid Library", "Boss Rash", "Green Acres"],
	"The Ender": ["Boss Rash"],
	"Mimic Season One": ["Boss Rash"],
	"Mimic Season Two": ["Boss Rash"],
	"Mimic Season Three": ["Boss Rash"],
	"Lord Ghost": ["Astral Stair"],
	"Tanuki": ["Mt.Moonspell"],
	"Orochimario": ["Mt.Moonspell"],
	"Avatar of Gaea": ["Lake Foscari"],
	"Minotaur (Castlevania DLC)": ["Ode to Castlevania"],
	"Small Blind": ["Ante Chamber"],
	"Big Blind": ["Ante Chamber"],
	"The Ox": ["Ante Chamber"],
	"The Manacle": ["Ante Chamber"],
	"The Wall": ["Ante Chamber"],
	"Crimson Heart": ["Ante Chamber"],
	"Kizzune": ["Whiteout"],
	"Skelegem": ["Mad Forest", "Eudaimonia M.", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna", "Il Molise", "Moongolow", "Green Acres", "The Bone Zone", "Boss Rash", "Whiteout", "The Coop", "Space 54", "Carlo Cart", "Laborratory", "Westwoods", "Bat Country", "Astral Stair", "Mazerella", "Tiny Bridge", "Mt.Moonspell", "Lake Foscari", "Abyss Foscari", "Ante Chamber", "Room 1665", "Neo Galuga", "Hectic Highway", "Ode to Castlevania", "Polus Replica", "Emerald Diorama"]
}

non_special_characters = [character for character in all_characters if character not in secret_characters and character not in megalo_characters and character not in unfair_characters]

location_dict = [
	*[items[0] for items in stages_beaten],
	*[items[0] for items in beat_with_character],
	*[items[0] for items in open_chests],
	*[items[0] for items in kill_enemies]
]