import math
from .Locations import *

# File is Auto-generated, see: [https://github.com/SWCreeperKing/ApWorldFactories/tree/master/ApWorldFactories/Games]

def get_rule_map(player):
	return {
		"Mad Forest Beaten": lambda state: has_hurry(state, player),
		"Eudaimonia M. Beaten": lambda state: has_hurry(state, player),
		"Holy Forbidden Beaten": lambda state: has_hurry(state, player),
		"Inlaid Library Beaten": lambda state: has_hurry(state, player),
		"Dairy Plant Beaten": lambda state: has_hurry(state, player),
		"Gallo Tower Beaten": lambda state: has_hurry(state, player),
		"Cappella Magna Beaten": lambda state: has_hurry(state, player),
		"Il Molise Beaten": lambda state: has_hurry(state, player),
		"Moongolow Beaten": lambda state: has_hurry(state, player),
		"Green Acres Beaten": lambda state: has_hurry(state, player),
		"The Bone Zone Beaten": lambda state: has_hurry(state, player),
		"Boss Rash Beaten": lambda state: has_hurry(state, player),
		"Whiteout Beaten": lambda state: has_hurry(state, player),
		"The Coop Beaten": lambda state: has_hurry(state, player),
		"Space 54 Beaten": lambda state: has_hurry(state, player),
		"Carlo Cart Beaten": lambda state: has_hurry(state, player),
		"Laborratory Beaten": lambda state: has_hurry(state, player),
		"Westwoods Beaten": lambda state: has_hurry(state, player),
		"Bat Country Beaten": lambda state: has_hurry(state, player),
		"Astral Stair Beaten": lambda state: has_hurry(state, player),
		"Mazerella Beaten": lambda state: has_hurry(state, player),
		"Tiny Bridge Beaten": lambda state: has_hurry(state, player),
		"Mt.Moonspell Beaten": lambda state: has_hurry(state, player),
		"Lake Foscari Beaten": lambda state: has_hurry(state, player),
		"Abyss Foscari Beaten": lambda state: has_hurry(state, player),
		"Profane Chapel Beaten": lambda state: has_hurry(state, player),
		"Ante Chamber Beaten": lambda state: has_hurry(state, player),
		"Room 1665 Beaten": lambda state: has_hurry(state, player),
		"Neo Galuga Beaten": lambda state: has_hurry(state, player),
		"Hectic Highway Beaten": lambda state: has_hurry(state, player),
		"Ode to Castlevania Beaten": lambda state: has_hurry(state, player),
		"Polus Replica Beaten": lambda state: has_hurry(state, player),
		"Emerald Diorama Beaten": lambda state: has_hurry(state, player),
		"Beat with Antonio Belpaese": lambda state: has_character(state, player, "Antonio Belpaese") and has_hurry(state, player),
		"Beat with Imelda Belpaese": lambda state: has_character(state, player, "Imelda Belpaese") and has_hurry(state, player),
		"Beat with Pasqualina Belpaese": lambda state: has_character(state, player, "Pasqualina Belpaese") and has_hurry(state, player),
		"Beat with Gennaro Belpaese": lambda state: has_character(state, player, "Gennaro Belpaese") and has_hurry(state, player),
		"Beat with Arca Ladonna": lambda state: has_character(state, player, "Arca Ladonna") and has_hurry(state, player),
		"Beat with Porta Ladonna": lambda state: has_character(state, player, "Porta Ladonna") and has_hurry(state, player),
		"Beat with Lama Ladonna": lambda state: has_character(state, player, "Lama Ladonna") and has_hurry(state, player),
		"Beat with Poe Ratcho": lambda state: has_character(state, player, "Poe Ratcho") and has_hurry(state, player),
		"Beat with Suor Clerici": lambda state: has_character(state, player, "Suor Clerici") and has_hurry(state, player),
		"Beat with Dommario": lambda state: has_character(state, player, "Dommario") and has_hurry(state, player),
		"Beat with Krochi Freetto": lambda state: has_character(state, player, "Krochi Freetto") and has_hurry(state, player),
		"Beat with Christine Davain": lambda state: has_character(state, player, "Christine Davain") and has_hurry(state, player),
		"Beat with Pugnala Provola": lambda state: has_character(state, player, "Pugnala Provola") and has_hurry(state, player),
		"Beat with Giovanna Grana": lambda state: has_character(state, player, "Giovanna Grana") and has_hurry(state, player),
		"Beat with Poppea Pecorina": lambda state: has_character(state, player, "Poppea Pecorina") and has_hurry(state, player),
		"Beat with Concetta Caciotta": lambda state: has_character(state, player, "Concetta Caciotta") and has_hurry(state, player),
		"Beat with Mortaccio": lambda state: has_character(state, player, "Mortaccio") and has_hurry(state, player),
		"Beat with Yatta Cavallo": lambda state: has_character(state, player, "Yatta Cavallo") and has_hurry(state, player),
		"Beat with Bianca Ramba": lambda state: has_character(state, player, "Bianca Ramba") and has_hurry(state, player),
		"Beat with O'Sole Meeo": lambda state: has_character(state, player, "O'Sole Meeo") and has_hurry(state, player),
		"Beat with Sir Ambrojoe": lambda state: has_character(state, player, "Sir Ambrojoe") and has_hurry(state, player),
		"Beat with Iguana Gallo Valletto": lambda state: has_character(state, player, "Iguana Gallo Valletto") and has_hurry(state, player),
		"Beat with Divano Thelma": lambda state: has_character(state, player, "Divano Thelma") and has_hurry(state, player),
		"Beat with Zi'Assunta Belpaese": lambda state: has_character(state, player, "Zi'Assunta Belpaese") and has_hurry(state, player),
		"Beat with Exdash Exiviiq": lambda state: has_character(state, player, "Exdash Exiviiq") and has_hurry(state, player),
		"Beat with Toastie": lambda state: has_character(state, player, "Toastie") and has_hurry(state, player),
		"Beat with Smith IV": lambda state: has_character(state, player, "Smith IV") and has_hurry(state, player),
		"Beat with Random": lambda state: has_character(state, player, "Random") and has_hurry(state, player),
		"Beat with Boon Marrabbio": lambda state: has_character(state, player, "Boon Marrabbio") and has_hurry(state, player),
		"Beat with Avatar Infernas": lambda state: has_character(state, player, "Avatar Infernas") and has_hurry(state, player),
		"Beat with Minnah Mannarah": lambda state: has_character(state, player, "Minnah Mannarah") and has_hurry(state, player),
		"Beat with Leda": lambda state: has_character(state, player, "Leda") and has_hurry(state, player),
		"Beat with Cosmo Pavone": lambda state: has_character(state, player, "Cosmo Pavone") and has_hurry(state, player),
		"Beat with Peppino": lambda state: has_character(state, player, "Peppino") and has_hurry(state, player),
		"Beat with Big Trouser": lambda state: has_character(state, player, "Big Trouser") and has_hurry(state, player),
		"Beat with missingN": lambda state: has_character(state, player, "missingN") and has_hurry(state, player),
		"Beat with Gains Boros": lambda state: has_character(state, player, "Gains Boros") and has_hurry(state, player),
		"Beat with Gyorunton": lambda state: has_character(state, player, "Gyorunton") and has_hurry(state, player),
		"Beat with Mask of the Red Death": lambda state: has_character(state, player, "Mask of the Red Death") and has_hurry(state, player),
		"Beat with Queen Sigma": lambda state: has_character(state, player, "Queen Sigma") and has_hurry(state, player),
		"Beat with Bat Robbert": lambda state: has_character(state, player, "Bat Robbert") and has_hurry(state, player),
		"Beat with Zi'Appunta Belpaese": lambda state: has_character(state, player, "Zi'Appunta Belpaese") and has_hurry(state, player),
		"Beat with She-Moon Eeta": lambda state: has_character(state, player, "She-Moon Eeta") and has_hurry(state, player),
		"Beat with Santa Ladonna": lambda state: has_character(state, player, "Santa Ladonna") and has_hurry(state, player),
		"Beat with Gazebo": lambda state: has_character(state, player, "Gazebo") and has_hurry(state, player),
		"Beat with Chula-Reh": lambda state: has_character(state, player, "Chula-Reh") and has_hurry(state, player),
		"Beat with Space Dude": lambda state: has_character(state, player, "Space Dude") and has_hurry(state, player),
		"Beat with Bats Bats Bats": lambda state: has_character(state, player, "Bats Bats Bats") and has_hurry(state, player),
		"Beat with Rose De Infernas": lambda state: has_character(state, player, "Rose De Infernas") and has_hurry(state, player),
		"Beat with Torino": lambda state: has_character(state, player, "Torino") and has_hurry(state, player),
		"Beat with Scorej-Oni": lambda state: has_character(state, player, "Scorej-Oni") and has_hurry(state, player),
		"Beat with Gyoruntin": lambda state: has_character(state, player, "Gyoruntin") and has_hurry(state, player),
		"Beat with Secretino": lambda state: has_character(state, player, "Secretino") and has_hurry(state, player),
		"Beat with Space Dette": lambda state: has_character(state, player, "Space Dette") and has_hurry(state, player),
		"Beat with Miang Moonspell": lambda state: has_character(state, player, "Miang Moonspell") and has_hurry(state, player),
		"Beat with Menya Moonspell": lambda state: has_character(state, player, "Menya Moonspell") and has_hurry(state, player),
		"Beat with Syuuto Moonspell": lambda state: has_character(state, player, "Syuuto Moonspell") and has_hurry(state, player),
		"Beat with Babi-Onna": lambda state: has_character(state, player, "Babi-Onna") and has_hurry(state, player),
		"Beat with McCoy-Oni": lambda state: has_character(state, player, "McCoy-Oni") and has_hurry(state, player),
		"Beat with Megalo Menya Moonspell": lambda state: has_character(state, player, "Megalo Menya Moonspell") and has_hurry(state, player),
		"Beat with Megalo Syuuto Moonspell": lambda state: has_character(state, player, "Megalo Syuuto Moonspell") and has_hurry(state, player),
		"Beat with Gab'Et-Oni": lambda state: has_character(state, player, "Gab'Et-Oni") and has_hurry(state, player),
		"Beat with Eleanor Uziron": lambda state: has_character(state, player, "Eleanor Uziron") and has_hurry(state, player),
		"Beat with Maruto Cuts": lambda state: has_character(state, player, "Maruto Cuts") and has_hurry(state, player),
		"Beat with Keitha Muort": lambda state: has_character(state, player, "Keitha Muort") and has_hurry(state, player),
		"Beat with Luminaire Foscari": lambda state: has_character(state, player, "Luminaire Foscari") and has_hurry(state, player),
		"Beat with Genevieve Gruyère": lambda state: has_character(state, player, "Genevieve Gruyère") and has_hurry(state, player),
		"Beat with Je-Ne-Viv": lambda state: has_character(state, player, "Je-Ne-Viv") and has_hurry(state, player),
		"Beat with Sammy": lambda state: has_character(state, player, "Sammy") and has_hurry(state, player),
		"Beat with Rottin'Ghoul": lambda state: has_character(state, player, "Rottin'Ghoul") and has_hurry(state, player),
		"Beat with Crewmate Dino": lambda state: has_character(state, player, "Crewmate Dino") and has_hurry(state, player),
		"Beat with Engineer Gino": lambda state: has_character(state, player, "Engineer Gino") and has_hurry(state, player),
		"Beat with Ghost Lino": lambda state: has_character(state, player, "Ghost Lino") and has_hurry(state, player),
		"Beat with Shapeshifter Nino": lambda state: has_character(state, player, "Shapeshifter Nino") and has_hurry(state, player),
		"Beat with Guardian Pina": lambda state: has_character(state, player, "Guardian Pina") and has_hurry(state, player),
		"Beat with Impostor Rina": lambda state: has_character(state, player, "Impostor Rina") and has_hurry(state, player),
		"Beat with Scientist Mina": lambda state: has_character(state, player, "Scientist Mina") and has_hurry(state, player),
		"Beat with Horse": lambda state: has_character(state, player, "Horse") and has_hurry(state, player),
		"Beat with Megalo Impostor Rina": lambda state: has_character(state, player, "Megalo Impostor Rina") and has_hurry(state, player),
		"Beat with Bill Rizer": lambda state: has_character(state, player, "Bill Rizer") and has_hurry(state, player),
		"Beat with Lance Bean": lambda state: has_character(state, player, "Lance Bean") and has_hurry(state, player),
		"Beat with Ariana": lambda state: has_character(state, player, "Ariana") and has_hurry(state, player),
		"Beat with Lucia Zero": lambda state: has_character(state, player, "Lucia Zero") and has_hurry(state, player),
		"Beat with Brad Fang": lambda state: has_character(state, player, "Brad Fang") and has_hurry(state, player),
		"Beat with Browny": lambda state: has_character(state, player, "Browny") and has_hurry(state, player),
		"Beat with Sheena Etranzi": lambda state: has_character(state, player, "Sheena Etranzi") and has_hurry(state, player),
		"Beat with Probotector": lambda state: has_character(state, player, "Probotector") and has_hurry(state, player),
		"Beat with Stanley": lambda state: has_character(state, player, "Stanley") and has_hurry(state, player),
		"Beat with Newt Plissken": lambda state: has_character(state, player, "Newt Plissken") and has_hurry(state, player),
		"Beat with Colonel Bahamut": lambda state: has_character(state, player, "Colonel Bahamut") and has_hurry(state, player),
		"Beat with Simondo": lambda state: has_character(state, player, "Simondo") and has_hurry(state, player),
		"Beat with Leon Belmont": lambda state: has_character(state, player, "Leon Belmont") and has_hurry(state, player),
		"Beat with Sonia Belmont": lambda state: has_character(state, player, "Sonia Belmont") and has_hurry(state, player),
		"Beat with Trevor Belmont": lambda state: has_character(state, player, "Trevor Belmont") and has_hurry(state, player),
		"Beat with Christopher Belmont": lambda state: has_character(state, player, "Christopher Belmont") and has_hurry(state, player),
		"Beat with Simon Belmont": lambda state: has_character(state, player, "Simon Belmont") and has_hurry(state, player),
		"Beat with Juste Belmont": lambda state: has_character(state, player, "Juste Belmont") and has_hurry(state, player),
		"Beat with Richter Belmont": lambda state: has_character(state, player, "Richter Belmont") and has_hurry(state, player),
		"Beat with Julius Belmont": lambda state: has_character(state, player, "Julius Belmont") and has_hurry(state, player),
		"Beat with Grant Danasty": lambda state: has_character(state, player, "Grant Danasty") and has_hurry(state, player),
		"Beat with Quincy Morris": lambda state: has_character(state, player, "Quincy Morris") and has_hurry(state, player),
		"Beat with John Morris": lambda state: has_character(state, player, "John Morris") and has_hurry(state, player),
		"Beat with Jonathan Morris": lambda state: has_character(state, player, "Jonathan Morris") and has_hurry(state, player),
		"Beat with Maxim Kischine": lambda state: has_character(state, player, "Maxim Kischine") and has_hurry(state, player),
		"Beat with Henry": lambda state: has_character(state, player, "Henry") and has_hurry(state, player),
		"Beat with Soma Cruz": lambda state: has_character(state, player, "Soma Cruz") and has_hurry(state, player),
		"Beat with Vlad Tepes Dracula": lambda state: has_character(state, player, "Vlad Tepes Dracula") and has_hurry(state, player),
		"Beat with Charlotte Aulin": lambda state: has_character(state, player, "Charlotte Aulin") and has_hurry(state, player),
		"Beat with Sypha Belnades": lambda state: has_character(state, player, "Sypha Belnades") and has_hurry(state, player),
		"Beat with Julia Laforeze": lambda state: has_character(state, player, "Julia Laforeze") and has_hurry(state, player),
		"Beat with Carrie Fernandez": lambda state: has_character(state, player, "Carrie Fernandez") and has_hurry(state, player),
		"Beat with Yoko Belnades": lambda state: has_character(state, player, "Yoko Belnades") and has_hurry(state, player),
		"Beat with Rinaldo Gandolfi": lambda state: has_character(state, player, "Rinaldo Gandolfi") and has_hurry(state, player),
		"Beat with Mina Hakuba": lambda state: has_character(state, player, "Mina Hakuba") and has_hurry(state, player),
		"Beat with Elizabeth Bartley": lambda state: has_character(state, player, "Elizabeth Bartley") and has_hurry(state, player),
		"Beat with Alucard": lambda state: has_character(state, player, "Alucard") and has_hurry(state, player),
		"Beat with Reinhardt Schneider": lambda state: has_character(state, player, "Reinhardt Schneider") and has_hurry(state, player),
		"Beat with Eric Lecarde": lambda state: has_character(state, player, "Eric Lecarde") and has_hurry(state, player),
		"Beat with Isaac": lambda state: has_character(state, player, "Isaac") and has_hurry(state, player),
		"Beat with Hector": lambda state: has_character(state, player, "Hector") and has_hurry(state, player),
		"Beat with Sara Trantoul": lambda state: has_character(state, player, "Sara Trantoul") and has_hurry(state, player),
		"Beat with Vincent Dorin": lambda state: has_character(state, player, "Vincent Dorin") and has_hurry(state, player),
		"Beat with Maria Renard": lambda state: has_character(state, player, "Maria Renard") and has_hurry(state, player),
		"Beat with Shanoa": lambda state: has_character(state, player, "Shanoa") and has_hurry(state, player),
		"Beat with Albus": lambda state: has_character(state, player, "Albus") and has_hurry(state, player),
		"Beat with Lisa": lambda state: has_character(state, player, "Lisa") and has_hurry(state, player),
		"Beat with Shaft": lambda state: has_character(state, player, "Shaft") and has_hurry(state, player),
		"Beat with Saint Germain": lambda state: has_character(state, player, "Saint Germain") and has_hurry(state, player),
		"Beat with Nathan Graves": lambda state: has_character(state, player, "Nathan Graves") and has_hurry(state, player),
		"Beat with Cornell": lambda state: has_character(state, player, "Cornell") and has_hurry(state, player),
		"Beat with Barlowe": lambda state: has_character(state, player, "Barlowe") and has_hurry(state, player),
		"Beat with Young Maria Renard": lambda state: has_character(state, player, "Young Maria Renard") and has_hurry(state, player),
		"Beat with Familiar": lambda state: has_character(state, player, "Familiar") and has_hurry(state, player),
		"Beat with Innocent Devil": lambda state: has_character(state, player, "Innocent Devil") and has_hurry(state, player),
		"Beat with Blue Crescent Moon Cornell": lambda state: has_character(state, player, "Blue Crescent Moon Cornell") and has_hurry(state, player),
		"Beat with Ferryman": lambda state: has_character(state, player, "Ferryman") and has_hurry(state, player),
		"Beat with Librarian": lambda state: has_character(state, player, "Librarian") and has_hurry(state, player),
		"Beat with Hammer": lambda state: has_character(state, player, "Hammer") and has_hurry(state, player),
		"Beat with Wind": lambda state: has_character(state, player, "Wind") and has_hurry(state, player),
		"Beat with Hugh Baldwin": lambda state: has_character(state, player, "Hugh Baldwin") and has_hurry(state, player),
		"Beat with Morris Baldwin": lambda state: has_character(state, player, "Morris Baldwin") and has_hurry(state, player),
		"Beat with Annette": lambda state: has_character(state, player, "Annette") and has_hurry(state, player),
		"Beat with Tera": lambda state: has_character(state, player, "Tera") and has_hurry(state, player),
		"Beat with Jonathan & Charlotte": lambda state: has_character(state, player, "Jonathan & Charlotte") and has_hurry(state, player),
		"Beat with Charlotte & Jonathan": lambda state: has_character(state, player, "Charlotte & Jonathan") and has_hurry(state, player),
		"Beat with Stella & Loretta Lecarde": lambda state: has_character(state, player, "Stella & Loretta Lecarde") and has_hurry(state, player),
		"Beat with Loretta & Stella Lecarde": lambda state: has_character(state, player, "Loretta & Stella Lecarde") and has_hurry(state, player),
		"Beat with Stella Lecarde": lambda state: has_character(state, player, "Stella Lecarde") and has_hurry(state, player),
		"Beat with Loretta Lecarde": lambda state: has_character(state, player, "Loretta Lecarde") and has_hurry(state, player),
		"Beat with Brauner": lambda state: has_character(state, player, "Brauner") and has_hurry(state, player),
		"Beat with Soleil Belmont": lambda state: has_character(state, player, "Soleil Belmont") and has_hurry(state, player),
		"Beat with Dario Bossi": lambda state: has_character(state, player, "Dario Bossi") and has_hurry(state, player),
		"Beat with Dmitri Blinov": lambda state: has_character(state, player, "Dmitri Blinov") and has_hurry(state, player),
		"Beat with Celia Fortner": lambda state: has_character(state, player, "Celia Fortner") and has_hurry(state, player),
		"Beat with Graham Jones": lambda state: has_character(state, player, "Graham Jones") and has_hurry(state, player),
		"Beat with Joachim": lambda state: has_character(state, player, "Joachim") and has_hurry(state, player),
		"Beat with Walter": lambda state: has_character(state, player, "Walter") and has_hurry(state, player),
		"Beat with Carmilla": lambda state: has_character(state, player, "Carmilla") and has_hurry(state, player),
		"Beat with Cave Troll": lambda state: has_character(state, player, "Cave Troll") and has_hurry(state, player),
		"Beat with Fleaman": lambda state: has_character(state, player, "Fleaman") and has_hurry(state, player),
		"Beat with Axe Armor": lambda state: has_character(state, player, "Axe Armor") and has_hurry(state, player),
		"Beat with Frozenshade": lambda state: has_character(state, player, "Frozenshade") and has_hurry(state, player),
		"Beat with Amalaric Sniper": lambda state: has_character(state, player, "Amalaric Sniper") and has_hurry(state, player),
		"Beat with Stone Skull": lambda state: has_character(state, player, "Stone Skull") and has_hurry(state, player),
		"Beat with Sword Ruler": lambda state: has_character(state, player, "Sword Ruler") and has_hurry(state, player),
		"Beat with Persephone": lambda state: has_character(state, player, "Persephone") and has_hurry(state, player),
		"Beat with Keremet": lambda state: has_character(state, player, "Keremet") and has_hurry(state, player),
		"Beat with Astarte": lambda state: has_character(state, player, "Astarte") and has_hurry(state, player),
		"Beat with Drolta": lambda state: has_character(state, player, "Drolta") and has_hurry(state, player),
		"Beat with Actrise": lambda state: has_character(state, player, "Actrise") and has_hurry(state, player),
		"Beat with Atlantis Shrine Wizard": lambda state: has_character(state, player, "Atlantis Shrine Wizard") and has_hurry(state, player),
		"Beat with Succubus": lambda state: has_character(state, player, "Succubus") and has_hurry(state, player),
		"Beat with Fake Trio": lambda state: has_character(state, player, "Fake Trio") and has_hurry(state, player),
		"Beat with Slogra and Gaibon": lambda state: has_character(state, player, "Slogra and Gaibon") and has_hurry(state, player),
		"Beat with Zephyr": lambda state: has_character(state, player, "Zephyr") and has_hurry(state, player),
		"Beat with Jiangshi": lambda state: has_character(state, player, "Jiangshi") and has_hurry(state, player),
		"Beat with Blackmore": lambda state: has_character(state, player, "Blackmore") and has_hurry(state, player),
		"Beat with Count Olrox": lambda state: has_character(state, player, "Count Olrox") and has_hurry(state, player),
		"Beat with Malphas": lambda state: has_character(state, player, "Malphas") and has_hurry(state, player),
		"Beat with Death": lambda state: has_character(state, player, "Death") and has_hurry(state, player),
		"Beat with Galamoth": lambda state: has_character(state, player, "Galamoth") and has_hurry(state, player),
		"Beat with Megalo Elizabeth Bartley": lambda state: has_character(state, player, "Megalo Elizabeth Bartley") and has_hurry(state, player),
		"Beat with Megalo Olrox": lambda state: has_character(state, player, "Megalo Olrox") and has_hurry(state, player),
		"Beat with Megalo Death": lambda state: has_character(state, player, "Megalo Death") and has_hurry(state, player),
		"Beat with Megalo Dracula": lambda state: has_character(state, player, "Megalo Dracula") and has_hurry(state, player),
		"Beat with Chaos": lambda state: has_character(state, player, "Chaos") and has_hurry(state, player),
		"Beat with Gaibon and Slogra": lambda state: has_character(state, player, "Gaibon and Slogra") and has_hurry(state, player),
		"Beat with Slogra": lambda state: has_character(state, player, "Slogra") and has_hurry(state, player),
		"Beat with Kid Dracula": lambda state: has_character(state, player, "Kid Dracula") and has_hurry(state, player),
		"Beat with Aeon": lambda state: has_character(state, player, "Aeon") and has_hurry(state, player),
		"Beat with Desmond Belmont": lambda state: has_character(state, player, "Desmond Belmont") and has_hurry(state, player),
		"Beat with Dolores Belmont": lambda state: has_character(state, player, "Dolores Belmont") and has_hurry(state, player),
		"Beat with Zoe Belmont": lambda state: has_character(state, player, "Zoe Belmont") and has_hurry(state, player),
		"Beat with Fishman": lambda state: has_character(state, player, "Fishman") and has_hurry(state, player),
		"Beat with Fake Trevor": lambda state: has_character(state, player, "Fake Trevor") and has_hurry(state, player),
		"Beat with Fake Sypha": lambda state: has_character(state, player, "Fake Sypha") and has_hurry(state, player),
		"Beat with Fake Grant": lambda state: has_character(state, player, "Fake Grant") and has_hurry(state, player),
		"Beat with Tsunanori Mido": lambda state: has_character(state, player, "Tsunanori Mido") and has_hurry(state, player),
		"Beat with Bonnie Blair": lambda state: has_character(state, player, "Bonnie Blair") and has_hurry(state, player),
		"Beat with Formina Franklyn": lambda state: has_character(state, player, "Formina Franklyn") and has_hurry(state, player),
		"Beat with Diva No. 5": lambda state: has_character(state, player, "Diva No. 5") and has_hurry(state, player),
		"Beat with Ameya Aisling": lambda state: has_character(state, player, "Ameya Aisling") and has_hurry(state, player),
		"Beat with Siugnas": lambda state: has_character(state, player, "Siugnas") and has_hurry(state, player),
		"Beat with Final Emperor": lambda state: has_character(state, player, "Final Emperor") and has_hurry(state, player),
		"Beat with Dolores": lambda state: has_character(state, player, "Dolores") and has_hurry(state, player),
		"Beat with Macha": lambda state: has_character(state, player, "Macha") and has_hurry(state, player),
		"Beat with Lita": lambda state: has_character(state, player, "Lita") and has_hurry(state, player),
		"Beat with Kugutsu": lambda state: has_character(state, player, "Kugutsu") and has_hurry(state, player),
		"Beat with Mr. S": lambda state: has_character(state, player, "Mr. S") and has_hurry(state, player),
		"Beat with Lolo, Hiss, Meow and Purr": lambda state: has_character(state, player, "Lolo, Hiss, Meow and Purr") and has_hurry(state, player),
		"Beat with Kina": lambda state: has_character(state, player, "Kina") and has_hurry(state, player),
		"Beat with Imakoo": lambda state: has_character(state, player, "Imakoo") and has_hurry(state, player),
		"Beat with Malevolent Door Spirit": lambda state: has_character(state, player, "Malevolent Door Spirit") and has_hurry(state, player),
		"Beat with Jimbo": lambda state: has_character(state, player, "Jimbo") and has_hurry(state, player),
		"Beat with Canio": lambda state: has_character(state, player, "Canio") and has_hurry(state, player),
		"Beat with Chicot": lambda state: has_character(state, player, "Chicot") and has_hurry(state, player),
		"Beat with Perkeo": lambda state: has_character(state, player, "Perkeo") and has_hurry(state, player),
		"Beat with Outer Saboteur": lambda state: has_character(state, player, "Outer Saboteur") and has_hurry(state, player),
		"Beat with Genya Arikado": lambda state: has_character(state, player, "Genya Arikado") and has_hurry(state, player),
		"Kill Pipeestrello": lambda state: has_any_stage(state, player, ["Mad Forest", "Gallo Tower", "Cappella Magna", "Green Acres", "Boss Rash", "Bat Country", "Tiny Bridge", "Mt.Moonspell", "Polus Replica", "Ante Chamber"]) or ( has_any_stage(state, player, ["Whiteout", "Inlaid Library", "Carlo Cart", "Eudaimonia M."]) and has_hurry(state, player) ),
		"Kill Zombie": lambda state: has_any_stage(state, player, ["Mad Forest", "Mt.Moonspell", "Green Acres"]) or ( has_any_stage(state, player, ["Eudaimonia M."]) and has_hurry(state, player) ),
		"Kill Skeleton": lambda state: has_any_stage(state, player, ["Mad Forest", "Dairy Plant", "Gallo Tower", "The Bone Zone", "Boss Rash", "Green Acres"]) or ( has_any_stage(state, player, ["Eudaimonia M."]) and has_hurry(state, player) ),
		"Kill Ghost": lambda state: has_any_stage(state, player, ["Mad Forest", "Inlaid Library", "Gallo Tower", "Whiteout", "Tiny Bridge", "Green Acres"]) or ( has_any_stage(state, player, ["Moongolow", "Boss Rash", "Astral Stair", "Eudaimonia M.", "Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Mudman": lambda state: has_any_stage(state, player, ["Mad Forest", "Green Acres"]) or ( has_any_stage(state, player, ["Astral Stair"]) and has_hurry(state, player) ),
		"Kill Giant Bat": lambda state: has_any_stage(state, player, ["Mad Forest", "Tiny Bridge", "Bat Country", "Green Acres"]) or ( has_any_stage(state, player, ["Inlaid Library", "Boss Rash", "Carlo Cart", "Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Werewolf": lambda state: has_any_stage(state, player, ["Mad Forest", "Green Acres"]) or ( has_any_stage(state, player, ["Boss Rash"]) and has_hurry(state, player) ),
		"Kill Mantichana": lambda state: has_any_stage(state, player, ["Mad Forest", "Green Acres"]) or ( has_any_stage(state, player, ["Boss Rash"]) and has_hurry(state, player) ),
		"Kill Big Mummy": lambda state: has_any_stage(state, player, ["Astral Stair", "Green Acres", "Inlaid Library"]) or ( has_any_stage(state, player, ["Mad Forest", "Boss Rash"]) and has_hurry(state, player) ),
		"Kill Flower Wall": lambda state: ( has_any_stage(state, player, ["Mad Forest", "Mt.Moonspell", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Venus": lambda state: ( has_any_stage(state, player, ["Mad Forest", "Boss Rash", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Dust Elemental": lambda state: has_any_stage(state, player, ["Inlaid Library", "Boss Rash", "Laborratory", "Green Acres"]) or ( has_any_stage(state, player, ["Eudaimonia M."]) and has_hurry(state, player) ),
		"Kill Musc Musc": lambda state: has_any_stage(state, player, ["Inlaid Library", "Space 54", "Green Acres"]) or ( has_any_stage(state, player, ["Boss Rash", "Laborratory"]) and has_hurry(state, player) ),
		"Kill Mummy": lambda state: has_any_stage(state, player, ["Inlaid Library", "Green Acres"]) or ( has_any_stage(state, player, ["Astral Stair", "Eudaimonia M.", "Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Testa di Mano": lambda state: has_any_stage(state, player, ["Inlaid Library", "Gallo Tower", "Green Acres"]) or ( has_any_stage(state, player, ["Room 1665", "Eudaimonia M."]) and has_hurry(state, player) ),
		"Kill Sneaky Head": lambda state: has_any_stage(state, player, ["Inlaid Library", "Boss Rash", "Mazerella", "Green Acres"]) or ( has_any_stage(state, player, ["Moongolow", "Tiny Bridge"]) and has_hurry(state, player) ),
		"Kill Lionhead": lambda state: has_any_stage(state, player, ["Inlaid Library", "Green Acres"]) or ( has_any_stage(state, player, ["Boss Rash", "Carlo Cart"]) and has_hurry(state, player) ),
		"Kill Undead Witch": lambda state: ( has_any_stage(state, player, ["Inlaid Library", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Undead Sassy Witch": lambda state: ( has_any_stage(state, player, ["Inlaid Library", "Boss Rash", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Skullone": lambda state: has_any_stage(state, player, ["The Bone Zone"]) or ( has_any_stage(state, player, ["Inlaid Library", "Gallo Tower", "Boss Rash", "Tiny Bridge", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Merdusa": lambda state: ( has_any_stage(state, player, ["Inlaid Library", "Boss Rash", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Merman": lambda state: has_any_stage(state, player, ["Dairy Plant", "Laborratory", "Green Acres"]) or ( has_any_stage(state, player, ["Moongolow", "Boss Rash", "Carlo Cart", "Eudaimonia M."]) and has_hurry(state, player) ),
		"Kill Lizard Pawn": lambda state: has_any_stage(state, player, ["Dairy Plant", "Laborratory", "Green Acres"]) or ( has_any_stage(state, player, ["Carlo Cart", "Eudaimonia M."]) and has_hurry(state, player) ),
		"Kill Milk Elemental": lambda state: has_any_stage(state, player, ["Dairy Plant", "Boss Rash", "Mazerella", "Green Acres"]) or ( has_any_stage(state, player, ["Eudaimonia M."]) and has_hurry(state, player) ),
		"Kill Lizard Rook": lambda state: has_any_stage(state, player, ["Dairy Plant", "Laborratory", "Green Acres"]) or ( has_any_stage(state, player, ["Carlo Cart"]) and has_hurry(state, player) ),
		"Kill Skeleton Ninja": lambda state: has_any_stage(state, player, ["Dairy Plant", "The Bone Zone", "Green Acres"]),
		"Kill Minotaur": lambda state: has_any_stage(state, player, ["Dairy Plant", "Ode to Castlevania", "Green Acres"]) or ( has_any_stage(state, player, ["Mazerella", "Boss Rash", "Carlo Cart", "Laborratory"]) and has_hurry(state, player) ),
		"Kill Twin Demons": lambda state: has_any_stage(state, player, ["Dairy Plant", "The Bone Zone", "Green Acres"]) or ( has_any_stage(state, player, ["Carlo Cart"]) and has_hurry(state, player) ),
		"Kill Twin Snakes": lambda state: has_any_stage(state, player, ["Dairy Plant", "Green Acres"]),
		"Kill Melone": lambda state: has_any_stage(state, player, ["Dairy Plant", "Green Acres"]),
		"Kill Archon Ascia": lambda state: has_any_stage(state, player, ["Cappella Magna", "Green Acres"]) or ( has_any_stage(state, player, ["Dairy Plant", "Boss Rash"]) and has_hurry(state, player) ),
		"Kill Lost Twin": lambda state: ( has_any_stage(state, player, ["Dairy Plant", "The Bone Zone", "Carlo Cart", "Laborratory", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Archon Lancia": lambda state: ( has_any_stage(state, player, ["Dairy Plant", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Tritont": lambda state: ( has_any_stage(state, player, ["Dairy Plant", "Boss Rash", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Big Golem": lambda state: has_any_stage(state, player, ["Astral Stair"]) or ( has_any_stage(state, player, ["Dairy Plant", "Boss Rash", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Skelewing": lambda state: has_any_stage(state, player, ["Tiny Bridge"]) or ( has_any_stage(state, player, ["Dairy Plant", "Gallo Tower", "The Bone Zone", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Sword Guardian": lambda state: ( has_any_stage(state, player, ["Dairy Plant", "Boss Rash", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Gallotrice": lambda state: has_any_stage(state, player, ["Tiny Bridge"]) or ( has_any_stage(state, player, ["Dairy Plant", "Gallo Tower", "Boss Rash", "Lake Foscari", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Skullino": lambda state: has_any_stage(state, player, ["Gallo Tower", "The Bone Zone", "Tiny Bridge", "Green Acres"]) or ( has_any_stage(state, player, ["Astral Stair", "Eudaimonia M."]) and has_hurry(state, player) ),
		"Kill Skulorosso": lambda state: has_any_stage(state, player, ["Gallo Tower", "The Bone Zone", "Green Acres"]) or ( has_any_stage(state, player, ["Eudaimonia M."]) and has_hurry(state, player) ),
		"Kill Scarleton": lambda state: has_any_stage(state, player, ["Gallo Tower", "The Bone Zone", "Green Acres"]),
		"Kill Ghiavolo": lambda state: has_any_stage(state, player, ["Gallo Tower", "Westwoods", "Green Acres"]),
		"Kill Bloodbath": lambda state: has_any_stage(state, player, ["Gallo Tower", "Green Acres"]),
		"Kill Impefinger": lambda state: has_any_stage(state, player, ["Gallo Tower", "Tiny Bridge", "Green Acres"]) or ( has_any_stage(state, player, ["Carlo Cart"]) and has_hurry(state, player) ),
		"Kill Dragon Shrimp": lambda state: has_any_stage(state, player, ["Gallo Tower", "Green Acres"]) or ( has_any_stage(state, player, ["The Bone Zone", "Boss Rash"]) and has_hurry(state, player) ),
		"Kill Harzia": lambda state: has_any_stage(state, player, ["Gallo Tower", "Boss Rash", "Westwoods", "Mazerella", "Tiny Bridge", "Green Acres"]),
		"Kill Undead Mage": lambda state: has_any_stage(state, player, ["Gallo Tower", "Green Acres"]),
		"Kill Archon Spada": lambda state: ( has_any_stage(state, player, ["Gallo Tower", "Cappella Magna", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Archon Disco": lambda state: ( has_any_stage(state, player, ["Gallo Tower", "Mazerella", "Boss Rash", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Manticore": lambda state: ( has_any_stage(state, player, ["Gallo Tower", "Mazerella", "Boss Rash", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Meat Golem": lambda state: ( has_any_stage(state, player, ["Gallo Tower", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Tetrabrachia": lambda state: has_any_stage(state, player, ["Cappella Magna", "Tiny Bridge", "Green Acres"]),
		"Kill Succubus": lambda state: has_any_stage(state, player, ["Cappella Magna", "Green Acres"]) or ( has_any_stage(state, player, ["Boss Rash", "Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Archon Fiamma": lambda state: has_any_stage(state, player, ["Cappella Magna", "Green Acres"]),
		"Kill Archon Rame": lambda state: has_any_stage(state, player, ["Cappella Magna", "Tiny Bridge", "Green Acres"]) or ( has_any_stage(state, player, ["Boss Rash"]) and has_hurry(state, player) ),
		"Kill Archon Oro": lambda state: ( has_any_stage(state, player, ["Cappella Magna", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Demon Beast": lambda state: ( has_any_stage(state, player, ["Cappella Magna", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Demon Priest": lambda state: ( has_any_stage(state, player, ["Cappella Magna", "Room 1665", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Archdemon": lambda state: ( has_any_stage(state, player, ["Cappella Magna", "Boss Rash", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Stage Killer": lambda state: ( has_any_stage(state, player, ["Cappella Magna", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Fallen Cherub": lambda state: ( has_any_stage(state, player, ["Cappella Magna", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Fallen Cherubbello": lambda state: ( has_any_stage(state, player, ["Cappella Magna", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Fallen Throne": lambda state: ( has_any_stage(state, player, ["Cappella Magna", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Trinacria": lambda state: ( has_any_stage(state, player, ["Cappella Magna", "Boss Rash", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Reaper Trainee": lambda state: ( has_any_stage(state, player, ["Cappella Magna", "Tiny Bridge", "Eudaimonia M.", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Sad Molisano": lambda state: has_any_stage(state, player, ["Il Molise"]),
		"Kill Cute Molisano": lambda state: has_any_stage(state, player, ["Il Molise"]),
		"Kill Happy Molisano": lambda state: has_any_stage(state, player, ["Il Molise"]),
		"Kill Old Molisano": lambda state: has_any_stage(state, player, ["Il Molise"]),
		"Kill Dead Molisano": lambda state: has_any_stage(state, player, ["Il Molise"]),
		"Kill Serpentvine": lambda state: has_any_stage(state, player, ["Moongolow"]),
		"Kill Sig.ra Blu": lambda state: has_any_stage(state, player, ["Moongolow"]),
		"Kill Non-Giant Enemy Crab": lambda state: has_any_stage(state, player, ["Moongolow"]) or ( has_any_stage(state, player, ["Boss Rash"]) and has_hurry(state, player) ),
		"Kill Nightshade": lambda state: has_any_stage(state, player, ["Moongolow"]) or ( has_any_stage(state, player, ["Boss Rash"]) and has_hurry(state, player) ),
		"Kill Garlic": lambda state: has_any_stage(state, player, ["Moongolow"]) or ( has_any_stage(state, player, ["Boss Rash"]) and has_hurry(state, player) ),
		"Kill Unknown": lambda state: has_any_stage(state, player, ["Moongolow", "Boss Rash"]) or ( has_any_stage(state, player, ["Cappella Magna", "Green Acres", "Eudaimonia M."]) and has_hurry(state, player) ),
		"Kill Twin Skulls": lambda state: has_any_stage(state, player, ["The Bone Zone"]),
		"Kill Skeleton Panther": lambda state: has_any_stage(state, player, ["The Bone Zone"]),
		"Kill Giant Skeleton": lambda state: ( has_any_stage(state, player, ["The Bone Zone", "Boss Rash"]) and has_hurry(state, player) ),
		"Kill Skeletone": lambda state: ( has_any_stage(state, player, ["The Bone Zone"]) and has_hurry(state, player) ),
		"Kill Tri-Anchors": lambda state: has_any_stage(state, player, ["Boss Rash"]),
		"Kill Miragellos": lambda state: has_any_stage(state, player, ["Whiteout"]),
		"Kill Madd-Onna": lambda state: has_any_stage(state, player, ["Whiteout"]),
		"Kill Menta Elemental": lambda state: has_any_stage(state, player, ["Whiteout"]),
		"Kill Bambaman": lambda state: has_any_stage(state, player, ["Whiteout"]),
		"Kill Chickenfantry": lambda state: has_any_stage(state, player, ["The Coop"]),
		"Kill Cockreliutennant": lambda state: has_any_stage(state, player, ["The Coop"]),
		"Kill Chik": lambda state: has_any_stage(state, player, ["The Coop"]),
		"Kill Egge": lambda state: has_any_stage(state, player, ["The Coop"]),
		"Kill Pol.lo Rosso": lambda state: has_any_stage(state, player, ["The Coop"]),
		"Kill Abraxas": lambda state: has_any_stage(state, player, ["The Coop"]),
		"Kill Abraxas Phronesis": lambda state: has_any_stage(state, player, ["The Coop"]),
		"Kill Abraxas Dynamis": lambda state: ( has_any_stage(state, player, ["The Coop"]) and has_hurry(state, player) ),
		"Kill Moon Duck": lambda state: has_any_stage(state, player, ["Space 54"]),
		"Kill Space Pickle": lambda state: has_any_stage(state, player, ["Space 54", "Polus Replica"]),
		"Kill Moon Rabbit": lambda state: has_any_stage(state, player, ["Space 54"]),
		"Kill Space Ant Onion": lambda state: has_any_stage(state, player, ["Space 54"]) or ( has_any_stage(state, player, ["Polus Replica"]) and has_hurry(state, player) ),
		"Kill ECMASlime": lambda state: has_any_stage(state, player, ["Space 54"]),
		"Kill Gala Invader": lambda state: ( has_any_stage(state, player, ["Space 54"]) and has_hurry(state, player) ),
		"Kill Sinistronz": lambda state: ( has_any_stage(state, player, ["Space 54"]) and has_hurry(state, player) ),
		"Kill Bounty Hunter": lambda state: has_any_stage(state, player, ["Laborratory"]),
		"Kill Holy Circuit Creations": lambda state: has_any_stage(state, player, ["Laborratory"]) or ( has_any_stage(state, player, ["Carlo Cart"]) and has_hurry(state, player) ),
		"Kill Space Hunter": lambda state: ( has_any_stage(state, player, ["Laborratory"]) and has_hurry(state, player) ),
		"Kill Tri-Blunder": lambda state: has_any_stage(state, player, ["Laborratory"]),
		"Kill Barm": lambda state: has_any_stage(state, player, ["Westwoods"]),
		"Kill Squillers": lambda state: has_any_stage(state, player, ["Westwoods"]),
		"Kill Goldie": lambda state: has_any_stage(state, player, ["Westwoods"]),
		"Kill Gamblin": lambda state: has_any_stage(state, player, ["Westwoods", "Ante Chamber"]),
		"Kill Ghoulette": lambda state: has_any_stage(state, player, ["Westwoods", "Ante Chamber"]),
		"Kill Gambergar": lambda state: has_any_stage(state, player, ["Westwoods"]),
		"Kill Toll": lambda state: has_any_stage(state, player, ["Westwoods"]),
		"Kill Card Sharp": lambda state: has_any_stage(state, player, ["Westwoods", "Ante Chamber"]),
		"Kill Dandybrine": lambda state: has_any_stage(state, player, ["Westwoods"]),
		"Kill Daimon": lambda state: has_any_stage(state, player, ["Westwoods"]),
		"Kill Valentine": lambda state: ( has_any_stage(state, player, ["Westwoods"]) and has_hurry(state, player) ),
		"Kill Astral Elemental": lambda state: has_any_stage(state, player, ["Astral Stair"]),
		"Kill Undead Stars": lambda state: has_any_stage(state, player, ["Astral Stair"]),
		"Kill Astral Curtain": lambda state: ( has_any_stage(state, player, ["Astral Stair"]) and has_hurry(state, player) ),
		"Kill Cosmic Egg": lambda state: ( has_any_stage(state, player, ["Astral Stair"]) and has_hurry(state, player) ),
		"Kill Torino": lambda state: has_any_stage(state, player, ["Mazerella"]),
		"Kill Joyatauro": lambda state: has_any_stage(state, player, ["Mazerella"]),
		"Kill AccumulaTori": lambda state: ( has_any_stage(state, player, ["Mazerella"]) and has_hurry(state, player) ),
		"Kill Ska'sa Ka'sos": lambda state: has_any_stage(state, player, ["Room 1665"]),
		"Kill Spiritello": lambda state: has_any_stage(state, player, ["Mt.Moonspell"]),
		"Kill Tsuchinoko": lambda state: has_any_stage(state, player, ["Mt.Moonspell"]),
		"Kill Kamaitachi": lambda state: has_any_stage(state, player, ["Mt.Moonspell"]) or ( has_any_stage(state, player, ["Tiny Bridge"]) and has_hurry(state, player) ),
		"Kill Raiju": lambda state: has_any_stage(state, player, ["Mt.Moonspell"]),
		"Kill Yamamba": lambda state: has_any_stage(state, player, ["Mt.Moonspell"]),
		"Kill Mikoshinyudo": lambda state: has_any_stage(state, player, ["Mt.Moonspell"]),
		"Kill Tengu": lambda state: ( has_any_stage(state, player, ["Mt.Moonspell"]) and has_hurry(state, player) ),
		"Kill Thunderous Oni": lambda state: has_any_stage(state, player, ["Mt.Moonspell"]),
		"Kill Windy Oni": lambda state: has_any_stage(state, player, ["Mt.Moonspell"]),
		"Kill Tsuchigumo": lambda state: ( has_any_stage(state, player, ["Mt.Moonspell"]) and has_hurry(state, player) ),
		"Kill Chompo": lambda state: has_any_stage(state, player, ["Lake Foscari"]),
		"Kill Brownie": lambda state: has_any_stage(state, player, ["Lake Foscari"]),
		"Kill Ceffoose": lambda state: has_any_stage(state, player, ["Lake Foscari"]),
		"Kill Hill Trow": lambda state: has_any_stage(state, player, ["Lake Foscari"]),
		"Kill Sea Trow": lambda state: has_any_stage(state, player, ["Lake Foscari"]),
		"Kill Wiseparke": lambda state: has_any_stage(state, player, ["Lake Foscari"]),
		"Kill Nutmeg": lambda state: has_any_stage(state, player, ["Lake Foscari"]),
		"Kill Vulvio": lambda state: has_any_stage(state, player, ["Lake Foscari"]),
		"Kill Lammuga": lambda state: has_any_stage(state, player, ["Lake Foscari"]),
		"Kill Njuggles": lambda state: has_any_stage(state, player, ["Lake Foscari"]),
		"Kill Sam the Sundown Clown": lambda state: has_any_stage(state, player, ["Lake Foscari"]),
		"Kill Notadam": lambda state: ( has_any_stage(state, player, ["Lake Foscari"]) and has_hurry(state, player) ),
		"Kill Crocifriggitore": lambda state: ( has_any_stage(state, player, ["Lake Foscari"]) and has_hurry(state, player) ),
		"Kill Missing Church": lambda state: has_any_stage(state, player, ["Abyss Foscari"]) or ( has_any_stage(state, player, ["Lake Foscari"]) and has_hurry(state, player) ),
		"Kill Green Knight": lambda state: ( has_any_stage(state, player, ["Lake Foscari"]) and has_hurry(state, player) ),
		"Kill Ghostly Apparition": lambda state: ( has_any_stage(state, player, ["Lake Foscari"]) and has_hurry(state, player) ),
		"Kill Average Hag": lambda state: ( has_any_stage(state, player, ["Lake Foscari"]) and has_hurry(state, player) ),
		"Kill Maronna": lambda state: ( has_any_stage(state, player, ["Lake Foscari"]) and has_hurry(state, player) ),
		"Kill Hand of Glory": lambda state: ( has_any_stage(state, player, ["Lake Foscari"]) and has_hurry(state, player) ),
		"Kill Cauld": lambda state: has_any_stage(state, player, ["Abyss Foscari"]),
		"Kill Redusa Head": lambda state: has_any_stage(state, player, ["Abyss Foscari"]) or ( has_any_stage(state, player, ["Astral Stair"]) and has_hurry(state, player) ),
		"Kill Blood Moss": lambda state: has_any_stage(state, player, ["Abyss Foscari"]) or ( has_any_stage(state, player, ["Astral Stair"]) and has_hurry(state, player) ),
		"Kill Rotting Ghoul": lambda state: has_any_stage(state, player, ["Abyss Foscari"]),
		"Kill Burning Skull": lambda state: has_any_stage(state, player, ["Abyss Foscari"]),
		"Kill Snek": lambda state: has_any_stage(state, player, ["Abyss Foscari", "Lake Foscari"]),
		"Kill Meatball": lambda state: has_any_stage(state, player, ["Abyss Foscari"]),
		"Kill Lost Head": lambda state: has_any_stage(state, player, ["Abyss Foscari"]),
		"Kill Frozen Meatball": lambda state: has_any_stage(state, player, ["Abyss Foscari"]),
		"Kill Cold Cauld": lambda state: has_any_stage(state, player, ["Abyss Foscari"]),
		"Kill Edna": lambda state: ( has_any_stage(state, player, ["Abyss Foscari"]) and has_hurry(state, player) ),
		"Kill Well Dweller": lambda state: ( has_any_stage(state, player, ["Abyss Foscari"]) and has_hurry(state, player) ),
		"Kill Wet Njuggles": lambda state: ( has_any_stage(state, player, ["Abyss Foscari"]) and has_hurry(state, player) ),
		"Kill Crocifriggitone": lambda state: ( has_any_stage(state, player, ["Abyss Foscari"]) and has_hurry(state, player) ),
		"Kill Still Notadam": lambda state: ( has_any_stage(state, player, ["Abyss Foscari"]) and has_hurry(state, player) ),
		"Kill Fomorians": lambda state: ( has_any_stage(state, player, ["Abyss Foscari"]) and has_hurry(state, player) ),
		"Kill Glove of Glory": lambda state: ( has_any_stage(state, player, ["Abyss Foscari"]) and has_hurry(state, player) ),
		"Kill Maronna Meea": lambda state: ( has_any_stage(state, player, ["Abyss Foscari"]) and has_hurry(state, player) ),
		"Kill Brainoid": lambda state: has_any_stage(state, player, ["Polus Replica"]),
		"Kill Frijjitello": lambda state: has_any_stage(state, player, ["Polus Replica"]),
		"Kill Shapeunshifter": lambda state: has_any_stage(state, player, ["Polus Replica"]),
		"Kill Space Apparition": lambda state: has_any_stage(state, player, ["Polus Replica"]),
		"Kill Mocholo": lambda state: has_any_stage(state, player, ["Polus Replica"]),
		"Kill Spotter": lambda state: has_any_stage(state, player, ["Polus Replica"]),
		"Kill Sponkey": lambda state: has_any_stage(state, player, ["Polus Replica"]),
		"Kill Victor Frankenstein": lambda state: has_any_stage(state, player, ["Polus Replica"]),
		"Kill Martian Face": lambda state: has_any_stage(state, player, ["Polus Replica"]),
		"Kill Steroid": lambda state: has_any_stage(state, player, ["Polus Replica"]),
		"Kill Trip Trop": lambda state: has_any_stage(state, player, ["Polus Replica"]),
		"Kill G062T": lambda state: has_any_stage(state, player, ["Polus Replica"]),
		"Kill Ledder": lambda state: has_any_stage(state, player, ["Neo Galuga"]),
		"Kill Greeder": lambda state: has_any_stage(state, player, ["Neo Galuga"]),
		"Kill Evil Snowman": lambda state: has_any_stage(state, player, ["Neo Galuga", "Hectic Highway"]),
		"Kill Warlord": lambda state: has_any_stage(state, player, ["Neo Galuga"]),
		"Kill Alien Centipede": lambda state: has_any_stage(state, player, ["Neo Galuga"]),
		"Kill Human Faced Dog": lambda state: has_any_stage(state, player, ["Neo Galuga"]),
		"Kill Garth": lambda state: has_any_stage(state, player, ["Neo Galuga"]),
		"Kill Ball Walker": lambda state: has_any_stage(state, player, ["Neo Galuga", "Hectic Highway"]),
		"Kill Flight Zako": lambda state: has_any_stage(state, player, ["Neo Galuga", "Hectic Highway"]),
		"Kill Junkyard Car": lambda state: has_any_stage(state, player, ["Neo Galuga", "Hectic Highway"]),
		"Kill Bugger": lambda state: has_any_stage(state, player, ["Neo Galuga"]),
		"Kill Bundle": lambda state: has_any_stage(state, player, ["Neo Galuga", "Hectic Highway"]),
		"Kill Poisonous Insect Gel": lambda state: has_any_stage(state, player, ["Neo Galuga"]),
		"Kill Zako Alien": lambda state: has_any_stage(state, player, ["Neo Galuga"]),
		"Kill Gigafly": lambda state: has_any_stage(state, player, ["Neo Galuga", "Hectic Highway"]),
		"Kill Mutant Crawler": lambda state: has_any_stage(state, player, ["Neo Galuga", "Hectic Highway"]),
		"Kill Gulcan Tank": lambda state: has_any_stage(state, player, ["Neo Galuga", "Hectic Highway"]),
		"Kill Metal Alien": lambda state: has_any_stage(state, player, ["Neo Galuga", "Hectic Highway"]),
		"Kill M78": lambda state: has_any_stage(state, player, ["Neo Galuga", "Hectic Highway"]),
		"Kill Kimkoh": lambda state: has_any_stage(state, player, ["Neo Galuga"]),
		"Kill Hellrider": lambda state: has_any_stage(state, player, ["Hectic Highway"]) or ( has_any_stage(state, player, ["Neo Galuga"]) and has_hurry(state, player) ),
		"Kill Flea Rider": lambda state: has_any_stage(state, player, ["Profane Chapel", "Ode to Castlevania"]),
		"Kill Frozen Shade": lambda state: has_any_stage(state, player, ["Profane Chapel", "Ode to Castlevania"]),
		"Kill Harpy": lambda state: has_any_stage(state, player, ["Profane Chapel", "Ode to Castlevania"]),
		"Kill Imp": lambda state: has_any_stage(state, player, ["Profane Chapel", "Ode to Castlevania"]),
		"Kill Flea Man": lambda state: has_any_stage(state, player, ["Profane Chapel", "Ode to Castlevania"]),
		"Kill Moldy Corpse": lambda state: has_any_stage(state, player, ["Profane Chapel", "Ode to Castlevania"]),
		"Kill Spittle Bone": lambda state: has_any_stage(state, player, ["Profane Chapel", "Ode to Castlevania"]),
		"Kill Ukoback": lambda state: has_any_stage(state, player, ["Profane Chapel", "Ode to Castlevania"]),
		"Kill Spectre": lambda state: has_any_stage(state, player, ["Profane Chapel", "Ode to Castlevania"]),
		"Kill Valhalla Knight": lambda state: has_any_stage(state, player, ["Profane Chapel", "Ode to Castlevania"]),
		"Kill Warg": lambda state: has_any_stage(state, player, ["Profane Chapel", "Ode to Castlevania"]),
		"Kill Bitterfly": lambda state: has_any_stage(state, player, ["Profane Chapel", "Ode to Castlevania"]),
		"Kill Bloody Painting": lambda state: has_any_stage(state, player, ["Profane Chapel", "Ode to Castlevania"]),
		"Kill Fishman": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]) or ( has_any_stage(state, player, ["Profane Chapel"]) and has_hurry(state, player) ),
		"Kill Flea Armor": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]) or ( has_any_stage(state, player, ["Profane Chapel"]) and has_hurry(state, player) ),
		"Kill Persephone": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]) or ( has_any_stage(state, player, ["Profane Chapel"]) and has_hurry(state, player) ),
		"Kill Ghost (Castlevania DLC)": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]) or ( has_any_stage(state, player, ["Profane Chapel"]) and has_hurry(state, player) ),
		"Kill Flying Zombie": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]),
		"Kill Yorick": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]),
		"Kill Dullahan": lambda state: has_any_stage(state, player, ["Ode to Castlevania", "Inlaid Library", "Green Acres"]),
		"Kill Gurkha Knife Master": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]),
		"Kill Disc Armor": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]),
		"Kill Axe Armor": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]),
		"Kill Bone Ark": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]),
		"Kill Bone Golem": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]),
		"Kill Killer Doll": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]),
		"Kill Gorgon": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]),
		"Kill Amalaric Sniper": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]),
		"Kill Magic Book": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]),
		"Kill Hippogyph": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]),
		"Kill Castle Werewolf": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Malachi": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]),
		"Kill Alastor": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]),
		"Kill Rana Combatant": lambda state: has_any_stage(state, player, ["Emerald Diorama"]),
		"Kill Alraune": lambda state: has_any_stage(state, player, ["Emerald Diorama"]),
		"Kill Skydiver": lambda state: has_any_stage(state, player, ["Emerald Diorama"]),
		"Kill Forest Hermit": lambda state: has_any_stage(state, player, ["Emerald Diorama"]),
		"Kill Boar Infantry": lambda state: has_any_stage(state, player, ["Emerald Diorama"]),
		"Kill Decobat": lambda state: has_any_stage(state, player, ["Emerald Diorama"]),
		"Kill Rascal": lambda state: has_any_stage(state, player, ["Emerald Diorama"]),
		"Kill Skeleton from Beyond": lambda state: has_any_stage(state, player, ["Emerald Diorama"]),
		"Kill Failinis": lambda state: has_any_stage(state, player, ["Emerald Diorama"]),
		"Kill Maggot Ball": lambda state: has_any_stage(state, player, ["Emerald Diorama"]),
		"Kill Kelpie": lambda state: has_any_stage(state, player, ["Emerald Diorama"]),
		"Kill Werewolf from Beyond": lambda state: has_any_stage(state, player, ["Emerald Diorama"]),
		"Kill Anti-Ant": lambda state: has_any_stage(state, player, ["Emerald Diorama"]),
		"Kill Moch": lambda state: has_any_stage(state, player, ["Emerald Diorama"]),
		"Kill Psychic Ogre": lambda state: has_any_stage(state, player, ["Emerald Diorama"]),
		"Kill Golden Baum": lambda state: has_any_stage(state, player, ["Emerald Diorama"]),
		"Kill Zombalatro": lambda state: has_any_stage(state, player, ["Ante Chamber"]),
		"Kill Jimbats": lambda state: has_any_stage(state, player, ["Ante Chamber"]),
		"Kill Mr Bones": lambda state: has_any_stage(state, player, ["Ante Chamber"]),
		"Kill Spectral Joker": lambda state: has_any_stage(state, player, ["Ante Chamber"]),
		"Kill Moonlover": lambda state: has_any_stage(state, player, ["Ante Chamber"]),
		"Kill Knight of Spades": lambda state: ( has_any_stage(state, player, ["Ante Chamber", "Westwoods"]) and has_hurry(state, player) ),
		"Kill Playing Mantis": lambda state: has_any_stage(state, player, ["Ante Chamber"]),
		"Kill Blue Venus": lambda state: ( has_any_stage(state, player, ["Ante Chamber"]) and has_hurry(state, player) ),
		"Kill Levatee Darkasso": lambda state: ( has_any_stage(state, player, ["Room 1665"]) and has_hurry(state, player) ),
		"Kill Juda R'kasso": lambda state: ( has_any_stage(state, player, ["Room 1665"]) and has_hurry(state, player) ),
		"Kill Levarsee Darkasso": lambda state: ( has_any_stage(state, player, ["Room 1665"]) and has_hurry(state, player) ),
		"Kill Shendi Darkasso": lambda state: ( has_any_stage(state, player, ["Room 1665"]) and has_hurry(state, player) ),
		"Kill Sphon'Dato Darkasso": lambda state: ( has_any_stage(state, player, ["Room 1665"]) and has_hurry(state, player) ),
		"Kill Eh'Lleve-Teh Darkasso": lambda state: ( has_any_stage(state, player, ["Room 1665"]) and has_hurry(state, player) ),
		"Kill Sig.ra Rossi": lambda state: ( has_any_stage(state, player, ["Inlaid Library", "Astral Stair", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Jellyfish": lambda state: has_any_stage(state, player, ["Dairy Plant", "Green Acres"]) or ( has_any_stage(state, player, ["Moongolow", "Boss Rash", "Laborratory"]) and has_hurry(state, player) ),
		"Kill Mignotaur": lambda state: has_any_stage(state, player, ["Laborratory", "Green Acres", "Dairy Plant"]),
		"Kill The Drowner": lambda state: has_any_stage(state, player, ["The Bone Zone", "Boss Rash"]) or ( has_any_stage(state, player, ["Carlo Cart"]) and has_hurry(state, player) ),
		"Kill LV128 Golden Bat": lambda state: has_any_stage(state, player, ["Bat Country"]),
		"Kill Suspicious Eyes": lambda state: has_any_stage(state, player, ["Polus Replica"]),
		"Kill Big Bot Gordea": lambda state: has_any_stage(state, player, ["Neo Galuga"]) or ( has_any_stage(state, player, ["Hectic Highway"]) and has_hurry(state, player) ),
		"Kill Taka": lambda state: has_any_stage(state, player, ["Neo Galuga"]) or ( has_any_stage(state, player, ["Hectic Highway"]) and has_hurry(state, player) ),
		"Kill Simondo Belmont": lambda state: has_any_stage(state, player, ["Neo Galuga"]),
		"Kill Big Fuzz": lambda state: has_any_stage(state, player, ["Neo Galuga"]),
		"Kill Devil": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]) or ( has_any_stage(state, player, ["Profane Chapel"]) and has_hurry(state, player) ),
		"Kill The Stalker": lambda state: has_any_stage(state, player, ["Boss Rash"]) or ( has_any_stage(state, player, ["Dairy Plant", "Green Acres", "The Bone Zone", "Carlo Cart"]) and has_hurry(state, player) ),
		"Kill Moongolow Atlanteans": lambda state: ( has_any_stage(state, player, ["Moongolow", "Abyss Foscari"]) and has_hurry(state, player) ),
		"Kill Giant Enemy Crab": lambda state: ( has_any_stage(state, player, ["Boss Rash", "Gallo Tower", "Green Acres"]) and has_hurry(state, player) ),
		"Kill The Trickster": lambda state: has_any_stage(state, player, ["Boss Rash"]) or ( has_any_stage(state, player, ["Carlo Cart"]) and has_hurry(state, player) ),
		"Kill The Maddener": lambda state: has_any_stage(state, player, ["Boss Rash"]) or ( has_any_stage(state, player, ["Carlo Cart"]) and has_hurry(state, player) ),
		"Kill The Directer": lambda state: ( has_any_stage(state, player, ["Eudaimonia M."]) and has_hurry(state, player) ),
		"Kill Rellyfish": lambda state: ( has_any_stage(state, player, ["Abyss Foscari"]) and has_hurry(state, player) ),
		"Kill Je-Ne-Viv": lambda state: ( has_any_stage(state, player, ["Abyss Foscari"]) and has_hurry(state, player) ),
		"Kill Bugbear": lambda state: has_any_stage(state, player, ["Ode to Castlevania", "Profane Chapel"]),
		"Kill Giant Medusa Head": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Behemoth": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Slogra": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Gaibon": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Doppelganger": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Puppet Master": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Blackmore": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Paranoia": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Zephyr": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Abbadon": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill The Creature": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Keremet": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Menace": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Eligor": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Treant": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Spirit Beast": lambda state: ( has_any_stage(state, player, ["Emerald Diorama"]) and has_hurry(state, player) ),
		"Kill Specter of Iwanaga-hime": lambda state: ( has_any_stage(state, player, ["Emerald Diorama"]) and has_hurry(state, player) ),
		"Kill Earth Dragon": lambda state: ( has_any_stage(state, player, ["Emerald Diorama"]) and has_hurry(state, player) ),
		"Kill Iron Maiden": lambda state: ( has_any_stage(state, player, ["Emerald Diorama"]) and has_hurry(state, player) ),
		"Kill Living Anguish": lambda state: ( has_any_stage(state, player, ["Emerald Diorama"]) and has_hurry(state, player) ),
		"Kill Sketamari": lambda state: ( has_any_stage(state, player, ["The Bone Zone"]) and has_hurry(state, player) ),
		"Kill Sun Atlantean": lambda state: ( has_any_stage(state, player, ["Mad Forest", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna", "Il Molise", "Moongolow", "Green Acres", "The Bone Zone", "Whiteout", "Laborratory", "Bat Country", "Mt.Moonspell", "Lake Foscari", "Abyss Foscari", "Polus Replica", "Neo Galuga", "Ode to Castlevania", "Emerald Diorama", "Ante Chamber"]) and has_hurry(state, player) ),
		"Kill Moon Atlantean": lambda state: ( has_any_stage(state, player, ["Mad Forest", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna", "Il Molise", "Moongolow", "Green Acres", "The Bone Zone", "Whiteout", "Laborratory", "Mt.Moonspell", "Lake Foscari", "Abyss Foscari", "Polus Replica", "Neo Galuga", "Ode to Castlevania", "Emerald Diorama", "Ante Chamber"]) and has_hurry(state, player) ),
		"Kill City Atlantean": lambda state: ( has_any_stage(state, player, ["Mad Forest", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna", "Il Molise", "Moongolow", "Green Acres", "The Bone Zone", "Whiteout", "Laborratory", "Mt.Moonspell", "Lake Foscari", "Abyss Foscari", "Polus Replica", "Neo Galuga", "Ode to Castlevania", "Emerald Diorama", "Ante Chamber"]) and has_hurry(state, player) ),
		"Kill Volcano Atlantean": lambda state: ( has_any_stage(state, player, ["Mad Forest", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna", "Il Molise", "Moongolow", "Green Acres", "The Bone Zone", "Whiteout", "Laborratory", "Mt.Moonspell", "Lake Foscari", "Abyss Foscari", "Polus Replica", "Neo Galuga", "Ode to Castlevania", "Emerald Diorama", "Ante Chamber"]) and has_hurry(state, player) ),
		"Kill The Blinder": lambda state: ( has_any_stage(state, player, ["Abyss Foscari"]) and has_hurry(state, player) ),
		"Kill Astral Chair": lambda state: has_any_stage(state, player, ["Astral Stair"]),
		"Kill Poetrait": lambda state: has_any_stage(state, player, ["Astral Stair"]),
		"Kill Much Much": lambda state: has_any_stage(state, player, ["Westwoods"]),
		"Kill Hitotsumekozo": lambda state: has_any_stage(state, player, ["Mt.Moonspell"]),
		"Kill Kappa": lambda state: has_any_stage(state, player, ["Mt.Moonspell"]),
		"Kill Poltergeist": lambda state: has_any_stage(state, player, ["Gallo Tower", "Green Acres"]) or ( has_any_stage(state, player, ["Cappella Magna"]) and has_hurry(state, player) ),
		"Kill Gold Pile": lambda state: has_any_stage(state, player, ["Westwoods"]),
		"Kill Big Oni": lambda state: has_any_stage(state, player, ["Mt.Moonspell"]),
		"Kill Goshadokuro": lambda state: has_any_stage(state, player, ["Mt.Moonspell"]),
		"Kill Sammy the Caterpillar": lambda state: has_any_stage(state, player, ["Lake Foscari"]),
		"Kill Fungoman": lambda state: has_any_stage(state, player, ["Lake Foscari"]),
		"Kill Corpseweed": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]),
		"Kill Bone Pillar": lambda state: has_any_stage(state, player, ["Ode to Castlevania"]),
		"Kill Gold Jellys": lambda state: has_any_stage(state, player, ["Westwoods"]),
		"Kill Mantichana Idol": lambda state: has_any_stage(state, player, ["Westwoods"]),
		"Kill Jastor": lambda state: has_any_stage(state, player, ["Westwoods"]),
		"Kill Mushroulette": lambda state: has_any_stage(state, player, ["Westwoods"]),
		"Kill 17th Collossus": lambda state: ( has_any_stage(state, player, ["Mazerella"]) and has_hurry(state, player) ),
		"Kill Pinthot & Coldellini": lambda state: has_any_stage(state, player, ["Polus Replica"]),
		"Kill Meat Bean": lambda state: has_any_stage(state, player, ["Polus Replica"]),
		"Kill Suspicio": lambda state: has_any_stage(state, player, ["Polus Replica"]),
		"Kill Jiang shi": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Gergoth": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Malevolent Door Spirit": lambda state: ( has_any_stage(state, player, ["Emerald Diorama"]) and has_hurry(state, player) ),
		"Kill Flower Pot": lambda state: has_any_stage(state, player, ["Ante Chamber"]),
		"Kill Spirit (Emerald DLC)": lambda state: ( has_any_stage(state, player, ["Emerald Diorama"]) and has_hurry(state, player) ),
		"Kill Foo'Ori Darkasso": lambda state: ( has_any_stage(state, player, ["Room 1665"]) and has_hurry(state, player) ),
		"Kill The Reaper": lambda state: ( has_any_stage(state, player, ["Mad Forest", "Holy Forbidden", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna", "Il Molise", "Moongolow", "Green Acres", "The Bone Zone", "Boss Rash", "Whiteout", "The Coop", "Space 54", "Carlo Cart", "Laborratory", "Westwoods", "Bat Country", "Astral Stair", "Mazerella", "Tiny Bridge", "Room 1665", "Mt.Moonspell", "Lake Foscari", "Abyss Foscari", "Polus Replica", "Neo Galuga", "Hectic Highway", "Ode to Castlevania", "Emerald Diorama", "Ante Chamber"]) and has_hurry(state, player) ),
		"Kill Nesufritto": lambda state: has_any_stage(state, player, ["Boss Rash"]) or ( has_any_stage(state, player, ["Inlaid Library", "Green Acres"]) and has_hurry(state, player) ),
		"Kill Hag": lambda state: has_any_stage(state, player, ["Boss Rash"]) or ( has_any_stage(state, player, ["Inlaid Library", "Green Acres"]) and has_hurry(state, player) ),
		"Kill The Ender": lambda state: has_any_stage(state, player, ["Boss Rash"]),
		"Kill Mimic Season One": lambda state: has_any_stage(state, player, ["Boss Rash"]),
		"Kill Mimic Season Two": lambda state: has_any_stage(state, player, ["Boss Rash"]),
		"Kill Mimic Season Three": lambda state: has_any_stage(state, player, ["Boss Rash"]),
		"Kill Lord Ghost": lambda state: has_any_stage(state, player, ["Astral Stair"]),
		"Kill Tanuki": lambda state: has_any_stage(state, player, ["Mt.Moonspell"]),
		"Kill Orochimario": lambda state: ( has_any_stage(state, player, ["Mt.Moonspell"]) and has_hurry(state, player) ),
		"Kill Avatar of Gaea": lambda state: ( has_any_stage(state, player, ["Lake Foscari"]) and has_hurry(state, player) ),
		"Kill Minotaur (Castlevania DLC)": lambda state: ( has_any_stage(state, player, ["Ode to Castlevania"]) and has_hurry(state, player) ),
		"Kill Small Blind": lambda state: has_any_stage(state, player, ["Ante Chamber"]),
		"Kill Big Blind": lambda state: has_any_stage(state, player, ["Ante Chamber"]),
		"Kill The Ox": lambda state: has_any_stage(state, player, ["Ante Chamber"]),
		"Kill The Manacle": lambda state: ( has_any_stage(state, player, ["Ante Chamber"]) and has_hurry(state, player) ),
		"Kill The Wall": lambda state: ( has_any_stage(state, player, ["Ante Chamber"]) and has_hurry(state, player) ),
		"Kill Crimson Heart": lambda state: ( has_any_stage(state, player, ["Ante Chamber"]) and has_hurry(state, player) ),
		"Kill Kizzune": lambda state: has_any_stage(state, player, ["Whiteout"]),
		"Kill Skelegem": lambda state: has_arcana(state, player) and has_any_stage(state, player, ["Mad Forest", "Eudaimonia M.", "Holy Forbidden", "Inlaid Library", "Dairy Plant", "Gallo Tower", "Cappella Magna", "Il Molise", "Moongolow", "Green Acres", "The Bone Zone", "Boss Rash", "Whiteout", "The Coop", "Space 54", "Carlo Cart", "Laborratory", "Westwoods", "Bat Country", "Astral Stair", "Mazerella", "Tiny Bridge", "Mt.Moonspell", "Lake Foscari", "Abyss Foscari", "Profane Chapel", "Ante Chamber", "Room 1665", "Neo Galuga", "Hectic Highway", "Ode to Castlevania", "Polus Replica", "Emerald Diorama"]),
		"Kill Death": lambda state: has_stage(state, player, "Ode to Castlevania") and has_character(state, player, "Richter Belmont") and has_hurry(state, player),
	}

def has_amount(state, player, item, amount) -> bool:
	return state.has(item, player, amount)

def has(state, player, item) -> bool:
	return has_amount(state, player, item, 1)

def has_any(state, player, items) -> bool:
	return any(has(state, player, item) for item in items)

def has_all(state, player, items) -> bool:
	return all(has(state, player, item) for item in items)

def has_character(state, player, character) -> bool:
	return has(state, player, f"Character Unlock: {character}")

def has_stage(state, player, stage) -> bool:
	return has(state, player, f"Stage Unlock: {stage}")

def has_any_stage(state, player, stages) -> bool:
	return has_any(state, player, [f"Stage Unlock: {stage}" for stage in stages])

def has_gamemode(state, player, gamemode) -> bool:
	return has(state, player, f"Gamemode Unlock: {gamemode}")

def has_hurry(state, player) -> bool:
	return has_gamemode(state, player, "Hurry")

def has_arcana(state, player) -> bool:
	return has_gamemode(state, player, "Arcanas")