# File is Auto-generated, see: [https://github.com/SWCreeperKing/ApWorldFactories/tree/master/ApWorldFactories/Games]

bacteria_techs = [
	["Bacteria Evolve: Bacterial Resilience 1", "Bacteria"],
	["Bacteria Evolve: Bacterial Resilience 2", "Bacteria"],
	["Bacteria Evolve: Bacterial Resilience 3", "Bacteria"],
	["Bacteria Evolve: Abscesses", "Bacteria"],
	["Bacteria Evolve: Air 1", "Bacteria"],
	["Bacteria Evolve: Air 2", "Bacteria"],
	["Bacteria Evolve: Anaemia", "Bacteria"],
	["Bacteria Evolve: Bird 1", "Bacteria"],
	["Bacteria Evolve: Bird 2", "Bacteria"],
	["Bacteria Evolve: Blood 1", "Bacteria"],
	["Bacteria Evolve: Blood 2", "Bacteria"],
	["Bacteria Evolve: Cold Resistance 1", "Bacteria"],
	["Bacteria Evolve: Cold Resistance 2", "Bacteria"],
	["Bacteria Evolve: Coma", "Bacteria"],
	["Bacteria Evolve: Coughing", "Bacteria"],
	["Bacteria Evolve: Cysts", "Bacteria"],
	["Bacteria Evolve: Diarrhoea", "Bacteria"],
	["Bacteria Evolve: Drug Resistance 1", "Bacteria"],
	["Bacteria Evolve: Drug Resistance 2", "Bacteria"],
	["Bacteria Evolve: Dysentery", "Bacteria"],
	["Bacteria Evolve: Environmental Hardening", "Bacteria"],
	["Bacteria Evolve: Extreme Bioaerosol", "Bacteria"],
	["Bacteria Evolve: Extreme Hematophagy", "Bacteria"],
	["Bacteria Evolve: Extreme Zoonosis", "Bacteria"],
	["Bacteria Evolve: Fever", "Bacteria"],
	["Bacteria Evolve: Genetic Hardening 1", "Bacteria"],
	["Bacteria Evolve: Genetic Hardening 2", "Bacteria"],
	["Bacteria Evolve: Genetic ReShuffle 1", "Bacteria"],
	["Bacteria Evolve: Genetic ReShuffle 2", "Bacteria"],
	["Bacteria Evolve: Genetic ReShuffle 3", "Bacteria"],
	["Bacteria Evolve: Haemophilia", "Bacteria"],
	["Bacteria Evolve: Heat Resistance 1", "Bacteria"],
	["Bacteria Evolve: Heat Resistance 2", "Bacteria"],
	["Bacteria Evolve: Hemorrhagic Shock", "Bacteria"],
	["Bacteria Evolve: Hyper sensitivity", "Bacteria"],
	["Bacteria Evolve: Immune Suppression", "Bacteria"],
	["Bacteria Evolve: Inflammation", "Bacteria"],
	["Bacteria Evolve: Insanity", "Bacteria"],
	["Bacteria Evolve: Insect 1", "Bacteria"],
	["Bacteria Evolve: Insect 2", "Bacteria"],
	["Bacteria Evolve: Insomnia", "Bacteria"],
	["Bacteria Evolve: Internal Haemorrhaging", "Bacteria"],
	["Bacteria Evolve: Livestock 1", "Bacteria"],
	["Bacteria Evolve: Livestock 2", "Bacteria"],
	["Bacteria Evolve: Nausea", "Bacteria"],
	["Bacteria Evolve: Necrosis", "Bacteria"],
	["Bacteria Evolve: Paralysis", "Bacteria"],
	["Bacteria Evolve: Paranoia", "Bacteria"],
	["Bacteria Evolve: Pneumonia", "Bacteria"],
	["Bacteria Evolve: Pulmonary Fibrosis", "Bacteria"],
	["Bacteria Evolve: Pulmonary Oedema", "Bacteria"],
	["Bacteria Evolve: Rash", "Bacteria"],
	["Bacteria Evolve: Rodent 1", "Bacteria"],
	["Bacteria Evolve: Rodent 2", "Bacteria"],
	["Bacteria Evolve: Seizures", "Bacteria"],
	["Bacteria Evolve: Skin Lesions", "Bacteria"],
	["Bacteria Evolve: Sneezing", "Bacteria"],
	["Bacteria Evolve: Sweating", "Bacteria"],
	["Bacteria Evolve: Systemic Infection", "Bacteria"],
	["Bacteria Evolve: Total Organ Failure", "Bacteria"],
	["Bacteria Evolve: Tumours", "Bacteria"],
	["Bacteria Evolve: Vomiting", "Bacteria"],
	["Bacteria Evolve: Water 1", "Bacteria"],
	["Bacteria Evolve: Water 2", "Bacteria"],
	["Beat Bacteria on Normal", "Bacteria"]
]

virus_techs = [
	["Virus Evolve: Abscesses", "Virus"],
	["Virus Evolve: Air 1", "Virus"],
	["Virus Evolve: Air 2", "Virus"],
	["Virus Evolve: Anaemia", "Virus"],
	["Virus Evolve: Bird 1", "Virus"],
	["Virus Evolve: Bird 2", "Virus"],
	["Virus Evolve: Blood 1", "Virus"],
	["Virus Evolve: Blood 2", "Virus"],
	["Virus Evolve: Cold Resistance 1", "Virus"],
	["Virus Evolve: Cold Resistance 2", "Virus"],
	["Virus Evolve: Coma", "Virus"],
	["Virus Evolve: Coughing", "Virus"],
	["Virus Evolve: Cysts", "Virus"],
	["Virus Evolve: Diarrhoea", "Virus"],
	["Virus Evolve: Drug Resistance 1", "Virus"],
	["Virus Evolve: Drug Resistance 2", "Virus"],
	["Virus Evolve: Dysentery", "Virus"],
	["Virus Evolve: Environmental Hardening", "Virus"],
	["Virus Evolve: Extreme Bioaerosol", "Virus"],
	["Virus Evolve: Extreme Hematophagy", "Virus"],
	["Virus Evolve: Extreme Zoonosis", "Virus"],
	["Virus Evolve: Fever", "Virus"],
	["Virus Evolve: Genetic Hardening 1", "Virus"],
	["Virus Evolve: Genetic Hardening 2", "Virus"],
	["Virus Evolve: Genetic ReShuffle 1", "Virus"],
	["Virus Evolve: Genetic ReShuffle 2", "Virus"],
	["Virus Evolve: Genetic ReShuffle 3", "Virus"],
	["Virus Evolve: Haemophilia", "Virus"],
	["Virus Evolve: Heat Resistance 1", "Virus"],
	["Virus Evolve: Heat Resistance 2", "Virus"],
	["Virus Evolve: Hemorrhagic Shock", "Virus"],
	["Virus Evolve: Hyper sensitivity", "Virus"],
	["Virus Evolve: Immune Suppression", "Virus"],
	["Virus Evolve: Inflammation", "Virus"],
	["Virus Evolve: Insanity", "Virus"],
	["Virus Evolve: Insect 1", "Virus"],
	["Virus Evolve: Insect 2", "Virus"],
	["Virus Evolve: Insomnia", "Virus"],
	["Virus Evolve: Internal Haemorrhaging", "Virus"],
	["Virus Evolve: Livestock 1", "Virus"],
	["Virus Evolve: Livestock 2", "Virus"],
	["Virus Evolve: Nausea", "Virus"],
	["Virus Evolve: Necrosis", "Virus"],
	["Virus Evolve: Paralysis", "Virus"],
	["Virus Evolve: Paranoia", "Virus"],
	["Virus Evolve: Pneumonia", "Virus"],
	["Virus Evolve: Pulmonary Fibrosis", "Virus"],
	["Virus Evolve: Pulmonary Oedema", "Virus"],
	["Virus Evolve: Rash", "Virus"],
	["Virus Evolve: Rodent 1", "Virus"],
	["Virus Evolve: Rodent 2", "Virus"],
	["Virus Evolve: Seizures", "Virus"],
	["Virus Evolve: Skin Lesions", "Virus"],
	["Virus Evolve: Sneezing", "Virus"],
	["Virus Evolve: Sweating", "Virus"],
	["Virus Evolve: Systemic Infection", "Virus"],
	["Virus Evolve: Total Organ Failure", "Virus"],
	["Virus Evolve: Tumours", "Virus"],
	["Virus Evolve: Vomiting", "Virus"],
	["Virus Evolve: Water 1", "Virus"],
	["Virus Evolve: Water 2", "Virus"],
	["Virus Evolve: Viral Instability 1", "Virus"],
	["Virus Evolve: Viral Instability 2", "Virus"],
	["Virus Evolve: Viral Instability 3", "Virus"],
	["Beat Virus on Normal", "Virus"]
]

fungus_techs = [
	["Fungus Evolve: Abscesses", "Fungus"],
	["Fungus Evolve: Air 1", "Fungus"],
	["Fungus Evolve: Air 2", "Fungus"],
	["Fungus Evolve: Anaemia", "Fungus"],
	["Fungus Evolve: Bird 1", "Fungus"],
	["Fungus Evolve: Bird 2", "Fungus"],
	["Fungus Evolve: Blood 1", "Fungus"],
	["Fungus Evolve: Blood 2", "Fungus"],
	["Fungus Evolve: Cold Resistance 1", "Fungus"],
	["Fungus Evolve: Cold Resistance 2", "Fungus"],
	["Fungus Evolve: Coma", "Fungus"],
	["Fungus Evolve: Coughing", "Fungus"],
	["Fungus Evolve: Cysts", "Fungus"],
	["Fungus Evolve: Diarrhoea", "Fungus"],
	["Fungus Evolve: Drug Resistance 1", "Fungus"],
	["Fungus Evolve: Drug Resistance 2", "Fungus"],
	["Fungus Evolve: Dysentery", "Fungus"],
	["Fungus Evolve: Environmental Hardening", "Fungus"],
	["Fungus Evolve: Extreme Bioaerosol", "Fungus"],
	["Fungus Evolve: Extreme Hematophagy", "Fungus"],
	["Fungus Evolve: Extreme Zoonosis", "Fungus"],
	["Fungus Evolve: Fever", "Fungus"],
	["Fungus Evolve: Genetic Hardening 1", "Fungus"],
	["Fungus Evolve: Genetic Hardening 2", "Fungus"],
	["Fungus Evolve: Genetic ReShuffle 1", "Fungus"],
	["Fungus Evolve: Genetic ReShuffle 2", "Fungus"],
	["Fungus Evolve: Genetic ReShuffle 3", "Fungus"],
	["Fungus Evolve: Haemophilia", "Fungus"],
	["Fungus Evolve: Heat Resistance 1", "Fungus"],
	["Fungus Evolve: Heat Resistance 2", "Fungus"],
	["Fungus Evolve: Hemorrhagic Shock", "Fungus"],
	["Fungus Evolve: Hyper sensitivity", "Fungus"],
	["Fungus Evolve: Immune Suppression", "Fungus"],
	["Fungus Evolve: Inflammation", "Fungus"],
	["Fungus Evolve: Insanity", "Fungus"],
	["Fungus Evolve: Insect 1", "Fungus"],
	["Fungus Evolve: Insect 2", "Fungus"],
	["Fungus Evolve: Insomnia", "Fungus"],
	["Fungus Evolve: Internal Haemorrhaging", "Fungus"],
	["Fungus Evolve: Livestock 1", "Fungus"],
	["Fungus Evolve: Livestock 2", "Fungus"],
	["Fungus Evolve: Nausea", "Fungus"],
	["Fungus Evolve: Necrosis", "Fungus"],
	["Fungus Evolve: Paralysis", "Fungus"],
	["Fungus Evolve: Paranoia", "Fungus"],
	["Fungus Evolve: Pneumonia", "Fungus"],
	["Fungus Evolve: Pulmonary Fibrosis", "Fungus"],
	["Fungus Evolve: Pulmonary Oedema", "Fungus"],
	["Fungus Evolve: Rash", "Fungus"],
	["Fungus Evolve: Rodent 1", "Fungus"],
	["Fungus Evolve: Rodent 2", "Fungus"],
	["Fungus Evolve: Seizures", "Fungus"],
	["Fungus Evolve: Skin Lesions", "Fungus"],
	["Fungus Evolve: Sneezing", "Fungus"],
	["Fungus Evolve: Sweating", "Fungus"],
	["Fungus Evolve: Systemic Infection", "Fungus"],
	["Fungus Evolve: Total Organ Failure", "Fungus"],
	["Fungus Evolve: Tumours", "Fungus"],
	["Fungus Evolve: Vomiting", "Fungus"],
	["Fungus Evolve: Water 1", "Fungus"],
	["Fungus Evolve: Water 2", "Fungus"],
	["Beat Fungus on Normal", "Fungus"]
]

parasite_techs = [
	["Parasite Evolve: Abscesses", "Parasite"],
	["Parasite Evolve: Air 1", "Parasite"],
	["Parasite Evolve: Air 2", "Parasite"],
	["Parasite Evolve: Anaemia", "Parasite"],
	["Parasite Evolve: Bird 1", "Parasite"],
	["Parasite Evolve: Bird 2", "Parasite"],
	["Parasite Evolve: Blood 1", "Parasite"],
	["Parasite Evolve: Blood 2", "Parasite"],
	["Parasite Evolve: Cold Resistance 1", "Parasite"],
	["Parasite Evolve: Cold Resistance 2", "Parasite"],
	["Parasite Evolve: Coma", "Parasite"],
	["Parasite Evolve: Coughing", "Parasite"],
	["Parasite Evolve: Cysts", "Parasite"],
	["Parasite Evolve: Diarrhoea", "Parasite"],
	["Parasite Evolve: Drug Resistance 1", "Parasite"],
	["Parasite Evolve: Drug Resistance 2", "Parasite"],
	["Parasite Evolve: Dysentery", "Parasite"],
	["Parasite Evolve: Environmental Hardening", "Parasite"],
	["Parasite Evolve: Extreme Bioaerosol", "Parasite"],
	["Parasite Evolve: Extreme Hematophagy", "Parasite"],
	["Parasite Evolve: Extreme Zoonosis", "Parasite"],
	["Parasite Evolve: Fever", "Parasite"],
	["Parasite Evolve: Genetic Hardening 1", "Parasite"],
	["Parasite Evolve: Genetic Hardening 2", "Parasite"],
	["Parasite Evolve: Genetic ReShuffle 1", "Parasite"],
	["Parasite Evolve: Genetic ReShuffle 2", "Parasite"],
	["Parasite Evolve: Genetic ReShuffle 3", "Parasite"],
	["Parasite Evolve: Haemophilia", "Parasite"],
	["Parasite Evolve: Heat Resistance 1", "Parasite"],
	["Parasite Evolve: Heat Resistance 2", "Parasite"],
	["Parasite Evolve: Hemorrhagic Shock", "Parasite"],
	["Parasite Evolve: Hyper sensitivity", "Parasite"],
	["Parasite Evolve: Immune Suppression", "Parasite"],
	["Parasite Evolve: Inflammation", "Parasite"],
	["Parasite Evolve: Insanity", "Parasite"],
	["Parasite Evolve: Insect 1", "Parasite"],
	["Parasite Evolve: Insect 2", "Parasite"],
	["Parasite Evolve: Insomnia", "Parasite"],
	["Parasite Evolve: Internal Haemorrhaging", "Parasite"],
	["Parasite Evolve: Livestock 1", "Parasite"],
	["Parasite Evolve: Livestock 2", "Parasite"],
	["Parasite Evolve: Nausea", "Parasite"],
	["Parasite Evolve: Necrosis", "Parasite"],
	["Parasite Evolve: Paralysis", "Parasite"],
	["Parasite Evolve: Paranoia", "Parasite"],
	["Parasite Evolve: Pneumonia", "Parasite"],
	["Parasite Evolve: Pulmonary Fibrosis", "Parasite"],
	["Parasite Evolve: Pulmonary Oedema", "Parasite"],
	["Parasite Evolve: Rash", "Parasite"],
	["Parasite Evolve: Rodent 1", "Parasite"],
	["Parasite Evolve: Rodent 2", "Parasite"],
	["Parasite Evolve: Seizures", "Parasite"],
	["Parasite Evolve: Skin Lesions", "Parasite"],
	["Parasite Evolve: Sneezing", "Parasite"],
	["Parasite Evolve: Sweating", "Parasite"],
	["Parasite Evolve: Systemic Infection", "Parasite"],
	["Parasite Evolve: Total Organ Failure", "Parasite"],
	["Parasite Evolve: Tumours", "Parasite"],
	["Parasite Evolve: Vomiting", "Parasite"],
	["Parasite Evolve: Water 1", "Parasite"],
	["Parasite Evolve: Water 2", "Parasite"],
	["Parasite Evolve: Symbiosis 1", "Parasite"],
	["Parasite Evolve: Symbiosis 2", "Parasite"],
	["Parasite Evolve: Symbiosis 3", "Parasite"],
	["Beat Parasite on Normal", "Parasite"]
]

prion_techs = [
	["Prion Evolve: Abscesses", "Prion"],
	["Prion Evolve: Air 1", "Prion"],
	["Prion Evolve: Air 2", "Prion"],
	["Prion Evolve: Anaemia", "Prion"],
	["Prion Evolve: Bird 1", "Prion"],
	["Prion Evolve: Bird 2", "Prion"],
	["Prion Evolve: Blood 1", "Prion"],
	["Prion Evolve: Blood 2", "Prion"],
	["Prion Evolve: Cold Resistance 1", "Prion"],
	["Prion Evolve: Cold Resistance 2", "Prion"],
	["Prion Evolve: Coma", "Prion"],
	["Prion Evolve: Coughing", "Prion"],
	["Prion Evolve: Cysts", "Prion"],
	["Prion Evolve: Diarrhoea", "Prion"],
	["Prion Evolve: Drug Resistance 1", "Prion"],
	["Prion Evolve: Drug Resistance 2", "Prion"],
	["Prion Evolve: Dysentery", "Prion"],
	["Prion Evolve: Environmental Hardening", "Prion"],
	["Prion Evolve: Extreme Bioaerosol", "Prion"],
	["Prion Evolve: Extreme Hematophagy", "Prion"],
	["Prion Evolve: Extreme Zoonosis", "Prion"],
	["Prion Evolve: Fever", "Prion"],
	["Prion Evolve: Genetic Hardening 1", "Prion"],
	["Prion Evolve: Genetic Hardening 2", "Prion"],
	["Prion Evolve: Genetic ReShuffle 1", "Prion"],
	["Prion Evolve: Genetic ReShuffle 2", "Prion"],
	["Prion Evolve: Genetic ReShuffle 3", "Prion"],
	["Prion Evolve: Haemophilia", "Prion"],
	["Prion Evolve: Heat Resistance 1", "Prion"],
	["Prion Evolve: Heat Resistance 2", "Prion"],
	["Prion Evolve: Hemorrhagic Shock", "Prion"],
	["Prion Evolve: Hyper sensitivity", "Prion"],
	["Prion Evolve: Immune Suppression", "Prion"],
	["Prion Evolve: Inflammation", "Prion"],
	["Prion Evolve: Insanity", "Prion"],
	["Prion Evolve: Insect 1", "Prion"],
	["Prion Evolve: Insect 2", "Prion"],
	["Prion Evolve: Insomnia", "Prion"],
	["Prion Evolve: Internal Haemorrhaging", "Prion"],
	["Prion Evolve: Livestock 1", "Prion"],
	["Prion Evolve: Livestock 2", "Prion"],
	["Prion Evolve: Nausea", "Prion"],
	["Prion Evolve: Necrosis", "Prion"],
	["Prion Evolve: Paralysis", "Prion"],
	["Prion Evolve: Paranoia", "Prion"],
	["Prion Evolve: Pneumonia", "Prion"],
	["Prion Evolve: Pulmonary Fibrosis", "Prion"],
	["Prion Evolve: Pulmonary Oedema", "Prion"],
	["Prion Evolve: Rash", "Prion"],
	["Prion Evolve: Rodent 1", "Prion"],
	["Prion Evolve: Rodent 2", "Prion"],
	["Prion Evolve: Seizures", "Prion"],
	["Prion Evolve: Skin Lesions", "Prion"],
	["Prion Evolve: Sneezing", "Prion"],
	["Prion Evolve: Sweating", "Prion"],
	["Prion Evolve: Systemic Infection", "Prion"],
	["Prion Evolve: Total Organ Failure", "Prion"],
	["Prion Evolve: Tumours", "Prion"],
	["Prion Evolve: Vomiting", "Prion"],
	["Prion Evolve: Water 1", "Prion"],
	["Prion Evolve: Water 2", "Prion"],
	["Prion Evolve: Neural Atrophy 1", "Prion"],
	["Prion Evolve: Neural Atrophy 2", "Prion"],
	["Prion Evolve: Neural Atrophy 3", "Prion"],
	["Beat Prion on Normal", "Prion"]
]

nano_virus_techs = [
	["Nano Virus Evolve: Abscesses", "Nano Virus"],
	["Nano Virus Evolve: Air 1", "Nano Virus"],
	["Nano Virus Evolve: Air 2", "Nano Virus"],
	["Nano Virus Evolve: Anaemia", "Nano Virus"],
	["Nano Virus Evolve: Bird 1", "Nano Virus"],
	["Nano Virus Evolve: Bird 2", "Nano Virus"],
	["Nano Virus Evolve: Blood 1", "Nano Virus"],
	["Nano Virus Evolve: Blood 2", "Nano Virus"],
	["Nano Virus Evolve: Cold Resistance 1", "Nano Virus"],
	["Nano Virus Evolve: Cold Resistance 2", "Nano Virus"],
	["Nano Virus Evolve: Coma", "Nano Virus"],
	["Nano Virus Evolve: Coughing", "Nano Virus"],
	["Nano Virus Evolve: Cysts", "Nano Virus"],
	["Nano Virus Evolve: Diarrhoea", "Nano Virus"],
	["Nano Virus Evolve: Drug Resistance 1", "Nano Virus"],
	["Nano Virus Evolve: Drug Resistance 2", "Nano Virus"],
	["Nano Virus Evolve: Dysentery", "Nano Virus"],
	["Nano Virus Evolve: Environmental Hardening", "Nano Virus"],
	["Nano Virus Evolve: Extreme Bioaerosol", "Nano Virus"],
	["Nano Virus Evolve: Extreme Hematophagy", "Nano Virus"],
	["Nano Virus Evolve: Extreme Zoonosis", "Nano Virus"],
	["Nano Virus Evolve: Fever", "Nano Virus"],
	["Nano Virus Evolve: Genetic Hardening 1", "Nano Virus"],
	["Nano Virus Evolve: Genetic Hardening 2", "Nano Virus"],
	["Nano Virus Evolve: Genetic ReShuffle 1", "Nano Virus"],
	["Nano Virus Evolve: Genetic ReShuffle 2", "Nano Virus"],
	["Nano Virus Evolve: Genetic ReShuffle 3", "Nano Virus"],
	["Nano Virus Evolve: Haemophilia", "Nano Virus"],
	["Nano Virus Evolve: Heat Resistance 1", "Nano Virus"],
	["Nano Virus Evolve: Heat Resistance 2", "Nano Virus"],
	["Nano Virus Evolve: Hemorrhagic Shock", "Nano Virus"],
	["Nano Virus Evolve: Hyper sensitivity", "Nano Virus"],
	["Nano Virus Evolve: Immune Suppression", "Nano Virus"],
	["Nano Virus Evolve: Inflammation", "Nano Virus"],
	["Nano Virus Evolve: Insanity", "Nano Virus"],
	["Nano Virus Evolve: Insect 1", "Nano Virus"],
	["Nano Virus Evolve: Insect 2", "Nano Virus"],
	["Nano Virus Evolve: Insomnia", "Nano Virus"],
	["Nano Virus Evolve: Internal Haemorrhaging", "Nano Virus"],
	["Nano Virus Evolve: Livestock 1", "Nano Virus"],
	["Nano Virus Evolve: Livestock 2", "Nano Virus"],
	["Nano Virus Evolve: Nausea", "Nano Virus"],
	["Nano Virus Evolve: Necrosis", "Nano Virus"],
	["Nano Virus Evolve: Paralysis", "Nano Virus"],
	["Nano Virus Evolve: Paranoia", "Nano Virus"],
	["Nano Virus Evolve: Pneumonia", "Nano Virus"],
	["Nano Virus Evolve: Pulmonary Fibrosis", "Nano Virus"],
	["Nano Virus Evolve: Pulmonary Oedema", "Nano Virus"],
	["Nano Virus Evolve: Rash", "Nano Virus"],
	["Nano Virus Evolve: Rodent 1", "Nano Virus"],
	["Nano Virus Evolve: Rodent 2", "Nano Virus"],
	["Nano Virus Evolve: Seizures", "Nano Virus"],
	["Nano Virus Evolve: Skin Lesions", "Nano Virus"],
	["Nano Virus Evolve: Sneezing", "Nano Virus"],
	["Nano Virus Evolve: Sweating", "Nano Virus"],
	["Nano Virus Evolve: Systemic Infection", "Nano Virus"],
	["Nano Virus Evolve: Total Organ Failure", "Nano Virus"],
	["Nano Virus Evolve: Tumours", "Nano Virus"],
	["Nano Virus Evolve: Vomiting", "Nano Virus"],
	["Nano Virus Evolve: Water 1", "Nano Virus"],
	["Nano Virus Evolve: Water 2", "Nano Virus"],
	["Nano Virus Evolve: Broadcast Interceptor overload", "Nano Virus"],
	["Nano Virus Evolve: Code fragment interception", "Nano Virus"],
	["Nano Virus Evolve: Code segment interception", "Nano Virus"],
	["Nano Virus Evolve: Drug immunity", "Nano Virus"],
	["Nano Virus Evolve: Encryption breached", "Nano Virus"],
	["Nano Virus Evolve: Kill Switch stasis", "Nano Virus"],
	["Nano Virus Evolve: Radical elements stabilised", "Nano Virus"],
	["Nano Virus Evolve: Replication Factory overload", "Nano Virus"],
	["Beat Nano Virus on Normal", "Nano Virus"]
]

bio_weapon_techs = [
	["Bio Weapon Evolve: Abscesses", "Bio Weapon"],
	["Bio Weapon Evolve: Air 1", "Bio Weapon"],
	["Bio Weapon Evolve: Air 2", "Bio Weapon"],
	["Bio Weapon Evolve: Anaemia", "Bio Weapon"],
	["Bio Weapon Evolve: Bird 1", "Bio Weapon"],
	["Bio Weapon Evolve: Bird 2", "Bio Weapon"],
	["Bio Weapon Evolve: Blood 1", "Bio Weapon"],
	["Bio Weapon Evolve: Blood 2", "Bio Weapon"],
	["Bio Weapon Evolve: Cold Resistance 1", "Bio Weapon"],
	["Bio Weapon Evolve: Cold Resistance 2", "Bio Weapon"],
	["Bio Weapon Evolve: Coma", "Bio Weapon"],
	["Bio Weapon Evolve: Coughing", "Bio Weapon"],
	["Bio Weapon Evolve: Cysts", "Bio Weapon"],
	["Bio Weapon Evolve: Diarrhoea", "Bio Weapon"],
	["Bio Weapon Evolve: Drug Resistance 1", "Bio Weapon"],
	["Bio Weapon Evolve: Drug Resistance 2", "Bio Weapon"],
	["Bio Weapon Evolve: Dysentery", "Bio Weapon"],
	["Bio Weapon Evolve: Environmental Hardening", "Bio Weapon"],
	["Bio Weapon Evolve: Extreme Bioaerosol", "Bio Weapon"],
	["Bio Weapon Evolve: Extreme Hematophagy", "Bio Weapon"],
	["Bio Weapon Evolve: Extreme Zoonosis", "Bio Weapon"],
	["Bio Weapon Evolve: Fever", "Bio Weapon"],
	["Bio Weapon Evolve: Genetic Hardening 1", "Bio Weapon"],
	["Bio Weapon Evolve: Genetic Hardening 2", "Bio Weapon"],
	["Bio Weapon Evolve: Genetic ReShuffle 1", "Bio Weapon"],
	["Bio Weapon Evolve: Genetic ReShuffle 2", "Bio Weapon"],
	["Bio Weapon Evolve: Genetic ReShuffle 3", "Bio Weapon"],
	["Bio Weapon Evolve: Haemophilia", "Bio Weapon"],
	["Bio Weapon Evolve: Heat Resistance 1", "Bio Weapon"],
	["Bio Weapon Evolve: Heat Resistance 2", "Bio Weapon"],
	["Bio Weapon Evolve: Hemorrhagic Shock", "Bio Weapon"],
	["Bio Weapon Evolve: Hyper sensitivity", "Bio Weapon"],
	["Bio Weapon Evolve: Immune Suppression", "Bio Weapon"],
	["Bio Weapon Evolve: Inflammation", "Bio Weapon"],
	["Bio Weapon Evolve: Insanity", "Bio Weapon"],
	["Bio Weapon Evolve: Insect 1", "Bio Weapon"],
	["Bio Weapon Evolve: Insect 2", "Bio Weapon"],
	["Bio Weapon Evolve: Insomnia", "Bio Weapon"],
	["Bio Weapon Evolve: Internal Haemorrhaging", "Bio Weapon"],
	["Bio Weapon Evolve: Livestock 1", "Bio Weapon"],
	["Bio Weapon Evolve: Livestock 2", "Bio Weapon"],
	["Bio Weapon Evolve: Nausea", "Bio Weapon"],
	["Bio Weapon Evolve: Necrosis", "Bio Weapon"],
	["Bio Weapon Evolve: Paralysis", "Bio Weapon"],
	["Bio Weapon Evolve: Paranoia", "Bio Weapon"],
	["Bio Weapon Evolve: Pneumonia", "Bio Weapon"],
	["Bio Weapon Evolve: Pulmonary Fibrosis", "Bio Weapon"],
	["Bio Weapon Evolve: Pulmonary Oedema", "Bio Weapon"],
	["Bio Weapon Evolve: Rash", "Bio Weapon"],
	["Bio Weapon Evolve: Rodent 1", "Bio Weapon"],
	["Bio Weapon Evolve: Rodent 2", "Bio Weapon"],
	["Bio Weapon Evolve: Seizures", "Bio Weapon"],
	["Bio Weapon Evolve: Skin Lesions", "Bio Weapon"],
	["Bio Weapon Evolve: Sneezing", "Bio Weapon"],
	["Bio Weapon Evolve: Sweating", "Bio Weapon"],
	["Bio Weapon Evolve: Systemic Infection", "Bio Weapon"],
	["Bio Weapon Evolve: Total Organ Failure", "Bio Weapon"],
	["Bio Weapon Evolve: Tumours", "Bio Weapon"],
	["Bio Weapon Evolve: Vomiting", "Bio Weapon"],
	["Bio Weapon Evolve: Water 1", "Bio Weapon"],
	["Bio Weapon Evolve: Water 2", "Bio Weapon"],
	["Bio Weapon Evolve: Deactivate modified genes 1", "Bio Weapon"],
	["Bio Weapon Evolve: Deactivate modified genes 2", "Bio Weapon"],
	["Bio Weapon Evolve: Deactivate modified genes 3", "Bio Weapon"],
	["Bio Weapon Evolve: Gene Compression 1", "Bio Weapon"],
	["Bio Weapon Evolve: Gene Compression 2", "Bio Weapon"],
	["Bio Weapon Evolve: Gene Compression 3", "Bio Weapon"],
	["Bio Weapon Evolve: Neucleic Acid Neutralisation 1", "Bio Weapon"],
	["Bio Weapon Evolve: Neucleic Acid Neutralisation 2", "Bio Weapon"],
	["Bio Weapon Evolve: Neucleic Acid Neutralisation 3", "Bio Weapon"],
	["Bio Weapon Evolve: Unlock Annihilate gene", "Bio Weapon"],
	["Beat Bio Weapon on Normal", "Bio Weapon"]
]

location_dict = [
	*[items[0] for items in bacteria_techs],
	*[items[0] for items in virus_techs],
	*[items[0] for items in fungus_techs],
	*[items[0] for items in parasite_techs],
	*[items[0] for items in prion_techs],
	*[items[0] for items in nano_virus_techs],
	*[items[0] for items in bio_weapon_techs]
]

victory_scores = {
	"Bacteria": {
		"Bacterial Resilience 1": 0,
		"Bacterial Resilience 2": 0,
		"Bacterial Resilience 3": 0,
		"Abscesses": 4,
		"Air 1": 4,
		"Air 2": 7,
		"Anaemia": 1,
		"Bird 1": 3,
		"Bird 2": 6,
		"Blood 1": 2,
		"Blood 2": 4,
		"Cold Resistance 1": 0,
		"Cold Resistance 2": 0,
		"Coma": 2,
		"Coughing": 3,
		"Cysts": 2,
		"Diarrhoea": 7,
		"Drug Resistance 1": 0,
		"Drug Resistance 2": 0,
		"Dysentery": 16,
		"Environmental Hardening": 0,
		"Extreme Bioaerosol": 5,
		"Extreme Hematophagy": 5,
		"Extreme Zoonosis": 5,
		"Fever": 7,
		"Genetic Hardening 1": 0,
		"Genetic Hardening 2": 0,
		"Genetic ReShuffle 1": 0,
		"Genetic ReShuffle 2": 0,
		"Genetic ReShuffle 3": 0,
		"Haemophilia": 3,
		"Heat Resistance 1": 0,
		"Heat Resistance 2": 0,
		"Hemorrhagic Shock": 15,
		"Hyper sensitivity": 1,
		"Immune Suppression": 6,
		"Inflammation": 4,
		"Insanity": 6,
		"Insect 1": 4,
		"Insect 2": 8,
		"Insomnia": 0,
		"Internal Haemorrhaging": 7,
		"Livestock 1": 2,
		"Livestock 2": 4,
		"Nausea": 1,
		"Necrosis": 23,
		"Paralysis": 2,
		"Paranoia": 0,
		"Pneumonia": 3,
		"Pulmonary Fibrosis": 5,
		"Pulmonary Oedema": 7,
		"Rash": 2,
		"Rodent 1": 3,
		"Rodent 2": 6,
		"Seizures": 4,
		"Skin Lesions": 11,
		"Sneezing": 5,
		"Sweating": 2,
		"Systemic Infection": 12,
		"Total Organ Failure": 25,
		"Tumours": 6,
		"Vomiting": 3,
		"Water 1": 4,
		"Water 2": 8
	},
	"Virus": {
		"Abscesses": 4,
		"Air 1": 4,
		"Air 2": 7,
		"Anaemia": 1,
		"Bird 1": 3,
		"Bird 2": 6,
		"Blood 1": 2,
		"Blood 2": 4,
		"Cold Resistance 1": 0,
		"Cold Resistance 2": 0,
		"Coma": 2,
		"Coughing": 3,
		"Cysts": 2,
		"Diarrhoea": 7,
		"Drug Resistance 1": 0,
		"Drug Resistance 2": 0,
		"Dysentery": 16,
		"Environmental Hardening": 0,
		"Extreme Bioaerosol": 5,
		"Extreme Hematophagy": 5,
		"Extreme Zoonosis": 5,
		"Fever": 7,
		"Genetic Hardening 1": 0,
		"Genetic Hardening 2": 0,
		"Genetic ReShuffle 1": 0,
		"Genetic ReShuffle 2": 0,
		"Genetic ReShuffle 3": 0,
		"Haemophilia": 3,
		"Heat Resistance 1": 0,
		"Heat Resistance 2": 0,
		"Hemorrhagic Shock": 15,
		"Hyper sensitivity": 1,
		"Immune Suppression": 6,
		"Inflammation": 4,
		"Insanity": 6,
		"Insect 1": 4,
		"Insect 2": 8,
		"Insomnia": 0,
		"Internal Haemorrhaging": 7,
		"Livestock 1": 2,
		"Livestock 2": 4,
		"Nausea": 1,
		"Necrosis": 23,
		"Paralysis": 2,
		"Paranoia": 0,
		"Pneumonia": 3,
		"Pulmonary Fibrosis": 5,
		"Pulmonary Oedema": 7,
		"Rash": 2,
		"Rodent 1": 3,
		"Rodent 2": 6,
		"Seizures": 4,
		"Skin Lesions": 11,
		"Sneezing": 5,
		"Sweating": 2,
		"Systemic Infection": 12,
		"Total Organ Failure": 25,
		"Tumours": 6,
		"Vomiting": 3,
		"Water 1": 4,
		"Water 2": 8,
		"Viral Instability 1": 0,
		"Viral Instability 2": 0,
		"Viral Instability 3": 0
	},
	"Fungus": {
		"Abscesses": 4,
		"Air 1": 4,
		"Air 2": 7,
		"Anaemia": 1,
		"Bird 1": 3,
		"Bird 2": 6,
		"Blood 1": 2,
		"Blood 2": 4,
		"Cold Resistance 1": 0,
		"Cold Resistance 2": 0,
		"Coma": 2,
		"Coughing": 3,
		"Cysts": 2,
		"Diarrhoea": 7,
		"Drug Resistance 1": 0,
		"Drug Resistance 2": 0,
		"Dysentery": 16,
		"Environmental Hardening": 0,
		"Extreme Bioaerosol": 5,
		"Extreme Hematophagy": 5,
		"Extreme Zoonosis": 5,
		"Fever": 7,
		"Genetic Hardening 1": 0,
		"Genetic Hardening 2": 0,
		"Genetic ReShuffle 1": 0,
		"Genetic ReShuffle 2": 0,
		"Genetic ReShuffle 3": 0,
		"Haemophilia": 3,
		"Heat Resistance 1": 0,
		"Heat Resistance 2": 0,
		"Hemorrhagic Shock": 15,
		"Hyper sensitivity": 1,
		"Immune Suppression": 6,
		"Inflammation": 4,
		"Insanity": 6,
		"Insect 1": 4,
		"Insect 2": 8,
		"Insomnia": 0,
		"Internal Haemorrhaging": 7,
		"Livestock 1": 2,
		"Livestock 2": 4,
		"Nausea": 1,
		"Necrosis": 23,
		"Paralysis": 2,
		"Paranoia": 0,
		"Pneumonia": 3,
		"Pulmonary Fibrosis": 5,
		"Pulmonary Oedema": 7,
		"Rash": 2,
		"Rodent 1": 3,
		"Rodent 2": 6,
		"Seizures": 4,
		"Skin Lesions": 11,
		"Sneezing": 5,
		"Sweating": 2,
		"Systemic Infection": 12,
		"Total Organ Failure": 25,
		"Tumours": 6,
		"Vomiting": 3,
		"Water 1": 4,
		"Water 2": 8
	},
	"Parasite": {
		"Abscesses": 4,
		"Air 1": 4,
		"Air 2": 7,
		"Anaemia": 1,
		"Bird 1": 3,
		"Bird 2": 6,
		"Blood 1": 2,
		"Blood 2": 4,
		"Cold Resistance 1": 0,
		"Cold Resistance 2": 0,
		"Coma": 2,
		"Coughing": 3,
		"Cysts": 2,
		"Diarrhoea": 7,
		"Drug Resistance 1": 0,
		"Drug Resistance 2": 0,
		"Dysentery": 16,
		"Environmental Hardening": 0,
		"Extreme Bioaerosol": 5,
		"Extreme Hematophagy": 5,
		"Extreme Zoonosis": 5,
		"Fever": 7,
		"Genetic Hardening 1": 0,
		"Genetic Hardening 2": 0,
		"Genetic ReShuffle 1": 0,
		"Genetic ReShuffle 2": 0,
		"Genetic ReShuffle 3": 0,
		"Haemophilia": 3,
		"Heat Resistance 1": 0,
		"Heat Resistance 2": 0,
		"Hemorrhagic Shock": 15,
		"Hyper sensitivity": 1,
		"Immune Suppression": 6,
		"Inflammation": 4,
		"Insanity": 6,
		"Insect 1": 4,
		"Insect 2": 8,
		"Insomnia": 0,
		"Internal Haemorrhaging": 7,
		"Livestock 1": 2,
		"Livestock 2": 4,
		"Nausea": 1,
		"Necrosis": 23,
		"Paralysis": 2,
		"Paranoia": 0,
		"Pneumonia": 3,
		"Pulmonary Fibrosis": 5,
		"Pulmonary Oedema": 7,
		"Rash": 2,
		"Rodent 1": 3,
		"Rodent 2": 6,
		"Seizures": 4,
		"Skin Lesions": 11,
		"Sneezing": 5,
		"Sweating": 2,
		"Systemic Infection": 12,
		"Total Organ Failure": 25,
		"Tumours": 6,
		"Vomiting": 3,
		"Water 1": 4,
		"Water 2": 8,
		"Symbiosis 1": 0,
		"Symbiosis 2": 0,
		"Symbiosis 3": 2
	},
	"Prion": {
		"Abscesses": 4,
		"Air 1": 4,
		"Air 2": 7,
		"Anaemia": 1,
		"Bird 1": 3,
		"Bird 2": 6,
		"Blood 1": 2,
		"Blood 2": 4,
		"Cold Resistance 1": 0,
		"Cold Resistance 2": 0,
		"Coma": 2,
		"Coughing": 3,
		"Cysts": 2,
		"Diarrhoea": 7,
		"Drug Resistance 1": 0,
		"Drug Resistance 2": 0,
		"Dysentery": 16,
		"Environmental Hardening": 0,
		"Extreme Bioaerosol": 5,
		"Extreme Hematophagy": 5,
		"Extreme Zoonosis": 5,
		"Fever": 7,
		"Genetic Hardening 1": 0,
		"Genetic Hardening 2": 0,
		"Genetic ReShuffle 1": 0,
		"Genetic ReShuffle 2": 0,
		"Genetic ReShuffle 3": 0,
		"Haemophilia": 3,
		"Heat Resistance 1": 0,
		"Heat Resistance 2": 0,
		"Hemorrhagic Shock": 15,
		"Hyper sensitivity": 1,
		"Immune Suppression": 6,
		"Inflammation": 4,
		"Insanity": 6,
		"Insect 1": 4,
		"Insect 2": 8,
		"Insomnia": 0,
		"Internal Haemorrhaging": 7,
		"Livestock 1": 2,
		"Livestock 2": 4,
		"Nausea": 1,
		"Necrosis": 23,
		"Paralysis": 2,
		"Paranoia": 0,
		"Pneumonia": 3,
		"Pulmonary Fibrosis": 5,
		"Pulmonary Oedema": 7,
		"Rash": 2,
		"Rodent 1": 3,
		"Rodent 2": 6,
		"Seizures": 4,
		"Skin Lesions": 11,
		"Sneezing": 5,
		"Sweating": 2,
		"Systemic Infection": 12,
		"Total Organ Failure": 25,
		"Tumours": 6,
		"Vomiting": 3,
		"Water 1": 4,
		"Water 2": 8,
		"Neural Atrophy 1": 0,
		"Neural Atrophy 2": 0,
		"Neural Atrophy 3": 0
	},
	"Nano Virus": {
		"Abscesses": 4,
		"Air 1": 4,
		"Air 2": 7,
		"Anaemia": 1,
		"Bird 1": 3,
		"Bird 2": 6,
		"Blood 1": 2,
		"Blood 2": 4,
		"Cold Resistance 1": 0,
		"Cold Resistance 2": 0,
		"Coma": 2,
		"Coughing": 3,
		"Cysts": 2,
		"Diarrhoea": 7,
		"Drug Resistance 1": 0,
		"Drug Resistance 2": 0,
		"Dysentery": 16,
		"Environmental Hardening": 0,
		"Extreme Bioaerosol": 5,
		"Extreme Hematophagy": 5,
		"Extreme Zoonosis": 5,
		"Fever": 7,
		"Genetic Hardening 1": 0,
		"Genetic Hardening 2": 0,
		"Genetic ReShuffle 1": 0,
		"Genetic ReShuffle 2": 0,
		"Genetic ReShuffle 3": 0,
		"Haemophilia": 3,
		"Heat Resistance 1": 0,
		"Heat Resistance 2": 0,
		"Hemorrhagic Shock": 15,
		"Hyper sensitivity": 1,
		"Immune Suppression": 6,
		"Inflammation": 4,
		"Insanity": 6,
		"Insect 1": 4,
		"Insect 2": 8,
		"Insomnia": 0,
		"Internal Haemorrhaging": 7,
		"Livestock 1": 2,
		"Livestock 2": 4,
		"Nausea": 1,
		"Necrosis": 23,
		"Paralysis": 2,
		"Paranoia": 0,
		"Pneumonia": 3,
		"Pulmonary Fibrosis": 5,
		"Pulmonary Oedema": 7,
		"Rash": 2,
		"Rodent 1": 3,
		"Rodent 2": 6,
		"Seizures": 4,
		"Skin Lesions": 11,
		"Sneezing": 5,
		"Sweating": 2,
		"Systemic Infection": 12,
		"Total Organ Failure": 25,
		"Tumours": 6,
		"Vomiting": 3,
		"Water 1": 4,
		"Water 2": 8,
		"Broadcast Interceptor overload": 0,
		"Code fragment interception": 0,
		"Code segment interception": 0,
		"Drug immunity": 0,
		"Encryption breached": 0,
		"Kill Switch stasis": 0,
		"Radical elements stabilised": 0,
		"Replication Factory overload": 0
	},
	"Bio Weapon": {
		"Abscesses": 4,
		"Air 1": 4,
		"Air 2": 7,
		"Anaemia": 1,
		"Bird 1": 3,
		"Bird 2": 6,
		"Blood 1": 2,
		"Blood 2": 4,
		"Cold Resistance 1": 0,
		"Cold Resistance 2": 0,
		"Coma": 2,
		"Coughing": 3,
		"Cysts": 2,
		"Diarrhoea": 7,
		"Drug Resistance 1": 0,
		"Drug Resistance 2": 0,
		"Dysentery": 16,
		"Environmental Hardening": 0,
		"Extreme Bioaerosol": 5,
		"Extreme Hematophagy": 5,
		"Extreme Zoonosis": 5,
		"Fever": 7,
		"Genetic Hardening 1": 0,
		"Genetic Hardening 2": 0,
		"Genetic ReShuffle 1": 0,
		"Genetic ReShuffle 2": 0,
		"Genetic ReShuffle 3": 0,
		"Haemophilia": 3,
		"Heat Resistance 1": 0,
		"Heat Resistance 2": 0,
		"Hemorrhagic Shock": 15,
		"Hyper sensitivity": 1,
		"Immune Suppression": 6,
		"Inflammation": 4,
		"Insanity": 6,
		"Insect 1": 4,
		"Insect 2": 8,
		"Insomnia": 0,
		"Internal Haemorrhaging": 7,
		"Livestock 1": 2,
		"Livestock 2": 4,
		"Nausea": 1,
		"Necrosis": 23,
		"Paralysis": 2,
		"Paranoia": 0,
		"Pneumonia": 3,
		"Pulmonary Fibrosis": 5,
		"Pulmonary Oedema": 7,
		"Rash": 2,
		"Rodent 1": 3,
		"Rodent 2": 6,
		"Seizures": 4,
		"Skin Lesions": 11,
		"Sneezing": 5,
		"Sweating": 2,
		"Systemic Infection": 12,
		"Total Organ Failure": 25,
		"Tumours": 6,
		"Vomiting": 3,
		"Water 1": 4,
		"Water 2": 8,
		"Deactivate modified genes 1": -2,
		"Deactivate modified genes 2": -3,
		"Deactivate modified genes 3": -5,
		"Gene Compression 1": 0,
		"Gene Compression 2": 0,
		"Gene Compression 3": 0,
		"Neucleic Acid Neutralisation 1": 0,
		"Neucleic Acid Neutralisation 2": 0,
		"Neucleic Acid Neutralisation 3": 0,
		"Unlock Annihilate gene": 140
	}
}