import math
from .Locations import *

# File is Auto-generated, see: [https://github.com/SWCreeperKing/ApWorldFactories/tree/master/ApWorldFactories/Games]

def get_rule_map(player):
	return {
		"Bacteria Evolve: Nausea": lambda state: has_item(state, player, "Nausea"),
		"Virus Evolve: Nausea": lambda state: has_item(state, player, "Nausea"),
		"Fungus Evolve: Nausea": lambda state: has_item(state, player, "Nausea"),
		"Parasite Evolve: Nausea": lambda state: has_item(state, player, "Nausea"),
		"Prion Evolve: Nausea": lambda state: has_item(state, player, "Nausea"),
		"Nano Virus Evolve: Nausea": lambda state: has_item(state, player, "Nausea"),
		"Bio Weapon Evolve: Nausea": lambda state: has_item(state, player, "Nausea"),
		"Bacteria Evolve: Coughing": lambda state: has_item(state, player, "Coughing"),
		"Virus Evolve: Coughing": lambda state: has_item(state, player, "Coughing"),
		"Fungus Evolve: Coughing": lambda state: has_item(state, player, "Coughing"),
		"Parasite Evolve: Coughing": lambda state: has_item(state, player, "Coughing"),
		"Prion Evolve: Coughing": lambda state: has_item(state, player, "Coughing"),
		"Nano Virus Evolve: Coughing": lambda state: has_item(state, player, "Coughing"),
		"Bio Weapon Evolve: Coughing": lambda state: has_item(state, player, "Coughing"),
		"Bacteria Evolve: Rash": lambda state: has_item(state, player, "Rash"),
		"Virus Evolve: Rash": lambda state: has_item(state, player, "Rash"),
		"Fungus Evolve: Rash": lambda state: has_item(state, player, "Rash"),
		"Parasite Evolve: Rash": lambda state: has_item(state, player, "Rash"),
		"Prion Evolve: Rash": lambda state: has_item(state, player, "Rash"),
		"Nano Virus Evolve: Rash": lambda state: has_item(state, player, "Rash"),
		"Bio Weapon Evolve: Rash": lambda state: has_item(state, player, "Rash"),
		"Bacteria Evolve: Insomnia": lambda state: has_item(state, player, "Insomnia"),
		"Virus Evolve: Insomnia": lambda state: has_item(state, player, "Insomnia"),
		"Fungus Evolve: Insomnia": lambda state: has_item(state, player, "Insomnia"),
		"Parasite Evolve: Insomnia": lambda state: has_item(state, player, "Insomnia"),
		"Prion Evolve: Insomnia": lambda state: has_item(state, player, "Insomnia"),
		"Nano Virus Evolve: Insomnia": lambda state: has_item(state, player, "Insomnia"),
		"Bio Weapon Evolve: Insomnia": lambda state: has_item(state, player, "Insomnia"),
		"Bacteria Evolve: Cysts": lambda state: has_item(state, player, "Cysts"),
		"Virus Evolve: Cysts": lambda state: has_item(state, player, "Cysts"),
		"Fungus Evolve: Cysts": lambda state: has_item(state, player, "Cysts"),
		"Parasite Evolve: Cysts": lambda state: has_item(state, player, "Cysts"),
		"Prion Evolve: Cysts": lambda state: has_item(state, player, "Cysts"),
		"Nano Virus Evolve: Cysts": lambda state: has_item(state, player, "Cysts"),
		"Bio Weapon Evolve: Cysts": lambda state: has_item(state, player, "Cysts"),
		"Bacteria Evolve: Anaemia": lambda state: has_item(state, player, "Anaemia"),
		"Virus Evolve: Anaemia": lambda state: has_item(state, player, "Anaemia"),
		"Fungus Evolve: Anaemia": lambda state: has_item(state, player, "Anaemia"),
		"Parasite Evolve: Anaemia": lambda state: has_item(state, player, "Anaemia"),
		"Prion Evolve: Anaemia": lambda state: has_item(state, player, "Anaemia"),
		"Nano Virus Evolve: Anaemia": lambda state: has_item(state, player, "Anaemia"),
		"Bio Weapon Evolve: Anaemia": lambda state: has_item(state, player, "Anaemia"),
		"Bacteria Evolve: Vomiting": lambda state: has_item(state, player, "Vomiting") and ( has_item(state, player, "Nausea") or has_item(state, player, "Diarrhoea") or has_item(state, player, "Pulmonary Oedema") ),
		"Virus Evolve: Vomiting": lambda state: has_item(state, player, "Vomiting") and ( has_item(state, player, "Nausea") or has_item(state, player, "Diarrhoea") or has_item(state, player, "Pulmonary Oedema") ),
		"Fungus Evolve: Vomiting": lambda state: has_item(state, player, "Vomiting") and ( has_item(state, player, "Nausea") or has_item(state, player, "Diarrhoea") or has_item(state, player, "Pulmonary Oedema") ),
		"Parasite Evolve: Vomiting": lambda state: has_item(state, player, "Vomiting") and ( has_item(state, player, "Nausea") or has_item(state, player, "Diarrhoea") or has_item(state, player, "Pulmonary Oedema") ),
		"Prion Evolve: Vomiting": lambda state: has_item(state, player, "Vomiting") and ( has_item(state, player, "Nausea") or has_item(state, player, "Diarrhoea") or has_item(state, player, "Pulmonary Oedema") ),
		"Nano Virus Evolve: Vomiting": lambda state: has_item(state, player, "Vomiting") and ( has_item(state, player, "Nausea") or has_item(state, player, "Diarrhoea") or has_item(state, player, "Pulmonary Oedema") ),
		"Bio Weapon Evolve: Vomiting": lambda state: has_item(state, player, "Vomiting") and ( has_item(state, player, "Nausea") or has_item(state, player, "Diarrhoea") or has_item(state, player, "Pulmonary Oedema") ),
		"Bacteria Evolve: Pneumonia": lambda state: has_item(state, player, "Pneumonia") and ( has_item(state, player, "Pulmonary Oedema") or has_item(state, player, "Pulmonary Fibrosis") or has_item(state, player, "Coughing") ),
		"Virus Evolve: Pneumonia": lambda state: has_item(state, player, "Pneumonia") and ( has_item(state, player, "Pulmonary Oedema") or has_item(state, player, "Pulmonary Fibrosis") or has_item(state, player, "Coughing") ),
		"Fungus Evolve: Pneumonia": lambda state: has_item(state, player, "Pneumonia") and ( has_item(state, player, "Pulmonary Oedema") or has_item(state, player, "Pulmonary Fibrosis") or has_item(state, player, "Coughing") ),
		"Parasite Evolve: Pneumonia": lambda state: has_item(state, player, "Pneumonia") and ( has_item(state, player, "Pulmonary Oedema") or has_item(state, player, "Pulmonary Fibrosis") or has_item(state, player, "Coughing") ),
		"Prion Evolve: Pneumonia": lambda state: has_item(state, player, "Pneumonia") and ( has_item(state, player, "Pulmonary Oedema") or has_item(state, player, "Pulmonary Fibrosis") or has_item(state, player, "Coughing") ),
		"Nano Virus Evolve: Pneumonia": lambda state: has_item(state, player, "Pneumonia") and ( has_item(state, player, "Pulmonary Oedema") or has_item(state, player, "Pulmonary Fibrosis") or has_item(state, player, "Coughing") ),
		"Bio Weapon Evolve: Pneumonia": lambda state: has_item(state, player, "Pneumonia") and ( has_item(state, player, "Pulmonary Oedema") or has_item(state, player, "Pulmonary Fibrosis") or has_item(state, player, "Coughing") ),
		"Bacteria Evolve: Sneezing": lambda state: has_item(state, player, "Sneezing") and ( has_item(state, player, "Coughing") or has_item(state, player, "Immune Suppression") or has_item(state, player, "Fever") ),
		"Virus Evolve: Sneezing": lambda state: has_item(state, player, "Sneezing") and ( has_item(state, player, "Coughing") or has_item(state, player, "Immune Suppression") or has_item(state, player, "Fever") ),
		"Fungus Evolve: Sneezing": lambda state: has_item(state, player, "Sneezing") and ( has_item(state, player, "Coughing") or has_item(state, player, "Immune Suppression") or has_item(state, player, "Fever") ),
		"Parasite Evolve: Sneezing": lambda state: has_item(state, player, "Sneezing") and ( has_item(state, player, "Coughing") or has_item(state, player, "Immune Suppression") or has_item(state, player, "Fever") ),
		"Prion Evolve: Sneezing": lambda state: has_item(state, player, "Sneezing") and ( has_item(state, player, "Coughing") or has_item(state, player, "Immune Suppression") or has_item(state, player, "Fever") ),
		"Nano Virus Evolve: Sneezing": lambda state: has_item(state, player, "Sneezing") and ( has_item(state, player, "Coughing") or has_item(state, player, "Immune Suppression") or has_item(state, player, "Fever") ),
		"Bio Weapon Evolve: Sneezing": lambda state: has_item(state, player, "Sneezing") and ( has_item(state, player, "Coughing") or has_item(state, player, "Immune Suppression") or has_item(state, player, "Fever") ),
		"Bacteria Evolve: Sweating": lambda state: has_item(state, player, "Sweating") and ( has_item(state, player, "Fever") or has_item(state, player, "Skin Lesions") or has_item(state, player, "Rash") ),
		"Virus Evolve: Sweating": lambda state: has_item(state, player, "Sweating") and ( has_item(state, player, "Fever") or has_item(state, player, "Skin Lesions") or has_item(state, player, "Rash") ),
		"Fungus Evolve: Sweating": lambda state: has_item(state, player, "Sweating") and ( has_item(state, player, "Fever") or has_item(state, player, "Skin Lesions") or has_item(state, player, "Rash") ),
		"Parasite Evolve: Sweating": lambda state: has_item(state, player, "Sweating") and ( has_item(state, player, "Fever") or has_item(state, player, "Skin Lesions") or has_item(state, player, "Rash") ),
		"Prion Evolve: Sweating": lambda state: has_item(state, player, "Sweating") and ( has_item(state, player, "Fever") or has_item(state, player, "Skin Lesions") or has_item(state, player, "Rash") ),
		"Nano Virus Evolve: Sweating": lambda state: has_item(state, player, "Sweating") and ( has_item(state, player, "Fever") or has_item(state, player, "Skin Lesions") or has_item(state, player, "Rash") ),
		"Bio Weapon Evolve: Sweating": lambda state: has_item(state, player, "Sweating") and ( has_item(state, player, "Fever") or has_item(state, player, "Skin Lesions") or has_item(state, player, "Rash") ),
		"Bacteria Evolve: Paranoia": lambda state: has_item(state, player, "Paranoia") and ( has_item(state, player, "Insomnia") or has_item(state, player, "Seizures") or has_item(state, player, "Inflammation") ),
		"Virus Evolve: Paranoia": lambda state: has_item(state, player, "Paranoia") and ( has_item(state, player, "Insomnia") or has_item(state, player, "Seizures") or has_item(state, player, "Inflammation") ),
		"Fungus Evolve: Paranoia": lambda state: has_item(state, player, "Paranoia") and ( has_item(state, player, "Insomnia") or has_item(state, player, "Seizures") or has_item(state, player, "Inflammation") ),
		"Parasite Evolve: Paranoia": lambda state: has_item(state, player, "Paranoia") and ( has_item(state, player, "Insomnia") or has_item(state, player, "Seizures") or has_item(state, player, "Inflammation") ),
		"Prion Evolve: Paranoia": lambda state: has_item(state, player, "Paranoia") and ( has_item(state, player, "Insomnia") or has_item(state, player, "Seizures") or has_item(state, player, "Inflammation") ),
		"Nano Virus Evolve: Paranoia": lambda state: has_item(state, player, "Paranoia") and ( has_item(state, player, "Insomnia") or has_item(state, player, "Seizures") or has_item(state, player, "Inflammation") ),
		"Bio Weapon Evolve: Paranoia": lambda state: has_item(state, player, "Paranoia") and ( has_item(state, player, "Insomnia") or has_item(state, player, "Seizures") or has_item(state, player, "Inflammation") ),
		"Bacteria Evolve: Hyper sensitivity": lambda state: has_item(state, player, "Hyper sensitivity") and ( has_item(state, player, "Inflammation") or has_item(state, player, "Paralysis") or has_item(state, player, "Cysts") ),
		"Virus Evolve: Hyper sensitivity": lambda state: has_item(state, player, "Hyper sensitivity") and ( has_item(state, player, "Inflammation") or has_item(state, player, "Paralysis") or has_item(state, player, "Cysts") ),
		"Fungus Evolve: Hyper sensitivity": lambda state: has_item(state, player, "Hyper sensitivity") and ( has_item(state, player, "Inflammation") or has_item(state, player, "Paralysis") or has_item(state, player, "Cysts") ),
		"Parasite Evolve: Hyper sensitivity": lambda state: has_item(state, player, "Hyper sensitivity") and ( has_item(state, player, "Inflammation") or has_item(state, player, "Paralysis") or has_item(state, player, "Cysts") ),
		"Prion Evolve: Hyper sensitivity": lambda state: has_item(state, player, "Hyper sensitivity") and ( has_item(state, player, "Inflammation") or has_item(state, player, "Paralysis") or has_item(state, player, "Cysts") ),
		"Nano Virus Evolve: Hyper sensitivity": lambda state: has_item(state, player, "Hyper sensitivity") and ( has_item(state, player, "Inflammation") or has_item(state, player, "Paralysis") or has_item(state, player, "Cysts") ),
		"Bio Weapon Evolve: Hyper sensitivity": lambda state: has_item(state, player, "Hyper sensitivity") and ( has_item(state, player, "Inflammation") or has_item(state, player, "Paralysis") or has_item(state, player, "Cysts") ),
		"Bacteria Evolve: Abscesses": lambda state: has_item(state, player, "Abscesses") and ( has_item(state, player, "Cysts") or has_item(state, player, "Systemic Infection") or has_item(state, player, "Tumours") ),
		"Virus Evolve: Abscesses": lambda state: has_item(state, player, "Abscesses") and ( has_item(state, player, "Cysts") or has_item(state, player, "Systemic Infection") or has_item(state, player, "Tumours") ),
		"Fungus Evolve: Abscesses": lambda state: has_item(state, player, "Abscesses") and ( has_item(state, player, "Cysts") or has_item(state, player, "Systemic Infection") or has_item(state, player, "Tumours") ),
		"Parasite Evolve: Abscesses": lambda state: has_item(state, player, "Abscesses") and ( has_item(state, player, "Cysts") or has_item(state, player, "Systemic Infection") or has_item(state, player, "Tumours") ),
		"Prion Evolve: Abscesses": lambda state: has_item(state, player, "Abscesses") and ( has_item(state, player, "Cysts") or has_item(state, player, "Systemic Infection") or has_item(state, player, "Tumours") ),
		"Nano Virus Evolve: Abscesses": lambda state: has_item(state, player, "Abscesses") and ( has_item(state, player, "Cysts") or has_item(state, player, "Systemic Infection") or has_item(state, player, "Tumours") ),
		"Bio Weapon Evolve: Abscesses": lambda state: has_item(state, player, "Abscesses") and ( has_item(state, player, "Cysts") or has_item(state, player, "Systemic Infection") or has_item(state, player, "Tumours") ),
		"Bacteria Evolve: Haemophilia": lambda state: has_item(state, player, "Haemophilia") and ( has_item(state, player, "Tumours") or has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Anaemia") ),
		"Virus Evolve: Haemophilia": lambda state: has_item(state, player, "Haemophilia") and ( has_item(state, player, "Tumours") or has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Anaemia") ),
		"Fungus Evolve: Haemophilia": lambda state: has_item(state, player, "Haemophilia") and ( has_item(state, player, "Tumours") or has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Anaemia") ),
		"Parasite Evolve: Haemophilia": lambda state: has_item(state, player, "Haemophilia") and ( has_item(state, player, "Tumours") or has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Anaemia") ),
		"Prion Evolve: Haemophilia": lambda state: has_item(state, player, "Haemophilia") and ( has_item(state, player, "Tumours") or has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Anaemia") ),
		"Nano Virus Evolve: Haemophilia": lambda state: has_item(state, player, "Haemophilia") and ( has_item(state, player, "Tumours") or has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Anaemia") ),
		"Bio Weapon Evolve: Haemophilia": lambda state: has_item(state, player, "Haemophilia") and ( has_item(state, player, "Tumours") or has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Anaemia") ),
		"Bacteria Evolve: Pulmonary Oedema": lambda state: has_item(state, player, "Pulmonary Oedema") and ( has_item(state, player, "Vomiting") or has_item(state, player, "Diarrhoea") or has_item(state, player, "Pneumonia") or has_item(state, player, "Pulmonary Fibrosis") ),
		"Virus Evolve: Pulmonary Oedema": lambda state: has_item(state, player, "Pulmonary Oedema") and ( has_item(state, player, "Vomiting") or has_item(state, player, "Diarrhoea") or has_item(state, player, "Pneumonia") or has_item(state, player, "Pulmonary Fibrosis") ),
		"Fungus Evolve: Pulmonary Oedema": lambda state: has_item(state, player, "Pulmonary Oedema") and ( has_item(state, player, "Vomiting") or has_item(state, player, "Diarrhoea") or has_item(state, player, "Pneumonia") or has_item(state, player, "Pulmonary Fibrosis") ),
		"Parasite Evolve: Pulmonary Oedema": lambda state: has_item(state, player, "Pulmonary Oedema") and ( has_item(state, player, "Vomiting") or has_item(state, player, "Diarrhoea") or has_item(state, player, "Pneumonia") or has_item(state, player, "Pulmonary Fibrosis") ),
		"Prion Evolve: Pulmonary Oedema": lambda state: has_item(state, player, "Pulmonary Oedema") and ( has_item(state, player, "Vomiting") or has_item(state, player, "Diarrhoea") or has_item(state, player, "Pneumonia") or has_item(state, player, "Pulmonary Fibrosis") ),
		"Nano Virus Evolve: Pulmonary Oedema": lambda state: has_item(state, player, "Pulmonary Oedema") and ( has_item(state, player, "Vomiting") or has_item(state, player, "Diarrhoea") or has_item(state, player, "Pneumonia") or has_item(state, player, "Pulmonary Fibrosis") ),
		"Bio Weapon Evolve: Pulmonary Oedema": lambda state: has_item(state, player, "Pulmonary Oedema") and ( has_item(state, player, "Vomiting") or has_item(state, player, "Diarrhoea") or has_item(state, player, "Pneumonia") or has_item(state, player, "Pulmonary Fibrosis") ),
		"Bacteria Evolve: Fever": lambda state: has_item(state, player, "Fever") and ( has_item(state, player, "Sneezing") or has_item(state, player, "Immune Suppression") or has_item(state, player, "Sweating") or has_item(state, player, "Skin Lesions") ),
		"Virus Evolve: Fever": lambda state: has_item(state, player, "Fever") and ( has_item(state, player, "Sneezing") or has_item(state, player, "Immune Suppression") or has_item(state, player, "Sweating") or has_item(state, player, "Skin Lesions") ),
		"Fungus Evolve: Fever": lambda state: has_item(state, player, "Fever") and ( has_item(state, player, "Sneezing") or has_item(state, player, "Immune Suppression") or has_item(state, player, "Sweating") or has_item(state, player, "Skin Lesions") ),
		"Parasite Evolve: Fever": lambda state: has_item(state, player, "Fever") and ( has_item(state, player, "Sneezing") or has_item(state, player, "Immune Suppression") or has_item(state, player, "Sweating") or has_item(state, player, "Skin Lesions") ),
		"Prion Evolve: Fever": lambda state: has_item(state, player, "Fever") and ( has_item(state, player, "Sneezing") or has_item(state, player, "Immune Suppression") or has_item(state, player, "Sweating") or has_item(state, player, "Skin Lesions") ),
		"Nano Virus Evolve: Fever": lambda state: has_item(state, player, "Fever") and ( has_item(state, player, "Sneezing") or has_item(state, player, "Immune Suppression") or has_item(state, player, "Sweating") or has_item(state, player, "Skin Lesions") ),
		"Bio Weapon Evolve: Fever": lambda state: has_item(state, player, "Fever") and ( has_item(state, player, "Sneezing") or has_item(state, player, "Immune Suppression") or has_item(state, player, "Sweating") or has_item(state, player, "Skin Lesions") ),
		"Bacteria Evolve: Inflammation": lambda state: has_item(state, player, "Inflammation") and ( has_item(state, player, "Seizures") or has_item(state, player, "Paranoia") or has_item(state, player, "Paralysis") or has_item(state, player, "Hyper sensitivity") ),
		"Virus Evolve: Inflammation": lambda state: has_item(state, player, "Inflammation") and ( has_item(state, player, "Seizures") or has_item(state, player, "Paranoia") or has_item(state, player, "Paralysis") or has_item(state, player, "Hyper sensitivity") ),
		"Fungus Evolve: Inflammation": lambda state: has_item(state, player, "Inflammation") and ( has_item(state, player, "Seizures") or has_item(state, player, "Paranoia") or has_item(state, player, "Paralysis") or has_item(state, player, "Hyper sensitivity") ),
		"Parasite Evolve: Inflammation": lambda state: has_item(state, player, "Inflammation") and ( has_item(state, player, "Seizures") or has_item(state, player, "Paranoia") or has_item(state, player, "Paralysis") or has_item(state, player, "Hyper sensitivity") ),
		"Prion Evolve: Inflammation": lambda state: has_item(state, player, "Inflammation") and ( has_item(state, player, "Seizures") or has_item(state, player, "Paranoia") or has_item(state, player, "Paralysis") or has_item(state, player, "Hyper sensitivity") ),
		"Nano Virus Evolve: Inflammation": lambda state: has_item(state, player, "Inflammation") and ( has_item(state, player, "Seizures") or has_item(state, player, "Paranoia") or has_item(state, player, "Paralysis") or has_item(state, player, "Hyper sensitivity") ),
		"Bio Weapon Evolve: Inflammation": lambda state: has_item(state, player, "Inflammation") and ( has_item(state, player, "Seizures") or has_item(state, player, "Paranoia") or has_item(state, player, "Paralysis") or has_item(state, player, "Hyper sensitivity") ),
		"Bacteria Evolve: Tumours": lambda state: has_item(state, player, "Tumours") and ( has_item(state, player, "Systemic Infection") or has_item(state, player, "Abscesses") or has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Haemophilia") ),
		"Virus Evolve: Tumours": lambda state: has_item(state, player, "Tumours") and ( has_item(state, player, "Systemic Infection") or has_item(state, player, "Abscesses") or has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Haemophilia") ),
		"Fungus Evolve: Tumours": lambda state: has_item(state, player, "Tumours") and ( has_item(state, player, "Systemic Infection") or has_item(state, player, "Abscesses") or has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Haemophilia") ),
		"Parasite Evolve: Tumours": lambda state: has_item(state, player, "Tumours") and ( has_item(state, player, "Systemic Infection") or has_item(state, player, "Abscesses") or has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Haemophilia") ),
		"Prion Evolve: Tumours": lambda state: has_item(state, player, "Tumours") and ( has_item(state, player, "Systemic Infection") or has_item(state, player, "Abscesses") or has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Haemophilia") ),
		"Nano Virus Evolve: Tumours": lambda state: has_item(state, player, "Tumours") and ( has_item(state, player, "Systemic Infection") or has_item(state, player, "Abscesses") or has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Haemophilia") ),
		"Bio Weapon Evolve: Tumours": lambda state: has_item(state, player, "Tumours") and ( has_item(state, player, "Systemic Infection") or has_item(state, player, "Abscesses") or has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Haemophilia") ),
		"Bacteria Evolve: Diarrhoea": lambda state: has_item(state, player, "Diarrhoea") and ( has_item(state, player, "Dysentery") or has_item(state, player, "Vomiting") or has_item(state, player, "Pulmonary Oedema") ),
		"Virus Evolve: Diarrhoea": lambda state: has_item(state, player, "Diarrhoea") and ( has_item(state, player, "Dysentery") or has_item(state, player, "Vomiting") or has_item(state, player, "Pulmonary Oedema") ),
		"Fungus Evolve: Diarrhoea": lambda state: has_item(state, player, "Diarrhoea") and ( has_item(state, player, "Dysentery") or has_item(state, player, "Vomiting") or has_item(state, player, "Pulmonary Oedema") ),
		"Parasite Evolve: Diarrhoea": lambda state: has_item(state, player, "Diarrhoea") and ( has_item(state, player, "Dysentery") or has_item(state, player, "Vomiting") or has_item(state, player, "Pulmonary Oedema") ),
		"Prion Evolve: Diarrhoea": lambda state: has_item(state, player, "Diarrhoea") and ( has_item(state, player, "Dysentery") or has_item(state, player, "Vomiting") or has_item(state, player, "Pulmonary Oedema") ),
		"Nano Virus Evolve: Diarrhoea": lambda state: has_item(state, player, "Diarrhoea") and ( has_item(state, player, "Dysentery") or has_item(state, player, "Vomiting") or has_item(state, player, "Pulmonary Oedema") ),
		"Bio Weapon Evolve: Diarrhoea": lambda state: has_item(state, player, "Diarrhoea") and ( has_item(state, player, "Dysentery") or has_item(state, player, "Vomiting") or has_item(state, player, "Pulmonary Oedema") ),
		"Bacteria Evolve: Pulmonary Fibrosis": lambda state: has_item(state, player, "Pulmonary Fibrosis") and ( has_item(state, player, "Pulmonary Oedema") or has_item(state, player, "Pneumonia") or has_item(state, player, "Total Organ Failure") ),
		"Virus Evolve: Pulmonary Fibrosis": lambda state: has_item(state, player, "Pulmonary Fibrosis") and ( has_item(state, player, "Pulmonary Oedema") or has_item(state, player, "Pneumonia") or has_item(state, player, "Total Organ Failure") ),
		"Fungus Evolve: Pulmonary Fibrosis": lambda state: has_item(state, player, "Pulmonary Fibrosis") and ( has_item(state, player, "Pulmonary Oedema") or has_item(state, player, "Pneumonia") or has_item(state, player, "Total Organ Failure") ),
		"Parasite Evolve: Pulmonary Fibrosis": lambda state: has_item(state, player, "Pulmonary Fibrosis") and ( has_item(state, player, "Pulmonary Oedema") or has_item(state, player, "Pneumonia") or has_item(state, player, "Total Organ Failure") ),
		"Prion Evolve: Pulmonary Fibrosis": lambda state: has_item(state, player, "Pulmonary Fibrosis") and ( has_item(state, player, "Pulmonary Oedema") or has_item(state, player, "Pneumonia") or has_item(state, player, "Total Organ Failure") ),
		"Nano Virus Evolve: Pulmonary Fibrosis": lambda state: has_item(state, player, "Pulmonary Fibrosis") and ( has_item(state, player, "Pulmonary Oedema") or has_item(state, player, "Pneumonia") or has_item(state, player, "Total Organ Failure") ),
		"Bio Weapon Evolve: Pulmonary Fibrosis": lambda state: has_item(state, player, "Pulmonary Fibrosis") and ( has_item(state, player, "Pulmonary Oedema") or has_item(state, player, "Pneumonia") or has_item(state, player, "Total Organ Failure") ),
		"Bacteria Evolve: Immune Suppression": lambda state: has_item(state, player, "Immune Suppression") and ( has_item(state, player, "Total Organ Failure") or has_item(state, player, "Sneezing") or has_item(state, player, "Fever") ),
		"Virus Evolve: Immune Suppression": lambda state: has_item(state, player, "Immune Suppression") and ( has_item(state, player, "Total Organ Failure") or has_item(state, player, "Sneezing") or has_item(state, player, "Fever") ),
		"Fungus Evolve: Immune Suppression": lambda state: has_item(state, player, "Immune Suppression") and ( has_item(state, player, "Total Organ Failure") or has_item(state, player, "Sneezing") or has_item(state, player, "Fever") ),
		"Parasite Evolve: Immune Suppression": lambda state: has_item(state, player, "Immune Suppression") and ( has_item(state, player, "Total Organ Failure") or has_item(state, player, "Sneezing") or has_item(state, player, "Fever") ),
		"Prion Evolve: Immune Suppression": lambda state: has_item(state, player, "Immune Suppression") and ( has_item(state, player, "Total Organ Failure") or has_item(state, player, "Sneezing") or has_item(state, player, "Fever") ),
		"Nano Virus Evolve: Immune Suppression": lambda state: has_item(state, player, "Immune Suppression") and ( has_item(state, player, "Total Organ Failure") or has_item(state, player, "Sneezing") or has_item(state, player, "Fever") ),
		"Bio Weapon Evolve: Immune Suppression": lambda state: has_item(state, player, "Immune Suppression") and ( has_item(state, player, "Total Organ Failure") or has_item(state, player, "Sneezing") or has_item(state, player, "Fever") ),
		"Bacteria Evolve: Skin Lesions": lambda state: has_item(state, player, "Skin Lesions") and ( has_item(state, player, "Fever") or has_item(state, player, "Sweating") or has_item(state, player, "Necrosis") ),
		"Virus Evolve: Skin Lesions": lambda state: has_item(state, player, "Skin Lesions") and ( has_item(state, player, "Fever") or has_item(state, player, "Sweating") or has_item(state, player, "Necrosis") ),
		"Fungus Evolve: Skin Lesions": lambda state: has_item(state, player, "Skin Lesions") and ( has_item(state, player, "Fever") or has_item(state, player, "Sweating") or has_item(state, player, "Necrosis") ),
		"Parasite Evolve: Skin Lesions": lambda state: has_item(state, player, "Skin Lesions") and ( has_item(state, player, "Fever") or has_item(state, player, "Sweating") or has_item(state, player, "Necrosis") ),
		"Prion Evolve: Skin Lesions": lambda state: has_item(state, player, "Skin Lesions") and ( has_item(state, player, "Fever") or has_item(state, player, "Sweating") or has_item(state, player, "Necrosis") ),
		"Nano Virus Evolve: Skin Lesions": lambda state: has_item(state, player, "Skin Lesions") and ( has_item(state, player, "Fever") or has_item(state, player, "Sweating") or has_item(state, player, "Necrosis") ),
		"Bio Weapon Evolve: Skin Lesions": lambda state: has_item(state, player, "Skin Lesions") and ( has_item(state, player, "Fever") or has_item(state, player, "Sweating") or has_item(state, player, "Necrosis") ),
		"Bacteria Evolve: Seizures": lambda state: has_item(state, player, "Seizures") and ( has_item(state, player, "Insanity") or has_item(state, player, "Paranoia") or has_item(state, player, "Inflammation") ),
		"Virus Evolve: Seizures": lambda state: has_item(state, player, "Seizures") and ( has_item(state, player, "Insanity") or has_item(state, player, "Paranoia") or has_item(state, player, "Inflammation") ),
		"Fungus Evolve: Seizures": lambda state: has_item(state, player, "Seizures") and ( has_item(state, player, "Insanity") or has_item(state, player, "Paranoia") or has_item(state, player, "Inflammation") ),
		"Parasite Evolve: Seizures": lambda state: has_item(state, player, "Seizures") and ( has_item(state, player, "Insanity") or has_item(state, player, "Paranoia") or has_item(state, player, "Inflammation") ),
		"Prion Evolve: Seizures": lambda state: has_item(state, player, "Seizures") and ( has_item(state, player, "Insanity") or has_item(state, player, "Paranoia") or has_item(state, player, "Inflammation") ),
		"Nano Virus Evolve: Seizures": lambda state: has_item(state, player, "Seizures") and ( has_item(state, player, "Insanity") or has_item(state, player, "Paranoia") or has_item(state, player, "Inflammation") ),
		"Bio Weapon Evolve: Seizures": lambda state: has_item(state, player, "Seizures") and ( has_item(state, player, "Insanity") or has_item(state, player, "Paranoia") or has_item(state, player, "Inflammation") ),
		"Bacteria Evolve: Paralysis": lambda state: has_item(state, player, "Paralysis") and ( has_item(state, player, "Inflammation") or has_item(state, player, "Hyper sensitivity") or has_item(state, player, "Coma") ),
		"Virus Evolve: Paralysis": lambda state: has_item(state, player, "Paralysis") and ( has_item(state, player, "Inflammation") or has_item(state, player, "Hyper sensitivity") or has_item(state, player, "Coma") ),
		"Fungus Evolve: Paralysis": lambda state: has_item(state, player, "Paralysis") and ( has_item(state, player, "Inflammation") or has_item(state, player, "Hyper sensitivity") or has_item(state, player, "Coma") ),
		"Parasite Evolve: Paralysis": lambda state: has_item(state, player, "Paralysis") and ( has_item(state, player, "Inflammation") or has_item(state, player, "Hyper sensitivity") or has_item(state, player, "Coma") ),
		"Prion Evolve: Paralysis": lambda state: has_item(state, player, "Paralysis") and ( has_item(state, player, "Inflammation") or has_item(state, player, "Hyper sensitivity") or has_item(state, player, "Coma") ),
		"Nano Virus Evolve: Paralysis": lambda state: has_item(state, player, "Paralysis") and ( has_item(state, player, "Inflammation") or has_item(state, player, "Hyper sensitivity") or has_item(state, player, "Coma") ),
		"Bio Weapon Evolve: Paralysis": lambda state: has_item(state, player, "Paralysis") and ( has_item(state, player, "Inflammation") or has_item(state, player, "Hyper sensitivity") or has_item(state, player, "Coma") ),
		"Bacteria Evolve: Systemic Infection": lambda state: has_item(state, player, "Systemic Infection") and ( has_item(state, player, "Coma") or has_item(state, player, "Abscesses") or has_item(state, player, "Tumours") ),
		"Virus Evolve: Systemic Infection": lambda state: has_item(state, player, "Systemic Infection") and ( has_item(state, player, "Coma") or has_item(state, player, "Abscesses") or has_item(state, player, "Tumours") ),
		"Fungus Evolve: Systemic Infection": lambda state: has_item(state, player, "Systemic Infection") and ( has_item(state, player, "Coma") or has_item(state, player, "Abscesses") or has_item(state, player, "Tumours") ),
		"Parasite Evolve: Systemic Infection": lambda state: has_item(state, player, "Systemic Infection") and ( has_item(state, player, "Coma") or has_item(state, player, "Abscesses") or has_item(state, player, "Tumours") ),
		"Prion Evolve: Systemic Infection": lambda state: has_item(state, player, "Systemic Infection") and ( has_item(state, player, "Coma") or has_item(state, player, "Abscesses") or has_item(state, player, "Tumours") ),
		"Nano Virus Evolve: Systemic Infection": lambda state: has_item(state, player, "Systemic Infection") and ( has_item(state, player, "Coma") or has_item(state, player, "Abscesses") or has_item(state, player, "Tumours") ),
		"Bio Weapon Evolve: Systemic Infection": lambda state: has_item(state, player, "Systemic Infection") and ( has_item(state, player, "Coma") or has_item(state, player, "Abscesses") or has_item(state, player, "Tumours") ),
		"Bacteria Evolve: Internal Haemorrhaging": lambda state: has_item(state, player, "Internal Haemorrhaging") and ( has_item(state, player, "Tumours") or has_item(state, player, "Haemophilia") or has_item(state, player, "Hemorrhagic Shock") ),
		"Virus Evolve: Internal Haemorrhaging": lambda state: has_item(state, player, "Internal Haemorrhaging") and ( has_item(state, player, "Tumours") or has_item(state, player, "Haemophilia") or has_item(state, player, "Hemorrhagic Shock") ),
		"Fungus Evolve: Internal Haemorrhaging": lambda state: has_item(state, player, "Internal Haemorrhaging") and ( has_item(state, player, "Tumours") or has_item(state, player, "Haemophilia") or has_item(state, player, "Hemorrhagic Shock") ),
		"Parasite Evolve: Internal Haemorrhaging": lambda state: has_item(state, player, "Internal Haemorrhaging") and ( has_item(state, player, "Tumours") or has_item(state, player, "Haemophilia") or has_item(state, player, "Hemorrhagic Shock") ),
		"Prion Evolve: Internal Haemorrhaging": lambda state: has_item(state, player, "Internal Haemorrhaging") and ( has_item(state, player, "Tumours") or has_item(state, player, "Haemophilia") or has_item(state, player, "Hemorrhagic Shock") ),
		"Nano Virus Evolve: Internal Haemorrhaging": lambda state: has_item(state, player, "Internal Haemorrhaging") and ( has_item(state, player, "Tumours") or has_item(state, player, "Haemophilia") or has_item(state, player, "Hemorrhagic Shock") ),
		"Bio Weapon Evolve: Internal Haemorrhaging": lambda state: has_item(state, player, "Internal Haemorrhaging") and ( has_item(state, player, "Tumours") or has_item(state, player, "Haemophilia") or has_item(state, player, "Hemorrhagic Shock") ),
		"Bacteria Evolve: Dysentery": lambda state: has_item(state, player, "Dysentery") and ( has_item(state, player, "Insanity") or has_item(state, player, "Diarrhoea") ),
		"Virus Evolve: Dysentery": lambda state: has_item(state, player, "Dysentery") and ( has_item(state, player, "Insanity") or has_item(state, player, "Diarrhoea") ),
		"Fungus Evolve: Dysentery": lambda state: has_item(state, player, "Dysentery") and ( has_item(state, player, "Insanity") or has_item(state, player, "Diarrhoea") ),
		"Parasite Evolve: Dysentery": lambda state: has_item(state, player, "Dysentery") and ( has_item(state, player, "Insanity") or has_item(state, player, "Diarrhoea") ),
		"Prion Evolve: Dysentery": lambda state: has_item(state, player, "Dysentery") and ( has_item(state, player, "Insanity") or has_item(state, player, "Diarrhoea") ),
		"Nano Virus Evolve: Dysentery": lambda state: has_item(state, player, "Dysentery") and ( has_item(state, player, "Insanity") or has_item(state, player, "Diarrhoea") ),
		"Bio Weapon Evolve: Dysentery": lambda state: has_item(state, player, "Dysentery") and ( has_item(state, player, "Insanity") or has_item(state, player, "Diarrhoea") ),
		"Bacteria Evolve: Insanity": lambda state: has_item(state, player, "Insanity") and ( has_item(state, player, "Dysentery") or has_item(state, player, "Seizures") ),
		"Virus Evolve: Insanity": lambda state: has_item(state, player, "Insanity") and ( has_item(state, player, "Dysentery") or has_item(state, player, "Seizures") ),
		"Fungus Evolve: Insanity": lambda state: has_item(state, player, "Insanity") and ( has_item(state, player, "Dysentery") or has_item(state, player, "Seizures") ),
		"Parasite Evolve: Insanity": lambda state: has_item(state, player, "Insanity") and ( has_item(state, player, "Dysentery") or has_item(state, player, "Seizures") ),
		"Prion Evolve: Insanity": lambda state: has_item(state, player, "Insanity") and ( has_item(state, player, "Dysentery") or has_item(state, player, "Seizures") ),
		"Nano Virus Evolve: Insanity": lambda state: has_item(state, player, "Insanity") and ( has_item(state, player, "Dysentery") or has_item(state, player, "Seizures") ),
		"Bio Weapon Evolve: Insanity": lambda state: has_item(state, player, "Insanity") and ( has_item(state, player, "Dysentery") or has_item(state, player, "Seizures") ),
		"Bacteria Evolve: Necrosis": lambda state: has_item(state, player, "Necrosis") and ( has_item(state, player, "Skin Lesions") or has_item(state, player, "Hemorrhagic Shock") ),
		"Virus Evolve: Necrosis": lambda state: has_item(state, player, "Necrosis") and ( has_item(state, player, "Skin Lesions") or has_item(state, player, "Hemorrhagic Shock") ),
		"Fungus Evolve: Necrosis": lambda state: has_item(state, player, "Necrosis") and ( has_item(state, player, "Skin Lesions") or has_item(state, player, "Hemorrhagic Shock") ),
		"Parasite Evolve: Necrosis": lambda state: has_item(state, player, "Necrosis") and ( has_item(state, player, "Skin Lesions") or has_item(state, player, "Hemorrhagic Shock") ),
		"Prion Evolve: Necrosis": lambda state: has_item(state, player, "Necrosis") and ( has_item(state, player, "Skin Lesions") or has_item(state, player, "Hemorrhagic Shock") ),
		"Nano Virus Evolve: Necrosis": lambda state: has_item(state, player, "Necrosis") and ( has_item(state, player, "Skin Lesions") or has_item(state, player, "Hemorrhagic Shock") ),
		"Bio Weapon Evolve: Necrosis": lambda state: has_item(state, player, "Necrosis") and ( has_item(state, player, "Skin Lesions") or has_item(state, player, "Hemorrhagic Shock") ),
		"Bacteria Evolve: Hemorrhagic Shock": lambda state: has_item(state, player, "Hemorrhagic Shock") and ( has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Necrosis") ),
		"Virus Evolve: Hemorrhagic Shock": lambda state: has_item(state, player, "Hemorrhagic Shock") and ( has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Necrosis") ),
		"Fungus Evolve: Hemorrhagic Shock": lambda state: has_item(state, player, "Hemorrhagic Shock") and ( has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Necrosis") ),
		"Parasite Evolve: Hemorrhagic Shock": lambda state: has_item(state, player, "Hemorrhagic Shock") and ( has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Necrosis") ),
		"Prion Evolve: Hemorrhagic Shock": lambda state: has_item(state, player, "Hemorrhagic Shock") and ( has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Necrosis") ),
		"Nano Virus Evolve: Hemorrhagic Shock": lambda state: has_item(state, player, "Hemorrhagic Shock") and ( has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Necrosis") ),
		"Bio Weapon Evolve: Hemorrhagic Shock": lambda state: has_item(state, player, "Hemorrhagic Shock") and ( has_item(state, player, "Internal Haemorrhaging") or has_item(state, player, "Necrosis") ),
		"Bacteria Evolve: Coma": lambda state: has_item(state, player, "Coma") and ( has_item(state, player, "Paralysis") or has_item(state, player, "Total Organ Failure") or has_item(state, player, "Systemic Infection") ),
		"Virus Evolve: Coma": lambda state: has_item(state, player, "Coma") and ( has_item(state, player, "Paralysis") or has_item(state, player, "Total Organ Failure") or has_item(state, player, "Systemic Infection") ),
		"Fungus Evolve: Coma": lambda state: has_item(state, player, "Coma") and ( has_item(state, player, "Paralysis") or has_item(state, player, "Total Organ Failure") or has_item(state, player, "Systemic Infection") ),
		"Parasite Evolve: Coma": lambda state: has_item(state, player, "Coma") and ( has_item(state, player, "Paralysis") or has_item(state, player, "Total Organ Failure") or has_item(state, player, "Systemic Infection") ),
		"Prion Evolve: Coma": lambda state: has_item(state, player, "Coma") and ( has_item(state, player, "Paralysis") or has_item(state, player, "Total Organ Failure") or has_item(state, player, "Systemic Infection") ),
		"Nano Virus Evolve: Coma": lambda state: has_item(state, player, "Coma") and ( has_item(state, player, "Paralysis") or has_item(state, player, "Total Organ Failure") or has_item(state, player, "Systemic Infection") ),
		"Bio Weapon Evolve: Coma": lambda state: has_item(state, player, "Coma") and ( has_item(state, player, "Paralysis") or has_item(state, player, "Total Organ Failure") or has_item(state, player, "Systemic Infection") ),
		"Bacteria Evolve: Total Organ Failure": lambda state: has_item(state, player, "Total Organ Failure") and ( has_item(state, player, "Pulmonary Fibrosis") or has_item(state, player, "Coma") or has_item(state, player, "Immune Suppression") ),
		"Virus Evolve: Total Organ Failure": lambda state: has_item(state, player, "Total Organ Failure") and ( has_item(state, player, "Pulmonary Fibrosis") or has_item(state, player, "Coma") or has_item(state, player, "Immune Suppression") ),
		"Fungus Evolve: Total Organ Failure": lambda state: has_item(state, player, "Total Organ Failure") and ( has_item(state, player, "Pulmonary Fibrosis") or has_item(state, player, "Coma") or has_item(state, player, "Immune Suppression") ),
		"Parasite Evolve: Total Organ Failure": lambda state: has_item(state, player, "Total Organ Failure") and ( has_item(state, player, "Pulmonary Fibrosis") or has_item(state, player, "Coma") or has_item(state, player, "Immune Suppression") ),
		"Prion Evolve: Total Organ Failure": lambda state: has_item(state, player, "Total Organ Failure") and ( has_item(state, player, "Pulmonary Fibrosis") or has_item(state, player, "Coma") or has_item(state, player, "Immune Suppression") ),
		"Nano Virus Evolve: Total Organ Failure": lambda state: has_item(state, player, "Total Organ Failure") and ( has_item(state, player, "Pulmonary Fibrosis") or has_item(state, player, "Coma") or has_item(state, player, "Immune Suppression") ),
		"Bio Weapon Evolve: Total Organ Failure": lambda state: has_item(state, player, "Total Organ Failure") and ( has_item(state, player, "Pulmonary Fibrosis") or has_item(state, player, "Coma") or has_item(state, player, "Immune Suppression") ),
		"Bacteria Evolve: Bird 1": lambda state: has_item(state, player, "Bird 1"),
		"Virus Evolve: Bird 1": lambda state: has_item(state, player, "Bird 1"),
		"Fungus Evolve: Bird 1": lambda state: has_item(state, player, "Bird 1"),
		"Parasite Evolve: Bird 1": lambda state: has_item(state, player, "Bird 1"),
		"Prion Evolve: Bird 1": lambda state: has_item(state, player, "Bird 1"),
		"Nano Virus Evolve: Bird 1": lambda state: has_item(state, player, "Bird 1"),
		"Bio Weapon Evolve: Bird 1": lambda state: has_item(state, player, "Bird 1"),
		"Bacteria Evolve: Bird 2": lambda state: has_item(state, player, "Bird 2") and has_item(state, player, "Bird 1"),
		"Virus Evolve: Bird 2": lambda state: has_item(state, player, "Bird 2") and has_item(state, player, "Bird 1"),
		"Fungus Evolve: Bird 2": lambda state: has_item(state, player, "Bird 2") and has_item(state, player, "Bird 1"),
		"Parasite Evolve: Bird 2": lambda state: has_item(state, player, "Bird 2") and has_item(state, player, "Bird 1"),
		"Prion Evolve: Bird 2": lambda state: has_item(state, player, "Bird 2") and has_item(state, player, "Bird 1"),
		"Nano Virus Evolve: Bird 2": lambda state: has_item(state, player, "Bird 2") and has_item(state, player, "Bird 1"),
		"Bio Weapon Evolve: Bird 2": lambda state: has_item(state, player, "Bird 2") and has_item(state, player, "Bird 1"),
		"Bacteria Evolve: Rodent 1": lambda state: has_item(state, player, "Rodent 1"),
		"Virus Evolve: Rodent 1": lambda state: has_item(state, player, "Rodent 1"),
		"Fungus Evolve: Rodent 1": lambda state: has_item(state, player, "Rodent 1"),
		"Parasite Evolve: Rodent 1": lambda state: has_item(state, player, "Rodent 1"),
		"Prion Evolve: Rodent 1": lambda state: has_item(state, player, "Rodent 1"),
		"Nano Virus Evolve: Rodent 1": lambda state: has_item(state, player, "Rodent 1"),
		"Bio Weapon Evolve: Rodent 1": lambda state: has_item(state, player, "Rodent 1"),
		"Bacteria Evolve: Rodent 2": lambda state: has_item(state, player, "Rodent 2") and has_item(state, player, "Rodent 1"),
		"Virus Evolve: Rodent 2": lambda state: has_item(state, player, "Rodent 2") and has_item(state, player, "Rodent 1"),
		"Fungus Evolve: Rodent 2": lambda state: has_item(state, player, "Rodent 2") and has_item(state, player, "Rodent 1"),
		"Parasite Evolve: Rodent 2": lambda state: has_item(state, player, "Rodent 2") and has_item(state, player, "Rodent 1"),
		"Prion Evolve: Rodent 2": lambda state: has_item(state, player, "Rodent 2") and has_item(state, player, "Rodent 1"),
		"Nano Virus Evolve: Rodent 2": lambda state: has_item(state, player, "Rodent 2") and has_item(state, player, "Rodent 1"),
		"Bio Weapon Evolve: Rodent 2": lambda state: has_item(state, player, "Rodent 2") and has_item(state, player, "Rodent 1"),
		"Bacteria Evolve: Livestock 1": lambda state: has_item(state, player, "Livestock 1"),
		"Virus Evolve: Livestock 1": lambda state: has_item(state, player, "Livestock 1"),
		"Fungus Evolve: Livestock 1": lambda state: has_item(state, player, "Livestock 1"),
		"Parasite Evolve: Livestock 1": lambda state: has_item(state, player, "Livestock 1"),
		"Prion Evolve: Livestock 1": lambda state: has_item(state, player, "Livestock 1"),
		"Nano Virus Evolve: Livestock 1": lambda state: has_item(state, player, "Livestock 1"),
		"Bio Weapon Evolve: Livestock 1": lambda state: has_item(state, player, "Livestock 1"),
		"Bacteria Evolve: Livestock 2": lambda state: has_item(state, player, "Livestock 2") and has_item(state, player, "Livestock 1"),
		"Virus Evolve: Livestock 2": lambda state: has_item(state, player, "Livestock 2") and has_item(state, player, "Livestock 1"),
		"Fungus Evolve: Livestock 2": lambda state: has_item(state, player, "Livestock 2") and has_item(state, player, "Livestock 1"),
		"Parasite Evolve: Livestock 2": lambda state: has_item(state, player, "Livestock 2") and has_item(state, player, "Livestock 1"),
		"Prion Evolve: Livestock 2": lambda state: has_item(state, player, "Livestock 2") and has_item(state, player, "Livestock 1"),
		"Nano Virus Evolve: Livestock 2": lambda state: has_item(state, player, "Livestock 2") and has_item(state, player, "Livestock 1"),
		"Bio Weapon Evolve: Livestock 2": lambda state: has_item(state, player, "Livestock 2") and has_item(state, player, "Livestock 1"),
		"Bacteria Evolve: Extreme Zoonosis": lambda state: has_item(state, player, "Extreme Zoonosis") and has_item(state, player, "Bird 2") and has_item(state, player, "Rodent 2") and has_item(state, player, "Livestock 2"),
		"Virus Evolve: Extreme Zoonosis": lambda state: has_item(state, player, "Extreme Zoonosis") and has_item(state, player, "Bird 2") and has_item(state, player, "Rodent 2") and has_item(state, player, "Livestock 2"),
		"Fungus Evolve: Extreme Zoonosis": lambda state: has_item(state, player, "Extreme Zoonosis") and has_item(state, player, "Bird 2") and has_item(state, player, "Rodent 2") and has_item(state, player, "Livestock 2"),
		"Parasite Evolve: Extreme Zoonosis": lambda state: has_item(state, player, "Extreme Zoonosis") and has_item(state, player, "Bird 2") and has_item(state, player, "Rodent 2") and has_item(state, player, "Livestock 2"),
		"Prion Evolve: Extreme Zoonosis": lambda state: has_item(state, player, "Extreme Zoonosis") and has_item(state, player, "Bird 2") and has_item(state, player, "Rodent 2") and has_item(state, player, "Livestock 2"),
		"Nano Virus Evolve: Extreme Zoonosis": lambda state: has_item(state, player, "Extreme Zoonosis") and has_item(state, player, "Bird 2") and has_item(state, player, "Rodent 2") and has_item(state, player, "Livestock 2"),
		"Bio Weapon Evolve: Extreme Zoonosis": lambda state: has_item(state, player, "Extreme Zoonosis") and has_item(state, player, "Bird 2") and has_item(state, player, "Rodent 2") and has_item(state, player, "Livestock 2"),
		"Bacteria Evolve: Air 1": lambda state: has_item(state, player, "Air 1"),
		"Virus Evolve: Air 1": lambda state: has_item(state, player, "Air 1"),
		"Fungus Evolve: Air 1": lambda state: has_item(state, player, "Air 1"),
		"Parasite Evolve: Air 1": lambda state: has_item(state, player, "Air 1"),
		"Prion Evolve: Air 1": lambda state: has_item(state, player, "Air 1"),
		"Nano Virus Evolve: Air 1": lambda state: has_item(state, player, "Air 1"),
		"Bio Weapon Evolve: Air 1": lambda state: has_item(state, player, "Air 1"),
		"Bacteria Evolve: Air 2": lambda state: has_item(state, player, "Air 2") and has_item(state, player, "Air 1"),
		"Virus Evolve: Air 2": lambda state: has_item(state, player, "Air 2") and has_item(state, player, "Air 1"),
		"Fungus Evolve: Air 2": lambda state: has_item(state, player, "Air 2") and has_item(state, player, "Air 1"),
		"Parasite Evolve: Air 2": lambda state: has_item(state, player, "Air 2") and has_item(state, player, "Air 1"),
		"Prion Evolve: Air 2": lambda state: has_item(state, player, "Air 2") and has_item(state, player, "Air 1"),
		"Nano Virus Evolve: Air 2": lambda state: has_item(state, player, "Air 2") and has_item(state, player, "Air 1"),
		"Bio Weapon Evolve: Air 2": lambda state: has_item(state, player, "Air 2") and has_item(state, player, "Air 1"),
		"Bacteria Evolve: Water 1": lambda state: has_item(state, player, "Water 1"),
		"Virus Evolve: Water 1": lambda state: has_item(state, player, "Water 1"),
		"Fungus Evolve: Water 1": lambda state: has_item(state, player, "Water 1"),
		"Parasite Evolve: Water 1": lambda state: has_item(state, player, "Water 1"),
		"Prion Evolve: Water 1": lambda state: has_item(state, player, "Water 1"),
		"Nano Virus Evolve: Water 1": lambda state: has_item(state, player, "Water 1"),
		"Bio Weapon Evolve: Water 1": lambda state: has_item(state, player, "Water 1"),
		"Bacteria Evolve: Water 2": lambda state: has_item(state, player, "Water 2") and has_item(state, player, "Water 1"),
		"Virus Evolve: Water 2": lambda state: has_item(state, player, "Water 2") and has_item(state, player, "Water 1"),
		"Fungus Evolve: Water 2": lambda state: has_item(state, player, "Water 2") and has_item(state, player, "Water 1"),
		"Parasite Evolve: Water 2": lambda state: has_item(state, player, "Water 2") and has_item(state, player, "Water 1"),
		"Prion Evolve: Water 2": lambda state: has_item(state, player, "Water 2") and has_item(state, player, "Water 1"),
		"Nano Virus Evolve: Water 2": lambda state: has_item(state, player, "Water 2") and has_item(state, player, "Water 1"),
		"Bio Weapon Evolve: Water 2": lambda state: has_item(state, player, "Water 2") and has_item(state, player, "Water 1"),
		"Bacteria Evolve: Extreme Bioaerosol": lambda state: has_item(state, player, "Extreme Bioaerosol") and has_item(state, player, "Air 2") and has_item(state, player, "Water 2"),
		"Virus Evolve: Extreme Bioaerosol": lambda state: has_item(state, player, "Extreme Bioaerosol") and has_item(state, player, "Air 2") and has_item(state, player, "Water 2"),
		"Fungus Evolve: Extreme Bioaerosol": lambda state: has_item(state, player, "Extreme Bioaerosol") and has_item(state, player, "Air 2") and has_item(state, player, "Water 2"),
		"Parasite Evolve: Extreme Bioaerosol": lambda state: has_item(state, player, "Extreme Bioaerosol") and has_item(state, player, "Air 2") and has_item(state, player, "Water 2"),
		"Prion Evolve: Extreme Bioaerosol": lambda state: has_item(state, player, "Extreme Bioaerosol") and has_item(state, player, "Air 2") and has_item(state, player, "Water 2"),
		"Nano Virus Evolve: Extreme Bioaerosol": lambda state: has_item(state, player, "Extreme Bioaerosol") and has_item(state, player, "Air 2") and has_item(state, player, "Water 2"),
		"Bio Weapon Evolve: Extreme Bioaerosol": lambda state: has_item(state, player, "Extreme Bioaerosol") and has_item(state, player, "Air 2") and has_item(state, player, "Water 2"),
		"Bacteria Evolve: Insect 1": lambda state: has_item(state, player, "Insect 1"),
		"Virus Evolve: Insect 1": lambda state: has_item(state, player, "Insect 1"),
		"Fungus Evolve: Insect 1": lambda state: has_item(state, player, "Insect 1"),
		"Parasite Evolve: Insect 1": lambda state: has_item(state, player, "Insect 1"),
		"Prion Evolve: Insect 1": lambda state: has_item(state, player, "Insect 1"),
		"Nano Virus Evolve: Insect 1": lambda state: has_item(state, player, "Insect 1"),
		"Bio Weapon Evolve: Insect 1": lambda state: has_item(state, player, "Insect 1"),
		"Bacteria Evolve: Insect 2": lambda state: has_item(state, player, "Insect 2") and has_item(state, player, "Insect 1"),
		"Virus Evolve: Insect 2": lambda state: has_item(state, player, "Insect 2") and has_item(state, player, "Insect 1"),
		"Fungus Evolve: Insect 2": lambda state: has_item(state, player, "Insect 2") and has_item(state, player, "Insect 1"),
		"Parasite Evolve: Insect 2": lambda state: has_item(state, player, "Insect 2") and has_item(state, player, "Insect 1"),
		"Prion Evolve: Insect 2": lambda state: has_item(state, player, "Insect 2") and has_item(state, player, "Insect 1"),
		"Nano Virus Evolve: Insect 2": lambda state: has_item(state, player, "Insect 2") and has_item(state, player, "Insect 1"),
		"Bio Weapon Evolve: Insect 2": lambda state: has_item(state, player, "Insect 2") and has_item(state, player, "Insect 1"),
		"Bacteria Evolve: Blood 1": lambda state: has_item(state, player, "Blood 1"),
		"Virus Evolve: Blood 1": lambda state: has_item(state, player, "Blood 1"),
		"Fungus Evolve: Blood 1": lambda state: has_item(state, player, "Blood 1"),
		"Parasite Evolve: Blood 1": lambda state: has_item(state, player, "Blood 1"),
		"Prion Evolve: Blood 1": lambda state: has_item(state, player, "Blood 1"),
		"Nano Virus Evolve: Blood 1": lambda state: has_item(state, player, "Blood 1"),
		"Bio Weapon Evolve: Blood 1": lambda state: has_item(state, player, "Blood 1"),
		"Bacteria Evolve: Blood 2": lambda state: has_item(state, player, "Blood 2") and has_item(state, player, "Blood 1"),
		"Virus Evolve: Blood 2": lambda state: has_item(state, player, "Blood 2") and has_item(state, player, "Blood 1"),
		"Fungus Evolve: Blood 2": lambda state: has_item(state, player, "Blood 2") and has_item(state, player, "Blood 1"),
		"Parasite Evolve: Blood 2": lambda state: has_item(state, player, "Blood 2") and has_item(state, player, "Blood 1"),
		"Prion Evolve: Blood 2": lambda state: has_item(state, player, "Blood 2") and has_item(state, player, "Blood 1"),
		"Nano Virus Evolve: Blood 2": lambda state: has_item(state, player, "Blood 2") and has_item(state, player, "Blood 1"),
		"Bio Weapon Evolve: Blood 2": lambda state: has_item(state, player, "Blood 2") and has_item(state, player, "Blood 1"),
		"Bacteria Evolve: Extreme Hematophagy": lambda state: has_item(state, player, "Extreme Hematophagy") and has_item(state, player, "Insect 2") and has_item(state, player, "Blood 2"),
		"Virus Evolve: Extreme Hematophagy": lambda state: has_item(state, player, "Extreme Hematophagy") and has_item(state, player, "Insect 2") and has_item(state, player, "Blood 2"),
		"Fungus Evolve: Extreme Hematophagy": lambda state: has_item(state, player, "Extreme Hematophagy") and has_item(state, player, "Insect 2") and has_item(state, player, "Blood 2"),
		"Parasite Evolve: Extreme Hematophagy": lambda state: has_item(state, player, "Extreme Hematophagy") and has_item(state, player, "Insect 2") and has_item(state, player, "Blood 2"),
		"Prion Evolve: Extreme Hematophagy": lambda state: has_item(state, player, "Extreme Hematophagy") and has_item(state, player, "Insect 2") and has_item(state, player, "Blood 2"),
		"Nano Virus Evolve: Extreme Hematophagy": lambda state: has_item(state, player, "Extreme Hematophagy") and has_item(state, player, "Insect 2") and has_item(state, player, "Blood 2"),
		"Bio Weapon Evolve: Extreme Hematophagy": lambda state: has_item(state, player, "Extreme Hematophagy") and has_item(state, player, "Insect 2") and has_item(state, player, "Blood 2"),
		"Bacteria Evolve: Cold Resistance 1": lambda state: has_item(state, player, "Cold Resistance 1"),
		"Virus Evolve: Cold Resistance 1": lambda state: has_item(state, player, "Cold Resistance 1"),
		"Fungus Evolve: Cold Resistance 1": lambda state: has_item(state, player, "Cold Resistance 1"),
		"Parasite Evolve: Cold Resistance 1": lambda state: has_item(state, player, "Cold Resistance 1"),
		"Prion Evolve: Cold Resistance 1": lambda state: has_item(state, player, "Cold Resistance 1"),
		"Nano Virus Evolve: Cold Resistance 1": lambda state: has_item(state, player, "Cold Resistance 1"),
		"Bio Weapon Evolve: Cold Resistance 1": lambda state: has_item(state, player, "Cold Resistance 1"),
		"Bacteria Evolve: Cold Resistance 2": lambda state: has_item(state, player, "Cold Resistance 2") and has_item(state, player, "Cold Resistance 1"),
		"Virus Evolve: Cold Resistance 2": lambda state: has_item(state, player, "Cold Resistance 2") and has_item(state, player, "Cold Resistance 1"),
		"Fungus Evolve: Cold Resistance 2": lambda state: has_item(state, player, "Cold Resistance 2") and has_item(state, player, "Cold Resistance 1"),
		"Parasite Evolve: Cold Resistance 2": lambda state: has_item(state, player, "Cold Resistance 2") and has_item(state, player, "Cold Resistance 1"),
		"Prion Evolve: Cold Resistance 2": lambda state: has_item(state, player, "Cold Resistance 2") and has_item(state, player, "Cold Resistance 1"),
		"Nano Virus Evolve: Cold Resistance 2": lambda state: has_item(state, player, "Cold Resistance 2") and has_item(state, player, "Cold Resistance 1"),
		"Bio Weapon Evolve: Cold Resistance 2": lambda state: has_item(state, player, "Cold Resistance 2") and has_item(state, player, "Cold Resistance 1"),
		"Bacteria Evolve: Heat Resistance 1": lambda state: has_item(state, player, "Heat Resistance 1"),
		"Virus Evolve: Heat Resistance 1": lambda state: has_item(state, player, "Heat Resistance 1"),
		"Fungus Evolve: Heat Resistance 1": lambda state: has_item(state, player, "Heat Resistance 1"),
		"Parasite Evolve: Heat Resistance 1": lambda state: has_item(state, player, "Heat Resistance 1"),
		"Prion Evolve: Heat Resistance 1": lambda state: has_item(state, player, "Heat Resistance 1"),
		"Nano Virus Evolve: Heat Resistance 1": lambda state: has_item(state, player, "Heat Resistance 1"),
		"Bio Weapon Evolve: Heat Resistance 1": lambda state: has_item(state, player, "Heat Resistance 1"),
		"Bacteria Evolve: Heat Resistance 2": lambda state: has_item(state, player, "Heat Resistance 2") and has_item(state, player, "Heat Resistance 1"),
		"Virus Evolve: Heat Resistance 2": lambda state: has_item(state, player, "Heat Resistance 2") and has_item(state, player, "Heat Resistance 1"),
		"Fungus Evolve: Heat Resistance 2": lambda state: has_item(state, player, "Heat Resistance 2") and has_item(state, player, "Heat Resistance 1"),
		"Parasite Evolve: Heat Resistance 2": lambda state: has_item(state, player, "Heat Resistance 2") and has_item(state, player, "Heat Resistance 1"),
		"Prion Evolve: Heat Resistance 2": lambda state: has_item(state, player, "Heat Resistance 2") and has_item(state, player, "Heat Resistance 1"),
		"Nano Virus Evolve: Heat Resistance 2": lambda state: has_item(state, player, "Heat Resistance 2") and has_item(state, player, "Heat Resistance 1"),
		"Bio Weapon Evolve: Heat Resistance 2": lambda state: has_item(state, player, "Heat Resistance 2") and has_item(state, player, "Heat Resistance 1"),
		"Bacteria Evolve: Environmental Hardening": lambda state: has_item(state, player, "Environmental Hardening") and has_item(state, player, "Cold Resistance 2") and has_item(state, player, "Heat Resistance 2"),
		"Virus Evolve: Environmental Hardening": lambda state: has_item(state, player, "Environmental Hardening") and has_item(state, player, "Cold Resistance 2") and has_item(state, player, "Heat Resistance 2"),
		"Fungus Evolve: Environmental Hardening": lambda state: has_item(state, player, "Environmental Hardening") and has_item(state, player, "Cold Resistance 2") and has_item(state, player, "Heat Resistance 2"),
		"Parasite Evolve: Environmental Hardening": lambda state: has_item(state, player, "Environmental Hardening") and has_item(state, player, "Cold Resistance 2") and has_item(state, player, "Heat Resistance 2"),
		"Prion Evolve: Environmental Hardening": lambda state: has_item(state, player, "Environmental Hardening") and has_item(state, player, "Cold Resistance 2") and has_item(state, player, "Heat Resistance 2"),
		"Nano Virus Evolve: Environmental Hardening": lambda state: has_item(state, player, "Environmental Hardening") and has_item(state, player, "Cold Resistance 2") and has_item(state, player, "Heat Resistance 2"),
		"Bio Weapon Evolve: Environmental Hardening": lambda state: has_item(state, player, "Environmental Hardening") and has_item(state, player, "Cold Resistance 2") and has_item(state, player, "Heat Resistance 2"),
		"Bacteria Evolve: Bacterial Resilience 1": lambda state: has_item(state, player, "Bacterial Resilience 1"),
		"Bacteria Evolve: Bacterial Resilience 2": lambda state: has_item(state, player, "Bacterial Resilience 2") and ( has_item(state, player, "Bacterial Resilience 1") or has_item(state, player, "Bacterial Resilience 3") ),
		"Bacteria Evolve: Bacterial Resilience 3": lambda state: has_item(state, player, "Bacterial Resilience 3") and ( has_item(state, player, "Bacterial Resilience 2") ),
		"Bacteria Evolve: Drug Resistance 1": lambda state: has_item(state, player, "Drug Resistance 1"),
		"Virus Evolve: Drug Resistance 1": lambda state: has_item(state, player, "Drug Resistance 1"),
		"Fungus Evolve: Drug Resistance 1": lambda state: has_item(state, player, "Drug Resistance 1"),
		"Parasite Evolve: Drug Resistance 1": lambda state: has_item(state, player, "Drug Resistance 1"),
		"Prion Evolve: Drug Resistance 1": lambda state: has_item(state, player, "Drug Resistance 1"),
		"Nano Virus Evolve: Drug Resistance 1": lambda state: has_item(state, player, "Drug Resistance 1"),
		"Bio Weapon Evolve: Drug Resistance 1": lambda state: has_item(state, player, "Drug Resistance 1"),
		"Bacteria Evolve: Drug Resistance 2": lambda state: has_item(state, player, "Drug Resistance 2") and has_item(state, player, "Drug Resistance 1"),
		"Virus Evolve: Drug Resistance 2": lambda state: has_item(state, player, "Drug Resistance 2") and has_item(state, player, "Drug Resistance 1"),
		"Fungus Evolve: Drug Resistance 2": lambda state: has_item(state, player, "Drug Resistance 2") and has_item(state, player, "Drug Resistance 1"),
		"Parasite Evolve: Drug Resistance 2": lambda state: has_item(state, player, "Drug Resistance 2") and has_item(state, player, "Drug Resistance 1"),
		"Prion Evolve: Drug Resistance 2": lambda state: has_item(state, player, "Drug Resistance 2") and has_item(state, player, "Drug Resistance 1"),
		"Nano Virus Evolve: Drug Resistance 2": lambda state: has_item(state, player, "Drug Resistance 2") and has_item(state, player, "Drug Resistance 1"),
		"Bio Weapon Evolve: Drug Resistance 2": lambda state: has_item(state, player, "Drug Resistance 2") and has_item(state, player, "Drug Resistance 1"),
		"Bacteria Evolve: Genetic Hardening 1": lambda state: has_item(state, player, "Genetic Hardening 1"),
		"Virus Evolve: Genetic Hardening 1": lambda state: has_item(state, player, "Genetic Hardening 1"),
		"Fungus Evolve: Genetic Hardening 1": lambda state: has_item(state, player, "Genetic Hardening 1"),
		"Parasite Evolve: Genetic Hardening 1": lambda state: has_item(state, player, "Genetic Hardening 1"),
		"Prion Evolve: Genetic Hardening 1": lambda state: has_item(state, player, "Genetic Hardening 1"),
		"Nano Virus Evolve: Genetic Hardening 1": lambda state: has_item(state, player, "Genetic Hardening 1"),
		"Bio Weapon Evolve: Genetic Hardening 1": lambda state: has_item(state, player, "Genetic Hardening 1"),
		"Bacteria Evolve: Genetic Hardening 2": lambda state: has_item(state, player, "Genetic Hardening 2") and has_item(state, player, "Genetic Hardening 1"),
		"Virus Evolve: Genetic Hardening 2": lambda state: has_item(state, player, "Genetic Hardening 2") and has_item(state, player, "Genetic Hardening 1"),
		"Fungus Evolve: Genetic Hardening 2": lambda state: has_item(state, player, "Genetic Hardening 2") and has_item(state, player, "Genetic Hardening 1"),
		"Parasite Evolve: Genetic Hardening 2": lambda state: has_item(state, player, "Genetic Hardening 2") and has_item(state, player, "Genetic Hardening 1"),
		"Prion Evolve: Genetic Hardening 2": lambda state: has_item(state, player, "Genetic Hardening 2") and has_item(state, player, "Genetic Hardening 1"),
		"Nano Virus Evolve: Genetic Hardening 2": lambda state: has_item(state, player, "Genetic Hardening 2") and has_item(state, player, "Genetic Hardening 1"),
		"Bio Weapon Evolve: Genetic Hardening 2": lambda state: has_item(state, player, "Genetic Hardening 2") and has_item(state, player, "Genetic Hardening 1"),
		"Bacteria Evolve: Genetic ReShuffle 1": lambda state: has_item(state, player, "Genetic ReShuffle 1"),
		"Virus Evolve: Genetic ReShuffle 1": lambda state: has_item(state, player, "Genetic ReShuffle 1"),
		"Fungus Evolve: Genetic ReShuffle 1": lambda state: has_item(state, player, "Genetic ReShuffle 1"),
		"Parasite Evolve: Genetic ReShuffle 1": lambda state: has_item(state, player, "Genetic ReShuffle 1"),
		"Prion Evolve: Genetic ReShuffle 1": lambda state: has_item(state, player, "Genetic ReShuffle 1"),
		"Nano Virus Evolve: Genetic ReShuffle 1": lambda state: has_item(state, player, "Genetic ReShuffle 1"),
		"Bio Weapon Evolve: Genetic ReShuffle 1": lambda state: has_item(state, player, "Genetic ReShuffle 1"),
		"Bacteria Evolve: Genetic ReShuffle 2": lambda state: has_item(state, player, "Genetic ReShuffle 2") and has_item(state, player, "Genetic ReShuffle 1"),
		"Virus Evolve: Genetic ReShuffle 2": lambda state: has_item(state, player, "Genetic ReShuffle 2") and has_item(state, player, "Genetic ReShuffle 1"),
		"Fungus Evolve: Genetic ReShuffle 2": lambda state: has_item(state, player, "Genetic ReShuffle 2") and has_item(state, player, "Genetic ReShuffle 1"),
		"Parasite Evolve: Genetic ReShuffle 2": lambda state: has_item(state, player, "Genetic ReShuffle 2") and has_item(state, player, "Genetic ReShuffle 1"),
		"Prion Evolve: Genetic ReShuffle 2": lambda state: has_item(state, player, "Genetic ReShuffle 2") and has_item(state, player, "Genetic ReShuffle 1"),
		"Nano Virus Evolve: Genetic ReShuffle 2": lambda state: has_item(state, player, "Genetic ReShuffle 2") and has_item(state, player, "Genetic ReShuffle 1"),
		"Bio Weapon Evolve: Genetic ReShuffle 2": lambda state: has_item(state, player, "Genetic ReShuffle 2") and has_item(state, player, "Genetic ReShuffle 1"),
		"Bacteria Evolve: Genetic ReShuffle 3": lambda state: has_item(state, player, "Genetic ReShuffle 3") and has_item(state, player, "Genetic ReShuffle 2"),
		"Virus Evolve: Genetic ReShuffle 3": lambda state: has_item(state, player, "Genetic ReShuffle 3") and has_item(state, player, "Genetic ReShuffle 2"),
		"Fungus Evolve: Genetic ReShuffle 3": lambda state: has_item(state, player, "Genetic ReShuffle 3") and has_item(state, player, "Genetic ReShuffle 2"),
		"Parasite Evolve: Genetic ReShuffle 3": lambda state: has_item(state, player, "Genetic ReShuffle 3") and has_item(state, player, "Genetic ReShuffle 2"),
		"Prion Evolve: Genetic ReShuffle 3": lambda state: has_item(state, player, "Genetic ReShuffle 3") and has_item(state, player, "Genetic ReShuffle 2"),
		"Nano Virus Evolve: Genetic ReShuffle 3": lambda state: has_item(state, player, "Genetic ReShuffle 3") and has_item(state, player, "Genetic ReShuffle 2"),
		"Bio Weapon Evolve: Genetic ReShuffle 3": lambda state: has_item(state, player, "Genetic ReShuffle 3") and has_item(state, player, "Genetic ReShuffle 2"),
		"Beat Bacteria on Normal": lambda state: has_item(state, player, "Bacteria") and has_item(state, player, "Normal") and has_score(state, player, "Bacteria", 50),
		"Beat Virus on Normal": lambda state: has_item(state, player, "Virus") and has_item(state, player, "Normal") and has_score(state, player, "Virus", 50),
		"Beat Fungus on Normal": lambda state: has_item(state, player, "Fungus") and has_item(state, player, "Normal") and has_score(state, player, "Fungus", 50),
		"Beat Parasite on Normal": lambda state: has_item(state, player, "Parasite") and has_item(state, player, "Normal") and has_score(state, player, "Parasite", 50),
		"Beat Prion on Normal": lambda state: has_item(state, player, "Prion") and has_item(state, player, "Normal") and has_score(state, player, "Prion", 50),
		"Beat Nano Virus on Normal": lambda state: has_item(state, player, "Nano Virus") and has_item(state, player, "Normal") and has_score(state, player, "Nano Virus", 50),
		"Beat Bio Weapon on Normal": lambda state: has_item(state, player, "Bio Weapon") and has_item(state, player, "Normal") and has_score(state, player, "Bio Weapon", 50),
	}

def has_item(state, player, item) -> bool:
	return state.has(item, player, 1)

def has_score(state, player, disease, target_score) -> bool:
	return sum([victory_scores[disease][item] for item, count in state.prog_items[player].items() if count > 0 and item in victory_scores[disease]]) >= target_score