# File is Auto-generated, see: [https://github.com/SWCreeperKing/Slimipelago/blob/master/Slimipelago/ApWorldShenanigans.cs]

upgrades = [
	"Buy Personal Upgrade (Heart Module lv.1)",
	"Buy Personal Upgrade (Heart Module lv.2)",
	"Buy Personal Upgrade (Heart Module lv.3)",
	"Buy Personal Upgrade (Heart Module lv.4)",
	"Buy Personal Upgrade (Tank Booster lv.1)",
	"Buy Personal Upgrade (Tank Booster lv.2)",
	"Buy Personal Upgrade (Tank Booster lv.3)",
	"Buy Personal Upgrade (Tank Booster lv.4)",
	"Buy Personal Upgrade (Dash Boots lv. 1)",
	"Buy Personal Upgrade (Dash Boots lv.2)",
	"Buy Personal Upgrade (Power Core lv.1)",
	"Buy Personal Upgrade (Power Core lv.2)",
	"Buy Personal Upgrade (Power Core lv.3)",
	"Buy Personal Upgrade (Treasure Cracker lv.1)",
	"Buy Personal Upgrade (Treasure Cracker lv.2)",
	"Buy Personal Upgrade (Treasure Cracker lv.3)",
	"Buy Personal Upgrade (Jetpack)",
	"Buy Personal Upgrade (Air Drive)",
	"Buy Personal Upgrade (Pulse Wave)",
	"Buy Personal Upgrade (Liquid Slot)"
]

upgrades_7z = [
	"Buy Personal Upgrade (Heart Module lv.4)",
	"Buy Personal Upgrade (Tank Booster lv.4)",
	"Buy Personal Upgrade (Dash Boots lv.2)"
]

interactables = [
	["Hobson's Note - Outside Ranch", "Dry Reef"],
	["Treasure Pod - Hidden Cave near Ranch Entry", "Dry Reef"],
	["Treasure Pod - Dry Reef Entrance", "Dry Reef"],
	["Treasure Pod - Dry Reef Arch Island", "Dry Reef"],
	["Hobson's Note - Cliff Near Tabby Slimes", "Dry Reef"],
	["Treasure Pod - Next to Slime Gate Ring Isle", "Dry Reef"],
	["Hobson's Note - Cliff Near Ring Island", "Dry Reef"],
	["Treasure Pod - Under Overgrowth Exit", "Dry Reef"],
	["Treasure Pod - Cliff Near Tabby Slimes", "Dry Reef"],
	["Treasure Pod - Tabby Gordo", "Dry Reef"],
	["Treasure Pod - Phosphor Gordo", "Dry Reef"],
	["Slime Sea - The Mustache Shrine", "Dry Reef"],
	["Hobson's Note - Ancient Ruins Entrance", "Ancient Ruins"],
	["Hobson's Note - The Grotto", "The Grotto"],
	["Treasure Pod - The Grotto", "The Grotto"],
	["Treasure Pod - Bridge Behind Indigo Quarry", "The Grotto"],
	["Treasure Pod - Alcove Behind Indigo Quarry", "The Grotto"],
	["Map Fragment - Dry Reef", "Dry Reef"],
	["Hobson's Note - Cliff Across Indigo Quarry", "Dry Reef"],
	["Hobson's Note - Cave to Indigo Quarry", "Dry Reef"],
	["Treasure Pod - Middle of Nowhere", "Moss Blanket"],
	["Treasure Pod - Dry Reef Ledge", "Dry Reef"],
	["Treasure Pod - Moss Blanket Wooden Staircase Escape", "Moss Blanket"],
	["Hobson's Note - Moss Blanket Main Area", "Moss Blanket"],
	["Hobson's Note - Moss Blanket Ledge", "Moss Blanket"],
	["Treasure Pod - Moss Blanket Entrance Cliff", "Moss Blanket"],
	["Treasure Pod - Moss Blanket Mushroom Tree Ledge", "Moss Blanket"],
	["Treasure Pod - Moss Blanket Flower Bed", "Moss Blanket"],
	["Map Fragment - Moss Blanket", "Moss Blanket"],
	["Treasure Pod - Moss Blanket Back Island", "Moss Blanket"],
	["Hobson's Note - Moss Blanket Mushroom Island", "Moss Blanket"],
	["Treasure Pod - Moss Blanket Underwater Pond", "Moss Blanket"],
	["Treasure Pod - Moss Blanket Wooden Ramps", "Moss Blanket"],
	["Treasure Pod - Quarry Cave Stalagmite near Rock Gordo", "Indigo Quarry"],
	["Treasure Pod - Moss Blanket Ledge Near Flower Area", "Moss Blanket"],
	["Treasure Pod - Moss Blanket Flower Area", "Moss Blanket"],
	["Treasure Pod - Quarry Cave Grass near Rock Gordo", "Indigo Quarry"],
	["Hobson's Note - Mushroom Feral Slime Area", "Moss Blanket"],
	["Treasure Pod - Quarry Entryway", "Indigo Quarry"],
	["Treasure Pod - Quarry Entryway Ledge", "Indigo Quarry"],
	["Hobson's Note - The Lab", "The Lab"],
	["Treasure Pod - The Lab", "The Lab"],
	["Treasure Pod - Mushroom Feral Slime Big Tree", "Moss Blanket"],
	["Treasure Pod - Quarry 3rd Area Coral Columns", "Indigo Quarry"],
	["Treasure Pod - Crystal Slime Cave Pillar", "Indigo Quarry"],
	["Hobson's Note - The Overgrowth", "The Overgrowth"],
	["Treasure Pod - Island Near Hunter Gordo", "Moss Blanket"],
	["Treasure Pod - Underwater After Log Tunnel", "Moss Blanket"],
	["Hobson's Note - Crystal Slime Cave", "Indigo Quarry"],
	["Treasure Pod - Through Crystal Slime Cave", "Indigo Quarry"],
	["Treasure Pod - In the Quarry Pond", "Indigo Quarry"],
	["Hobson's Note - Indigo Quarry Pond", "Indigo Quarry"],
	["Hobson's Note - The Docks", "The Overgrowth"],
	["Treasure Pod - Moss Blanket Alcove Cliff", "Moss Blanket"],
	["Hobson's Note - Indigo Quarry Entry", "Indigo Quarry"],
	["Treasure Pod - Alcove Above Moss Teleporter", "Moss Blanket"],
	["Treasure Pod - Near Island Teleport Gordo", "Indigo Quarry"],
	["Treasure Pod - In Quarry Wooden Structure", "Indigo Quarry"],
	["Treasure Pod - Northernmost Cliff of Indigo Quarry Mainland", "Indigo Quarry"],
	["Treasure Pod - Rad Gordo Cave", "Indigo Quarry"],
	["Treasure Pod - Cliff Past Rad Gordo", "Indigo Quarry"],
	["Treasure Pod - Near Quarry Exit Teleporter", "Indigo Quarry"],
	["Hobson's Note - Ash Isle", "Indigo Quarry"],
	["Treasure Pod - Ash Isle Fireflower Patch", "Indigo Quarry"],
	["Treasure Pod - Ash Isle Ledge", "Indigo Quarry"],
	["Map Fragment - Indigo Quarry", "Indigo Quarry"],
	["Treasure Pod - Ruins Door Puzzle", "Ancient Ruins Transition"],
	["Treasure Pod - Moss Blanket Under Log Tunnel", "Moss Blanket"],
	["Treasure Pod - Ring Island Flower Patch Cliff", "Dry Reef"],
	["Treasure Pod - Ring Island Brick Wall Ledge", "Dry Reef"],
	["Treasure Pod - Ring Island Hidden Cave", "Dry Reef"],
	["Hobson's Note - Ring Island", "Dry Reef"],
	["Treasure Pod - Moss Blanket Under Big Tree", "Moss Blanket"],
	["Treasure Pod - Moss Blanket Mushroom Island", "Moss Blanket"],
	["Treasure Pod - Ancient Top Floor Alcove", "Ancient Ruins"],
	["Treasure Pod - Ancient Bottom Floor Cave", "Ancient Ruins"],
	["Treasure Pod - Ancient Flower Bed", "Ancient Ruins"],
	["Treasure Pod - Ancient Hidden Dungeon", "Ancient Ruins"],
	["Hobson's Note - Ancient Bottom Floor Mushroom Cave", "Ancient Ruins"],
	["Treasure Pod - Ancient Bottom Floor Under Tree", "Ancient Ruins"],
	["Treasure Pod - Ancient Ruins Behind Wall", "Ancient Ruins"],
	["Treasure Pod - Ancient Ruins In A High Place", "Ancient Ruins"],
	["Hobson's Note - Ancient Ruins Back Half Oasis", "Ancient Ruins"],
	["Hobson's Note - End of Ancient Ruins", "Ancient Ruins"],
	["Treasure Pod - End of Ancient Ruins Bridge Alcove", "Ancient Ruins"],
	["Treasure Pod - End of Ancient Ruins Complimentary Pod", "Ancient Ruins"],
	["Treasure Pod - Ancient Ruins '???'", "Ancient Ruins"],
	["Treasure Pod - Boom Gordo", "Ancient Ruins"],
	["Treasure Pod - On Top of Ancient Ruins", "Ancient Ruins"],
	["Ancient Ruins - Follow the Upper Brick Road", "Ancient Ruins"],
	["Ancient Ruins - At the End of a Broken Pillar Path", "Ancient Ruins"],
	["Ancient Ruins - Hidden Room Behind a Leaf Drape", "Ancient Ruins"],
	["Treasure Pod - Outside The Desert Teleporter Room", "Glass Desert"],
	["Treasure Pod - Inside The Desert Teleporter Room", "Glass Desert"],
	["Hobson's Note - Entrance to Glass Desert", "Glass Desert"],
	["Treasure Pod - Glass Desert On a Rock", "Glass Desert"],
	["Hobson's Note - Glass Desert Rock Slime Fountain", "Glass Desert"],
	["Map Fragment - Glass Desert", "Glass Desert"],
	["Treasure Pod - Desert Fountain Hiding Place", "Glass Desert"],
	["Treasure Pod - On Top of Glass Desert Entrance", "Glass Desert"],
	["Treasure Pod - Above Tangle Gordo", "Glass Desert"],
	["Treasure Pod - Glass Desert Cliff Above Secret Style", "Glass Desert"],
	["Treasure Pod - Glass Desert Leftside Ruins", "Glass Desert"],
	["Treasure Pod - Glass Desert Leftside Isle", "Glass Desert"],
	["Treasure Pod - Edge of Glass Desert Cliff", "Glass Desert"],
	["Treasure Pod - Glass Desert Cliff Above Tangle Gordo", "Glass Desert"],
	["Treasure Pod - Under Glass Desert Western Ruins", "Glass Desert"],
	["Treasure Pod - Glass Desert Crevasse Pod", "Glass Desert"],
	["Treasure Pod - Glass Desert Cliff Ruins", "Glass Desert"],
	["Treasure Pod - Glass Desert Northern Ruins", "Glass Desert"],
	["Hobson's Note - Glass Desert Northern Courtyard", "Glass Desert"],
	["Treasure Pod - Glass Desert Western Ruins", "Glass Desert"],
	["Treasure Pod - Firey Glass Cliff", "Glass Desert"],
	["Treasure Pod - Glass Desert Western", "Glass Desert"],
	["Treasure Pod - Glass Desert Northern Cliff", "Glass Desert"],
	["Treasure Pod - Glass Desert Northern Steeple", "Glass Desert"],
	["Hobson's Note - Glass Desert Northern Ruins", "Glass Desert"],
	["Hobson's Note - Glass Desert Slime Statue", "Glass Desert"],
	["Hobson's Note - Doors Like These", "Glass Desert"],
	["Glass Desert - Two Doors", "Glass Desert"],
	["Glass Desert - Sold the Ranch", "Glass Desert"],
	["Glass Desert - Hover from One Tower to Another", "Glass Desert"],
	["Glass Desert - Hidden High Above the Ancient Fountain", "Glass Desert"]
]

dlc_interactables = [
	["Treasure Pod - Slime Sea Cosmetic (Angelic)", "The Grotto"],
	["Treasure Pod - Dry Reef Cosmetic (Sparkly)", "Dry Reef"],
	["Treasure Pod - Dry Reef Cosmetic (Heavy Metal)", "Dry Reef"],
	["Treasure Pod - Moss Blanket Cosmetic (Arcane)", "Moss Blanket"],
	["Treasure Pod - Moss Blanket Cosmetic (Cheshire)", "Moss Blanket"],
	["Treasure Pod - Moss Blanket Cosmetic (Royal Jelly)", "Moss Blanket"],
	["Indigo Quarry - Ashore Near Puddle Lake - Secret Style", "Indigo Quarry"],
	["Treasure Pod - Ring Island Cosmetic (Gilded)", "Dry Reef"],
	["Treasure Pod - Dry Reef Cosmetic (Tiger)", "Dry Reef"],
	["Ancient Ruins Transition - Hidden In a Cave Outside the Garden", "Ancient Ruins Transition"],
	["Treasure Pod - End of Ancient Ruins Cosmetic (Monochrome)", "Ancient Ruins"],
	["Treasure Pod - Ancient Ruins Cosmetic (Guardian)", "Ancient Ruins"],
	["Treasure Pod - Glass Desert Cosmetic (Nebula)", "Glass Desert"],
	["Treasure Pod - Glass Desert Leftside Ruins Secret Style", "Glass Desert"],
	["Treasure Pod - Glass Desert Western Secret Style", "Glass Desert"],
	["Treasure Pod - Glass Desert Northern", "Glass Desert"],
	["Ash Isle - Blooming From Fire Flowers", "Indigo Quarry"]
]

corporate_locations = [
	["7Zee lv.1: Roostro Weathervane", "Menu"],
	["7Zee lv.2: Fence Upgrade", "Menu"],
	["7Zee lv.3: Path Upgrade", "Dry Reef"],
	["7Zee lv.4: Porch Upgrade", "Dry Reef"],
	["7Zee lv.5: Chroma Station", "Dry Reef"],
	["7Zee lv.5: Cobalt Chroma", "Dry Reef"],
	["7Zee lv.5: Milkshake Chroma", "Dry Reef"],
	["7Zee lv.6: Arch Upgrade", "Dry Reef"],
	["7Zee lv.7: Firecracker Chroma", "Dry Reef"],
	["7Zee lv.7: Grapeshot Chroma", "Dry Reef"],
	["7Zee lv.8: Slime Toy Shop", "Dry Reef"],
	["7Zee lv.9: Robo Ranger Chroma", "Dry Reef"],
	["7Zee lv.9: Maidatron Chroma", "Dry Reef"],
	["7Zee lv.10: Advanced Slime Toys", "Dry Reef"],
	["7Zee lv.11: Gingersnap Chroma", "Ancient Ruins Transition"],
	["7Zee lv.11: Peapod Chroma", "Ancient Ruins Transition"],
	["7Zee lv.11: Market Link", "Ancient Ruins Transition"],
	["7Zee lv.12: Grotto Upgrade", "Ancient Ruins Transition"],
	["7Zee lv.13: Decorizer", "Ancient Ruins Transition"],
	["7Zee lv.13: Vanguard Chroma", "Ancient Ruins Transition"],
	["7Zee lv.13: Willow Chroma", "Ancient Ruins Transition"],
	["7Zee lv.14: Slime Trophy I", "Ancient Ruins Transition"],
	["7Zee lv.15: Daybreak Chroma", "Ancient Ruins Transition"],
	["7Zee lv.15: Eventide Chroma", "Ancient Ruins Transition"],
	["7Zee lv.16: Overgrowth Upgrade", "Ancient Ruins"],
	["7Zee lv.17: Salamander Chroma", "Ancient Ruins"],
	["7Zee lv.17: Royalton Chroma", "Ancient Ruins"],
	["7Zee lv.18: Slime Trophy II", "Ancient Ruins"],
	["7Zee lv.19: Neopolitan Chroma", "Ancient Ruins"],
	["7Zee lv.19: Min Chip Chroma", "Ancient Ruins"],
	["7Zee lv.19: Ultra Dash Boots", "Ancient Ruins"],
	["7Zee lv.20: Tank Booster Ultra", "Ancient Ruins"],
	["7Zee lv.20: Master Gordo Snare Blueprint", "Ancient Ruins"],
	["7Zee lv.21: Ghost Wine Chroma", "Ancient Ruins"],
	["7Zee lv.21: Volcanic Chroma", "Ancient Ruins"],
	["7Zee lv.21: Heart Module Ultra", "Ancient Ruins"],
	["7Zee lv.22: Lab Upgrade", "Ancient Ruins"],
	["7Zee lv.22: Golden Sureshot", "Ancient Ruins"],
	["7Zee lv.23: Knight Light Chroma", "Ancient Ruins"],
	["7Zee lv.23: Pretty Loud Chroma", "Ancient Ruins"],
	["7Zee lv.23: Titan Drill Blueprint", "Ancient Ruins"],
	["7Zee lv.24: Slime Trophy III", "Glass Desert"],
	["7Zee lv.24: Abyssal Pump Blueprint", "Glass Desert"],
	["7Zee lv.25: Silverfox Chroma", "Glass Desert"],
	["7Zee lv.25: Frozen Violet Chroma", "Glass Desert"],
	["7Zee lv.25: Royal Apiary Blueprint", "Glass Desert"],
	["7Zee lv.26: Docks Upgrade", "Glass Desert"],
	["7Zee lv.26: Gold Slime Lamp Blueprint", "Glass Desert"],
	["7Zee lv.27: Goldleaf Chroma", "Glass Desert"],
	["7Zee lv.27: Astro Pearl Chroma", "Glass Desert"],
	["7Zee lv.27: Gold Warp Depot Blueprint", "Glass Desert"],
	["7Zee lv.28: Slime Trophy IV", "Glass Desert"],
	["7Zee lv.28: Gold Teleporter Blueprint", "Glass Desert"]
]

location_dict = [
	*[items for items in upgrades],
	*[items[0] for items in interactables],
	*[items[0] for items in dlc_interactables],
	*[items[0] for items in corporate_locations]
]