# File is Auto-generated, see: [https://github.com/SWCreeperKing/ApWorldFactories/tree/master/ApWorldFactories/Games]

upgrades = [
	"Buy Personal Upgrade (Heart Module lv.1)",
	"Buy Personal Upgrade (Heart Module lv.2)",
	"Buy Personal Upgrade (Heart Module lv.3)",
	"Buy Personal Upgrade (Heart Module lv.4)",
	"Buy Personal Upgrade (Tank Booster lv.1)",
	"Buy Personal Upgrade (Tank Booster lv.2)",
	"Buy Personal Upgrade (Tank Booster lv.3)",
	"Buy Personal Upgrade (Tank Booster lv.4)",
	"Buy Personal Upgrade (Dash Boots lv.1)",
	"Buy Personal Upgrade (Dash Boots lv.2)",
	"Buy Personal Upgrade (Power Core lv.1)",
	"Buy Personal Upgrade (Power Core lv.2)",
	"Buy Personal Upgrade (Power Core lv.3)",
	"Buy Personal Upgrade (Treasure Cracker lv.1)",
	"Buy Personal Upgrade (Treasure Cracker lv.2)",
	"Buy Personal Upgrade (Treasure Cracker lv.3)",
	"Buy Personal Upgrade (Jetpack)",
	"Buy Personal Upgrade (Air Drive)",
	"Buy Personal Upgrade (Pulse Wave)",
	"Buy Personal Upgrade (Liquid Slot)"
]

upgrades_7z = [
	"Buy Personal Upgrade (Heart Module lv.4)",
	"Buy Personal Upgrade (Tank Booster lv.4)",
	"Buy Personal Upgrade (Dash Boots lv.2)"
]

interactables = [
	["The Overgrowth - Artificial Moss Blanket", "The Overgrowth"],
	["The Docks - Our Greater Purpose", "The Docks"],
	["Dry Reef -  Hobson's Greetings", "Dry Reef - Main"],
	["Dry Reef - Indigo Quarry Entrance", "Dry Reef - Main"],
	["Dry Reef - Great Big Tree", "Dry Reef - Main"],
	["Dry Reef - Map Data Node", "Dry Reef - Main"],
	["Dry Reef - Hidden Behind a Short Wall", "Dry Reef - Main"],
	["Dry Reef - Phosphor Gordo's Personal Pod", "Dry Reef - Main"],
	["Dry Reef - Cliff Tree Prize", "Dry Reef - Main"],
	["Dry Reef - Ruminating on the Beach", "Dry Reef - Beach"],
	["Dry Reef - Hidden in the Shade", "Dry Reef - Offshoot"],
	["Dry Reef - Outside Tabby Gordo's Home", "Dry Reef - Main"],
	["Indigo Quarry - I Liked Her Laugh", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - The Boom Zone", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Map Data Node", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Skate Fast Eat Grass", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Crystal Wind Chime", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Coral Tube Treasure", "Indigo Quarry - Before First Bridge"],
	["Dry Reef - A Darn Good Boot", "Dry Reef - Main"],
	["Indigo Quarry - Peeping Puddle Slimes", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Under a Hexium Crystal", "Indigo Quarry - After The Bridge"],
	["Ash Isles - Looking to the Stars", "Indigo Quarry - Ash Isles"],
	["Moss Blanket - Map Data Node", "Moss Blanket - Main"],
	["Ring Island - Flower Viewing on a Cliff", "Dry Reef - Ring Island"],
	["Ring Island - Naturally Curious", "Dry Reef - Ring Island"],
	["Moss Blanket - New Ancient Jungle", "Moss Blanket - Main"],
	["Moss Blanket - Overgrown Fungus Pod", "Moss Blanket - Main"],
	["Moss Blanket - MOSS BLANKET STUCK", "Moss Blanket - Main"],
	["Moss Blanket - Hidden Flowery Place", "Moss Blanket - Main"],
	["Dry Reef - Hidden Away on an ARCH-ipelago", "Dry Reef - Main"],
	["Dry Reef - Carrot Chest", "Dry Reef - Beach"],
	["Ring Island - Perilously Perched Pod", "Dry Reef - Ring Island"],
	["Dry Reef - Overlooking the Tarr Hotspot", "Dry Reef - Main"],
	["Indigo Quarry - Above the Smoke and Ashes", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Personal Puddle Pod", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Under Crumbled Scaffolding", "Indigo Quarry - After The Bridge"],
	["Indigo Quarry - Slightly Irradiated Reward", "Indigo Quarry - After The Bridge"],
	["Indigo Quarry - Treasure After the End", "Indigo Quarry - Ancient Ruins Transition Overlap"],
	["Ash Isles - Atop a Firey Perch", "Indigo Quarry - Ash Isles"],
	["The Grotto - The Limitless Black of Space", "The Grotto"],
	["The Grotto - Overlooking the Slime Sea", "The Grotto"],
	["Dry Reef - On the Middle Shelf", "Dry Reef - Offshoot"],
	["Moss Blanket - The Cupboard under the Stairs", "Moss Blanket - Main"],
	["Moss Blanket - Above the Hungry Hungry Largos", "Moss Blanket - Main"],
	["Moss Blanket - Can't Recommend Love Enough", "Moss Blanket - Mushroom Island"],
	["Moss Blanket - Just Under a Ledge", "Moss Blanket - Mushroom Island"],
	["Moss Blanket - At the Bottom of a Sheer Wall", "Moss Blanket - Mushroom Island"],
	["Moss Blanket - Briar Hen Pen", "Moss Blanket - Main"],
	["Moss Blanket - Peepers Peeled!", "Moss Blanket - Hunter's Domain"],
	["Moss Blanket - Tall Tree Treasure", "Moss Blanket - Hunter's Domain"],
	["Moss Blanket - The Lost Archipelago", "Moss Blanket - Hunter's Domain"],
	["Moss Blanket - Under The (Not) Sea", "Moss Blanket - Main"],
	["Ancient Ruins Transition - Slime Buddy", "Ancient Ruins Transition"],
	["Ancient Ruins - The Purpose of the Ruins", "Ancient Ruins - Main"],
	["Ancient Ruins - You Gotta Choose a Path", "Ancient Ruins - Main"],
	["Ancient Ruins - Map Data Node", "Ancient Ruins - Main"],
	["Ancient Ruins - Hidden Nook", "Ancient Ruins - Main"],
	["Ancient Ruins - At the End of a Broken Pillar Path", "Ancient Ruins - Main"],
	["Ancient Ruins - Tree Memorial", "Ancient Ruins - Main"],
	["Ancient Ruins - The Hidden Turnabout", "Ancient Ruins - Main"],
	["Ancient Ruins - Caught Up in the Explosion", "Ancient Ruins - Main"],
	["Ancient Ruins - A Flowery Respite", "Ancient Ruins - Main"],
	["Ancient Ruins - Overlooking From a Flowery Ledge", "Ancient Ruins - Main"],
	["Ancient Ruins - Ice-Cold Lemonade", "Ancient Ruins - Main"],
	["Ancient Ruins - In a Crumbled Pile", "Ancient Ruins - Main"],
	["Ancient Ruins - Truly Untamed Country", "Ancient Ruins - Teleporter Room"],
	["Dry Reef - Hidden Crevice Under the Hidden Cliff", "Dry Reef - Main"],
	["Indigo Quarry - Hidden Behind Stalagtmites", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - On a Cliff Before Puddle Lake", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Isolated from the Quarry", "Indigo Quarry - After The Bridge"],
	["Indigo Quarry - Crystal Cache behind Rickety Bridges", "Indigo Quarry - After The Bridge"],
	["Indigo Quarry - Across Hexium Crystal Formations", "Indigo Quarry - Before First Bridge"],
	["Ring Island - On a Dirty Patch", "Dry Reef - Ring Island"],
	["The Lab - The Wonders of Plort Technology", "The Lab"],
	["The Lab - Tinkerer's Starting Cache", "The Lab"],
	["Ash Isles - The Edge of the World", "Indigo Quarry - Ash Isles"],
	["The Slime Sea - Floating Alone in the Sea", "Dry Reef - Main"],
	["The Mustache Shrine - Mustache Stache Cache", "The Slime Sea - Mustache Shrine"],
	["Moss Blanket - Lonely Rock Pile", "Moss Blanket - Main"],
	["Moss Blanket - In the Roots of a Huge Tree", "Moss Blanket - Main"],
	["Moss Blanket - Overlooking the Tiny Pond", "Moss Blanket - Main"],
	["Moss Blanket - Sunken Treasure", "Moss Blanket - Mushroom Island"],
	["Moss Blanket - In the Rock Circle", "Moss Blanket - Main"],
	["The Slime Sea - On the Giant Tree Stump", "The Slime Sea - Off Moss Blanket"],
	["Moss Blanket - The 'Missed the Jump' Crevice", "Moss Blanket - Hunter's Domain"],
	["Ancient Ruins - There's Slimes in the Walls", "Ancient Ruins - Main"],
	["Ancient Ruins - Collapsed Upper Staircase", "Ancient Ruins - Main"],
	["Ancient Ruins - The Room With No Door", "Ancient Ruins - Main"],
	["Ancient Ruins - Shrine Overlooking the Ancient Ruins", "Ancient Ruins - Main"],
	["Ancient Ruins - Hidden Nook on a High Up Platform", "Ancient Ruins - Main"],
	["Ancient Ruins - Just Around the Corner", "Ancient Ruins - Main"],
	["Glass Desert - Buried Among Rubble", "Glass Desert - First Half"],
	["Glass Desert - Slime Statue Offering", "Glass Desert - First Half"],
	["Glass Desert - At the Tippy Top of the Highest Mountain", "Glass Desert - First Half"],
	["Glass Desert - Behind a False Wall", "Glass Desert - First Half"],
	["Glass Desert - You'll Risk Burning Your Tuchus!", "Glass Desert - First Half"],
	["Glass Desert - Atop the Pillar before a Chasm", "Glass Desert - First Half"],
	["Glass Desert - Map Data Node", "Glass Desert - First Half"],
	["Glass Desert - The Side of the Central Ruin", "Glass Desert - First Half"],
	["Glass Desert - In a High-up Nook", "Glass Desert - First Half"],
	["Glass Desert - Under the Private Island", "Glass Desert - Second Half"],
	["Glass Desert - Hiding Behind a Sheer Mountain", "Glass Desert - Second Half"],
	["Glass Desert - Down in a Hole", "Glass Desert - Second Half"],
	["Glass Desert - Two Overlapping Times", "Glass Desert - Second Half"],
	["Glass Desert - Hover from One Tower to Another", "Glass Desert - Second Half"],
	["Glass Desert - Two Doors", "Glass Desert - Second Half"],
	["Glass Desert - She Stole a Piece of My Heart", "Glass Desert - Second Half"],
	["Glass Desert - Sold the Ranch", "Glass Desert - Second Half"],
	["Glass Desert - I Wasn't Ready", "Glass Desert - Second Half"],
	["Glass Desert - Stupidly High Up", "Glass Desert - Second Half"],
	["Glass Desert - Secret Crevice Above Death Pit", "Glass Desert - Second Half"],
	["Glass Desert - Situated on a Collapsed Bridge", "Glass Desert - First Half"],
	["Glass Desert - Hidden in the Rafters", "Glass Desert - First Half"],
	["Glass Desert - Life Waiting to Flow", "Glass Desert - First Half"],
	["Glass Desert - In a Supporting Pillar", "Glass Desert - Second Half"],
	["Glass Desert - Hidden at the Edge of the Sand Sea", "Glass Desert - Second Half"],
	["Glass Desert - At the Base of a Fire Glass Sculpture", "Glass Desert - Second Half"],
	["Glass Desert - Just Around the Brick Wall", "Glass Desert - Second Half"],
	["Glass Desert - The Sand Sea", "Glass Desert - Second Half"],
	["Glass Desert - The Highest Fountain", "Glass Desert - Second Half"],
	["The Slimeulation - Under a Cliff Bordering The Simulated Sea", "The Slimeulation"],
	["The Slimeulation - Not Quite Rendered Arch", "The Slimeulation"],
	["The Slimeulation - Non-Rendered Cliff", "The Slimeulation"],
	["The Slimeulation - Platforming On Blocky Clouds", "The Slimeulation"],
	["The Slimeulation - Off The Rendered Path", "The Slimeulation"],
	["The Slimeulation - Just Around the Corner", "The Slimeulation"],
	["The Slimeulation - On Top Of The Simulated Winding Path", "The Slimeulation"],
	["The Slimeulation - Blocky Crevice Beside Moss Entrance", "The Slimeulation"],
	["The Slimeulation - In Between Muhsrooms and Rivers", "The Slimeulation"],
	["The Slimeulation - Underwater in a Ravine", "The Slimeulation"],
	["The Slimeulation - Offshoot of a Hazardous Pathway", "The Slimeulation"],
	["The Slimeulation - Looking Over the Puddle Slimes", "The Slimeulation"],
	["The Wilds - Across From the Hunter's Sakura Tree", "The Wilds"],
	["The Wilds - Inside a Pink Tree Stump", "The Wilds"],
	["The Wilds - On a Cliff Dividing Two Entrances", "The Wilds"],
	["The Wilds - Hidden Bridge Behind a Triangular Staircase", "The Wilds"],
	["The Wilds - A Precarious Ledge By the Waterfall", "The Wilds"],
	["The Wilds - Double Waterfall Treasure", "The Wilds"],
	["The Wilds - An Outcropping Near the Beach", "The Wilds"],
	["Nimble Valley - In a Nook on Top of The Final Stretch Arch", "Nimble Valley"],
	["Nimble Valley - Floating Above the Second Stretch", "Nimble Valley"],
	["Nimble Valley - Bordering the Slime Sea", "Nimble Valley"],
	["Nimble Valley - Inside the Magneticore Pillar", "Nimble Valley"],
	["Nimble Valley - Floating Outcropping Above a Crevice", "Nimble Valley"],
	["Nimble Valley - Hidden in some Magneticore Ore", "Nimble Valley"]
]

dlc_interactables = [
	["Dry Reef - Hidden Treasure of the Pink Gordo", "Dry Reef - Main"],
	["Dry Reef - Nested in Crystal", "Dry Reef - Main"],
	["Indigo Quarry - Puddle Lake", "Indigo Quarry - Before First Bridge"],
	["Dry Reef - Tiny Not-Huge Island", "Dry Reef - Beach"],
	["Ash Isles - Blooming from Fire Flowers", "Indigo Quarry - Ash Isles"],
	["Moss Blanket - Fairy Circle Treasure", "Moss Blanket - Main"],
	["Ring Island - King of the Hill", "Dry Reef - Ring Island"],
	["Indigo Quarry - Follow the Ravine", "Indigo Quarry - Ancient Ruins Transition Overlap"],
	["Slime Sea - In Between a Rock and an Island", "The Slime Sea - Between Grotto and Dry Reef Island 1"],
	["Moss Blanket - On a Lone Island", "Moss Blanket - Mushroom Island"],
	["Moss Blanket - The End Reward", "Moss Blanket - Main"],
	["Ancient Ruins - Everything Quiet on the Western Front", "Ancient Ruins - Main"],
	["Ancient Ruins - Above the Ancient Teleporter", "Ancient Ruins - Main"],
	["Glass Desert - Painted Hen Stowaway Crate", "Glass Desert - First Half"],
	["Glass Desert - On a Private Island", "Glass Desert - Second Half"],
	["Glass Desert - Overlooking Great Glass Pillars", "Glass Desert - Second Half"],
	["Glass Desert - Jagged Rock Formation in a Plateu", "Glass Desert - Second Half"],
	["The Slimeulation - Right Across from the Exit", "The Slimeulation"],
	["The Wilds - Coral Ring Island Exit", "The Wilds"],
	["Nimble Valley - Overlooking the Beginner Start", "Nimble Valley"]
]

corporate_locations = [
	["7Zee lv.1: Roostro Weathervane", "Menu"],
	["7Zee lv.2: Fence Upgrade", "Menu"],
	["7Zee lv.3: Path Upgrade", "Dry Reef - Main"],
	["7Zee lv.4: Porch Upgrade", "Dry Reef - Main"],
	["7Zee lv.5: Chroma Station", "Dry Reef - Main"],
	["7Zee lv.5: Cobalt Chroma", "Dry Reef - Main"],
	["7Zee lv.5: Milkshake Chroma", "Dry Reef - Main"],
	["7Zee lv.6: Arch Upgrade", "Dry Reef - Main"],
	["7Zee lv.7: Firecracker Chroma", "Dry Reef - Main"],
	["7Zee lv.7: Grapeshot Chroma", "Dry Reef - Main"],
	["7Zee lv.8: Slime Toy Shop", "Dry Reef - Main"],
	["7Zee lv.9: Robo Ranger Chroma", "Dry Reef - Main"],
	["7Zee lv.9: Maidatron Chroma", "Dry Reef - Main"],
	["7Zee lv.10: Advanced Slime Toys", "Dry Reef - Main"],
	["7Zee lv.11: Gingersnap Chroma", "Ancient Ruins Transition"],
	["7Zee lv.11: Peapod Chroma", "Ancient Ruins Transition"],
	["7Zee lv.11: Market Link", "Ancient Ruins Transition"],
	["7Zee lv.12: Grotto Upgrade", "Ancient Ruins Transition"],
	["7Zee lv.13: Decorizer", "Ancient Ruins Transition"],
	["7Zee lv.13: Vanguard Chroma", "Ancient Ruins Transition"],
	["7Zee lv.13: Willow Chroma", "Ancient Ruins Transition"],
	["7Zee lv.14: Slime Trophy I", "Ancient Ruins Transition"],
	["7Zee lv.15: Daybreak Chroma", "Ancient Ruins Transition"],
	["7Zee lv.15: Eventide Chroma", "Ancient Ruins Transition"],
	["7Zee lv.16: Overgrowth Upgrade", "Ancient Ruins - Main"],
	["7Zee lv.17: Salamander Chroma", "Ancient Ruins - Main"],
	["7Zee lv.17: Royalton Chroma", "Ancient Ruins - Main"],
	["7Zee lv.18: Slime Trophy II", "Ancient Ruins - Main"],
	["7Zee lv.19: Neopolitan Chroma", "Ancient Ruins - Main"],
	["7Zee lv.19: Min Chip Chroma", "Ancient Ruins - Main"],
	["7Zee lv.19: Ultra Dash Boots", "Ancient Ruins - Main"],
	["7Zee lv.20: Tank Booster Ultra", "Ancient Ruins - Main"],
	["7Zee lv.20: Master Gordo Snare Blueprint", "Ancient Ruins - Main"],
	["7Zee lv.21: Ghost Wine Chroma", "Ancient Ruins - Main"],
	["7Zee lv.21: Volcanic Chroma", "Ancient Ruins - Main"],
	["7Zee lv.21: Heart Module Ultra", "Ancient Ruins - Main"],
	["7Zee lv.22: Lab Upgrade", "Ancient Ruins - Main"],
	["7Zee lv.22: Golden Sureshot", "Ancient Ruins - Main"],
	["7Zee lv.23: Knight Light Chroma", "Ancient Ruins - Main"],
	["7Zee lv.23: Pretty Loud Chroma", "Ancient Ruins - Main"],
	["7Zee lv.23: Titan Drill Blueprint", "Ancient Ruins - Main"],
	["7Zee lv.24: Slime Trophy III", "Glass Desert - First Half"],
	["7Zee lv.24: Abyssal Pump Blueprint", "Glass Desert - First Half"],
	["7Zee lv.25: Silverfox Chroma", "Glass Desert - First Half"],
	["7Zee lv.25: Frozen Violet Chroma", "Glass Desert - First Half"],
	["7Zee lv.25: Royal Apiary Blueprint", "Glass Desert - First Half"],
	["7Zee lv.26: Docks Upgrade", "Glass Desert - First Half"],
	["7Zee lv.26: Gold Slime Lamp Blueprint", "Glass Desert - First Half"],
	["7Zee lv.27: Goldleaf Chroma", "Glass Desert - First Half"],
	["7Zee lv.27: Astro Pearl Chroma", "Glass Desert - First Half"],
	["7Zee lv.27: Gold Warp Depot Blueprint", "Glass Desert - First Half"],
	["7Zee lv.28: Slime Trophy IV", "Glass Desert - First Half"],
	["7Zee lv.28: Gold Teleporter Blueprint", "Glass Desert - First Half"]
]

location_dict = [
	*[items for items in upgrades],
	*[items[0] for items in interactables],
	*[items[0] for items in dlc_interactables],
	*[items[0] for items in corporate_locations]
]