# File is Auto-generated, see: [https://github.com/SWCreeperKing/ApWorldFactories/tree/master/ApWorldFactories/Games]

plorts = [
	"Sell a Pink Plort",
	"Sell a Tabby Plort",
	"Sell a Rock Plort",
	"Sell a Phosphor Plort",
	"Sell a Boom Plort",
	"Sell a Rad Plort",
	"Sell a Crystal Plort",
	"Sell a Honey Plort",
	"Sell a Hunter Plort",
	"Sell a Quantum Plort",
	"Sell a Dervish Plort",
	"Sell a Tangle Plort",
	"Sell a Mosaic Plort",
	"Sell a Gold Plort",
	"Sell a Saber Plort",
	"Sell a Puddle Plort",
	"Sell a Fire Plort"
]

upgrades = [
	["Buy Personal Upgrade (Heart Module lv.1)", "Menu"],
	["Buy Personal Upgrade (Heart Module lv.2)", "Dry Reef - Main"],
	["Buy Personal Upgrade (Heart Module lv.3)", "Dry Reef - Main"],
	["Buy Personal Upgrade (Heart Module lv.4)", "Ancient Ruins - Main"],
	["Buy Personal Upgrade (Tank Booster lv.1)", "Menu"],
	["Buy Personal Upgrade (Tank Booster lv.2)", "Dry Reef - Main"],
	["Buy Personal Upgrade (Tank Booster lv.3)", "Dry Reef - Main"],
	["Buy Personal Upgrade (Tank Booster lv.4)", "Ancient Ruins - Main"],
	["Buy Personal Upgrade (Dash Boots lv.1)", "Menu"],
	["Buy Personal Upgrade (Dash Boots lv.2)", "Ancient Ruins - Main"],
	["Buy Personal Upgrade (Power Core lv.1)", "Menu"],
	["Buy Personal Upgrade (Power Core lv.2)", "Dry Reef - Main"],
	["Buy Personal Upgrade (Power Core lv.3)", "Dry Reef - Main"],
	["Buy Personal Upgrade (Treasure Cracker lv.1)", "The Lab"],
	["Buy Personal Upgrade (Treasure Cracker lv.2)", "The Lab"],
	["Buy Personal Upgrade (Treasure Cracker lv.3)", "The Lab"],
	["Buy Personal Upgrade (Jetpack)", "Menu"],
	["Buy Personal Upgrade (Air Drive)", "Dry Reef - Main"],
	["Buy Personal Upgrade (Pulse Wave)", "Menu"],
	["Buy Personal Upgrade (Liquid Slot)", "Menu"]
]

interactables = [
	["The Grotto - The Limitless Black of Space", "The Grotto"],
	["The Grotto - Overlooking the Slime Sea", "The Grotto"],
	["The Overgrowth - Artifical Moss Blanket", "The Overgrowth"],
	["The Lab - The Wonders of Plort Technology", "The Lab"],
	["The Lab - Tinkerer's Starting Cache", "The Lab"],
	["The Docks - Our Greater Purpose", "The Docks"],
	["Ogden's Retreat - That's a Whole Lotta Kookabobas", "The Wilds"],
	["Dry Reef - Hobson's Greetings", "Dry Reef - Main"],
	["Dry Reef - Indigo Quarry Entrance", "Dry Reef - Main"],
	["Dry Reef - Great Big Tree", "Dry Reef - Main"],
	["Dry Reef - A Darn Good Boot", "Dry Reef - Main"],
	["Dry Reef - Map Data Node", "Dry Reef - Main"],
	["Dry Reef - Hidden Behind a Short Wall", "Dry Reef - Main"],
	["Dry Reef - Phosphor Gordo's Personal Pod", "Dry Reef - Main"],
	["Dry Reef - In the Cliff Tree's Roots", "Dry Reef - Main"],
	["Dry Reef - Nested by Tabby Gordo", "Dry Reef - Main"],
	["Dry Reef - Stony Hen Hen Coop", "Dry Reef - Main"],
	["Dry Reef - Hidden Away on an ARCH-ipelago", "Dry Reef - Main"],
	["Dry Reef - Overlooking the Tarr Hotspot", "Dry Reef - Main"],
	["Dry Reef - Hidden Crevice Under the Hidden Cliff", "Dry Reef - Main"],
	["Dry Reef - Ruminating on the Beach", "Dry Reef - Beach"],
	["Dry Reef - Carrot Patch Cache", "Dry Reef - Beach"],
	["Ring Island - We'd Get Along Just Fine", "Dry Reef - Ring Island"],
	["Ring Island - Flower Viewing on a Cliff", "Dry Reef - Ring Island"],
	["Ring Island - Perilously Perched Pod", "Dry Reef - Ring Island"],
	["Ring Island - Hidden on the Backside of the Island", "Dry Reef - Ring Island"],
	["Dry Reef - Hidden in the Shade", "Dry Reef - Offshoot"],
	["Dry Reef - Beneath the Wooden Scaffolding", "Dry Reef - Offshoot"],
	["Ring Island Vault - Don't Get Too Greedy Pod 1", "Dry Reef - H Vault"],
	["Ring Island Vault - Don't Get Too Greedy Pod 2", "Dry Reef - H Vault"],
	["Ring Island Vault - Don't Get Too Greedy Pod 3", "Dry Reef - H Vault"],
	["Ring Island Vault - Don't Get Too Greedy Pod 4", "Dry Reef - H Vault"],
	["Ring Island Vault - The Quintessential Quintuplet #1", "Dry Reef - H Vault"],
	["Ring Island Vault - The Quintessential Quintuplet #2", "Dry Reef - H Vault"],
	["Ring Island Vault - The Quintessential Quintuplet #3", "Dry Reef - H Vault"],
	["Ring Island Vault - The Quintessential Quintuplet #4", "Dry Reef - H Vault"],
	["Ring Island Vault - The Quintessential Quintuplet #5", "Dry Reef - H Vault"],
	["Ring Island Vault - Mushroom Column Riches #1", "Dry Reef - H Vault"],
	["Ring Island Vault - Mushroom Column Riches #2", "Dry Reef - H Vault"],
	["Ring Island Vault - Mushroom Column Riches #3", "Dry Reef - H Vault"],
	["Ring Island Vault - Boring Column Riches #1", "Dry Reef - H Vault"],
	["Ring Island Vault - Boring Column Riches #2", "Dry Reef - H Vault"],
	["The Slime Sea - Island Alone in the Sea", "Dry Reef - Main"],
	["The Mustache Shrine - Mustache Stache Cache", "The Slime Sea - Mustache Shrine"],
	["The Slime Sea - On the Giant Tree Stump", "The Slime Sea - Off Moss Blanket"],
	["Indigo Quarry - I Liked Her Laugh", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Crystal Wind Chime", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Peeping Puddle Slimes", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Map Data Node", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Skate Fast Eat Grass", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Coral Tube Treasure", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - The Boom Zone", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Above the Smoke and Ashes", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Personal Puddle Pod", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Hidden Behind Stalagtmites", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - On a Cliff Before Puddle Lake", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Across Hexium Crystal Formations", "Indigo Quarry - Before First Bridge"],
	["Indigo Quarry - Under a Hexium Crystal", "Indigo Quarry - After The Bridge"],
	["Indigo Quarry - Under Crumbled Scaffolding", "Indigo Quarry - After The Bridge"],
	["Indigo Quarry - Slightly Irradiated Reward", "Indigo Quarry - After The Bridge"],
	["Indigo Quarry - Through the Radiation Cave", "Indigo Quarry - After The Bridge"],
	["Indigo Quarry - Crystal Cache behind Rickety Bridges", "Indigo Quarry - After The Bridge"],
	["Ash Isles - Looking to the Stars", "Indigo Quarry - Ash Isles"],
	["Ash Isles - Atop a Firey Perch", "Indigo Quarry - Ash Isles"],
	["Ash Isles - The Edge of the World", "Indigo Quarry - Ash Isles"],
	["Indigo Quarry - Treasure After the End", "Indigo Quarry - Ancient Ruins Transition Overlap"],
	["Ash Isle Vault - The Lone Pod Stands Alone", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - Daniel #1", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - Daniel #2", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - Daniel #3", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - The Cooler Daniel #1", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - The Cooler Daniel #2", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - The Cooler Daniel #3", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - The Cooler Daniel #4", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - The Cooler Daniel #5", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - Golden Rain #1", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - Golden Rain #2", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - Golden Rain #3", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - Golden Rain #4", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - Golden Rain #5", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - Okay Listen, I'm Running Out of Good Names For These Treasure Pods, And They All Look The Same So Hopefully You Can Take This As My Apology #1", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - Okay Listen, I'm Running Out of Good Names For These Treasure Pods, And They All Look The Same So Hopefully You Can Take This As My Apology #2", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - Okay Listen, I'm Running Out of Good Names For These Treasure Pods, And They All Look The Same So Hopefully You Can Take This As My Apology #3", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - The Council Member 1", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - The Council Member 2", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - The Council Member 3", "Indigo Quarry - H Vault"],
	["Ash Isle Vault - The Council Member 4", "Indigo Quarry - H Vault"],
	["Moss Blanket - New Ancient Jungle", "Moss Blanket - Main"],
	["Moss Blanket - MOSS BLANKET STUCK", "Moss Blanket - Main"],
	["Moss Blanket - Map Data Node", "Moss Blanket - Main"],
	["Moss Blanket - Surrounded by Mushrooms", "Moss Blanket - Main"],
	["Moss Blanket - Flowery Dead End", "Moss Blanket - Main"],
	["Moss Blanket - Above the Hungry Hungry Largos", "Moss Blanket - Main"],
	["Moss Blanket - In the Honey Heaven", "Moss Blanket - Main"],
	["Moss Blanket - The Cupboard under the Stairs", "Moss Blanket - Main"],
	["Moss Blanket - Under the Log River", "Moss Blanket - Main"],
	["Moss Blanket - Behind a Lonely Mountain", "Moss Blanket - Main"],
	["Moss Blanket - In the Roots of a Huge Tree", "Moss Blanket - Main"],
	["Moss Blanket - Overlooking the Tiny Pond", "Moss Blanket - Main"],
	["Moss Blanket - Under the Log Bridge", "Moss Blanket - Main"],
	["Moss Blanket - Can't Recommend Love Enough", "Moss Blanket - Mushroom Island"],
	["Moss Blanket - Just Under a Ledge", "Moss Blanket - Mushroom Island"],
	["Moss Blanket - At the Bottom of a Sheer Wall", "Moss Blanket - Mushroom Island"],
	["Moss Blanket - Sunken Treasure", "Moss Blanket - Mushroom Island"],
	["Moss Blanket - Peepers Peeled!", "Moss Blanket - Hunter's Domain"],
	["Moss Blanket - Very, Very, Very Tall Tree", "Moss Blanket - Hunter's Domain"],
	["Moss Blanket - The Lost Archipelago", "Moss Blanket - Hunter's Domain"],
	["Moss Blanket - The 'Missed the Jump' Crevice", "Moss Blanket - Hunter's Domain"],
	["Moss Blanket Vault - The Slime Central's Left-Hand Man", "Moss Blanket - H Vault"],
	["Moss Blanket Vault - The Slime Central's Right-Hand Man", "Moss Blanket - H Vault"],
	["Moss Blanket Vault - What's Left of the Riches #1", "Moss Blanket - H Vault"],
	["Moss Blanket Vault - What's Left of the Riches #2", "Moss Blanket - H Vault"],
	["Moss Blanket Vault - What's Right of the Riches #1", "Moss Blanket - H Vault"],
	["Moss Blanket Vault - What's Right of the Riches #2", "Moss Blanket - H Vault"],
	["Moss Blanket Vault - A Mountain of Gold #1", "Moss Blanket - H Vault"],
	["Moss Blanket Vault - A Mountain of Gold #2", "Moss Blanket - H Vault"],
	["Moss Blanket Vault - A Mountain of Gold #3", "Moss Blanket - H Vault"],
	["Moss Blanket Vault - A Mountain of Gold #4", "Moss Blanket - H Vault"],
	["Moss Blanket Vault - A Mountain of Gold #5", "Moss Blanket - H Vault"],
	["Ancient Ruins Transition - Slime Buddy", "Ancient Ruins Transition"],
	["Ancient Ruins - These Folks Like Slimes", "Ancient Ruins - Main"],
	["Ancient Ruins - You Gotta Choose a Path", "Ancient Ruins - Main"],
	["Ancient Ruins - Ice-Cold Lemonade", "Ancient Ruins - Main"],
	["Ancient Ruins - Map Data Node", "Ancient Ruins - Main"],
	["Ancient Ruins - Tree Memorial", "Ancient Ruins - Main"],
	["Ancient Ruins - A Flowery Respite", "Ancient Ruins - Main"],
	["Ancient Ruins - Hidden Nook", "Ancient Ruins - Main"],
	["Ancient Ruins - The Hidden Turnabout", "Ancient Ruins - Main"],
	["Ancient Ruins - Caught Up in the Explosion", "Ancient Ruins - Main"],
	["Ancient Ruins - The End of a Long and Arduous Journey", "Ancient Ruins - Main"],
	["Ancient Ruins - In a Crumbled Pile", "Ancient Ruins - Main"],
	["Ancient Ruins - At the End of a Broken Pillar Path", "Ancient Ruins - Main"],
	["Ancient Ruins - There's Slimes in the Walls", "Ancient Ruins - Main"],
	["Ancient Ruins - Collapsed Upper Staircase", "Ancient Ruins - Main"],
	["Ancient Ruins - The Room With No Door", "Ancient Ruins - Main"],
	["Ancient Ruins - Shrine Overlooking the Ancient Ruins", "Ancient Ruins - Main"],
	["Ancient Ruins - Hidden Nook on a High Up Platform", "Ancient Ruins - Main"],
	["Ancient Ruins - Follow the Sunken Pillars", "Ancient Ruins - Main"],
	["Ancient Ruins - Truly Untamed Country", "Ancient Ruins - Teleporter Room"],
	["Glass Desert - You'll Risk Burning Your Tuchus!", "Glass Desert - First Half"],
	["Glass Desert - Life Waiting to Flow", "Glass Desert - First Half"],
	["Glass Desert - Buried Among Rubble", "Glass Desert - First Half"],
	["Glass Desert - Behind a False Wall", "Glass Desert - First Half"],
	["Glass Desert - Atop the Pillar before a Chasm", "Glass Desert - First Half"],
	["Glass Desert - Hidden in the Rafters", "Glass Desert - First Half"],
	["Glass Desert - Slime Statue Offering", "Glass Desert - First Half"],
	["Glass Desert - At the Tippy Top of the Highest Mountain", "Glass Desert - First Half"],
	["Glass Desert - Halfway up a Towering Tower", "Glass Desert - First Half"],
	["Glass Desert - In a High-up Nook", "Glass Desert - First Half"],
	["Glass Desert - Situated on a Collapsed Bridge", "Glass Desert - First Half"],
	["Glass Desert - Flames Burning at an Unperceivable Pace", "Glass Desert - Second Half"],
	["Glass Desert - Two Doors", "Glass Desert - Second Half"],
	["Glass Desert - She Stole a Piece of My Heart", "Glass Desert - Second Half"],
	["Glass Desert - Sold the Ranch", "Glass Desert - Second Half"],
	["Glass Desert - I Wasn't Ready", "Glass Desert - Second Half"],
	["Glass Desert - The Sand Sea", "Glass Desert - Second Half"],
	["Glass Desert - Down in a Hole", "Glass Desert - Second Half"],
	["Glass Desert - Just Around the Brick Wall", "Glass Desert - Second Half"],
	["Glass Desert - Dead-End Forgotten to the World", "Glass Desert - Second Half"],
	["Glass Desert - Under the Private Island", "Glass Desert - Second Half"],
	["Glass Desert - Hiding Behind a Sheer Mountain", "Glass Desert - Second Half"],
	["Glass Desert - Hover from One Tower to Another", "Glass Desert - Second Half"],
	["Glass Desert - Stupidly High Up", "Glass Desert - Second Half"],
	["Glass Desert - Ruined Wall On a Cliff", "Glass Desert - Second Half"],
	["Glass Desert - In a Supporting Pillar", "Glass Desert - Second Half"],
	["Glass Desert - Hidden at the Edge of the Sand Sea", "Glass Desert - Second Half"],
	["Glass Desert - At the Base of a Fire Glass Sculpture", "Glass Desert - Second Half"],
	["Glass Desert - The Highest Fountain", "Glass Desert - Second Half"],
	["Lonely Pillar in the Sand Sea", "Glass Desert - Second Half"],
	["The Slimeulation - Under a Cliff Bordering The Simulated Sea", "The Slimeulation"],
	["The Slimeulation - Not Quite Rendered Arch", "The Slimeulation"],
	["The Slimeulation - Just Around the Corner", "The Slimeulation"],
	["The Slimeulation - Blocky Crevice Beside Moss Entrance", "The Slimeulation"],
	["The Slimeulation - Underwater in a Ravine", "The Slimeulation"],
	["The Slimeulation - Offshoot of a Hazardous Pathway", "The Slimeulation"],
	["The Slimeulation - Looking Over the Puddle Slimes", "The Slimeulation"],
	["The Slimeulation - Hidden Crevice under the Slimeulated Cliff", "The Slimeulation"],
	["The Slimeulation - Non-Rendered Cliff", "The Slimeulation"],
	["The Slimeulation - Platforming On Blocky Clouds", "The Slimeulation"],
	["The Slimeulation - Off The Rendered Path", "The Slimeulation"],
	["The Slimeulation - On Top Of The Simulated Winding Path", "The Slimeulation"],
	["The Slimeulation - In Between Muhsrooms and Rivers", "The Slimeulation"],
	["The Wilds - Across From the Hunter's Sakura Tree", "The Wilds"],
	["The Wilds - On a Cliff Dividing Two Entrances", "The Wilds"],
	["The Wilds - A Precarious Ledge By the Waterfall", "The Wilds"],
	["The Wilds - An Outcropping Near the Beach", "The Wilds"],
	["The Wilds - Inside a Pink Tree Stump", "The Wilds"],
	["The Wilds - Hidden Bridge Behind a Triangular Staircase", "The Wilds"],
	["The Wilds - Double Waterfall Treasure", "The Wilds"],
	["The Wilds - On a Tiny Ledge Overlooking the Underground River", "The Wilds"],
	["Nimble Valley - In a Nook on Top of The Final Stretch Arch", "Nimble Valley"],
	["Nimble Valley - Bordering the Slime Sea", "Nimble Valley"],
	["Nimble Valley - Inside the Magneticore Pillar", "Nimble Valley"],
	["Nimble Valley - Floating Outcropping Above a Crevice", "Nimble Valley"],
	["Nimble Valley - Floating Above the Second Stretch", "Nimble Valley"],
	["Nimble Valley - Hidden in some Magneticore Ore", "Nimble Valley"]
]

dlc_interactables = [
	["Dry Reef - Hidden Treasure of the Pink Gordo", "Dry Reef - Main"],
	["Dry Reef - Nested in Crystal", "Dry Reef - Main"],
	["Dry Reef - Tiny Not-Huge Island", "Dry Reef - Beach"],
	["Ring Island - King of the Hill", "Dry Reef - Ring Island"],
	["The Slime Sea - In Between a Rock and an Island", "The Slime Sea - Between Grotto and Dry Reef Island 1"],
	["Indigo Quarry - Ashore Near Puddle Lake", "Indigo Quarry - Before First Bridge"],
	["Ash Isles - Blooming from Fire Flowers", "Indigo Quarry - Ash Isles"],
	["Indigo Quarry - Follow the Ravine", "Indigo Quarry - Ancient Ruins Transition Overlap"],
	["Moss Blanket - Fairy Circle Treasure", "Moss Blanket - Main"],
	["Moss Blanket - Not Quite Hidden", "Moss Blanket - Main"],
	["Moss Blanket - Off the Unbeaten Path", "Moss Blanket - Mushroom Island"],
	["Ancient Ruins - Everything Quiet on the Western Front", "Ancient Ruins - Main"],
	["Ancient Ruins - Above the Ancient Teleporter", "Ancient Ruins - Main"],
	["Glass Desert - Painted Hen Stowaway Crate", "Glass Desert - First Half"],
	["Glass Desert - On a Private Island", "Glass Desert - Second Half"],
	["Glass Desert - Overlooking Great Glass Pillars", "Glass Desert - Second Half"],
	["Glass Desert - Jagged Rock Formation in a Plateu", "Glass Desert - Second Half"],
	["The Slimeulation - Right Across from the Exit", "The Slimeulation"],
	["The Wilds - Coral Ring Island Exit", "The Wilds"],
	["Nimble Valley - Overlooking the Beginner Start", "Nimble Valley"]
]

corporate_locations = [
	["7Zee lv.1: Roostro Weathervane", "Menu"],
	["7Zee lv.2: Fence Upgrade", "Menu"],
	["7Zee lv.3: Path Upgrade", "Dry Reef - Main"],
	["7Zee lv.4: Porch Upgrade", "Dry Reef - Main"],
	["7Zee lv.5: Chroma Station", "Dry Reef - Main"],
	["7Zee lv.5: Cobalt Chroma", "Dry Reef - Main"],
	["7Zee lv.5: Milkshake Chroma", "Dry Reef - Main"],
	["7Zee lv.6: Arch Upgrade", "Dry Reef - Main"],
	["7Zee lv.7: Firecracker Chroma", "Dry Reef - Main"],
	["7Zee lv.7: Grapeshot Chroma", "Dry Reef - Main"],
	["7Zee lv.8: Slime Toy Shop", "Dry Reef - Main"],
	["7Zee lv.9: Robo Ranger Chroma", "Dry Reef - Main"],
	["7Zee lv.9: Maidatron Chroma", "Dry Reef - Main"],
	["7Zee lv.10: Advanced Slime Toys", "Dry Reef - Main"],
	["7Zee lv.11: Gingersnap Chroma", "Ancient Ruins Transition"],
	["7Zee lv.11: Peapod Chroma", "Ancient Ruins Transition"],
	["7Zee lv.11: Market Link", "Ancient Ruins Transition"],
	["7Zee lv.12: Grotto Upgrade", "Ancient Ruins Transition"],
	["7Zee lv.13: Decorizer", "Ancient Ruins Transition"],
	["7Zee lv.13: Vanguard Chroma", "Ancient Ruins Transition"],
	["7Zee lv.13: Willow Chroma", "Ancient Ruins Transition"],
	["7Zee lv.14: Slime Trophy I", "Ancient Ruins Transition"],
	["7Zee lv.15: Daybreak Chroma", "Ancient Ruins Transition"],
	["7Zee lv.15: Eventide Chroma", "Ancient Ruins Transition"],
	["7Zee lv.16: Overgrowth Upgrade", "Ancient Ruins - Main"],
	["7Zee lv.17: Salamander Chroma", "Ancient Ruins - Main"],
	["7Zee lv.17: Royalton Chroma", "Ancient Ruins - Main"],
	["7Zee lv.18: Slime Trophy II", "Ancient Ruins - Main"],
	["7Zee lv.19: Neopolitan Chroma", "Ancient Ruins - Main"],
	["7Zee lv.19: Min Chip Chroma", "Ancient Ruins - Main"],
	["7Zee lv.19: Ultra Dash Boots", "Ancient Ruins - Main"],
	["7Zee lv.20: Tank Booster Ultra", "Ancient Ruins - Main"],
	["7Zee lv.20: Master Gordo Snare Blueprint", "Ancient Ruins - Main"],
	["7Zee lv.21: Ghost Wine Chroma", "Ancient Ruins - Main"],
	["7Zee lv.21: Volcanic Chroma", "Ancient Ruins - Main"],
	["7Zee lv.21: Heart Module Ultra", "Ancient Ruins - Main"],
	["7Zee lv.22: Lab Upgrade", "Ancient Ruins - Main"],
	["7Zee lv.22: Golden Sureshot", "Ancient Ruins - Main"],
	["7Zee lv.23: Knight Light Chroma", "Ancient Ruins - Main"],
	["7Zee lv.23: Pretty Loud Chroma", "Ancient Ruins - Main"],
	["7Zee lv.23: Titan Drill Blueprint", "Ancient Ruins - Main"],
	["7Zee lv.24: Slime Trophy III", "Glass Desert - First Half"],
	["7Zee lv.24: Abyssal Pump Blueprint", "Glass Desert - First Half"],
	["7Zee lv.25: Silverfox Chroma", "Glass Desert - First Half"],
	["7Zee lv.25: Frozen Violet Chroma", "Glass Desert - First Half"],
	["7Zee lv.25: Royal Apiary Blueprint", "Glass Desert - First Half"],
	["7Zee lv.26: Docks Upgrade", "Glass Desert - First Half"],
	["7Zee lv.26: Gold Slime Lamp Blueprint", "Glass Desert - First Half"],
	["7Zee lv.27: Goldleaf Chroma", "Glass Desert - First Half"],
	["7Zee lv.27: Astro Pearl Chroma", "Glass Desert - First Half"],
	["7Zee lv.27: Gold Warp Depot Blueprint", "Glass Desert - First Half"],
	["7Zee lv.28: Slime Trophy IV", "Glass Desert - First Half"],
	["7Zee lv.28: Gold Teleporter Blueprint", "Glass Desert - First Half"]
]

gates = [
	["Slime Gate - Dry Reef Beach to Ring Island", "Dry Reef - Ring Island"],
	["Slime Gate - Dry Reef to Moss Blanket", "Moss Blanket - Main"],
	["Slime Gate - Dry Reef to Indigo Quarry", "Indigo Quarry - Before First Bridge"],
	["Slime Gate - Moss Blanket to Ancient Ruins Transition", "Ancient Ruins Transition"],
	["Slime Gate - Indigo Quarry to Ancient Ruins Transition", "Ancient Ruins Transition"],
	["Slime Gate - Ancient Ruins to Glass Desert", "Glass Desert - First Half"],
	["Slime Gate - Glass Desert Central Gate", "Glass Desert - Second Half"],
	["Slime Gate - Glass Desert Lower Gate", "Glass Desert - Second Half"],
	["Slime Gate - Ancient Ruins Transition to Ancient Ruins", "Ancient Ruins - Main"]
]

location_dict = [
	*[items[0] for items in upgrades],
	*[items[0] for items in interactables],
	*[items[0] for items in dlc_interactables],
	*[items[0] for items in corporate_locations],
	*[items[0] for items in gates],
	*[items for items in plorts]
]