import math
from .Locations import *

# File is Auto-generated, see: [https://github.com/SWCreeperKing/ApWorldFactories/tree/master/ApWorldFactories/Games]

def get_rule_map(player, options):
	return {
		"Buy Personal Upgrade (Treasure Cracker lv.1)": lambda state: has_region(state, player, options, "Dry Reef"),
		"Buy Personal Upgrade (Treasure Cracker lv.2)": lambda state: has_region(state, player, options, "Dry Reef"),
		"Buy Personal Upgrade (Treasure Cracker lv.3)": lambda state: has_region(state, player, options, "Dry Reef"),
		"The Grotto - Overlooking the Slime Sea": lambda state: has_cracker(state, player, options, 2),
		"The Lab - Tinkerer's Starting Cache": lambda state: has_cracker(state, player, options, 1),
		"Ogden's Retreat - That's a Whole Lotta Kookabobas": lambda state: has_cracker(state, player, options, 1),
		"Dry Reef - A Darn Good Boot": lambda state: has_jetpack(state, player, options) or get_yaml_option(state, player, options, 'obscure_locations'),
		"Dry Reef - Hidden Behind a Short Wall": lambda state: has_cracker(state, player, options, 1),
		"Dry Reef - Phosphor Gordo's Personal Pod": lambda state: has_cracker(state, player, options, 1),
		"Dry Reef - In the Cliff Tree's Roots": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 1)) or (has_cracker(state, player, options, 1) and get_yaml_option(state, player, options, 'easy_skips')),
		"Dry Reef - Nested by Tabby Gordo": lambda state: has_cracker(state, player, options, 1),
		"Dry Reef - Stony Hen Hen Coop": lambda state: has_cracker(state, player, options, 1),
		"Dry Reef - Hidden Away on an ARCH-ipelago": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 2),
		"Dry Reef - Overlooking the Tarr Hotspot": lambda state: has_cracker(state, player, options, 2) or (has_cracker(state, player, options, 2) and get_yaml_option(state, player, options, 'jetpack_boosts')) or (has_cracker(state, player, options, 2) and get_yaml_option(state, player, options, 'obscure_locations')),
		"Dry Reef - Hidden Crevice Under the Hidden Cliff": lambda state: has_cracker(state, player, options, 3),
		"Dry Reef - Carrot Patch Cache": lambda state: has_cracker(state, player, options, 2),
		"Dry Reef - Tiny Not-Huge Island": lambda state: has_jetpack(state, player, options) or (has_jetpack(state, player, options) and get_yaml_option(state, player, options, 'precise_movement') and get_yaml_option(state, player, options, 'dangerous_skips')),
		"Ring Island - We'd Get Along Just Fine": lambda state: has_jetpack(state, player, options),
		"Ring Island - Flower Viewing on a Cliff": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 1)) or (has_cracker(state, player, options, 1) and get_yaml_option(state, player, options, 'easy_skips')),
		"Ring Island - Perilously Perched Pod": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 2)) or (has_cracker(state, player, options, 2) and get_yaml_option(state, player, options, 'precise_movement')),
		"Ring Island - Hidden on the Backside of the Island": lambda state: has_cracker(state, player, options, 3),
		"Ring Island - King of the Hill": lambda state: has_jetpack(state, player, options) or get_yaml_option(state, player, options, 'easy_skips'),
		"Dry Reef - Hidden in the Shade": lambda state: has_cracker(state, player, options, 1),
		"Dry Reef - Beneath the Wooden Scaffolding": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 2)) or (has_cracker(state, player, options, 2) and get_yaml_option(state, player, options, 'precise_movement')),
		"Ring Island Vault - Don't Get Too Greedy Pod 1": lambda state: has_cracker(state, player, options, 3),
		"Ring Island Vault - Don't Get Too Greedy Pod 2": lambda state: has_cracker(state, player, options, 3),
		"Ring Island Vault - Don't Get Too Greedy Pod 3": lambda state: has_cracker(state, player, options, 3),
		"Ring Island Vault - Don't Get Too Greedy Pod 4": lambda state: has_cracker(state, player, options, 3),
		"Ring Island Vault - The Quintessential Quintuplet #1": lambda state: has_cracker(state, player, options, 3),
		"Ring Island Vault - The Quintessential Quintuplet #2": lambda state: has_cracker(state, player, options, 3),
		"Ring Island Vault - The Quintessential Quintuplet #3": lambda state: has_cracker(state, player, options, 3),
		"Ring Island Vault - The Quintessential Quintuplet #4": lambda state: has_cracker(state, player, options, 3),
		"Ring Island Vault - The Quintessential Quintuplet #5": lambda state: has_cracker(state, player, options, 3),
		"Ring Island Vault - Mushroom Column Riches #1": lambda state: has_cracker(state, player, options, 3),
		"Ring Island Vault - Mushroom Column Riches #2": lambda state: has_cracker(state, player, options, 3),
		"Ring Island Vault - Mushroom Column Riches #3": lambda state: has_cracker(state, player, options, 3),
		"Ring Island Vault - Boring Column Riches #1": lambda state: has_cracker(state, player, options, 3),
		"Ring Island Vault - Boring Column Riches #2": lambda state: has_cracker(state, player, options, 3),
		"The Slime Sea - Island Alone in the Sea": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 2) and has_energy(state, player, options, 3),
		"The Mustache Shrine - Mustache Stache Cache": lambda state: has_cracker(state, player, options, 3),
		"The Slime Sea - On the Giant Tree Stump": lambda state: has_cracker(state, player, options, 3),
		"Indigo Quarry - Crystal Wind Chime": lambda state: has_jetpack(state, player, options) or get_yaml_option(state, player, options, 'easy_skips'),
		"Indigo Quarry - Skate Fast Eat Grass": lambda state: has_cracker(state, player, options, 1),
		"Indigo Quarry - Coral Tube Treasure": lambda state: has_cracker(state, player, options, 1),
		"Indigo Quarry - The Boom Zone": lambda state: has_cracker(state, player, options, 1),
		"Indigo Quarry - Above the Smoke and Ashes": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 2)) or (has_cracker(state, player, options, 2) and get_yaml_option(state, player, options, 'easy_skips')),
		"Indigo Quarry - Personal Puddle Pod": lambda state: has_cracker(state, player, options, 2),
		"Indigo Quarry - Hidden Behind Stalagtmites": lambda state: has_cracker(state, player, options, 3),
		"Indigo Quarry - On a Cliff Before Puddle Lake": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'easy_skips')),
		"Indigo Quarry - Across Hexium Crystal Formations": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3),
		"Indigo Quarry - Under a Hexium Crystal": lambda state: has_cracker(state, player, options, 1),
		"Indigo Quarry - Under Crumbled Scaffolding": lambda state: has_cracker(state, player, options, 2),
		"Indigo Quarry - Slightly Irradiated Reward": lambda state: has_cracker(state, player, options, 2),
		"Indigo Quarry - Through the Radiation Cave": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3),
		"Indigo Quarry - Crystal Cache behind Rickety Bridges": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'precise_movement') and get_yaml_option(state, player, options, 'dangerous_skips')),
		"Ash Isles - Atop a Firey Perch": lambda state: has_cracker(state, player, options, 2),
		"Ash Isles - The Edge of the World": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'precise_movement')),
		"Indigo Quarry - Treasure After the End": lambda state: has_cracker(state, player, options, 2),
		"Ash Isle Vault - The Lone Pod Stands Alone": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - Daniel #1": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - Daniel #2": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - Daniel #3": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - The Cooler Daniel #1": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - The Cooler Daniel #2": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - The Cooler Daniel #3": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - The Cooler Daniel #4": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - The Cooler Daniel #5": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - Golden Rain #1": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - Golden Rain #2": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - Golden Rain #3": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - Golden Rain #4": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - Golden Rain #5": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - Okay Listen, I'm Running Out of Good Names For These Treasure Pods, And They All Look The Same So Hopefully You Can Take This As My Apology #1": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - Okay Listen, I'm Running Out of Good Names For These Treasure Pods, And They All Look The Same So Hopefully You Can Take This As My Apology #2": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - Okay Listen, I'm Running Out of Good Names For These Treasure Pods, And They All Look The Same So Hopefully You Can Take This As My Apology #3": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - The Council Member 1": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - The Council Member 2": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - The Council Member 3": lambda state: has_cracker(state, player, options, 3),
		"Ash Isle Vault - The Council Member 4": lambda state: has_cracker(state, player, options, 3),
		"Moss Blanket - MOSS BLANKET STUCK": lambda state: has_jetpack(state, player, options) or get_yaml_option(state, player, options, 'largo_jumps') or get_yaml_option(state, player, options, 'obscure_locations'),
		"Moss Blanket - Map Data Node": lambda state: has_jetpack(state, player, options) or get_yaml_option(state, player, options, 'easy_skips'),
		"Moss Blanket - Surrounded by Mushrooms": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 1)) or (has_cracker(state, player, options, 1) and get_yaml_option(state, player, options, 'obscure_locations')),
		"Moss Blanket - Flowery Dead End": lambda state: has_cracker(state, player, options, 1),
		"Moss Blanket - Above the Hungry Hungry Largos": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 1)) or (has_cracker(state, player, options, 1) and get_yaml_option(state, player, options, 'precise_movement')),
		"Moss Blanket - In the Honey Heaven": lambda state: has_cracker(state, player, options, 1),
		"Moss Blanket - The Cupboard under the Stairs": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 2)) or (has_cracker(state, player, options, 2) and get_yaml_option(state, player, options, 'largo_jumps')) or (has_cracker(state, player, options, 2) and get_yaml_option(state, player, options, 'obscure_locations')),
		"Moss Blanket - Under the Log River": lambda state: has_cracker(state, player, options, 2),
		"Moss Blanket - Behind a Lonely Mountain": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and has_energy(state, player, options, 2)) or (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and has_energy(state, player, options, 1) and get_yaml_option(state, player, options, 'precise_movement') and get_yaml_option(state, player, options, 'dangerous_skips')),
		"Moss Blanket - In the Roots of a Huge Tree": lambda state: has_cracker(state, player, options, 3),
		"Moss Blanket - Overlooking the Tiny Pond": lambda state: (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'obscure_locations')) or (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)),
		"Moss Blanket - Under the Log Bridge": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'dangerous_skips')),
		"Moss Blanket - Just Under a Ledge": lambda state: has_cracker(state, player, options, 2),
		"Moss Blanket - At the Bottom of a Sheer Wall": lambda state: has_cracker(state, player, options, 2),
		"Moss Blanket - Sunken Treasure": lambda state: has_cracker(state, player, options, 3),
		"Moss Blanket - Off the Unbeaten Path": lambda state: has_jetpack(state, player, options) or (get_yaml_option(state, player, options, 'precise_movement') and get_yaml_option(state, player, options, 'dangerous_skips')),
		"Moss Blanket - Very, Very, Very Tall Tree": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 1) and has_energy(state, player, options, 1)) or (has_jetpack(state, player, options) and has_cracker(state, player, options, 1) and get_yaml_option(state, player, options, 'precise_movement')),
		"Moss Blanket - The Lost Archipelago": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 1),
		"Moss Blanket - The 'Missed the Jump' Crevice": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3),
		"Moss Blanket Vault - The Slime Central's Left-Hand Man": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'precise_movement') and get_yaml_option(state, player, options, 'largo_jumps')),
		"Moss Blanket Vault - The Slime Central's Right-Hand Man": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'precise_movement') and get_yaml_option(state, player, options, 'largo_jumps')),
		"Moss Blanket Vault - What's Left of the Riches #1": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'largo_jumps')),
		"Moss Blanket Vault - What's Left of the Riches #2": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'largo_jumps')),
		"Moss Blanket Vault - What's Right of the Riches #1": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'largo_jumps')),
		"Moss Blanket Vault - What's Right of the Riches #2": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'largo_jumps')),
		"Moss Blanket Vault - A Mountain of Gold #1": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'precise_movement') and get_yaml_option(state, player, options, 'largo_jumps')),
		"Moss Blanket Vault - A Mountain of Gold #2": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'precise_movement') and get_yaml_option(state, player, options, 'largo_jumps')),
		"Moss Blanket Vault - A Mountain of Gold #3": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'precise_movement') and get_yaml_option(state, player, options, 'largo_jumps')),
		"Moss Blanket Vault - A Mountain of Gold #4": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'precise_movement') and get_yaml_option(state, player, options, 'largo_jumps')),
		"Moss Blanket Vault - A Mountain of Gold #5": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'precise_movement') and get_yaml_option(state, player, options, 'largo_jumps')),
		"Ancient Ruins Transition - Slime Buddy": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 2)) or (has_jetpack(state, player, options) and has_cracker(state, player, options, 2) and get_yaml_option(state, player, options, 'precise_movement')),
		"Ancient Ruins - Tree Memorial": lambda state: has_cracker(state, player, options, 1),
		"Ancient Ruins - A Flowery Respite": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 1)) or (has_cracker(state, player, options, 1) and get_yaml_option(state, player, options, 'precise_movement')),
		"Ancient Ruins - Hidden Nook": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 2)) or (has_jetpack(state, player, options) and has_cracker(state, player, options, 2) and get_yaml_option(state, player, options, 'jetpack_boosts')) or (has_cracker(state, player, options, 2) and get_yaml_option(state, player, options, 'largo_jumps')) or (has_cracker(state, player, options, 2) and get_yaml_option(state, player, options, 'precise_movement')),
		"Ancient Ruins - The Hidden Turnabout": lambda state: has_cracker(state, player, options, 2),
		"Ancient Ruins - Caught Up in the Explosion": lambda state: has_cracker(state, player, options, 2),
		"Ancient Ruins - The End of a Long and Arduous Journey": lambda state: has_cracker(state, player, options, 2),
		"Ancient Ruins - In a Crumbled Pile": lambda state: has_cracker(state, player, options, 2),
		"Ancient Ruins - At the End of a Broken Pillar Path": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 2)) or (has_cracker(state, player, options, 2) and get_yaml_option(state, player, options, 'precise_movement')),
		"Ancient Ruins - There's Slimes in the Walls": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3),
		"Ancient Ruins - Collapsed Upper Staircase": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3),
		"Ancient Ruins - The Room With No Door": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'precise_movement')),
		"Ancient Ruins - Shrine Overlooking the Ancient Ruins": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'jetpack_boosts')) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'obscure_locations') and get_yaml_option(state, player, options, 'largo_jumps')),
		"Ancient Ruins - Hidden Nook on a High Up Platform": lambda state: has_cracker(state, player, options, 3),
		"Ancient Ruins - Follow the Sunken Pillars": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'precise_movement') and get_yaml_option(state, player, options, 'obscure_locations')),
		"Glass Desert - Buried Among Rubble": lambda state: has_cracker(state, player, options, 2),
		"Glass Desert - Behind a False Wall": lambda state: has_cracker(state, player, options, 2),
		"Glass Desert - Atop the Pillar before a Chasm": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 2),
		"Glass Desert - Hidden in the Rafters": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 2),
		"Glass Desert - Slime Statue Offering": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and has_energy(state, player, options, 2),
		"Glass Desert - At the Tippy Top of the Highest Mountain": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and has_energy(state, player, options, 3)) or (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and has_energy(state, player, options, 2) and get_yaml_option(state, player, options, 'precise_movement')),
		"Glass Desert - Halfway up a Towering Tower": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and has_energy(state, player, options, 1)) or (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'precise_movement')),
		"Glass Desert - In a High-up Nook": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and has_energy(state, player, options, 1)) or (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'precise_movement')),
		"Glass Desert - Situated on a Collapsed Bridge": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and has_energy(state, player, options, 1)) or (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'precise_movement')),
		"Glass Desert - The Sand Sea": lambda state: has_jetpack(state, player, options),
		"Glass Desert - Down in a Hole": lambda state: has_cracker(state, player, options, 2),
		"Glass Desert - Just Around the Brick Wall": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 2)) or (has_cracker(state, player, options, 2) and get_yaml_option(state, player, options, 'precise_movement')),
		"Glass Desert - Dead-End Forgotten to the World": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 2) and has_energy(state, player, options, 1),
		"Glass Desert - Under the Private Island": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3),
		"Glass Desert - Hiding Behind a Sheer Mountain": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3),
		"Glass Desert - Hover from One Tower to Another": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and has_energy(state, player, options, 1)) or (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'precise_movement')),
		"Glass Desert - Stupidly High Up": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and has_energy(state, player, options, 1)) or (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'precise_movement')),
		"Glass Desert - Ruined Wall On a Cliff": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and has_energy(state, player, options, 1)) or (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'precise_movement')),
		"Glass Desert - In a Supporting Pillar": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3),
		"Glass Desert - Hidden at the Edge of the Sand Sea": lambda state: has_cracker(state, player, options, 3),
		"Glass Desert - At the Base of a Fire Glass Sculpture": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and has_energy(state, player, options, 2),
		"Glass Desert - The Highest Fountain": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3),
		"Glass Desert - Lonely Pillar in the Sand Sea": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and has_energy(state, player, options, 1),
		"Glass Desert - On a Private Island": lambda state: has_jetpack(state, player, options),
		"Glass Desert - Jagged Rock Formation in a Plateu": lambda state: has_jetpack(state, player, options),
		"The Slimeulation - Under a Cliff Bordering The Simulated Sea": lambda state: has_cracker(state, player, options, 2),
		"The Slimeulation - Not Quite Rendered Arch": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 2),
		"The Slimeulation - Just Around the Corner": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 2),
		"The Slimeulation - Blocky Crevice Beside Moss Entrance": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 2),
		"The Slimeulation - Underwater in a Ravine": lambda state: has_cracker(state, player, options, 2),
		"The Slimeulation - Offshoot of a Hazardous Pathway": lambda state: has_cracker(state, player, options, 2),
		"The Slimeulation - Looking Over the Puddle Slimes": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 2),
		"The Slimeulation - Non-Rendered Cliff": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3)) or (has_cracker(state, player, options, 3) and get_yaml_option(state, player, options, 'obscure_locations')),
		"The Slimeulation - Platforming On Blocky Clouds": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3),
		"The Slimeulation - Off The Rendered Path": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3),
		"The Slimeulation - On Top Of The Simulated Winding Path": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3),
		"The Slimeulation - In Between Muhsrooms and Rivers": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3),
		"The Slimeulation - Right Across from the Exit": lambda state: has_jetpack(state, player, options),
		"The Wilds - Across From the Hunter's Sakura Tree": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 1),
		"The Wilds - On a Cliff Dividing Two Entrances": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 1)) or (has_jetpack(state, player, options) and has_cracker(state, player, options, 1) and get_yaml_option(state, player, options, 'jetpack_boosts')) or (has_cracker(state, player, options, 1) and get_yaml_option(state, player, options, 'obscure_locations') and get_yaml_option(state, player, options, 'dangerous_skips')),
		"The Wilds - A Precarious Ledge By the Waterfall": lambda state: has_cracker(state, player, options, 1),
		"The Wilds - An Outcropping Near the Beach": lambda state: has_cracker(state, player, options, 1),
		"The Wilds - Inside a Pink Tree Stump": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 2) and has_energy(state, player, options, 1),
		"The Wilds - Hidden Bridge Behind a Triangular Staircase": lambda state: has_cracker(state, player, options, 2),
		"The Wilds - Double Waterfall Treasure": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3),
		"The Wilds - On a Tiny Ledge Overlooking the Underground River": lambda state: (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and has_energy(state, player, options, 1)) or (has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and has_energy(state, player, options, 1) and get_yaml_option(state, player, options, 'jetpack_boosts')),
		"Nimble Valley - In a Nook on Top of The Final Stretch Arch": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 1) and has_energy(state, player, options, 1),
		"Nimble Valley - Bordering the Slime Sea": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 1),
		"Nimble Valley - Inside the Magneticore Pillar": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 2),
		"Nimble Valley - Floating Outcropping Above a Crevice": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 2) and has_energy(state, player, options, 1),
		"Nimble Valley - Floating Above the Second Stretch": lambda state: has_jetpack(state, player, options) and has_cracker(state, player, options, 3) and has_energy(state, player, options, 2),
		"Nimble Valley - Hidden in some Magneticore Ore": lambda state: has_cracker(state, player, options, 3),
		"Nimble Valley - Overlooking the Beginner Start": lambda state: has_jetpack(state, player, options),
		"Sell a Pink Plort": lambda state: has(state, player, options, "Pink Plort"),
		"Sell a Tabby Plort": lambda state: has(state, player, options, "Tabby Plort"),
		"Sell a Rock Plort": lambda state: has(state, player, options, "Rock Plort"),
		"Sell a Phosphor Plort": lambda state: has(state, player, options, "Phosphor Plort"),
		"Sell a Boom Plort": lambda state: has(state, player, options, "Boom Plort"),
		"Sell a Rad Plort": lambda state: has(state, player, options, "Rad Plort"),
		"Sell a Crystal Plort": lambda state: has(state, player, options, "Crystal Plort"),
		"Sell a Honey Plort": lambda state: has(state, player, options, "Honey Plort"),
		"Sell a Hunter Plort": lambda state: has(state, player, options, "Hunter Plort"),
		"Sell a Quantum Plort": lambda state: has(state, player, options, "Quantum Plort"),
		"Sell a Dervish Plort": lambda state: has(state, player, options, "Dervish Plort"),
		"Sell a Tangle Plort": lambda state: has(state, player, options, "Tangle Plort"),
		"Sell a Mosaic Plort": lambda state: has(state, player, options, "Mosaic Plort"),
		"Sell a Gold Plort": lambda state: has(state, player, options, "Gold Plort"),
		"Sell a Saber Plort": lambda state: has(state, player, options, "Saber Plort"),
		"Sell a Puddle Plort": lambda state: has(state, player, options, "Puddle Plort"),
		"Sell a Fire Plort": lambda state: has(state, player, options, "Fire Plort"),
	}

def get_yaml_option(state, player, options, option) -> bool:
	return options.get_options_map(option).value

def has_amount(state, player, options, item, amount) -> bool:
	return state.has(item, player, amount)

def has(state, player, options, item) -> bool:
	return has_amount(state, player, options, item, 1)

def has_any(state, player, options, items) -> bool:
	return any(has(state, player, options, item) for item in items)

def has_all(state, player, options, items) -> bool:
	return all(has(state, player, options, item) for item in items)

def has_cracker(state, player, options, level) -> bool:
	return has_amount(state, player, options, 'Progressive Treasure Cracker', level)

def has_energy(state, player, options, amount) -> bool:
	return has_amount(state, player, options, 'Progressive Max Energy', amount)

def has_jetpack(state, player, options) -> bool:
	return has(state, player, options, 'Progressive Jetpack')

def has_region(state, player, options, region) -> bool:
	return has(state, player, options, f"Region Unlock: {region}")

def has_gate(state, player, options, gate) -> bool:
	return has(state, player, options, f"Opened Gate: {gate}")