# File is Auto-generated, see: https://github.com/SWCreeperKing/Slimipelago/blob/master/Slimipelago/ApWorldShenanigans.cs

def get_rule_map(player, world):
    return {
        "Treasure Pod - Hidden Cave near Ranch Entry": lambda state: has_cracker(state, player, 3),
		"Treasure Pod - Dry Reef Entrance": lambda state: has_cracker(state, player, 1),
		"Treasure Pod - Dry Reef Arch Island": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Treasure Pod - Next to Slime Gate Ring Isle": lambda state: has_cracker(state, player, 1),
		"Treasure Pod - Under Overgrowth Exit": lambda state: has_cracker(state, player, 2),
		"Treasure Pod - Cliff Near Tabby Slimes": lambda state: has_cracker(state, player, 1),
		"Treasure Pod - Tabby Gordo": lambda state: has_cracker(state, player, 1),
		"Treasure Pod - Phosphor Gordo": lambda state: has_cracker(state, player, 1),
		"Treasure Pod - The Grotto": lambda state: has_cracker(state, player, 2),
		"Treasure Pod - Bridge Behind Indigo Quarry": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Treasure Pod - Alcove Behind Indigo Quarry": lambda state: has_cracker(state, player, 1) and has_jetpack(state, player),
		"Hobson's Note - Cliff Across Indigo Quarry": lambda state: has_jetpack(state, player),
		"Treasure Pod - Middle of Nowhere": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player) and has_energy(state, player, 3),
		"Treasure Pod - Dry Reef Ledge": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Treasure Pod - Moss Blanket Wooden Staircase Escape": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Hobson's Note - Moss Blanket Ledge": lambda state: has_jetpack(state, player),
		"Treasure Pod - Moss Blanket Entrance Cliff": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player),
		"Treasure Pod - Moss Blanket Mushroom Tree Ledge": lambda state: has_cracker(state, player, 1) and has_jetpack(state, player),
		"Treasure Pod - Moss Blanket Flower Bed": lambda state: has_cracker(state, player, 1),
		"Map Fragment - Moss Blanket": lambda state: has_jetpack(state, player),
		"Treasure Pod - Moss Blanket Back Island": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player) and has_energy(state, player, 2),
		"Hobson's Note - Moss Blanket Mushroom Island": lambda state: has_jetpack(state, player),
		"Treasure Pod - Moss Blanket Underwater Pond": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player),
		"Treasure Pod -  Moss Blanket Wooden Ramps": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Treasure Pod - Quarry Cave Stalagmite near Rock Gordo": lambda state: has_cracker(state, player, 3),
		"Treasure Pod - Moss Blanket Ledge Near Flower Area": lambda state: has_cracker(state, player, 1) and has_jetpack(state, player),
		"Treasure Pod - Moss Blanket Flower Area": lambda state: has_cracker(state, player, 1),
		"Treasure Pod - Quarry Cave Grass near Rock Gordo": lambda state: has_cracker(state, player, 1),
		"Hobson's Note - Mushroom Feral Slime Area": lambda state: has_jetpack(state, player),
		"Treasure Pod - Quarry Entryway": lambda state: has_cracker(state, player, 1),
		"Treasure Pod - Quarry Entryway Ledge": lambda state: has_cracker(state, player, 3),
		"Treasure Pod - The Lab": lambda state: has_cracker(state, player, 1),
		"Treasure Pod - Mushroom Feral Slime Big Tree": lambda state: has_cracker(state, player, 1) and has_jetpack(state, player),
		"Treasure Pod - Quarry 3rd Area Coral Columns": lambda state: has_cracker(state, player, 1),
		"Treasure Pod - Crystal Slime Cave Pillar": lambda state: has_cracker(state, player, 2),
		"Treasure Pod - Island Near Hunter Gordo": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player) and has_energy(state, player, 2),
		"Treasure Pod - Underwater After Log Tunnel": lambda state: has_cracker(state, player, 2),
		"Treasure Pod - Through Crystal Slime Cave": lambda state: has_cracker(state, player, 3),
		"Treasure Pod - In the Quarry Pond": lambda state: has_cracker(state, player, 2),
		"Treasure Pod - Moss Blanket Alcove Cliff": lambda state: has_cracker(state, player, 1) and has_jetpack(state, player),
		"Treasure Pod - Alcove Above Moss Teleporter": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player),
		"Treasure Pod - Near Island Teleport Gordo": lambda state: has_cracker(state, player, 1) and has_jetpack(state, player),
		"Treasure Pod - In Quarry Wooden Structure": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Treasure Pod - Northernmost Cliff of Indigo Quarry Mainland": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player),
		"Treasure Pod - Rad Gordo Cave": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Treasure Pod - Cliff Past Rad Gordo": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player),
		"Treasure Pod - Near Quarry Exit Teleporter": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Hobson's Note - Ash Isle": lambda state: has_jetpack(state, player),
		"Treasure Pod - Ash Isle Fireflower Patch": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Treasure Pod - Ash Isle Ledge": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player),
		"Treasure Pod - Ruins Door Puzzle": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Treasure Pod - Moss Blanket Under Log Tunnel": lambda state: has_cracker(state, player, 3),
		"Treasure Pod - Ring Island Flower Patch Cliff": lambda state: has_cracker(state, player, 1) and has_jetpack(state, player),
		"Treasure Pod - Ring Island Brick Wall Ledge": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Treasure Pod - Ring Island Hidden Cave": lambda state: has_cracker(state, player, 3),
		"Hobson's Note - Ring Island": lambda state: has_jetpack(state, player),
		"Treasure Pod - Moss Blanket Under Big Tree": lambda state: has_cracker(state, player, 3),
		"Treasure Pod - Moss Blanket Mushroom Island": lambda state: has_cracker(state, player, 2),
		"Treasure Pod - Ancient Top Floor Alcove": lambda state: has_cracker(state, player, 3),
		"Treasure Pod - Ancient Bottom Floor Cave": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player) and has_energy(state, player, 3),
		"Treasure Pod - Ancient Flower Bed": lambda state: has_cracker(state, player, 1) and has_jetpack(state, player) and has_energy(state, player, 3),
		"Treasure Pod - Ancient Hidden Dungeon": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player) and has_energy(state, player, 2),
		"Treasure Pod - Ancient Bottom Floor Under Tree": lambda state: has_cracker(state, player, 1),
		"Treasure Pod - Ancient Ruins Behind Wall": lambda state: has_cracker(state, player, 2),
		"Treasure Pod - Ancient Ruins In A High Place": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player) and has_energy(state, player, 2),
		"Hobson's Note - Ancient Ruins Back Half Oasis": lambda state: has_jetpack(state, player),
		"Hobson's Note - End of Ancient Ruins": lambda state: has_jetpack(state, player),
		"Treasure Pod - End of Ancient Ruins Bridge Alcove": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player),
		"Treasure Pod - End of Ancient Ruins Complimentary Pod": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Treasure Pod - Ancient Ruins '???'": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Treasure Pod - Boom Gordo": lambda state: has_cracker(state, player, 2),
		"Treasure Pod - On Top of Ancient Ruins": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player) and has_energy(state, player, 2),
		"Treasure Pod - Outside The Desert Teleporter Room": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player),
		"Treasure Pod - Inside The Desert Teleporter Room": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Hobson's Note - Entrance to Glass Desert": lambda state: has_jetpack(state, player),
		"Treasure Pod - Glass Desert On a Rock": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Hobson's Note - Glass Desert Rock Slime Fountain": lambda state: has_jetpack(state, player),
		"Map Fragment - Glass Desert": lambda state: has_jetpack(state, player),
		"Treasure Pod - Desert Fountain Hiding Place": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Treasure Pod - On Top of Glass Desert Entrance": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player) and has_energy(state, player, 3),
		"Treasure Pod - Above Tangle Gordo": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player),
		"Treasure Pod - Glass Desert Cliff Above Secret Style": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player),
		"Treasure Pod - Glass Desert Leftside Ruins": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player),
		"Treasure Pod - Glass Desert Leftside Isle ": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player),
		"Treasure Pod - Edge of Glass Desert Cliff": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player) and has_energy(state, player, 2),
		"Treasure Pod - Glass Desert Cliff Above Tangle Gordo": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player),
		"Treasure Pod - Under Glass Desert Western Ruins": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player),
		"Treasure Pod - Glass Desert Crevasse Pod": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player) and has_energy(state, player, 2),
		"Treasure Pod - Glass Desert Cliff Ruins": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player) and has_energy(state, player, 2),
		"Treasure Pod - Glass Desert Northern Ruins": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Hobson's Note - Glass Desert Northern Courtyard": lambda state: has_jetpack(state, player),
		"Treasure Pod - Glass Desert Western Ruins ": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player),
		"Treasure Pod - Firey Glass Cliff": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player) and has_energy(state, player, 3),
		"Treasure Pod - Glass Desert Western": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player),
		"Treasure Pod - Glass Desert Northern Cliff": lambda state: has_cracker(state, player, 2) and has_jetpack(state, player) and has_energy(state, player, 2),
		"Treasure Pod - Glass Desert Northern Steeple": lambda state: has_cracker(state, player, 3) and has_jetpack(state, player) and has_energy(state, player, 2),
		"Hobson's Note - Glass Desert Northern Ruins": lambda state: has_jetpack(state, player),
		"Hobson's Note - Glass Desert Slime Statue": lambda state: has_jetpack(state, player),
		"Hobson's Note - Doors Like These": lambda state: has_jetpack(state, player),
		"Treasure Pod - Slime Sea Cosmetic (Angelic)": lambda state: has_jetpack(state, player),
		"Treasure Pod - Moss Blanket Cosmetic (Cheshire)": lambda state: has_jetpack(state, player),
		"Treasure Pod - Ring Island Cosmetic (Gilded)": lambda state: has_jetpack(state, player),
		"Treasure Pod - Dry Reef Cosmetic (Tiger)": lambda state: has_jetpack(state, player),
		"Treasure Pod - End of Ancient Ruins Cosmetic (Monochrome)": lambda state: has_jetpack(state, player),
		"Treasure Pod - Glass Desert Cosmetic (Nebula)": lambda state: has_jetpack(state, player),
		"Treasure Pod - Glass Desert Leftside Ruins Secret Style": lambda state: has_jetpack(state, player) and has_energy(state, player, 3),
		"Treasure Pod - Glass Desert Western Secret Style": lambda state: has_jetpack(state, player),
		"Treasure Pod - Glass Desert Northern": lambda state: has_jetpack(state, player),
        "Buy Personal Upgrade (Max Health lv.2)": lambda state: has_region(state, player, "Dry Reef"),
		"Buy Personal Upgrade (Max Health lv.3)": lambda state: has_region(state, player, "Dry Reef"),
		"Buy Personal Upgrade (Max Ammo lv.2)": lambda state: has_region(state, player, "Dry Reef"),
		"Buy Personal Upgrade (Max Ammo lv.3)": lambda state: has_region(state, player, "Dry Reef"),
		"Buy Personal Upgrade (Max Energy lv.2)": lambda state: has_region(state, player, "Dry Reef"),
		"Buy Personal Upgrade (Max Energy lv.3)": lambda state: has_region(state, player, "Dry Reef"),
		"Buy Personal Upgrade (Treasure Cracker lv.1)": lambda state: has_region(state, player, "The Lab") and has_region(state, player, "Indigo Quarry"),
		"Buy Personal Upgrade (Treasure Cracker lv.2)": lambda state: has_region(state, player, "The Lab") and has_region(state, player, "Indigo Quarry"),
		"Buy Personal Upgrade (Treasure Cracker lv.3)": lambda state: has_region(state, player, "The Lab") and has_region(state, player, "Indigo Quarry"),
		"Buy Personal Upgrade (Jetpack Efficiency)": lambda state: has_region(state, player, "Dry Reef"),
        "Buy Personal Upgrade (Max Health lv.4)": lambda state: has_region(state, player, "Indigo Quarry"),
		"Buy Personal Upgrade (Max Ammo lv.4)": lambda state: has_region(state, player, "Indigo Quarry"),
		"Buy Personal Upgrade (Run Efficiency lv.2)": lambda state: has_region(state, player, "Indigo Quarry"),
    }

def has_cracker(state, player, level) -> bool:
    return state.has("Progressive Treasure Cracker", player, level)

def has_energy(state, player, amount) -> bool:
    return state.has("Progressive Max Energy", player, amount) 

def has_jetpack(state, player) -> bool:
    return state.has("Progressive Jetpack", player)
    
def has_region(state, player, region) -> bool:
    return state.has(f"Region Unlock: {region}", player) 