# File is Auto-generated, see: [https://github.com/SWCreeperKing/ApWorldFactories/tree/master/ApWorldFactories/Games]

base_game = [
	["Duck", "Column 1"],
	["Skeleton Duck", "Column 1"],
	["Camo Duck", "Column 1"],
	["Sea Green Duck", "Column 1"],
	["MLG Duck", "Column 1"],
	["Zebra Duck", "Column 2"],
	["Fowl Language Duck", "Column 2"],
	["Submarine Duck", "Column 2"],
	["Arizona Tea Duck", "Column 2"],
	["Moss Duck", "Column 3"],
	["Metallic Pink Duck", "Column 3"],
	["Gay Duck", "Column 3"],
	["Glow in the Duck", "Column 3"],
	["Wireframe Duck", "Column 3"],
	["Wood Duck", "Column 4"],
	["Panda Duck", "Column 4"],
	["Imposter Duck", "Column 4"],
	["Dragon Duck", "Column 4"],
	["Murdurous Duck", "Column 4"],
	["Plaid Duck", "Column 5"],
	["Flower Duck", "Column 5"],
	["Tiger Duck", "Column 5"],
	["Firefighter Duck", "Column 5"],
	["Gold Duck", "Column 5"],
	["Stone Duck", "Column 6"],
	["Lightning Duck", "Column 6"],
	["Black Duck", "Column 6"],
	["Magma Duck", "Column 6"],
	["Graffiti Duck", "Column 6"],
	["Marble Duck", "Column 7"],
	["Cacti Duck", "Column 7"],
	["Space Duck", "Column 7"],
	["Cow Duck", "Column 7"],
	["LSDuck", "Column 7"],
	["Red Duck", "Column 8"],
	["KISS Duck", "Column 8"],
	["Pink Lightning Duck", "Column 8"],
	["Calavera Duck", "Column 8"],
	["Propeller Hat Duck", "Column 9"],
	["Leopard Duck", "Column 9"],
	["Fractured Duck", "Column 9"],
	["Cartoon Duck", "Column 9"],
	["Polka Dot Duck", "Column 10"],
	["Anime Duck", "Column 10"],
	["8-Ball Duck", "Column 10"],
	["Fancy Duck", "Column 10"]
]

ducks_please = [
	["Paper Duck", "Column 1"],
	["Donut Duck", "Column 1"],
	["Unicorn Duck", "Column 1"],
	["Chameleon Duck", "Column 2"],
	["Crystalline Duck", "Column 2"],
	["FBDUCK", "Column 2"],
	["Watermelon Duck", "Column 3"],
	["Egged Duck", "Column 3"],
	["Quackboard Duck", "Column 3"],
	["Negative Duck", "Column 4"],
	["Depressed Duck", "Column 4"],
	["Duck of Hearts", "Column 4"],
	["Potted Duck", "Column 5"],
	["Disco Duck", "Column 5"],
	["China Duck", "Column 5"],
	["Big Head Duck", "Column 6"],
	["Buck", "Column 6"],
	["Baseball Duck", "Column 6"],
	["Strawberry Duck", "Column 7"],
	["Firequacker Duck", "Column 7"],
	["Turbolento Duck", "Column 7"],
	["Sad Duck", "Column 8"],
	["Positive Duck", "Column 8"],
	["Injured Duck", "Column 9"],
	["Tesla Duck", "Column 9"],
	["Sponge Duck", "Column 10"],
	["Scrooge McDuck", "Column 10"]
]

duck_addiction = [
	["Shark Duck", "Column 1"],
	["Matryoshka Duck", "Column 1"],
	["Slim'd Duck", "Column 1"],
	["Tabby Duck", "Column 2"],
	["Overalls Duck", "Column 2"],
	["Bull Duck", "Column 3"],
	["Ship in a Beak-le", "Column 3"],
	["Lancelot Duck", "Column 4"],
	["Ranch Pizza Duck", "Column 4"],
	["Duck of Spades", "Column 4"],
	["Birthday Duck", "Column 5"],
	["Crossword Duck", "Column 5"],
	["Piquackso Duck", "Column 5"],
	["Elvis Quackly", "Column 6"],
	["Shinobi Duck", "Column 6"],
	["CENSORED Duck", "Column 6"],
	["Luchaduck", "Column 7"],
	["Steampunk Duck", "Column 7"],
	["Groovy Duck", "Column 7"],
	["DIY Duck", "Column 8"],
	["Cyber-Duck", "Column 8"],
	["Stamped Duck", "Column 9"],
	["Robo-Duck", "Column 9"],
	["Starry Duck", "Column 10"],
	["Ghost Duck", "Column 10"]
]

so_many_ducks = [
	["Sushi Duck", "Column 1"],
	["Pressure Cooker Duck", "Column 1"],
	["Froggy Duck", "Column 1"],
	["Snail Duck", "Column 2"],
	["Milk Duck", "Column 2"],
	["Puffer-Duck", "Column 2"],
	["Polly Duck", "Column 3"],
	["SW_CreeperDuck", "Column 3"],
	["Disk Drive Duck", "Column 3"],
	["Charlie Duck", "Column 4"],
	["Crypto Duck", "Column 4"],
	["Arcade Duck", "Column 4"],
	["Rainy Duck", "Column 5"],
	["Red Jello Duck", "Column 5"],
	["Retro Duck", "Column 5"],
	["Banana Duck", "Column 6"],
	["Yellow Jello Duck", "Column 6"],
	["Holo-Duck", "Column 6"],
	["Fabriquackted Duck", "Column 7"],
	["Blue Jello Duck", "Column 7"],
	["PJs Duck", "Column 8"],
	["Boxing Duck", "Column 8"],
	["Piggy Bank Duck", "Column 9"],
	["Ladybug Duck", "Column 9"],
	["Thief Duck", "Column 10"],
	["Diver Duck", "Column 10"]
]

ducks_galore = [
	["Tangerine Duck", "Column 1"],
	["Peacock Duck", "Column 1"],
	["Balloon Duck", "Column 1"],
	["Kick-Me Duck", "Column 2"],
	["City Nights Duck", "Column 2"],
	["Pincushion Duck", "Column 2"],
	["Lovely Duck", "Column 3"],
	["Koi Duck", "Column 3"],
	["Gachapon Duck", "Column 3"],
	["Constellation Duck", "Column 4"],
	["Trans Duck", "Column 4"],
	["Tamoduckchi", "Column 4"],
	["Clicker Duck", "Column 5"],
	["Player Duck", "Column 5"],
	["Funi Raccoon Duck", "Column 5"],
	["Caterpillar Duck", "Column 6"],
	["Water Fight Duck", "Column 6"],
	["Neon Duck", "Column 6"],
	["Musicbox Duck", "Column 7"],
	["Octopus Duck", "Column 7"],
	["Kamiquackze Duck", "Column 7"],
	["Flapjack Duck", "Column 8"],
	["Mosaic Duck", "Column 8"],
	["Kawaii Duck", "Column 9"],
	["Fungduck", "Column 9"],
	["Doodle Duck", "Column 10"],
	["Flavored Milk Duck", "Column 10"]
]

ducklings = [
	["Duckling's First Toy", "Column 1"],
	["KISS Duckling", "Column 1"],
	["Math Duckling", "Column 2"],
	["Sad Duckling", "Column 2"],
	["Egged Duckling", "Column 3"],
	["Ice Cream Duckling", "Column 3"],
	["School Duckling", "Column 4"],
	["Bread Duckling", "Column 4"],
	["Bnuuy Duckling", "Column 5"],
	["Annoying Duckling", "Column 5"],
	["Cherry Ducklings", "Column 6"],
	["Sponge Duckling", "Column 7"],
	["HotBeaks Duck", "Column 8"],
	["Real Duckling", "Column 9"],
	["Student Duckling", "Column 10"]
]

location_dict = [
	*[items[0] for items in base_game],
	*[items[0] for items in ducks_please],
	*[items[0] for items in duck_addiction],
	*[items[0] for items in so_many_ducks],
	*[items[0] for items in ducks_galore],
	*[items[0] for items in ducklings]
]