from typing import Dict

locations = [
    "Base Duck",
    "Dragon Duck",
    "Wood Duck",
    "Plaid Duck",
    "Stone Duck",
    "Marble Duck",
    "Submarine Duck",
    "Propeller Hat Duck",
    "Fireman Duck",
    "Lord Duck",
    "Cow Duck",
    "Metallic Pink Duck",
    "Calavera Duck",
    "Flower Duck",
    "Glow Duck",
    "Gold Duck",
    "KISS Duck",
    "Leopard Duck",
    "Manga Duck",
    "Military Duck",
    "Pink Duck",
    "Psychedelic Duck",
    "Imposter Duck",
    "Tiger Duck",
    "Black Duck",
    "Cartoon Duck",
    "Pink Lightning Duck",
    "Fractured Duck",
    "Graffiti Duck",
    "Green Duck",
    "Lava Duck",
    "Lightning Duck",
    "Moss Duck",
    "Red Duck",
    "Zebra Duck",
    "Panda Duck",
    "Sci-Fi Duck",
    "Skeleton Duck",
    "MLG Duck",
    "Knife Duck",
    "Wireframe Duck",
    "Polka Dot Duck",
    "Sakura Duck",
    "Cactus Duck",
    "8-Ball Duck",
    "Alien Duck",
    "Gay Duck",
    "QR Duck",
    "Computer Duck",
    "Computer Mouse Duck",
    "Gamer Duck",
]


columns = [
    ["Base Duck", "Skeleton Duck", "Military Duck", "Green Duck", "MLG Duck"],
    # ["Alien Duck", "Zebra Duck", "Pink Duck", "Submarine Duck", "Sakura Duck"],
    ["Zebra Duck", "Pink Duck", "Submarine Duck", "Sakura Duck"],
    ["Moss Duck", "Metallic Pink Duck", "Gay Duck", "Glow Duck", "Wireframe Duck"],
    ["Wood Duck", "Panda Duck", "Imposter Duck", "Dragon Duck", "Knife Duck"],
    ["Plaid Duck", "Flower Duck", "Tiger Duck", "Fireman Duck", "Gold Duck"],
    ["Stone Duck", "Lightning Duck", "Black Duck", "Lava Duck", "Graffiti Duck"],
    ["Marble Duck", "Cactus Duck", "Sci-Fi Duck", "Cow Duck", "Psychedelic Duck"],
    ["Red Duck", "KISS Duck", "Pink Lightning Duck", "Calavera Duck"],
    ["Propeller Hat Duck", "Leopard Duck", "Fractured Duck", "Cartoon Duck"],
    ["Polka Dot Duck", "Manga Duck", "8-Ball Duck", "Lord Duck"]
]
