import math
from .Locations import *

# File is Auto-generated, see: [https://github.com/SWCreeperKing/ApWorldFactories/tree/master/ApWorldFactories/Games]

def get_rule_map(player, options):
	return {
		"Paper Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Donut Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Unicorn Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Chameleon Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Crystalline Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"FBDUCK": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Watermelon Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Egged Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Quackboard Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Negative Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Depressed Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Duck of Hearts": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Potted Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Disco Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"China Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Big Head Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Buck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Baseball Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Strawberry Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Firequacker Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Turbolento Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Sad Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Positive Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Injured Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Tesla Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Sponge Duck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Scrooge McDuck": lambda state: has(state, player, options, "Ducks Please Ducks"),
		"Shark Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Matryoshka Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Slim'd Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Tabby Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Overalls Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Bull Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Ship in a Beak-le": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Lancelot Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Ranch Pizza Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Duck of Spades": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Birthday Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Crossword Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Piquackso Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Elvis Quackly": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Shinobi Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"CENSORED Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Luchaduck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Steampunk Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Groovy Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"DIY Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Cyber-Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Stamped Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Robo-Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Starry Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Ghost Duck": lambda state: has(state, player, options, "Duck Addiction Ducks"),
		"Sushi Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Pressure Cooker Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Froggy Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Snail Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Milk Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Puffer-Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Polly Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"SW_CreeperDuck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Disk Drive Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Charlie Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Crypto Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Arcade Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Rainy Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Red Jello Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Retro Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Banana Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Yellow Jello Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Holo-Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Fabriquackted Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Blue Jello Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"PJs Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Boxing Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Piggy Bank Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Ladybug Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Thief Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Diver Duck": lambda state: has(state, player, options, "So Many Ducks Ducks"),
		"Tangerine Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Peacock Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Balloon Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Kick-Me Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"City Nights Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Pincushion Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Lovely Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Koi Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Gachapon Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Constellation Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Trans Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Tamoduckchi": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Clicker Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Player Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Funi Raccoon Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Caterpillar Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Water Fight Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Neon Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Musicbox Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Octopus Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Kamiquackze Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Flapjack Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Mosaic Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Kawaii Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Fungduck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Doodle Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Flavored Milk Duck": lambda state: has(state, player, options, "Ducks Galore Ducks"),
		"Duckling's First Toy": lambda state: has(state, player, options, "Ducklings Ducks"),
		"KISS Duckling": lambda state: has(state, player, options, "Ducklings Ducks"),
		"Math Duckling": lambda state: has(state, player, options, "Ducklings Ducks"),
		"Sad Duckling": lambda state: has(state, player, options, "Ducklings Ducks"),
		"Egged Duckling": lambda state: has(state, player, options, "Ducklings Ducks"),
		"Ice Cream Duckling": lambda state: has(state, player, options, "Ducklings Ducks"),
		"School Duckling": lambda state: has(state, player, options, "Ducklings Ducks"),
		"Bread Duckling": lambda state: has(state, player, options, "Ducklings Ducks"),
		"Bnuuy Duckling": lambda state: has(state, player, options, "Ducklings Ducks"),
		"Annoying Duckling": lambda state: has(state, player, options, "Ducklings Ducks"),
		"Cherry Ducklings": lambda state: has(state, player, options, "Ducklings Ducks"),
		"Sponge Duckling": lambda state: has(state, player, options, "Ducklings Ducks"),
		"HotBeaks Duck": lambda state: has(state, player, options, "Ducklings Ducks"),
		"Real Duckling": lambda state: has(state, player, options, "Ducklings Ducks"),
		"Student Duckling": lambda state: has(state, player, options, "Ducklings Ducks"),
	}

def get_yaml_option(state, player, options, option) -> bool:
	return options.get_options_map(option).value

def has_amount(state, player, options, item, amount) -> bool:
	return state.has(item, player, amount)

def has(state, player, options, item) -> bool:
	return has_amount(state, player, options, item, 1)

def has_any(state, player, options, items) -> bool:
	return any(has(state, player, options, item) for item in items)

def has_all(state, player, options, items) -> bool:
	return all(has(state, player, options, item) for item in items)

def has_column(state, player, options, number) -> bool:
	return has_amount(state, player, options, "Progressive Column Unlock", number - 1)