# File is Auto-generated, see: [https://github.com/SWCreeperKing/ApWorldFactories/tree/master/ApWorldFactories/Games]

locations = [
	["Pickup Axe", "Gripp's Hoard"],
	["Pickup Photo #5", "Gripp's Hoard"],
	["Rat Skull #1", "Junk Rivers"],
	["Pickup Cog", "Launch Pad"],
	["Pickup Coal", "Tunnels"],
	["Pickup Photo #3", "Tunnels"],
	["Rat Skull #6", "Tunnels"],
	["Pickup Carrot", "Tunnels"],
	["Pickup Worm Castings", "Tunnels"],
	["Pickup Fancy Button", "Tunnels"],
	["Pickup Coin", "Launch Pad"],
	["Pickup Cute Button", "Garden"],
	["Pickup Feather", "Garden"],
	["Rat Skull #3", "Garden"],
	["Pickup Snail Slime", "Lake Path"],
	["Pickup Photo #2", "Lake Path"],
	["Pickup Valve Handle", "Lake Path"],
	["Pickup Potato Battery", "Lake Path"],
	["Rat Skull #2", "Lake Path"],
	["Pickup Photo #1", "Lake Path"],
	["Pickup Yellow Moss", "Lake Path"],
	["Pickup Spoon", "Mountain"],
	["Rat Skull #7", "Mountain"],
	["Pickup Basic Button", "Mountain"],
	["Pickup Match", "Mountain"],
	["Pickup Maggot", "Mountain"],
	["Rat Skull #8", "Mountain"],
	["Pickup Bone Key", "Mountain"],
	["Pickup Photo #6", "Mountain"],
	["Pickup Magenta Blossom", "Water Gate"],
	["Pickup Fish", "Fisherman's Island"],
	["Pickup Old Key", "Junk Rivers"],
	["Pickup Frying Pan", "Backrooms #1"],
	["Pickup Machete", "Backrooms #2"],
	["Rat Skull #5", "Backrooms #2"],
	["Rat Skull #4", "Garden Cave"],
	["Pickup Cyan Berries", "Garden Cave"],
	["Craft Cyan Pigment", "Garden"],
	["Craft Yellow Pigment", "Garden"],
	["Craft Magenta Pigment", "Garden"],
	["Craft Red Paint", "Water Gate"],
	["Craft Blue Paint", "Water Gate"],
	["Craft Green Paint", "Water Gate"],
	["Pickup Bucket", "Garden"],
	["Milk Beetle", "Launch Pad"],
	["Craft Cooked Fish Dinner", "Mountain"],
	["Pickup Rope", "Lake Path"],
	["Rat Skull #9", "Mountain Top"],
	["Pickup Golden Key", "Mountain Top"],
	["Pickup Cymbal Button", "Mountain Top"],
	["Pickup Dog Treat", "Tunnels Cave"],
	["Pickup Bug Steak", "Tunnels Cave"],
	["Pickup Pacifier", "Tunnels Cave"],
	["Pickup Photo #4", "Tunnels Cave"]
]

location_dict = [
	*[items[0] for items in locations]
]