# File is Auto-generated, see: [https://github.com/SWCreeperKing/ApWorldFactories/tree/master/ApWorldFactories/Games]

quests = [
	["A Warm Welcome", "Sanctum"],
	["Communing Catacombs", "Sanctum"],
	["Diva Must Die", "Sanctum"],
	["The Keep Within", "Sanctum"],
	["Tethering Grove", "Sanctum"],
	["The Glyphik Booklet", "Sanctum"],
	["Cleaning Terrace", "Sanctum"],
	["Ancient Beings", "Sanctum"],
	["Wicked Wizboars", "Sanctum"],
	["Spiraling In The Grove", "Sanctum"],
	["Hell In The Grove", "Sanctum"],
	["Nulversa Magica", "Sanctum"],
	["Finding Ammagon", "Sanctum"],
	["The Colossus", "Sanctum"],
	["Night Spirits", "Sanctum"],
	["Ridding Slimes", "Sanctum"],
	["Huntin' Hogs", "Sanctum"],
	["Purging the Grove", "Sanctum"],
	["Cleansing the Grove", "Sanctum"],
	["Nulversa Viscera", "Sanctum"],
	["Call of Fury", "Sanctum"],
	["Mastery of Strength", "Sanctum"],
	["Beckoning Foes", "Sanctum"],
	["Ghostly Goods", "Sanctum"],
	["Makin' a Mekspear", "Sanctum"],
	["Makin' a Wizwand", "Sanctum"],
	["Makin' a Vile Blade", "Sanctum"],
	["Makin' a Golem Chestpiece", "Sanctum"],
	["Makin' a Ragespear", "Sanctum"],
	["Makin' a Monolith Chestpiece", "Sanctum"],
	["Makin' a Firebreath Blade", "Sanctum"],
	["Makin' a Follycannon", "Sanctum"],
	["Summore' Spectral Powder!", "Sanctum"],
	["Makin' More Mekspears", "Sanctum"],
	["Makin' More Wizwands", "Sanctum"],
	["Makin' More Vile Blades", "Sanctum"],
	["Summore' Golem Chestpieces", "Sanctum"],
	["Makin' More Ragespears", "Sanctum"],
	["Summore' Monolith Chestpieces", "Sanctum"],
	["Nulversa, Greenversa!", "Sanctum"],
	["Summore' Firebreath Blades", "Sanctum"],
	["Makin' More Follycannons", "Sanctum"],
	["Focusin' in", "Sanctum"],
	["Mastery of Dexterity", "Sanctum"],
	["Whatta' Rush!", "Sanctum"],
	["The Voice of Zuulneruda", "Arcwood Pass"],
	["Killing Tomb", "Arcwood Pass"],
	["Purging the Undead", "Arcwood Pass"],
	["Rattlecage Rage", "Arcwood Pass"],
	["Consumed Madness", "Arcwood Pass"],
	["Eradicating the Undead", "Arcwood Pass"],
	["Reviling the Rageboars", "Bularr Fortress"],
	["Gatling Galius", "Bularr Fortress"],
	["Reviling more Rageboars", "Bularr Fortress"],
	["Facing Foes", "Bularr Fortress"],
	["The Gall of Galius", "Bularr Fortress"],
	["Up and Over It", "Wall of the Stars"],
	["Dense Ingots", "Sanctum"],
	["Amberite Ingots", "Sanctum"],
	["Sapphite Ingots", "Sanctum"]
]

levels = [
	["Reach Level 2", "Menu"],
	["Reach Level 4", "Menu"],
	["Reach Level 6", "Menu"],
	["Reach Level 8", "Menu"],
	["Reach Level 10", "Menu"],
	["Reach Level 12", "Menu"],
	["Reach Level 14", "Menu"],
	["Reach Level 16", "Menu"],
	["Reach Level 18", "Menu"],
	["Reach Level 20", "Menu"],
	["Reach Level 22", "Menu"],
	["Reach Level 24", "Menu"],
	["Reach Level 26", "Menu"],
	["Reach Level 28", "Menu"],
	["Reach Level 30", "Menu"],
	["Reach Level 32", "Menu"]
]

merchants = [
	["Buy Item #1 from Sally's Nook", "Sanctum"],
	["Buy Item #2 from Sally's Nook", "Sanctum"],
	["Buy Item #3 from Sally's Nook", "Sanctum"],
	["Buy Item #4 from Sally's Nook", "Sanctum"],
	["Buy Item #5 from Sally's Nook", "Sanctum"],
	["Buy Item #1 from Skrit's Sikrit Market", "Sanctum"],
	["Buy Item #2 from Skrit's Sikrit Market", "Sanctum"],
	["Buy Item #3 from Skrit's Sikrit Market", "Sanctum"],
	["Buy Item #4 from Skrit's Sikrit Market", "Sanctum"],
	["Buy Item #5 from Skrit's Sikrit Market", "Sanctum"],
	["Buy Item #1 from Frankie's Goods", "Arcwood Pass"],
	["Buy Item #2 from Frankie's Goods", "Arcwood Pass"],
	["Buy Item #3 from Frankie's Goods", "Arcwood Pass"],
	["Buy Item #4 from Frankie's Goods", "Arcwood Pass"],
	["Buy Item #5 from Frankie's Goods", "Arcwood Pass"],
	["Buy Item #1 from Craig's Bazzar", "Wall of the Stars"],
	["Buy Item #2 from Craig's Bazzar", "Wall of the Stars"],
	["Buy Item #3 from Craig's Bazzar", "Wall of the Stars"],
	["Buy Item #4 from Craig's Bazzar", "Wall of the Stars"],
	["Buy Item #5 from Craig's Bazzar", "Wall of the Stars"],
	["Buy Item #1 from Dye Merchant", "Sanctum"],
	["Buy Item #2 from Dye Merchant", "Sanctum"],
	["Buy Item #3 from Dye Merchant", "Sanctum"],
	["Buy Item #4 from Dye Merchant", "Sanctum"],
	["Buy Item #5 from Dye Merchant", "Sanctum"],
	["Buy Item #1 from Tesh's Wares", "Sanctum Catacombs lvl 2"],
	["Buy Item #2 from Tesh's Wares", "Sanctum Catacombs lvl 2"],
	["Buy Item #3 from Tesh's Wares", "Sanctum Catacombs lvl 2"],
	["Buy Item #4 from Tesh's Wares", "Sanctum Catacombs lvl 2"],
	["Buy Item #5 from Tesh's Wares", "Sanctum Catacombs lvl 2"],
	["Buy Item #1 from Nesh's Wares", "Sanctum Catacombs lvl 3"],
	["Buy Item #2 from Nesh's Wares", "Sanctum Catacombs lvl 3"],
	["Buy Item #3 from Nesh's Wares", "Sanctum Catacombs lvl 3"],
	["Buy Item #4 from Nesh's Wares", "Sanctum Catacombs lvl 3"],
	["Buy Item #5 from Nesh's Wares", "Sanctum Catacombs lvl 3"],
	["Buy Item #1 from Rikko's Treasures", "Cresent Grove lvl 1"],
	["Buy Item #2 from Rikko's Treasures", "Cresent Grove lvl 1"],
	["Buy Item #3 from Rikko's Treasures", "Cresent Grove lvl 1"],
	["Buy Item #4 from Rikko's Treasures", "Cresent Grove lvl 1"],
	["Buy Item #5 from Rikko's Treasures", "Cresent Grove lvl 1"],
	["Buy Item #1 from Cotoo's Treasures", "Cresent Grove lvl 2"],
	["Buy Item #2 from Cotoo's Treasures", "Cresent Grove lvl 2"],
	["Buy Item #3 from Cotoo's Treasures", "Cresent Grove lvl 2"],
	["Buy Item #4 from Cotoo's Treasures", "Cresent Grove lvl 2"],
	["Buy Item #5 from Cotoo's Treasures", "Cresent Grove lvl 2"],
	["Buy Item #1 from Ruka's Furnace", "Sanctum"],
	["Buy Item #2 from Ruka's Furnace", "Sanctum"],
	["Buy Item #3 from Ruka's Furnace", "Sanctum"],
	["Buy Item #4 from Ruka's Furnace", "Sanctum"],
	["Buy Item #5 from Ruka's Furnace", "Sanctum"],
	["Buy Item #1 from Torta's Fishing Shack", "Sanctum"],
	["Buy Item #2 from Torta's Fishing Shack", "Sanctum"],
	["Buy Item #3 from Torta's Fishing Shack", "Sanctum"],
	["Buy Item #4 from Torta's Fishing Shack", "Sanctum"],
	["Buy Item #5 from Torta's Fishing Shack", "Sanctum"],
	["Buy Item #1 from Mad Statue's Gift", "Sanctum"],
	["Buy Item #2 from Mad Statue's Gift", "Sanctum"],
	["Buy Item #3 from Mad Statue's Gift", "Sanctum"],
	["Buy Item #4 from Mad Statue's Gift", "Sanctum"],
	["Buy Item #5 from Mad Statue's Gift", "Sanctum"]
]

professions = [
	["Fishing Lv. 1", "Menu"],
	["Fishing Lv. 2", "Menu"],
	["Fishing Lv. 3", "Menu"],
	["Fishing Lv. 4", "Menu"],
	["Fishing Lv. 5", "Menu"],
	["Fishing Lv. 6", "Menu"],
	["Fishing Lv. 7", "Menu"],
	["Fishing Lv. 8", "Menu"],
	["Fishing Lv. 9", "Menu"],
	["Fishing Lv. 10", "Menu"],
	["Mining Lv. 1", "Menu"],
	["Mining Lv. 2", "Menu"],
	["Mining Lv. 3", "Menu"],
	["Mining Lv. 4", "Menu"],
	["Mining Lv. 5", "Menu"],
	["Mining Lv. 6", "Menu"],
	["Mining Lv. 7", "Menu"],
	["Mining Lv. 8", "Menu"],
	["Mining Lv. 9", "Menu"],
	["Mining Lv. 10", "Menu"]
]

achievements = [
	["A New Journey", "Sanctum"],
	["Clearing Catacombs (1-6)", "Sanctum Catacombs lvl 1"],
	["Clearing Catacombs (6-12)", "Sanctum Catacombs lvl 2"],
	["Becoming a Fighter", "Sanctum"],
	["Becoming a Mystic", "Sanctum"],
	["Becoming a Bandit", "Sanctum"],
	["Clearing Catacombs (12-18)", "Sanctum Catacombs lvl 3"],
	["Clearing Grove (15-20)", "Cresent Grove lvl 1"],
	["Clearing Grove (20-25)", "Cresent Grove lvl 2"],
	["Judgement", "Sanctum"],
	["Corrupted Arcana", "Sanctum"],
	["Holier than Thou", "Sanctum"],
	["Altered Vision", "Sanctum"],
	["Scaling the Tower", "Sanctum"],
	["Scaling Stars", "Trial of the Stars"],
	["Rude!", "Sanctum"]
]

location_dict = [
	*[items[0] for items in quests],
	*[items[0] for items in levels],
	*[items[0] for items in merchants],
	*[items[0] for items in professions],
	*[items[0] for items in achievements]
]

location_grind_data = [
	["Sanctum", 0, 0],
	["Outer Sanctum", 1, 4],
	["Arcwood Pass", 1, 4],
	["Effold Terrace", 1, 10],
	["Tuul Valley", 8, 14],
	["Sanctum Catacombs lvl 1", 1, 6],
	["Sanctum Catacombs lvl 2", 6, 12],
	["Sanctum Catacombs lvl 3", 12, 18],
	["Cresent Road", 8, 14],
	["Tuul Enclave", 13, 16],
	["Luvora Garden", 13, 18],
	["Cresent Keep", 8, 13],
	["Bularr Fortress", 17, 26],
	["Cresent Grove lvl 1", 15, 20],
	["Cresent Grove lvl 2", 20, 25],
	["Gate of the Moon", 0, 0],
	["Wall of the Stars", 0, 0],
	["Redwoud", 26, 30],
	["Trial of the Stars", 0, 0]
]

fishing_grind_data = [
	["Sanctum", 1, 3],
	["Arcwood Pass", 3, 6],
	["Cresent Road", 6, 10]
]

mining_grind_data = [
	["Arcwood Pass", 1, 2],
	["Effold Terrace", 1, 2],
	["Arcwood Pass", 2, 3],
	["Effold Terrace", 2, 3],
	["Outer Sanctum", 2, 3],
	["Cresent Keep", 2, 3],
	["Tuul Enclave", 2, 3],
	["Tuul Valley", 3, 6],
	["Cresent Keep", 3, 6],
	["Tuul Enclave", 6, 10]
]

enemy_data = {
	"Lesser Wisp": [1, ["Outer Sanctum", "Arcwood Pass", "Sanctum Catacombs lvl 1"]],
	"Slime": [1, ["Outer Sanctum", "Arcwood Pass", "Effold Terrace"]],
	"Tar Spawn": [3, ["Effold Terrace", "Tuul Valley"]],
	"Greater Wisp": [4, ["Arcwood Pass", "Effold Terrace", "Sanctum Catacombs lvl 1", "Sanctum Catacombs lvl 2"]],
	"Mini Geist": [4, ["Sanctum Catacombs lvl 1", "Cresent Road", "Cresent Keep"]],
	"Slimek": [5, ["Effold Terrace"]],
	"Deathgel": [6, ["Sanctum Catacombs lvl 2"]],
	"Geist": [7, ["Sanctum Catacombs lvl 1", "Sanctum Catacombs lvl 2", "Sanctum Catacombs lvl 3"]],
	"Mekboar": [8, ["Tuul Valley", "Cresent Keep"]],
	"Mini Golem": [8, ["Cresent Road", "Cresent Keep"]],
	"Toxin": [8, ["Sanctum Catacombs lvl 2", "Sanctum Catacombs lvl 3"]],
	"Blightwood": [9, ["Cresent Road", "Cresent Keep"]],
	"Mouth": [10, ["Cresent Road", "Cresent Keep"]],
	"Golem": [12, ["Cresent Road", "Cresent Keep"]],
	"Hellsludge": [13, ["Sanctum Catacombs lvl 3"]],
	"Klamkull": [13, ["Arcwood Pass", "Cresent Road"]],
	"Wizboar": [13, ["Tuul Valley", "Tuul Enclave", "Cresent Keep"]],
	"Miasma": [14, ["Sanctum Catacombs lvl 3"]],
	"Vout": [14, ["Tuul Enclave"]],
	"Deadwood": [15, ["Cresent Grove lvl 1"]],
	"Stezza": [16, ["Cresent Grove lvl 1"]],
	"Alshar": [16, ["Cresent Grove lvl 1"]],
	"Blue Minichroom": [16, ["Cresent Grove lvl 1"]],
	"Red Minichroom": [16, ["Cresent Grove lvl 1"]],
	"Rageboar": [17, ["Bularr Fortress"]],
	"Maw": [17, ["Cresent Grove lvl 1"]],
	"Mandragora": [18, ["Luvora Garden"]],
	"Gale Muchroom": [20, ["Cresent Grove lvl 2"]],
	"Aqua Muchroom": [20, ["Cresent Grove lvl 2"]],
	"Firebreath": [24, ["Cresent Grove lvl 2"]],
	"Sinroot": [30, ["Redwoud"]],
	"Poltergeist": [16, ["Sanctum Catacombs lvl 3"]],
	"Vultia": [16, ["Tuul Enclave"]],
	"Boomboar": [18, ["Bularr Fortress"]],
	"Carbuncle": [18, ["Cresent Grove lvl 1"]],
	"Monolith": [19, ["Cresent Grove lvl 1"]],
	"Nagrath": [20, ["Cresent Grove lvl 2"]],
	"Barknaught": [22, ["Cresent Grove lvl 2"]],
	"Warboar": [23, ["Bularr Fortress"]],
	"Sirius": [23, ["Cresent Grove lvl 2"]],
	"Death Knight": [24, ["Cresent Grove lvl 2"]],
	"Demigolem": [24, ["Cresent Grove lvl 2"]],
	"Biggun": [4, ["Arcwood Pass"]],
	"Nograd": [4, ["Arcwood Pass"]],
	"Rokkamek": [14, ["Tuul Valley"]],
	"Dolkin": [14, ["Arcwood Pass"]],
	"Gahool": [15, ["Tuul Valley"]],
	"Kruole": [21, ["Tuul Enclave"]],
	"Slime Diva": [10, ["Effold Terrace"]],
	"Lord Zuulneruda": [12, ["Sanctum Catacombs lvl 2"]],
	"Lord Kaluuz": [18, ["Sanctum Catacombs lvl 3"]],
	"Colossus": [20, ["Cresent Grove lvl 1"]],
	"Valdur": [25, ["Cresent Grove lvl 2"]],
	"Galius": [26, ["Bularr Fortress"]]
}

portal_counts = {
	"Sanctum": 0,
	"Outer Sanctum": 1,
	"Arcwood Pass": 2,
	"Effold Terrace": 4,
	"Tuul Valley": 5,
	"Sanctum Catacombs lvl 1": 3,
	"Sanctum Catacombs lvl 2": 3,
	"Sanctum Catacombs lvl 3": 3,
	"Cresent Road": 6,
	"Tuul Enclave": 9,
	"Luvora Garden": 7,
	"Cresent Keep": 8,
	"Bularr Fortress": 11,
	"Cresent Grove lvl 1": 10,
	"Cresent Grove lvl 2": 10,
	"Gate of the Moon": 0,
	"Wall of the Stars": 0,
	"Redwoud": 0,
	"Trial of the Stars": 0
}