# File is Auto-generated, see: [https://github.com/SWCreeperKing/ApWorldFactories/tree/master/ApWorldFactories/Games]

levels = [
	"Reach Level 2",
	"Reach Level 4",
	"Reach Level 6",
	"Reach Level 8",
	"Reach Level 10",
	"Reach Level 12",
	"Reach Level 14",
	"Reach Level 16",
	"Reach Level 18",
	"Reach Level 20",
	"Reach Level 22",
	"Reach Level 24",
	"Reach Level 26",
	"Reach Level 28",
	"Reach Level 30",
	"Reach Level 32"
]

quests = [
	["A Warm Welcome", "Sanctum"],
	["Communing Catacombs", "Sanctum"],
	["Diva Must Die", "Sanctum"],
	["The Keep Within", "Sanctum"],
	["Tethering Grove", "Sanctum"],
	["The Glyphik Booklet", "Sanctum"],
	["Cleaning Terrace", "Sanctum"],
	["Ancient Beings", "Sanctum"],
	["Wicked Wizboars", "Sanctum"],
	["Spiraling In The Grove", "Sanctum"],
	["Hell In The Grove", "Sanctum"],
	["Nulversa Magica", "Sanctum"],
	["Finding Ammagon", "Sanctum"],
	["The Colossus", "Sanctum"],
	["Night Spirits", "Sanctum"],
	["Ridding Slimes", "Sanctum"],
	["Huntin' Hogs", "Sanctum"],
	["Purging the Grove", "Sanctum"],
	["Cleansing the Grove", "Sanctum"],
	["Nulversa Viscera", "Sanctum"],
	["Call of Fury", "Sanctum"],
	["Mastery of Strength", "Sanctum"],
	["Beckoning Foes", "Sanctum"],
	["Ghostly Goodes", "Sanctum"],
	["Makin' a Mekspear", "Sanctum"],
	["Makin' a Wizwand", "Sanctum"],
	["Makin' a Vile Blade", "Sanctum"],
	["Makin' a Golem Chestpiece", "Sanctum"],
	["Makin' a Ragespear", "Sanctum"],
	["Makin' a Monolith Chestpiece", "Sanctum"],
	["Makin' a Firebreath Blade", "Sanctum"],
	["Makin' a Follycannon", "Sanctum"],
	["Summore' Spectral Powder!", "Sanctum"],
	["Makin' More Mekspears", "Sanctum"],
	["Makin' More Wizwands", "Sanctum"],
	["Makin' More Vile Blades", "Sanctum"],
	["Summore' Golem Chestpieces", "Sanctum"],
	["Makin' More Ragespears", "Sanctum"],
	["Summore' Monolith Chestpieces", "Sanctum"],
	["Nulversa, Greenversa!", "Sanctum"],
	["Summore' Firebreath Blades", "Sanctum"],
	["Makin' More Follycannons", "Sanctum"],
	["Focusin' in", "Sanctum"],
	["Mastery of Dexterity", "Sanctum"],
	["Whatta' Rush!", "Sanctum"],
	["The Voice of Zuulneruda", "Arcwood Pass"],
	["Killing Tomb", "Arcwood Pass"],
	["Purging the Undead", "Arcwood Pass"],
	["Rattlecage Rage", "Arcwood Pass"],
	["Consumed Madness", "Arcwood Pass"],
	["Eradicating the Undead", "Arcwood Pass"],
	["Reviling the Rageboars", "Bularr Fortress"],
	["Gatling Galius", "Bularr Fortress"],
	["Reviling more Rageboars", "Bularr Fortress"],
	["Facing Foes", "Bularr Fortress"],
	["The Gall of Galius", "Bularr Fortress"],
	["Up and Over It", "Wall of the Stars"],
	["Dense Ingots", "Sanctum"],
	["Amberite Ingots", "Sanctum"],
	["Sapphite Ingots", "Sanctum"]
]

merchants = [
	["Buy Item #1 from Sally's Nook", "Sanctum"],
	["Buy Item #2 from Sally's Nook", "Sanctum"],
	["Buy Item #3 from Sally's Nook", "Sanctum"],
	["Buy Item #4 from Sally's Nook", "Sanctum"],
	["Buy Item #5 from Sally's Nook", "Sanctum"],
	["Buy Item #1 from Skrit's Sikrit Market", "Sanctum"],
	["Buy Item #2 from Skrit's Sikrit Market", "Sanctum"],
	["Buy Item #3 from Skrit's Sikrit Market", "Sanctum"],
	["Buy Item #4 from Skrit's Sikrit Market", "Sanctum"],
	["Buy Item #5 from Skrit's Sikrit Market", "Sanctum"],
	["Buy Item #1 from Frankie's Goods", "Arcwood Pass"],
	["Buy Item #2 from Frankie's Goods", "Arcwood Pass"],
	["Buy Item #3 from Frankie's Goods", "Arcwood Pass"],
	["Buy Item #4 from Frankie's Goods", "Arcwood Pass"],
	["Buy Item #5 from Frankie's Goods", "Arcwood Pass"],
	["Buy Item #1 from Craig's Bazzar", "Wall of the Stars"],
	["Buy Item #2 from Craig's Bazzar", "Wall of the Stars"],
	["Buy Item #3 from Craig's Bazzar", "Wall of the Stars"],
	["Buy Item #4 from Craig's Bazzar", "Wall of the Stars"],
	["Buy Item #5 from Craig's Bazzar", "Wall of the Stars"],
	["Buy Item #1 from Dye Merchant", "Sanctum"],
	["Buy Item #2 from Dye Merchant", "Sanctum"],
	["Buy Item #3 from Dye Merchant", "Sanctum"],
	["Buy Item #4 from Dye Merchant", "Sanctum"],
	["Buy Item #5 from Dye Merchant", "Sanctum"],
	["Buy Item #1 from Tesh's Wares", "Sanctum Catacombs lvl 2"],
	["Buy Item #2 from Tesh's Wares", "Sanctum Catacombs lvl 2"],
	["Buy Item #3 from Tesh's Wares", "Sanctum Catacombs lvl 2"],
	["Buy Item #4 from Tesh's Wares", "Sanctum Catacombs lvl 2"],
	["Buy Item #5 from Tesh's Wares", "Sanctum Catacombs lvl 2"],
	["Buy Item #1 from Nesh's Wares", "Sanctum Catacombs lvl 3"],
	["Buy Item #2 from Nesh's Wares", "Sanctum Catacombs lvl 3"],
	["Buy Item #3 from Nesh's Wares", "Sanctum Catacombs lvl 3"],
	["Buy Item #4 from Nesh's Wares", "Sanctum Catacombs lvl 3"],
	["Buy Item #5 from Nesh's Wares", "Sanctum Catacombs lvl 3"],
	["Buy Item #1 from Rikko's Treasures", "Cresent Grove lvl 1"],
	["Buy Item #2 from Rikko's Treasures", "Cresent Grove lvl 1"],
	["Buy Item #3 from Rikko's Treasures", "Cresent Grove lvl 1"],
	["Buy Item #4 from Rikko's Treasures", "Cresent Grove lvl 1"],
	["Buy Item #5 from Rikko's Treasures", "Cresent Grove lvl 1"],
	["Buy Item #1 from Cotoo's Treasures", "Cresent Grove lvl 2"],
	["Buy Item #2 from Cotoo's Treasures", "Cresent Grove lvl 2"],
	["Buy Item #3 from Cotoo's Treasures", "Cresent Grove lvl 2"],
	["Buy Item #4 from Cotoo's Treasures", "Cresent Grove lvl 2"],
	["Buy Item #5 from Cotoo's Treasures", "Cresent Grove lvl 2"],
	["Buy Item #1 from Ruka's Furnace", "Sanctum"],
	["Buy Item #2 from Ruka's Furnace", "Sanctum"],
	["Buy Item #3 from Ruka's Furnace", "Sanctum"],
	["Buy Item #4 from Ruka's Furnace", "Sanctum"],
	["Buy Item #5 from Ruka's Furnace", "Sanctum"],
	["Buy Item #1 from Torta's Fishing Shack", "Sanctum"],
	["Buy Item #2 from Torta's Fishing Shack", "Sanctum"],
	["Buy Item #3 from Torta's Fishing Shack", "Sanctum"],
	["Buy Item #4 from Torta's Fishing Shack", "Sanctum"],
	["Buy Item #5 from Torta's Fishing Shack", "Sanctum"],
	["Buy Item #1 from Mad Statue's Gift", "Sanctum"],
	["Buy Item #2 from Mad Statue's Gift", "Sanctum"],
	["Buy Item #3 from Mad Statue's Gift", "Sanctum"],
	["Buy Item #4 from Mad Statue's Gift", "Sanctum"],
	["Buy Item #5 from Mad Statue's Gift", "Sanctum"]
]

location_dict = [
	*[items[0] for items in quests],
	*[items for items in levels],
	*[items[0] for items in merchants]
]

location_grind_data = [
	["Sanctum", 0, 0],
	["Outer Sanctum", 1, 4],
	["Arcwood Pass", 1, 4],
	["Effold Terrace", 1, 10],
	["Tuul Valley", 8, 14],
	["Sanctum Catacombs lvl 1", 1, 6],
	["Sanctum Catacombs lvl 2", 6, 12],
	["Sanctum Catacombs lvl 3", 12, 18],
	["Cresent Road", 8, 14],
	["Tuul Enclave", 13, 16],
	["Luvora Garden", 13, 18],
	["Cresent Keep", 8, 13],
	["Bularr Fortress", 17, 26],
	["Cresent Grove lvl 1", 15, 20],
	["Cresent Grove lvl 2", 20, 25],
	["Gate of the Moon", 0, 0],
	["Wall of the Stars", 0, 0],
	["Redwoud", 30, 30],
	["Trial of the Stars", 0, 0]
]

fishing_grind_data = [
	["Sanctum", 1, 3],
	["Arcwood Pass", 3, 6],
	["Cresent Road", 6, 10]
]

mining_grind_data = [
	["Arcwood Pass", 1, 2],
	["Effold Terrace", 1, 2],
	["Arcwood Pass", 2, 3],
	["Effold Terrace", 2, 3],
	["Outer Sanctum", 2, 3],
	["Cresent Keep", 2, 3],
	["Tuul Enclave", 2, 3],
	["Tuul Valley", 3, 6],
	["Cresent Keep", 3, 6],
	["Tuul Enclave", 6, 10]
]