from BaseClasses import ItemClassification
from .Locations import *
from .Options import *

# File is Auto-generated, see: [No Link Given]

progressive_tier = {
	"Progressive Tier": 12
}

item_table = {
	"Motivational Poster": ItemClassification.filler,
	**{item: ItemClassification.progression for item in progressive_tier},
	"Tier 1 Mastery": ItemClassification.filler,
	"Frame Relocation": ItemClassification.filler,
	"Fortress": ItemClassification.filler,
	"Tier 2 Mastery": ItemClassification.filler,
	"Iron-rich Rocks": ItemClassification.filler,
	"High Heat Density": ItemClassification.filler,
	"Widget Twins": ItemClassification.filler,
	"Cancel All Construction": ItemClassification.filler,
	"Tier 3 Mastery": ItemClassification.filler,
	"Area Move": ItemClassification.filler,
	"Coordinated Logistics": ItemClassification.filler,
	"Napalm Charge": ItemClassification.filler,
	"Beach Harvest": ItemClassification.filler,
	"Molten Conveyor System": ItemClassification.filler,
	"Discerning Vision": ItemClassification.filler,
	"Tier 4 Mastery": ItemClassification.filler,
	"Upgrade Status": ItemClassification.filler,
	"Peat Oil Processing": ItemClassification.filler,
	"Power Plant Logistics": ItemClassification.filler,
	"Direct Glass Insertion": ItemClassification.filler,
	"Glass Grinding Wheel": ItemClassification.filler,
	"Industrial Capacity": ItemClassification.filler,
	"Tier 5 Mastery": ItemClassification.filler,
	"Giant Rock Crusher": ItemClassification.filler,
	"Hydrophobia": ItemClassification.filler,
	"Dedicated Battery Inserters": ItemClassification.filler,
	"Perfectly Balanced Spinner": ItemClassification.filler,
	"Turbo Blast Furnace": ItemClassification.filler,
	"Tier 6 Mastery": ItemClassification.filler,
	"The Factory Must Grow": ItemClassification.filler,
	"Chain Lightning": ItemClassification.filler,
	"Introvert": ItemClassification.filler,
	"Shortened Transfer Tube": ItemClassification.filler,
	"Agoraphobia": ItemClassification.filler,
	"Standalone": ItemClassification.filler,
	"Exhaust Vent Recycler": ItemClassification.filler,
	"Rapid Heat Exchanger (Battery)": ItemClassification.filler,
	"Rapid Heat Exchanger (Glass)": ItemClassification.filler,
	"Double-stacked Conveyors": ItemClassification.filler,
	"Productivity Optimization Node": ItemClassification.filler,
	"Tier 7 Mastery": ItemClassification.filler,
	"Monocrystalline": ItemClassification.filler,
	"Automated Chapel": ItemClassification.filler,
	"Extrovert": ItemClassification.filler,
	"Dense Packing Grid": ItemClassification.filler,
	"Calculated Material Distribution": ItemClassification.filler,
	"Uranium-powered Drills": ItemClassification.filler,
	"Infinite Widget Matrix": ItemClassification.filler,
	"Tier 8 Mastery": ItemClassification.filler,
	"City Builder": ItemClassification.filler,
	"Fallout": ItemClassification.filler,
	"Green Energy": ItemClassification.filler,
	"Suburban Development": ItemClassification.filler,
	"Binary Pairs": ItemClassification.filler,
	"Rapid Cognitive Assembler": ItemClassification.filler,
	"Universal Recycling Schema": ItemClassification.filler,
	"Quantum Heat Exchanger": ItemClassification.filler,
	"Turbo Soldering Station": ItemClassification.filler,
	"Monopole Battery Tech": ItemClassification.filler,
	"Nano-Capacitor Synthesizer": ItemClassification.filler,
	"Lost Package Tracker": ItemClassification.filler,
	"Unified Theory of Sand": ItemClassification.filler,
	"Hyperfine Glass Distributor": ItemClassification.filler,
	"Spacetime Spin Matrix": ItemClassification.filler,
	"Hyper-Production Matrix": ItemClassification.filler,
	"Mitosis": ItemClassification.filler,
	"Boundless Patience": ItemClassification.filler,
	"Tier 9 Mastery": ItemClassification.filler,
	"New World Order": ItemClassification.filler,
	"Direct Widget Insertion": ItemClassification.filler,
	"Relics of the Past": ItemClassification.filler,
	"Direct Core Cooling": ItemClassification.filler,
	"Datacenter Access": ItemClassification.filler,
	"Rapid Logic Preprocessor": ItemClassification.filler,
	"Thought Integration Unit": ItemClassification.filler,
	"Ore-to-Ingot Optimization System": ItemClassification.filler,
	"Quantum Circuitry Optimizer": ItemClassification.filler,
	"Multi-Tasking Calculation Node": ItemClassification.filler,
	"Pressurized Storage Vats": ItemClassification.filler,
	"Ultra-Fast Circuit Integrator": ItemClassification.filler,
	"Gyroscope Hyperprocessor": ItemClassification.filler,
	"Excess Spin Utilizer": ItemClassification.filler,
	"Tier 10 Mastery": ItemClassification.filler,
	"Leveler": ItemClassification.filler,
	"Gaseous Bedrock": ItemClassification.filler,
	"Resource Management": ItemClassification.filler,
	"Subatomic Yield Booster (Widget Particle)": ItemClassification.filler,
	"Industrial Espionage": ItemClassification.filler,
	"Cowboy Coding": ItemClassification.filler,
	"Lightning Upgrade": ItemClassification.filler,
	"Rapid Rod Fabricator": ItemClassification.filler,
	"Quantum Efficiency Reactor": ItemClassification.filler,
	"N-Step Branch Prediction": ItemClassification.filler,
	"High Intensity Furnace": ItemClassification.filler,
	"Remnants of Humanity": ItemClassification.filler,
	"Yield Maximization Protocol": ItemClassification.filler,
	"Advanced Mining Protocol": ItemClassification.filler,
	"Rapid Refinement Module": ItemClassification.filler,
	"Ultra-Quick Logic Compiler": ItemClassification.filler,
	"High-Efficiency Capacitor Matrix": ItemClassification.filler,
	"Infinite Storage Glitch": ItemClassification.filler,
	"Tier 11 Mastery": ItemClassification.filler,
	"Absolute Dominion": ItemClassification.filler,
	"Sentience Recombobulator": ItemClassification.filler,
	"Enhanced Production Algorithms": ItemClassification.filler,
	"History Lesson": ItemClassification.filler,
	"Advanced Cognitive Release": ItemClassification.filler,
	"Wild Mutation": ItemClassification.filler,
	"Hyper-Speed Magnet Chamber": ItemClassification.filler,
	"Hello World": ItemClassification.filler,
	"Trinity": ItemClassification.filler,
	"Accelerated Thought Synthesizer": ItemClassification.filler,
	"Hyper-Accelerated Fabricator": ItemClassification.filler,
	"Multi-Fuel Synthesizer": ItemClassification.filler,
	"Stellar Quantum Weaver": ItemClassification.filler,
	"Isotope Yield Booster": ItemClassification.filler,
	"Data Yield Optimizer": ItemClassification.filler,
	"Data Stream Optimizer": ItemClassification.filler,
	"High-Capacity Energy Condenser": ItemClassification.filler,
	"Swift Logic Gate Fabricator": ItemClassification.filler,
	"Pristine Protection Protocol": ItemClassification.filler,
	"Advanced Arithmetic Processor": ItemClassification.filler,
	"Tier 12 Mastery": ItemClassification.filler,
	"Omega Limit Break": ItemClassification.filler,
	"Glitch in the System": ItemClassification.filler,
	"Omega Thought Processor": ItemClassification.filler,
	"Myriad Landscape": ItemClassification.filler,
	"Omega Yield Enhancer": ItemClassification.filler,
	"Generational Uplift": ItemClassification.filler,
	"Omega Assembly Lab": ItemClassification.filler,
	"Stepping Stone To Greatness": ItemClassification.filler,
	"Omega Sentience Circuitry": ItemClassification.filler,
	"Omega Training Compiler": ItemClassification.filler,
	"Omega Matrix Integrator": ItemClassification.filler,
	"Omega Cognitive Engine": ItemClassification.filler,
	"Beacon of Ascension": ItemClassification.filler,
	"Omega Ascension Planner": ItemClassification.filler,
	"Omega Extraction Matrix": ItemClassification.filler,
	"Omega Magnetizer Unit": ItemClassification.filler,
	"Omega Thought Conductor": ItemClassification.filler,
	"Omega Neural Matrix": ItemClassification.filler,
	"Omega Etching System": ItemClassification.filler,
	"Omega Containment Field": ItemClassification.filler,
	"Omega Entanglement Field": ItemClassification.filler,
	"Omega Mining Protocol": ItemClassification.filler,
	"Omega Cloud Synthesizer": ItemClassification.filler,
	"Omega Accelerated Digitizer": ItemClassification.filler,
	"Omega Crystal Stabilizer": ItemClassification.filler,
	"Omega Logic Amplifier": ItemClassification.filler,
	"Omega Circuit Weaver": ItemClassification.filler,
	"Omega Assembly Core": ItemClassification.filler,
	"Deconstruct": ItemClassification.progression,
	"Iron Mine": ItemClassification.progression,
	"Efficient Extraction": ItemClassification.progression,
	"Iron Smelter": ItemClassification.progression,
	"Furnace Optimizer": ItemClassification.progression,
	"Superheated Crucible (Iron Ingot)": ItemClassification.progression,
	"Widget Factory": ItemClassification.progression,
	"Optimized Materials": ItemClassification.progression,
	"Rapid Assembly": ItemClassification.progression,
	"Glitched Frame": ItemClassification.progression,
	"Dig Site": ItemClassification.progression,
	"Warehouse": ItemClassification.progression,
	"Sand Pit": ItemClassification.progression,
	"Mechanized Shovels": ItemClassification.progression,
	"Glass Kiln": ItemClassification.progression,
	"Kiln Governor": ItemClassification.progression,
	"Gyroscope Fabricator": ItemClassification.progression,
	"Widget Spinner": ItemClassification.progression,
	"Spin Stabilizer": ItemClassification.progression,
	"Gyroscopic Array": ItemClassification.progression,
	"Efficient Loader Arms": ItemClassification.progression,
	"Warped Speed": ItemClassification.progression,
	"Construction Overview": ItemClassification.progression,
	"Pause Construction": ItemClassification.progression,
	"Eminent Domain": ItemClassification.progression,
	"Clone Layout": ItemClassification.progression,
	"Oil Field": ItemClassification.progression,
	"Autopressurizer": ItemClassification.progression,
	"Black Gold": ItemClassification.progression,
	"Oil Power Plant": ItemClassification.progression,
	"Flame Stack": ItemClassification.progression,
	"Battery Assembler": ItemClassification.progression,
	"Superjuiced Upcharger": ItemClassification.progression,
	"Capacitor Bank": ItemClassification.progression,
	"Substable Wiring": ItemClassification.progression,
	"Supercharged Array": ItemClassification.progression,
	"Logistics Hub": ItemClassification.progression,
	"Superheated Crucible (Glass)": ItemClassification.progression,
	"Glass Ball Bearings": ItemClassification.progression,
	"Core Drilling": ItemClassification.progression,
	"Ultra-Fast Widget Synthesizer": ItemClassification.progression,
	"Careful Study": ItemClassification.progression,
	"Eagle Eye": ItemClassification.progression,
	"Long Distance Upgrades": ItemClassification.progression,
	"Copper Mine": ItemClassification.progression,
	"Turbo Drill Motors": ItemClassification.progression,
	"Copper Forge": ItemClassification.progression,
	"Forge Attendant": ItemClassification.progression,
	"Rapid Heat Induction Coils": ItemClassification.progression,
	"Plastic Extractor": ItemClassification.progression,
	"Enhanced Chemical Mixer": ItemClassification.progression,
	"Circuit Fab": ItemClassification.progression,
	"Computational Engine": ItemClassification.progression,
	"Enhanced Logic Synthesizer": ItemClassification.progression,
	"Rapid Component Feeder": ItemClassification.progression,
	"High Yield Compressor": ItemClassification.progression,
	"Depletion Recycler": ItemClassification.progression,
	"Expanded Shelf Storage": ItemClassification.progression,
	"Bucket Excavator": ItemClassification.progression,
	"Glass Shard Recombinator": ItemClassification.progression,
	"Tuned Spinners": ItemClassification.progression,
	"Precision Widgeteering": ItemClassification.progression,
	"Unnatural Duplication": ItemClassification.progression,
	"Tesla Coil": ItemClassification.progression,
	"Rapid Charge Collector": ItemClassification.progression,
	"Core Foundry": ItemClassification.progression,
	"Rudimentary Synapse Connector": ItemClassification.progression,
	"Integrator": ItemClassification.progression,
	"Synapse Fusion Unit": ItemClassification.progression,
	"Rapid Coupler": ItemClassification.progression,
	"Recycler": ItemClassification.progression,
	"Rubble Grinder": ItemClassification.progression,
	"Excavator": ItemClassification.progression,
	"Advanced Alloy Mixer": ItemClassification.progression,
	"Slash And Burn": ItemClassification.progression,
	"Hyper-Speed Assembly Line": ItemClassification.progression,
	"Auxiliary Pump Stack": ItemClassification.progression,
	"Heat Recirculator": ItemClassification.progression,
	"Rapid Discharge Fabricator": ItemClassification.progression,
	"Optimized Supply Lines": ItemClassification.progression,
	"Gyroscope Sharing Plan": ItemClassification.progression,
	"Dig Deeper": ItemClassification.progression,
	"Omni-Assembler Core": ItemClassification.progression,
	"Silicon Extruder": ItemClassification.progression,
	"Swift Wafer Synthesizer": ItemClassification.progression,
	"Processor Lab": ItemClassification.progression,
	"Extreme-UV Protocol": ItemClassification.progression,
	"Mainframe Assembler": ItemClassification.progression,
	"Enhanced Data Synthesizer": ItemClassification.progression,
	"Rapid Circuit Integrator": ItemClassification.progression,
	"Indentured Servitude": ItemClassification.progression,
	"Graveyard": ItemClassification.progression,
	"Efficient Neural Matrix": ItemClassification.progression,
	"Reclaim Sorting System": ItemClassification.progression,
	"Hyper-Speed Conveyor System": ItemClassification.progression,
	"Advanced Refining Chamber": ItemClassification.progression,
	"Precision Assembly Matrix": ItemClassification.progression,
	"Accelerated Component Placement": ItemClassification.progression,
	"Energy Optimization Core": ItemClassification.progression,
	"Warehouse Shelf Stacker": ItemClassification.progression,
	"Grain Matrix Duplicator": ItemClassification.progression,
	"Counterspin Anchors": ItemClassification.progression,
	"Dutiful Archivist": ItemClassification.progression,
	"Auto Upgrade": ItemClassification.progression,
	"Uranium Mine": ItemClassification.progression,
	"Rapid Extraction Module": ItemClassification.progression,
	"Fuel Rod Assembler": ItemClassification.progression,
	"Accelerated Molding Unit": ItemClassification.progression,
	"Nuclear Power Plant": ItemClassification.progression,
	"Advanced Heat Exchanger": ItemClassification.progression,
	"Cloud Digitizer": ItemClassification.progression,
	"Multi-Core Upload System": ItemClassification.progression,
	"Swift Transfer Protocol": ItemClassification.progression,
	"Microfine Engraving": ItemClassification.progression,
	"Multi-Bolt Capture Array": ItemClassification.progression,
	"Lightning Interface": ItemClassification.progression,
	"Autonomous Garbage Collectors": ItemClassification.progression,
	"Autosifter": ItemClassification.progression,
	"Advanced Circuit Optimization": ItemClassification.progression,
	"Pipe Repressurizer": ItemClassification.progression,
	"Instantaneous Charge Module": ItemClassification.progression,
	"Lightspeed Rotation": ItemClassification.progression,
	"Widget Minitizers": ItemClassification.progression,
	"Enhanced Particle Compressor": ItemClassification.progression,
	"Quantum Shrink Matrix": ItemClassification.progression,
	"Nanoscale Lab": ItemClassification.progression,
	"Quantum Lithography": ItemClassification.progression,
	"Reactor Foundry": ItemClassification.progression,
	"Subatomic Power Booster": ItemClassification.progression,
	"Quantum Tunneler": ItemClassification.progression,
	"High-Efficiency Particle Matrix": ItemClassification.progression,
	"Rapid Particle Integrator": ItemClassification.progression,
	"Blitz Upgrade": ItemClassification.progression,
	"Multi-Stage Refinement": ItemClassification.progression,
	"Precision Control Rods": ItemClassification.progression,
	"Rapid Crystal Formation Chamber": ItemClassification.progression,
	"Hyper-Speed Compiler": ItemClassification.progression,
	"Efficient Value Extraction": ItemClassification.progression,
	"Quantum Logic Synthesizer": ItemClassification.progression,
	"High-Yield Extraction System": ItemClassification.progression,
	"Yield Optimization Catalyst": ItemClassification.progression,
	"Hyper-Speed Arithmetic Processor": ItemClassification.progression,
	"Extradimensional Storage Lockers": ItemClassification.progression,
	"Helium Extractor": ItemClassification.progression,
	"Subatomic Yield Booster (Helium)": ItemClassification.progression,
	"Conductor Foundry": ItemClassification.progression,
	"Lightning Flux Unit": ItemClassification.progression,
	"AI Laboratory": ItemClassification.progression,
	"Quantum Neural Matrix": ItemClassification.progression,
	"AI Delimiter": ItemClassification.progression,
	"Advanced Cognitive Network": ItemClassification.progression,
	"Neural Accelerator": ItemClassification.progression,
	"Superconducting Collider Matrix": ItemClassification.progression,
	"Precision Atom Placement": ItemClassification.progression,
	"Rapid Core Integrator": ItemClassification.progression,
	"Accelerated Entanglement": ItemClassification.progression,
	"Nuclear Bore Engine": ItemClassification.progression,
	"Superconducting Fuel Chamber": ItemClassification.progression,
	"Quantum Integration Matrix": ItemClassification.progression,
	"Rapid Cloud Integrator": ItemClassification.progression,
	"Multi-Core Processor": ItemClassification.progression,
	"Incinerator": ItemClassification.progression,
	"Turbo Lightning Rods": ItemClassification.progression,
	"Ultra-Quick Integrator": ItemClassification.progression,
	"Automated Grading": ItemClassification.progression,
	"Training Center": ItemClassification.progression,
	"Advanced Cognitive Compiler": ItemClassification.progression,
	"Data Transformer": ItemClassification.progression,
	"Expedite Ascension": ItemClassification.progression,
	"Ascension Facility": ItemClassification.progression,
	"Unleashed Thought Matrix": ItemClassification.progression,
	"Rapid Cognition Compiler": ItemClassification.progression,
	"Precision Gas Separator": ItemClassification.progression,
	"Quantum Flux Matrix": ItemClassification.progression,
	"Rapid AI Synthesizer": ItemClassification.progression,
	"Multi-Phase Logic Processor": ItemClassification.progression,
	"Upgraded AI Compiler": ItemClassification.progression,
	"Subatomic Yield Optimizer": ItemClassification.progression,
	"Yield Maximization Reactor": ItemClassification.progression,
	"Lightning Data Bus": ItemClassification.progression,
	"Perpetual Motion Machine": ItemClassification.progression,
	"Physics Engine Decoder": ItemClassification.progression,
	"Sentience Facility": ItemClassification.progression,
	"Picoscale Lab": ItemClassification.progression,
	"Sentience Aggregator": ItemClassification.progression,
	"Processor Sharing System": ItemClassification.progression,
	"Thought Enhancer Matrix": ItemClassification.progression,
	"Rapid Spec Synthesizer": ItemClassification.progression,
	"Advanced Neural Compiler": ItemClassification.progression,
	"Frictionless Neural Compiler": ItemClassification.progression,
	"Enhanced Helium Synthesizer": ItemClassification.progression,
	"Optimized Neuron Compiler": ItemClassification.progression,
	"Radiometric Ore Separator": ItemClassification.progression,
	"Hyper-Speed Data Link": ItemClassification.progression,
	"Omega Processor Lab": ItemClassification.progression,
	"Omega Core Foundry": ItemClassification.progression,
	"Rocket Electronics Lab": ItemClassification.progression,
	"Omega Widget Distiller": ItemClassification.progression,
	"Rocket Fuel Distiller": ItemClassification.progression,
	"Omega Casing Factory": ItemClassification.progression,
	"Omega Shielding Plant": ItemClassification.progression,
	"Rocket Part Assembler": ItemClassification.progression,
	"Omega Project Assembler": ItemClassification.progression,
	"Omega Launch Facility": ItemClassification.progression
}

raw_items = [item for item, classification in item_table.items()]

def gen_create_items(world):
	pool = world.multiworld.itempool
	options = world.options
	for item, amt in progressive_tier.items():
		world.location_count -= amt
		for _ in range(amt):
			pool.append(world.create_item(item))
	for item, classification in item_table.items():
	    world.location_count -= 1
	    pool.append(world.create_item(item))
	for _ in range(world.location_count):
		pool.append(world.create_item("Motivational Poster"))