# File is Auto-generated, see: [https://github.com/SWCreeperKing/Widgitpelago/blob/master/Widgitpelago/Archipelago/ApShenanigans.cs]

tech_tree = [
	["Tier 1", "Menu"],
	["Tier 1 Mastery", "Tier 1"],
	["Deconstruct", "Tier 1"],
	["Frame Relocation", "Tier 1"],
	["Iron Mine", "Tier 1"],
	["Efficient Extraction", "Tier 1"],
	["Iron Smelter", "Tier 1"],
	["Furnace Optimizer", "Tier 1"],
	["Superheated Crucible (Iron Ingot)", "Tier 1"],
	["Widget Factory", "Tier 1"],
	["Optimized Materials", "Tier 1"],
	["Rapid Assembly", "Tier 1"],
	["Glitched Frame", "Tier 1"],
	["Fortress", "Tier 1"],
	["Dig Site", "Tier 1"],
	["Tier 2", "Tier 1"],
	["Tier 2 Mastery", "Tier 2"],
	["Warehouse", "Tier 2"],
	["Sand Pit", "Tier 2"],
	["Mechanized Shovels", "Tier 2"],
	["Glass Kiln", "Tier 2"],
	["Kiln Governor", "Tier 2"],
	["Gyroscope Fabricator", "Tier 2"],
	["Widget Spinner", "Tier 2"],
	["Spin Stabilizer", "Tier 2"],
	["Gyroscopic Array", "Tier 2"],
	["Iron-rich Rocks", "Tier 2"],
	["Efficient Loader Arms", "Tier 2"],
	["High Heat Density", "Tier 2"],
	["Widget Twins", "Tier 2"],
	["Warped Speed", "Tier 2"],
	["Tier 3", "Tier 2"],
	["Construction Overview", "Tier 3"],
	["Pause Construction", "Tier 3"],
	["Cancel All Construction", "Tier 3"],
	["Tier 3 Mastery", "Tier 3"],
	["Eminent Domain", "Tier 3"],
	["Clone Layout", "Tier 3"],
	["Area Move", "Tier 3"],
	["Oil Field", "Tier 3"],
	["Autopressurizer", "Tier 3"],
	["Black Gold", "Tier 3"],
	["Oil Power Plant", "Tier 3"],
	["Flame Stack", "Tier 3"],
	["Battery Assembler", "Tier 3"],
	["Superjuiced Upcharger", "Tier 3"],
	["Capacitor Bank", "Tier 3"],
	["Substable Wiring", "Tier 3"],
	["Supercharged Array", "Tier 3"],
	["Logistics Hub", "Tier 3"],
	["Coordinated Logistics", "Tier 3"],
	["Napalm Charge", "Tier 3"],
	["Beach Harvest", "Tier 3"],
	["Molten Conveyor System", "Tier 3"],
	["Superheated Crucible (Glass)", "Tier 3"],
	["Glass Ball Bearings", "Tier 3"],
	["Core Drilling", "Tier 3"],
	["Ultra-Fast Widget Synthesizer", "Tier 3"],
	["Careful Study", "Tier 3"],
	["Tier 4", "Tier 3"],
	["Eagle Eye", "Tier 4"],
	["Discerning Vision", "Tier 4"],
	["Tier 4 Mastery", "Tier 4"],
	["Long Distance Upgrades", "Tier 4"],
	["Upgrade Status", "Tier 4"],
	["Copper Mine", "Tier 4"],
	["Turbo Drill Motors", "Tier 4"],
	["Copper Forge", "Tier 4"],
	["Forge Attendant", "Tier 4"],
	["Rapid Heat Induction Coils", "Tier 4"],
	["Plastic Extractor", "Tier 4"],
	["Enhanced Chemical Mixer", "Tier 4"],
	["Circuit Fab", "Tier 4"],
	["Computational Engine", "Tier 4"],
	["Enhanced Logic Synthesizer", "Tier 4"],
	["Rapid Component Feeder", "Tier 4"],
	["Peat Oil Processing", "Tier 4"],
	["Power Plant Logistics", "Tier 4"],
	["High Yield Compressor", "Tier 4"],
	["Depletion Recycler", "Tier 4"],
	["Expanded Shelf Storage", "Tier 4"],
	["Bucket Excavator", "Tier 4"],
	["Glass Shard Recombinator", "Tier 4"],
	["Direct Glass Insertion", "Tier 4"],
	["Tuned Spinners", "Tier 4"],
	["Glass Grinding Wheel", "Tier 4"],
	["Industrial Capacity", "Tier 4"],
	["Precision Widgeteering", "Tier 4"],
	["Unnatural Duplication", "Tier 4"],
	["Tier 5", "Tier 4"],
	["Tier 5 Mastery", "Tier 5"],
	["Tesla Coil", "Tier 5"],
	["Rapid Charge Collector", "Tier 5"],
	["Core Foundry", "Tier 5"],
	["Rudimentary Synapse Connector", "Tier 5"],
	["Integrator", "Tier 5"],
	["Synapse Fusion Unit", "Tier 5"],
	["Rapid Coupler", "Tier 5"],
	["Recycler", "Tier 5"],
	["Rubble Grinder", "Tier 5"],
	["Excavator", "Tier 5"],
	["Giant Rock Crusher", "Tier 5"],
	["Advanced Alloy Mixer", "Tier 5"],
	["Slash And Burn", "Tier 5"],
	["Hyper-Speed Assembly Line", "Tier 5"],
	["Auxiliary Pump Stack", "Tier 5"],
	["Heat Recirculator", "Tier 5"],
	["Hydrophobia", "Tier 5"],
	["Dedicated Battery Inserters", "Tier 5"],
	["Rapid Discharge Fabricator", "Tier 5"],
	["Optimized Supply Lines", "Tier 5"],
	["Perfectly Balanced Spinner", "Tier 5"],
	["Gyroscope Sharing Plan", "Tier 5"],
	["Dig Deeper", "Tier 5"],
	["Turbo Blast Furnace", "Tier 5"],
	["Omni-Assembler Core", "Tier 5"],
	["Tier 6", "Tier 5"],
	["Tier 6 Mastery", "Tier 6"],
	["The Factory Must Grow", "Tier 6"],
	["Silicon Extruder", "Tier 6"],
	["Swift Wafer Synthesizer", "Tier 6"],
	["Processor Lab", "Tier 6"],
	["Extreme-UV Protocol", "Tier 6"],
	["Mainframe Assembler", "Tier 6"],
	["Enhanced Data Synthesizer", "Tier 6"],
	["Rapid Circuit Integrator", "Tier 6"],
	["Indentured Servitude", "Tier 6"],
	["Graveyard", "Tier 6"],
	["Chain Lightning", "Tier 6"],
	["Efficient Neural Matrix", "Tier 6"],
	["Introvert", "Tier 6"],
	["Reclaim Sorting System", "Tier 6"],
	["Hyper-Speed Conveyor System", "Tier 6"],
	["Shortened Transfer Tube", "Tier 6"],
	["Advanced Refining Chamber", "Tier 6"],
	["Precision Assembly Matrix", "Tier 6"],
	["Agoraphobia", "Tier 6"],
	["Standalone", "Tier 6"],
	["Accelerated Component Placement", "Tier 6"],
	["Exhaust Vent Recycler", "Tier 6"],
	["Rapid Heat Exchanger (Battery)", "Tier 6"],
	["Energy Optimization Core", "Tier 6"],
	["Warehouse Shelf Stacker", "Tier 6"],
	["Grain Matrix Duplicator", "Tier 6"],
	["Rapid Heat Exchanger (Glass)", "Tier 6"],
	["Counterspin Anchors", "Tier 6"],
	["Double-stacked Conveyors", "Tier 6"],
	["Productivity Optimization Node", "Tier 6"],
	["Dutiful Archivist", "Tier 6"],
	["Tier 7", "Tier 6"],
	["Tier 7 Mastery", "Tier 7"],
	["Auto Upgrade", "Tier 7"],
	["Uranium Mine", "Tier 7"],
	["Rapid Extraction Module", "Tier 7"],
	["Fuel Rod Assembler", "Tier 7"],
	["Accelerated Molding Unit", "Tier 7"],
	["Nuclear Power Plant", "Tier 7"],
	["Advanced Heat Exchanger", "Tier 7"],
	["Cloud Digitizer", "Tier 7"],
	["Multi-Core Upload System", "Tier 7"],
	["Swift Transfer Protocol", "Tier 7"],
	["Monocrystalline", "Tier 7"],
	["Microfine Engraving", "Tier 7"],
	["Automated Chapel", "Tier 7"],
	["Multi-Bolt Capture Array", "Tier 7"],
	["Lightning Interface", "Tier 7"],
	["Extrovert", "Tier 7"],
	["Autonomous Garbage Collectors", "Tier 7"],
	["Autosifter", "Tier 7"],
	["Dense Packing Grid", "Tier 7"],
	["Advanced Circuit Optimization", "Tier 7"],
	["Pipe Repressurizer", "Tier 7"],
	["Instantaneous Charge Module", "Tier 7"],
	["Lightspeed Rotation", "Tier 7"],
	["Calculated Material Distribution", "Tier 7"],
	["Uranium-powered Drills", "Tier 7"],
	["Infinite Widget Matrix", "Tier 7"],
	["Tier 8", "Tier 7"],
	["Tier 8 Mastery", "Tier 8"],
	["Widget Minitizers", "Tier 8"],
	["Enhanced Particle Compressor", "Tier 8"],
	["Quantum Shrink Matrix", "Tier 8"],
	["Nanoscale Lab", "Tier 8"],
	["Quantum Lithography", "Tier 8"],
	["Reactor Foundry", "Tier 8"],
	["Subatomic Power Booster", "Tier 8"],
	["Quantum Tunneler", "Tier 8"],
	["High-Efficiency Particle Matrix", "Tier 8"],
	["Rapid Particle Integrator", "Tier 8"],
	["City Builder", "Tier 8"],
	["Blitz Upgrade", "Tier 8"],
	["Fallout", "Tier 8"],
	["Multi-Stage Refinement", "Tier 8"],
	["Green Energy", "Tier 8"],
	["Precision Control Rods", "Tier 8"],
	["Rapid Crystal Formation Chamber", "Tier 8"],
	["Suburban Development", "Tier 8"],
	["Binary Pairs", "Tier 8"],
	["Hyper-Speed Compiler", "Tier 8"],
	["Efficient Value Extraction", "Tier 8"],
	["Rapid Cognitive Assembler", "Tier 8"],
	["Quantum Logic Synthesizer", "Tier 8"],
	["Universal Recycling Schema", "Tier 8"],
	["High-Yield Extraction System", "Tier 8"],
	["Quantum Heat Exchanger", "Tier 8"],
	["Yield Optimization Catalyst", "Tier 8"],
	["Turbo Soldering Station", "Tier 8"],
	["Hyper-Speed Arithmetic Processor", "Tier 8"],
	["Monopole Battery Tech", "Tier 8"],
	["Nano-Capacitor Synthesizer", "Tier 8"],
	["Lost Package Tracker", "Tier 8"],
	["Extradimensional Storage Lockers", "Tier 8"],
	["Unified Theory of Sand", "Tier 8"],
	["Hyperfine Glass Distributor", "Tier 8"],
	["Spacetime Spin Matrix", "Tier 8"],
	["Hyper-Production Matrix", "Tier 8"],
	["Mitosis", "Tier 8"],
	["Boundless Patience", "Tier 8"],
	["Tier 9", "Tier 8"],
	["Tier 9 Mastery", "Tier 9"],
	["New World Order", "Tier 9"],
	["Helium Extractor", "Tier 9"],
	["Subatomic Yield Booster (Helium)", "Tier 9"],
	["Conductor Foundry", "Tier 9"],
	["Lightning Flux Unit", "Tier 9"],
	["AI Laboratory", "Tier 9"],
	["Quantum Neural Matrix", "Tier 9"],
	["AI Delimiter", "Tier 9"],
	["Advanced Cognitive Network", "Tier 9"],
	["Neural Accelerator", "Tier 9"],
	["Direct Widget Insertion", "Tier 9"],
	["Superconducting Collider Matrix", "Tier 9"],
	["Precision Atom Placement", "Tier 9"],
	["Relics of the Past", "Tier 9"],
	["Rapid Core Integrator", "Tier 9"],
	["Accelerated Entanglement", "Tier 9"],
	["Nuclear Bore Engine", "Tier 9"],
	["Direct Core Cooling", "Tier 9"],
	["Superconducting Fuel Chamber", "Tier 9"],
	["Datacenter Access", "Tier 9"],
	["Quantum Integration Matrix", "Tier 9"],
	["Rapid Cloud Integrator", "Tier 9"],
	["Rapid Logic Preprocessor", "Tier 9"],
	["Multi-Core Processor", "Tier 9"],
	["Incinerator", "Tier 9"],
	["Turbo Lightning Rods", "Tier 9"],
	["Thought Integration Unit", "Tier 9"],
	["Ultra-Quick Integrator", "Tier 9"],
	["Automated Grading", "Tier 9"],
	["Ore-to-Ingot Optimization System", "Tier 9"],
	["Quantum Circuitry Optimizer", "Tier 9"],
	["Multi-Tasking Calculation Node", "Tier 9"],
	["Pressurized Storage Vats", "Tier 9"],
	["Ultra-Fast Circuit Integrator", "Tier 9"],
	["Gyroscope Hyperprocessor", "Tier 9"],
	["Excess Spin Utilizer", "Tier 9"],
	["Tier 10", "Tier 9"],
	["Tier 10 Mastery", "Tier 10"],
	["Training Center", "Tier 10"],
	["Advanced Cognitive Compiler", "Tier 10"],
	["Data Transformer", "Tier 10"],
	["Expedite Ascension", "Tier 10"],
	["Ascension Facility", "Tier 10"],
	["Unleashed Thought Matrix", "Tier 10"],
	["Rapid Cognition Compiler", "Tier 10"],
	["Leveler", "Tier 10"],
	["Gaseous Bedrock", "Tier 10"],
	["Precision Gas Separator", "Tier 10"],
	["Quantum Flux Matrix", "Tier 10"],
	["Resource Management", "Tier 10"],
	["Rapid AI Synthesizer", "Tier 10"],
	["Multi-Phase Logic Processor", "Tier 10"],
	["Upgraded AI Compiler", "Tier 10"],
	["Subatomic Yield Booster (Widget Particle)", "Tier 10"],
	["Industrial Espionage", "Tier 10"],
	["Subatomic Yield Optimizer", "Tier 10"],
	["Cowboy Coding", "Tier 10"],
	["Lightning Upgrade", "Tier 10"],
	["Rapid Rod Fabricator", "Tier 10"],
	["Quantum Efficiency Reactor", "Tier 10"],
	["Yield Maximization Reactor", "Tier 10"],
	["N-Step Branch Prediction", "Tier 10"],
	["Lightning Data Bus", "Tier 10"],
	["High Intensity Furnace", "Tier 10"],
	["Remnants of Humanity", "Tier 10"],
	["Yield Maximization Protocol", "Tier 10"],
	["Advanced Mining Protocol", "Tier 10"],
	["Rapid Refinement Module", "Tier 10"],
	["Ultra-Quick Logic Compiler", "Tier 10"],
	["High-Efficiency Capacitor Matrix", "Tier 10"],
	["Infinite Storage Glitch", "Tier 10"],
	["Tier 11", "Tier 10"],
	["Tier 11 Mastery", "Tier 11"],
	["Absolute Dominion", "Tier 11"],
	["Perpetual Motion Machine", "Tier 11"],
	["Physics Engine Decoder", "Tier 11"],
	["Sentience Facility", "Tier 11"],
	["Sentience Recombobulator", "Tier 11"],
	["Picoscale Lab", "Tier 11"],
	["Enhanced Production Algorithms", "Tier 11"],
	["Sentience Aggregator", "Tier 11"],
	["Processor Sharing System", "Tier 11"],
	["Thought Enhancer Matrix", "Tier 11"],
	["History Lesson", "Tier 11"],
	["Rapid Spec Synthesizer", "Tier 11"],
	["Advanced Cognitive Release", "Tier 11"],
	["Wild Mutation", "Tier 11"],
	["Advanced Neural Compiler", "Tier 11"],
	["Frictionless Neural Compiler", "Tier 11"],
	["Enhanced Helium Synthesizer", "Tier 11"],
	["Hyper-Speed Magnet Chamber", "Tier 11"],
	["Hello World", "Tier 11"],
	["Optimized Neuron Compiler", "Tier 11"],
	["Trinity", "Tier 11"],
	["Accelerated Thought Synthesizer", "Tier 11"],
	["Hyper-Accelerated Fabricator", "Tier 11"],
	["Multi-Fuel Synthesizer", "Tier 11"],
	["Stellar Quantum Weaver", "Tier 11"],
	["Radiometric Ore Separator", "Tier 11"],
	["Isotope Yield Booster", "Tier 11"],
	["Data Yield Optimizer", "Tier 11"],
	["Hyper-Speed Data Link", "Tier 11"],
	["Data Stream Optimizer", "Tier 11"],
	["High-Capacity Energy Condenser", "Tier 11"],
	["Swift Logic Gate Fabricator", "Tier 11"],
	["Pristine Protection Protocol", "Tier 11"],
	["Advanced Arithmetic Processor", "Tier 11"],
	["Tier 12", "Tier 11"],
	["Tier 12 Mastery", "Tier 12"],
	["Omega Processor Lab", "Tier 12"],
	["Omega Core Foundry", "Tier 12"],
	["Rocket Electronics Lab", "Tier 12"],
	["Omega Widget Distiller", "Tier 12"],
	["Rocket Fuel Distiller", "Tier 12"],
	["Omega Casing Factory", "Tier 12"],
	["Omega Shielding Plant", "Tier 12"],
	["Rocket Part Assembler", "Tier 12"],
	["Omega Project Assembler", "Tier 12"],
	["Omega Launch Facility", "Tier 12"],
	["Omega Limit Break", "Tier 12"],
	["Glitch in the System", "Tier 12"],
	["Omega Thought Processor", "Tier 12"],
	["Myriad Landscape", "Tier 12"],
	["Omega Yield Enhancer", "Tier 12"],
	["Generational Uplift", "Tier 12"],
	["Omega Assembly Lab", "Tier 12"],
	["Stepping Stone To Greatness", "Tier 12"],
	["Omega Sentience Circuitry", "Tier 12"],
	["Omega Training Compiler", "Tier 12"],
	["Omega Matrix Integrator", "Tier 12"],
	["Omega Cognitive Engine", "Tier 12"],
	["Beacon of Ascension", "Tier 12"],
	["Omega Ascension Planner", "Tier 12"],
	["Omega Extraction Matrix", "Tier 12"],
	["Omega Magnetizer Unit", "Tier 12"],
	["Omega Thought Conductor", "Tier 12"],
	["Omega Neural Matrix", "Tier 12"],
	["Omega Etching System", "Tier 12"],
	["Omega Containment Field", "Tier 12"],
	["Omega Entanglement Field", "Tier 12"],
	["Omega Mining Protocol", "Tier 12"],
	["Omega Cloud Synthesizer", "Tier 12"],
	["Omega Accelerated Digitizer", "Tier 12"],
	["Omega Crystal Stabilizer", "Tier 12"],
	["Omega Logic Amplifier", "Tier 12"],
	["Omega Circuit Weaver", "Tier 12"],
	["Omega Assembly Core", "Tier 12"],
	["Starting Check (1)", "Menu"],
	["Starting Check (2)", "Menu"],
	["Starting Check (3)", "Menu"]
]

location_dict = [
	*[items[0] for items in tech_tree]
]